### ISSUE TITLE
Deprecated media types

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1000]
EPUB 3.1 deprecated text/javascript and application/vnd.ms-opentype

Do these remain deprecated in 3.2 and impact existing content or do they become valid again and have to be discouraged through other means?

**Comment by GarthConboy** [comment]
It would seem fine to leave deprecated to me.  Will not impact content validity.

**Comment by mattgarrish** [comment]
> Will not impact content validity.

But all javascripts have to be identified by the deprecated media type until we release and get support in epubcheck for application/javascript.

We're then going to have a cut-over phase where older epubchecks will say the new media types are invalid and newer will say the old media types are invalid.

**Comment by GarthConboy** [comment]
Argh.  Yes, you raise a valid point.  That change didn't make the changes document, so hadn't recalled it.

I guess given the epubcheck transition, we should probably include both in 3.2:

text/javascript -- deprecagted
application/javascript -- preferred

So, basically retaining 3.1 language.  epubhcheck, regardless, we have some, semi-simple, catching up to do with 3.2.  Current epubcheck will push toward the former, as it won't like the latter, when updated, this will be reversed, but this seems okay, as old content will be valid both ways.

**Comment by GarthConboy** [comment]
Actually -- seems we should keep both an not formally deprecate the older ones -- but the new variants should be "preferred".

**Comment by mattgarrish** [comment]
Closing with the merge of PR #1042.
