### ISSUE TITLE
Former editors

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1002]
We should look at identifying former editors in the new revision so the specifications don't still look IDPF-driven. I think it's safe to say Markus and Bill are not resuming any active editing duties at this point.

**Comment by dauwhe** [comment]
I think we can do this in respec with spec metadata. CSS does this all the time.

**Comment by mattgarrish** [comment]
Respec was updated last week to allow this to be done cleanly:
https://github.com/w3c/respec/wiki/formerEditors

I've updated the specs accordingly: https://github.com/w3c/publ-epub-revision/commit/35128babf16ed59121d38d40715c6f659f26bb8a

Only thing of note is that without Markus or James participating in the CG, we don't have an active editor for OCF. I've passed this honour on to Garth, as the most recent changes I can think of have been around obfuscation and encryption, which he drove. We can always change later.
