### ISSUE TITLE
Updated contributors

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1003]
The EPUB overview is becoming dominated by lists of people who contributed to each and every IDPF release going back to 2.0. Given that participation in the W3C CG and BG are fluid, persisting this going forward is arguably not worth the effort.

One option would be to strip the lists of individual contributors at this point and simply acknowledge "all members" of the CG and BG, and only specifically call out the CG chairs for each revision.

This section could replace list in the 3.2 specification and the overview could be returned to focusing on providing an overview.

**Comment by murata2makoto** [comment]
I agree to drop the lists of individual contributors.

**Comment by GarthConboy** [comment]
Are you proposing dropping entirely, or relegating elsewhere?

I can live with either.

**Comment by mattgarrish** [comment]
I would drop the old lists of names from the overview since they're all IDPF member-focused.

All I think we need is a chair list and generic thank you here: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#app-contributors

**Comment by dauwhe** [comment]
In CSS, spec editors typically [acknowledge](https://drafts.csswg.org/css-inline/#ack) those people who actually contribute to a particular specification. I like this approach better than listing members of a working group, some of whom may never have even seen the spec in question.

**Comment by murata2makoto** [comment]
>In CSS, spec editors typically acknowledge those people who actually contribute to a particular specification. I like this approach better than listing members of a working group, some of whom may never have even seen the spec in question.

 Is it too much if I hope to be acknowledged?

**Comment by GarthConboy** [comment]
Me too!  :-)

**Comment by mattgarrish** [comment]
> typically acknowledge those people who actually contribute to a particular specification

I can live with that, too, but how is it determined who is in or out of those lists? Do chairs decide who has been substantively involved?

**Comment by dauwhe** [comment]
> I can live with that, too, but how is it determined who is in or out of those lists? Do chairs decide who has been substantively involved?

In my experience, the editors decide.

**Comment by mattgarrish** [comment]
Perhaps scribing 2+ meetings should be an entry level requirement... ;)

**Comment by mattgarrish** [comment]
I'm going to close this issue, as we can tweak the exact wording and list of people as we go. I've removed the IDPF member lists and replaced with a placeholder statement.
