### ISSUE TITLE
restore refines examples?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1005]
In addition to stripping the refines attribute, we also stripped examples in the package document (e.g., for various title types).

Should these be re-integrated if we're returning the attribute and meta vocabulary properties?

**Comment by mattgarrish** [comment]
Note that this will also involve re-adding normative prose related to the meta properties.

**Comment by TzviyaSiegman** [comment]
I think we should still discourage refines. Examples encourage use. People often think examples are requirements and simply copy them.

**Comment by murata2makoto** [comment]
I strongly think that the examples should be restored.  Japanese users will have to continue to use refines anyway.

**Comment by mattgarrish** [comment]
They're mostly bloat, though. We just say here's a property you may use and then have an example. The examples would work equally well in their respective vocabularies, and make them more useful.

There are also some normative oddities that might get re-introduced, like whether title-type is recommended when there is more than one title.

**Comment by GarthConboy** [comment]
I'm with Makoto on this one (sorry Tzviya! :-) .  Maybe compromise... keep examples, but discourage anyhow.

**Comment by laudrain** [comment]
I'm with Tzviya here. 
@murata2makoto japanese EPUB3 producers do certainly know now how to use refines. IMO, 3.2 doesn't need to bring back examples. In any case, these examples are still in 3.0.1.
Message discouraging refines will be more clear if we don't bring back examples.

**Comment by murata2makoto** [comment]
I thought that we are going to drop 3.1 attributes and thus un-deprecate refines.

#986

I know that refines is ugly.  But a minor version in the EPUB 3 family is not the right place to drop badly-designed features.

**Comment by laudrain** [comment]
You are right, but Matt question is just on re-introducing examples. 
I agree we have to un-deprecate refines, but shouln't we discourage its use, particularly for new EPUB 3.2 producers ?

**Comment by murata2makoto** [comment]
No, we shouldn't discourage its use.  We have to give up migration and continue to provide refines as the only solution for Japanese publishers.

**Comment by mattgarrish** [comment]
> No, we shouldn't discourage its use.

Tzviya wasn't saying that we should actively discourage use, only that we don't need to promote refines so heavily and give the impression it's needed technology for everyone.

I still believe these belong in the meta properties vocabulary if they're kept. It doesn't make a lot of sense to separate the examples from where the properties are actually defined.

**Comment by GarthConboy** [comment]
Clearly refines needs to be kept -- that's the overall goal of 3.2 -- backwards compatibility.

I can live without examples -- I wouldn't too actively discourage use (as on our current path I expect we'll never remove), but perhaps say other options are preferred.

**Comment by mattgarrish** [comment]
The examples have now been added to the [meta properties vocabulary](https://idpf.github.io/epub-vocabs/package/meta/meta.html).
