### ISSUE TITLE
remove duration attribute

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1006]
This was another addition to manifest items to deal with the lack of refines in 3.1 - to define the media overlay duration. If we're going back to compatibility with 3.0.1, we should continue to use the media:duration property.

**Comment by GarthConboy** [comment]
Indeed.

**Comment by murata2makoto** [comment]
The title of this issue implies that the new attribute should be dropped, but Matt also wrote: "should continue to use".  What is your intention?  > @mattgarrish

**Comment by mattgarrish** [comment]
That was a reference to continuing to use the property.

The attribute was added because without refines you can't attach the media:duration property to each manifest entry.

Attaching a media:duration to each file is clunky, but it's what people have had to do until this point.

**Comment by mattgarrish** [comment]
Closing this with the merge of PR #1040.
