### ISSUE TITLE
expected behaviour when no supported fallbacks

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1007]
Expanding on the issue in the EPUB 3.2 specification about what do when a fallback isn't provided for a foreign resource, there's also a question of what happens if the reading system doesn't support any of the specified fallbacks.

There should be an expectation that the reading system will inform the user that a document cannot be rendered so that the user doesn't silently pass over content. There won't always be visual clues or clear breaks in the logical consistency of the narrative to clue the user in.

**Comment by GarthConboy** [comment]
Actually, I'd tend to go the other way.  I'm not a fan of UX requirements on the Reading Systems.  I'd tend to go more with a "if a RS can't resolve a resource via fallback chain to some support type, it may silently drop the resource."  Or some such.  Maybe with a SHOULD for being less silent, but not a MUST.

**Comment by murata2makoto** [comment]
I guess that EPUB RSs will simply rely on browser engines here.  If this is the case, no matter what we write in our specs, RSs implementors can do nothing.

**Comment by mattgarrish** [comment]
> I guess that EPUB RSs will simply rely on browser engines here.

This is about manifest fallback chains, not content fallbacks. The RS has to take ownership of this case.

**Comment by murata2makoto** [comment]
3.1 provides some examples.  "directly from spine itemref elements; from [HTML] img, iframe and link elements in XHTML Content Documents; and from @import rules in CSS Style Sheets".

I think that fallback chains make sense only for the itemref case.  But a core media type is required in the fallback chain.  Are you talking about the case that the RS does not support the specified CMT?

**Comment by mattgarrish** [comment]
Yes, this is about manifest fallbacks. There's an unlogged issue in the 3.2 specification asking about this, I assume added by @dauwhe?

We don't need to do anything about the in-content cases, as I agree those are for the browser engines. But we don't say anything about what an RS is expected to do when it processes a foreign resource that doesn't contain a fallback or the chain ends before it reaches a CMT (whether there is no CMT or the chain becomes circular, which is why I logged that other issue).

It's one of the cases where we rely on authors doing the right thing and I tend to agree with this issue that we should do a better job of clarifying expectations for reading systems, even if it's probably not a common occurrence.

HTML audio and video both display a message when no supported media type can be found in their fallback chains, so having something similar for manifest fallbacks would be more user-friendly than blank pages or skipped documents or whatever the RS happens to implement.

But, again, I also don't think it's critical we solve this for 3.2.

**Comment by dauwhe** [comment]
A manifest fallback chain must end with a core media type. Are we talking about how a reading system responds to an invalid EPUB?

**Comment by dauwhe** [comment]
Added text:

> If a Reading System does not support any resource in the fallback chain, it MUST alert the reader that content could not be displayed.

**Comment by dauwhe** [comment]
Closed with #1060
