### ISSUE TITLE
terminating circular fallback chains

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1008]
This is perhaps self-evident, but if we want to be more explicit about user agent behaviours then this statement:

> Fallback chains MUST NOT contain any circular- or self-references to item elements in the chain.

Should probably be followed by a statement that user agents must terminate the fallback chain at the first reference to a manifest item that has already been encountered.

**Comment by GarthConboy** [comment]
I'm not sure it needs a change.  But, I have no objection to your suggestion.

**Comment by murata2makoto** [comment]
Many other errors are possible.  Are we going to specify RS behaviors for all such errors?

**Comment by mattgarrish** [comment]
I wouldn't call it error handling so much as how much of the RS process are we going to define, if that's indeed important to do?

I agree with not defining UI expectations, but there are processes that can be more succinctly spelled out that are not variable. Rendering a fallback is one case that is an odd mix of saying what a reading system has to do sometimes and then expecting behaviours to be inferred from authoring practices others.

But I don't think this needs to be a concern for 3.2, which is why I didn't add it to the milestone. 3.2 should stay focused on its one primary objective.

**Comment by dauwhe** [comment]
Fixed with #1053
