### ISSUE TITLE
Revert package version number

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1009]
The value of the “version” attribute on the ```<package>``` element is “3.0” rather than “3.1” for EPUB 3.2.

**Comment by dauwhe** [comment]
Our [current draft](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-package-elem) states,

> The version attribute specifies the EPUB specification version to which the given EPUB Package conforms. The attribute MUST have the value "3.0" to indicate compliance with this version of the specification.

I will try to get CG approval for this today. We might as well make progress on our single largest issue!

**Comment by GarthConboy** [comment]
Indeed, this is core to the 3.2 effort – we're not get getting to backward compatible without this change.
