### ISSUE TITLE
Note 3.2's relationship to 3.1/3.01 in changes document

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1010]
Update EPUB Revision History to note that EPUB 3.2 retracts incompatibilities between EPUB 3.0.1 and EPUB 3.1.  And further note that EPUB 3.2, as now defined, is backward compatible with EPUB 3.0.1 and replaces EPUB 3.1 as the most modern EPUB specification.

**Comment by dauwhe** [comment]
It seems the current text does most of this: 

> EPUB 3.2 can be considered as a successor to both EPUB 3.0.1 and EPUB 3.1. While reverting certain incompatible changes to EPUB 3.0.1 that were introduced in EPUB 3.1, it also retains most of the rest of the updates made during the 3.1 revision.

> Since EPUB 3.1 did not receive widespread adoption, the community group has decided to retain a list of all changes made during the EPUB 3.1 revision that are still reflected in EPUB 3.2. This decision was made to simplify comprehension of what has changed since EPUB 3.0.1 (i.e., readers do not have to review EPUB 3.1 before being able to determine how this new version updates EPUB 3.0.1).

I'll try to add something about compatibility.

**Comment by GarthConboy** [comment]
I might consider ditching the 2nd paragraph and just updating our 3.2 Changes document to be those changes from 3.0.1... a nice attempt to forget 3.1!  :-)

**Comment by mattgarrish** [comment]
That's what the second paragraph is saying, though. This changes doc is a list of everything that's changed from 3.0.1 to 3.2, including things that were technically in 3.1. It's an answer to the question of whether you have to figure out what changed in 3.1 before reading 3.2.

I'd be fine tacking a shorter sentence like the following onto the end of the first and leaving out the full history lesson:

> It is not necessary to read EPUB 3.1 to determine what has changed between this version of EPUB 3.0.1.

**Comment by GarthConboy** [comment]
Yea, yea.  ;-)   I guess "retain a list of all changes made during the EPUB 3.1 revision" does kinda say that... I'd just tend to be more explicit.  "3.1 is withdrawn; 3.2 is the follow-on version to 3.0.1."

**Comment by dauwhe** [comment]
> 3.1 is withdrawn

I like to think of it as fast-forwarding :)

**Comment by mattgarrish** [comment]
Sure, I don't care if we say something like "withdrawn". I'm just concerned that if we don't explicitly tell people they can ignore reading 3.1 then there will be a lingering question about what "withdrawn" means and whether there is still a progression you have to follow to understand how to get to 3.2.

**Comment by dauwhe** [comment]
I think we're good now:

> This document describes all changes to EPUB made since EPUB 3.0.1, so that readers do not have to review EPUB 3.1 before being able to determine how this new version updates EPUB 3.0.1.
