### ISSUE TITLE
Allow RS to fail when encountering unknown foreign resources

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1011]
Allow EPUB 3.2 Reading Systems to fail if they encounter Foreign Resources without Fallbacks, but strongly recommend they do not do so. [[3.1 section](http://www.idpf.org/epub/31/spec/epub-spec.html#sec-foreign-restrictions)]  Along the lines of "Foreign Resources may be included in an EPUB Publication without a fallback provided ..."  but add "however RS's may ignore these resources".

**Comment by mattgarrish** [comment]
When is the reading system the consumer of these resources if they aren't used in the spine? Wasn't this exclusively an epubcheck issue we were trying to solve - that it would report manifest items without fallbacks as errors and we were trying to allow script data, etc.?

**Comment by murata2makoto** [comment]
Do such foreign resources occur only in Javascript programs?

**Comment by mattgarrish** [comment]
There's not much of a provision for them to be used anywhere else, and that was the main case presented for adding this ability.

The missing part of the quote above is:

> provided they are not referenced from spine itemref elements [Packages32] or directly rendered in their native format in EPUB Content Documents (e.g., via [HTML] embedded content and [SVG] image and foreignObject elements)

Unless a reading system fails because something is listed in the manifest it doesn't like the media type of, any problems with non-compliance are going to be handled by the browser engine rendering the content.

The other case was to include data files in the epub for transport without having to hide them from epubcheck. But there's no requirement on the reading system to do anything with such resources, especially with the display restrictions. There would have to be instructions in the content that the resource can be obtained from the package.

We can add a statement not to fail, but it only adds confusion in my mind what the provision is for. Why not add a note that explains the purpose better?

**Comment by GeorgeKerscher** [comment]
Yes, explaining the use case is good, even a link to an example.
 
Best
Geeorge

**Comment by mattgarrish** [comment]
Closing as a usage example note was added in PR #1033 as resolved on the 2018-04-26 telecon.
