### ISSUE TITLE
Allow RS to refuse remotely-hosted resources

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1012]
Allow EPUB 3.2 Reading Systems to refuse Remotely-Hosted Resources. But recommend they do not do so.

**Comment by dauwhe** [comment]
Current language in [spec](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-epub-rs-conf):

> It SHOULD support remote resources, as defined in Resource Locations.

Is this good enough?

**Comment by RachelComerford** [comment]
Resolved 5/17: SHOULD support remote resources, as defined in Resource Locations.

**Comment by dauwhe** [comment]
Closed as we have consensus that the language in the spec now is acceptable.

**Comment by mattgarrish** [comment]
Late to the game, but I meant to ask whether "support" is the right wording for this one? It sounds like an override of the media type requirements above it.

Is the intent more along these lines: "If it has network access, it SHOULD support the retrieval of remote resources as defined in ...".
