### ISSUE TITLE
Re-add OPF2 meta element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1013]
Reintroduce, but highly discourage the use of, the OPF2 ```<meta>``` element.  Retain the EPUB 3.0.1 language that is obsoleted.

**Comment by dauwhe** [comment]
Link to draft is [here](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-meta-opf2-elem).

This was "[obsoleted and replaced](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-opf-meta-elem)" in 3.0.1.

How do we classify this one? If it's just deprecated, EPUB 3.2 reading systems will be required to support it. Is this another candidate for being superseded? Or Garth's new "deprecated with prejudice" category (to be defined)...

**Comment by mattgarrish** [comment]
Closing as the element was added and marked as legacy in #1029.
