### ISSUE TITLE
Reconsider status of NCX

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1014]
In EPUB 3.0.1 the NCX was "superseded" and in EPUB 3.1 it was "superseded and marked for removal".  For 3.2, it should be simply "deprecated" (or even just leaving as "superseded" could be okay).

**Comment by GarthConboy** [comment]
Well, as I wrote "For 3.2, it should be simply "deprecated" (or even just leaving as "superseded" could be okay).", I'm clearly okay with either.  :-)

**Comment by dauwhe** [comment]
We should not use deprecated, as it requires EPUB 3.2 reading systems to support the NCX as defined. [Superceded](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#superceded) makes the most sense, I think, as the definition matches exactly what we want:

> The superseded feature MAY be removed in a future version of the specification, but there is no definite timeline for removal.

Sadly, we don't have a definite timeline for removal any more :(

> Authors MAY include the superseded feature for compatibility with older versions of the specification.

This is exactly our goal.

> Reading Systems MUST NOT support the superseded feature in content that conforms to the current version of the specification.

Yes, the NCX should be ignored when a NAV file exists. 

> Validation tools MUST NOT alert Authors about the presence of the superseded feature in an EPUB Publication, as it is valid for backwards compatibility. Validation tools MUST alert Authors if the superseded feature is not conformant to its definition or otherwise breaks a usage requirement.

Again, exactly what we want. Authors are free to use NCX without epubcheck complaining, unless they're doing it wrong.

**Comment by GarthConboy** [comment]
On additional thought, agree with Dave.  "Superseded" is fine.  As folks will want to continue to include it, to concurrently support 3.2 and 2.x reading systems.  I'm also fine with "Superseded and marked for removal".

**Comment by mattgarrish** [comment]
Closing as the element was added and marked as legacy in #1029.
