### ISSUE TITLE
Re-add guide element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1015]
Reintroduce the ```<guide>``` element of ```<package>```, but note that it is obsolete and deprecated.  Allow EPUB 3.2 Reading Systems to not support it.

**Comment by dauwhe** [comment]
Guide was deprecated in 3.0.1 and removed in 3.1. Note that even 3.0.1 did not include a definition, but referred to EPUB 2.something. 

Do we actually want superseded? Reading systems must not use the guide if there are landmarks?

**Comment by GarthConboy** [comment]
Okay with Dave's suggestion, or taking a queue from whatever language Matt comes up with for NCX.

**Comment by mattgarrish** [comment]
Closing as the element was added and marked as legacy in #1029.
