### ISSUE TITLE
Re-add trigger element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1018]
Reintroduce but strongly discourage the ```<trigger>``` element.  Allow EPUB 3.2 Reading Systems to not support it.

**Comment by dauwhe** [comment]
How do we do this? I used the word "deprecated" in the draft, but that's not correct, as deprecated means that reading systems must support the feature. Saying superceded is also inaccurate, as that does not strongly discourage authors.

**Comment by GarthConboy** [comment]
I think we let Matt come up with wording proposal -- the concept of "deprecated/superceded and optional for 3.2 RS's to support" is what we want

**Comment by mattgarrish** [comment]
Closing as the element was added and deprecated in #1029.
