### ISSUE TITLE
Draft edupub terms

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1019]
The structural semantics vocabulary still makes reference to draft terms from edupub.

Drop the draft labels and reference to edupub, or leave them as-is? Is anyone realistically going to review the semantics anymore?

**Comment by GarthConboy** [comment]
Hmmm... no strong vote (strangely).  Maybe drop the "draft"?  Matt, your opinion?

**Comment by mattgarrish** [comment]
I would drop the draft status. They've been in there for years now, so pulling them would be controversial, and there's no reason to leave them lingering on as drafts. Let's wrap that up and deal with them like we would any other semantics, whether or not an education-focused group resurfaces to look at them.

The only reference to edupub is the one about the terms still being drafts, so if we drop draft status that reference goes away.

**Comment by TzviyaSiegman** [comment]
I disagree. Dropping the draft label will indicate that these have gone through some sort of formalization process, and we risk that people will start using them. I don't know if people are using them or not, but I don't think it's a good idea to leave the terms in. @RachelComerford do you have a sense of usage of EPUB for Ed terms? If they are not in use, I vote to pull the terms.

**Comment by mattgarrish** [comment]
> and we risk that people will start using them

Aren't they already valid in epubcheck now, or do you have to trigger them with the dc:type to validate?

**Comment by RachelComerford** [comment]
@mattgarrish I believe you have to trigger them with dc:type but I'm not certain

@TzviyaSiegman Macmillan is using these. I'm wondering if @rickj can get data on how many titles coming into VS are using these tags? 

I'm getting the impression overall that we're in the minority for usage. Selfishly, I'd rather not change our internal implementation guide but if we're alone in usage, that makes the most sense.

**Comment by mattgarrish** [comment]
> I believe you have to trigger them with dc:type

No, I just tested and they are valid for use without a dc:type. It used to be the case that you needed one to trigger validation, but I believe when we wrapped up the last iteration and were asking people to go forth and multiply their implementations the draft terms were made universal in epubcheck.

**Comment by mattgarrish** [comment]
But I don't see anything in the epubcheck issues where we requested them be made official...

@rdeltour - do you recall if allowing edupub terms without a dc:type was intentional?

At any rate, they validate to the latest epubcheck, so no matter the answer we're in a bit of a pickle.

**Comment by BillKasdorf** [comment]
@RachelComerford: You're not alone at ML. I know of other educational publishers using the terms.

**Comment by mattgarrish** [comment]
Closing this without any change and removing from 3.2 timeline.

As discussed on the 2018-05-03 telcon, validation of epub:type needs to be addressed in epubcheck.
