### ISSUE TITLE
alternate script(s)?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1020]
While returning the meta properties, I noticed the definition for alternate-script only allows one to be attached to any metadata item. Epubcheck has never enforced this to my knowledge, and I wonder how much awareness there is of it. Even the samples repository has technically incorrect uses of it.

Shall we change it to one or more to reflect reality?

**Comment by GarthConboy** [comment]
That would seem reasonable to me.

@murata2makoto for comment?

**Comment by mattgarrish** [comment]
The [definition has been updated](https://idpf.github.io/epub-vocabs/package/meta/meta.html#sec-alternate-script) in the new vocabulary.
