### ISSUE TITLE
drop "in the metadata section" cardinality

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1021]
The meta properties all have a cardinality of zero or more "in the metadata section", but this is superfluous information. Of course there can be zero or more if each property can have at least one of these properties attached to it.

The properties are not global, so there's never a case where they can appear in the metadata without being 'refined' to something else.

We probably had some good reason why we thought this might reduce confusion, but whatever it was is lost in the sands of time to me, and it just seems to add confusion where none is needed.

**Comment by murata2makoto** [comment]
> The meta properties all have a cardinality of zero or more "in the metadata section"

I am afraid that I do not quite understand.   I have to refresh my memory...

The phrase "in the metadata section" appears in [EPUB Packages 3.2 ](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html) six times.  But "zero or more" appears in [EPUB Metadata Link Vocabulary](https://idpf.github.io/epub-vocabs/package/link/) and [EPUB Manifest Properties Vocabulary](https://idpf.github.io/epub-vocabs/package/item/).    Are you talking about these specifications?

Several attributes in package documents specify properties.  I am afraid that I do not understand which is which.  

- the property attribute of package/metadata/meta and package/collection/metadata/meta
- the scheme attribute of package/metadata/meta and package/collection/metadata/meta
- the properties attribute of package/metadata/link and package/collection/metadata/link
- the rel attribute of metadata/link and package/collection/link
- the properties attribute of manifest/item
- the properties attribute of spine/itemref

Does cardinality mean "within a single attribute" or "within a manifest/item element" or  "within a spine/itemref element" or what?

**Comment by JayPanoz** [comment]
You lost me at “cardinality”, and quite frankly this is not the first instance I, as a non-native speaker, felt awful trouble trying to understand this concept and the issue after researching it – I have a bachelor’s degree in English, FWIW and still, I’m feeling lost, as was the case for “infoset” for web publications. 

It would be nice of native speakers to assume non-native speakers may not get it straightforwardly, as it may end up excluding a lot of people who have feedback to offer.

**Comment by mattgarrish** [comment]
> The phrase "in the metadata section" appears in EPUB Packages 3.2 six times.

These are the meta properties that were stripped in 3.1. If you want to see them, you need to go back to 3.0.1: http://www.idpf.org/epub/301/spec/epub-publications.html#meta-properties-publication

**Comment by mattgarrish** [comment]
> You lost me at “cardinality”

There's nothing specifically "English" about the term; it's the common expression in xml for defining occurrence constraints.

We've seen the problems that arise when non-technical language gets inserted -- like saying to use the first instance of X in the metadata as primary, instead of saying the first encountered in "document order".

But we've also explained cardinality elsewhere: https://idpf.github.io/epub-vocabs/package/item/#sec-item-property-values

Since we're returning the meta vocabulary, I don't have any particular issue providing a similar explanation in the document if it's seen as helpful.

**Comment by mattgarrish** [comment]
Here's what the document can look like with the cardinality simplified and heading descriptions added:

https://idpf.github.io/epub-vocabs/package/meta/meta.html#sec-meta-property-values

**Comment by mattgarrish** [comment]
Closing as document has been modified as in previous comment.
