### ISSUE TITLE
does rendition:spread=both still make sense?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1030]
If the "portrait" value is deprecated, then what to make of "both"? Shouldn't it be deprecated, too?

**Comment by GarthConboy** [comment]
No, I don't think so.  We deprecated "portrait" because it was dumb to want spread only in portrait, but not in landscape.  "Both" is valid and used and supported.

**Comment by mattgarrish** [comment]
But "both" means use a spread when in landscape and portrait orientations, so portrait spreads are only deprecated when asked for individually?

I agree portraits are dumb, so it seems like "both" is half dumb and not necessary anymore.

**Comment by GarthConboy** [comment]
Yes, only "portrait" is deprecated (meaning only do synthetic spreads in portrait, not landscape).  If pages so want to be together so badly that you're willing to do so in portrait (the non-natural orientation for synthetic spreads), "both" is the right choice.  This was our rationale for deprecating "portrait".  This value ("both") is used frequently, and is quite valuable, and should stay.

**Comment by mattgarrish** [comment]
Wouldn't it make sense then to say that a landscape spread should be created regardless of the device orientation? Isn't the user just going to be forced to turn the device anyway?

**Comment by mattgarrish** [comment]
But, regardless, some brief explanation why portrait has been deprecated would probably help (what you say, that portrait spreads are generally useless but if you want to force the user to see that there is a spread  independent of orientation use "both").

**Comment by GarthConboy** [comment]
A reading system may or may not do spreads in landscape -- it may be the default.  But these properties provide publisher control.  By my read, the 3.1 verbiage for this is just fine as is.  If you want to add a note that portrait is deprecated because it makes no sense to force spreads in portrait if they are not also desired in landscape (thus use "both"), that would be fine.

**Comment by mattgarrish** [comment]
My thought would be to put portrait back in the list of values and instead of a definition deprecate it with the following statement:

> The use of spreads only in portrait orientation is deprecated. Authors are advised to use the value "both" instead, as spreads that are readable in portrait orientation are also readable in landscape.

(I'm less and less liking the approach we took of hiding deprecated features in an appendix list, especially when we often have to identify where in content models the deprecated and legacy features are allowed.)

**Comment by GarthConboy** [comment]
That approach is completely fine with me!   😀

**Comment by mattgarrish** [comment]
Closing this issues as it was addressed in PR #1029 and #1034.
