### ISSUE TITLE
HTTP protocol for linked metadata resources?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1032]
I just noticed that we still have 11 open issues related to this:
https://github.com/w3c/publ-epub-revision/issues?q=is%3Aissue+is%3Aopen+label%3ACat-MetaHTTPProtocol

The protocol was an appendix at one point in 3.1, but then there was a decision to move it to an informational document. That's where the trail goes cold for me. It seems like it fizzled out at that point.

Do we intend to resume work on this (in 3.2?) or should we just close off the issues and be done with it?

**Comment by GarthConboy** [comment]
I vote for that latter.  Out of scope for 3.2.

**Comment by mattgarrish** [comment]
Should we just close the issues off, then, or is there any likelihood we'll finish or publish the protocol?

For the record, I believe this is the document as it was last edited:
https://docs.google.com/document/d/1qEd1pOISrMcRpEwNiFwRy04AW5Mc1JbYsqPIhI23i-M/edit#heading=h.18zis1xnzk2i

**Comment by dauwhe** [comment]
Have reading systems requested guidance on how to do this? Do decisions made here affect the authoring of metadata? Would someone who implements this want to read a spec containing bits and pieces of other standards, which in fact are well-understood by the web world? My guess is that the answer to all of these questions is "no." I'm certainly open to arguments on why we need to do this, but I haven't heard those arguments yet.

**Comment by mattgarrish** [comment]
I think it was destined to be an informational note if it got published, so it wasn't going to carry much weight.

It would be nice to start trimming the epub-revision back to just the core specs we tackle during revisions. If work needs to be done on this or other satellite specifications, they should have their own dedicated repositories.

I'd be all for adding something like an "unresolved" label and closing off all issues that aren't related to the core specs and vocabularies. That would allow anyone picking up the work later to find issues we dropped here.

**Comment by mattgarrish** [comment]
Issues have been closed off with a status of "abandoned" as discussed on the 2018-05-03 telecon.
