### ISSUE TITLE
Utility of validating attribute values in epub-type

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1039]
During the CG call today, I brought up the possibility of relaxing the validation of attribute values in `@epub-type`. This was somewhat inspired by an actual problem, where the change from `help` to `tip` in the [structural semantics vocabulary](https://idpf.github.io/epub-vocabs/structure/) (SSV) means that files that follow the 3.0.1 spec (which references the changing SSV) are rejected by epubcheck, but the deprecated value is supported. 

I'm wondering if the costs of restricting attribute values exceeds the benefit. Most `@epub-type` attribute values do not change the behavior of reading systems or assistive technology (the exception being footnotes). The major advantage now is that the system helps people who misspell "footnote" :)

I propose we say people SHOULD use the SSV. And we let the web platform worry about an alternative to `@role` for non-a11y semantic information.

**Comment by GarthConboy** [comment]
Agree.  Fits with my plan for Play Books to "resolve" he help/tip issue!  :-)

**Comment by dauwhe** [comment]
How would we make this happen? The spec [says](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-contentdocs-default-vocab)

> The default vocabulary for Content Documents is defined to be the [EPUB-SSV].

Do we say something like:

> Unprefixed terms that are not part of the SSV may be used, but reading systems have no obligations to support them. 

?

**Comment by GarthConboy** [comment]
That level of liberalness does not offend me (in fact I kinda like it)... but, you know, I'm from California.

**Comment by dauwhe** [comment]
Closed with #1056
