### ISSUE TITLE
deprecate display-seq

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1041]
Related to #992, can we deprecate display-seq and tighten up the document order precedence wherever it matters?

We have conflicting statements from 3.1 if we continue to say that document order must be used in certain cases while allowing display-seq to also define a different order.

**Comment by llemeurfr** [comment]
Deprecating this feature means the reading systems MUST still support it. Does it mean that if no display-seq is included, the document order should be followed for metadata display (= default) but if it is included, the display-seq order should be followed?

**Comment by mattgarrish** [comment]
No, reading systems never had a requirement to support the refinement properties. It was only ever an optional way authors could specify an order, and I don't know that it's ever been supported.

We weren't very clear about how to give precedence for display, which is partly why the property was created, but started clearing that up in 3.0.1/3.1. But now that we're returning the meta properties, we have directives to use document order but will also have display-seq floating around suggesting that perhaps document order can be ignored.

(display-seq also introduced the idea that if the property wasn't present on some metadata, then only the ones with it should be rendered, but that's also inconsistent with saying to use document order.)

If display-seq stays, then we need to go back to where we've said document order must be used and correct the instances to using document order unless some other mechanism exists. But that probably only leads to inconsistency in how to interpret the specs, which is what 3.1 was trying to fix.

**Comment by llemeurfr** [comment]
@mattgarrish, can you point me to a document which defines what EPUB 3 reading systems have the requirement to support or not? I thought that reading systems were to support everything specified (even if nobody did). 
We must remember that Reading system developers will try to create a software that is compliant with EPUB 3.0.1 *and* EPUB 3.2 (which is 100% backward compatible). I'm happy to see display-seq deprecated in 3.2, still we may decide to support it for 3.0.1 compatibility. This is the source of my question.

**Comment by mattgarrish** [comment]
Reading system requirements are generalized in the Reading System Conformance sections, with additional specifics interspersed in the relevant sections. In the case of metadata, there are very few actual requirements on reading systems.

That was part of the original problem. Most reading systems were using document order to give precedence to displaying creators, but one notable reading system was doing the reverse and there was nothing in the specification to say it was incorrect.

Metadata about metadata, which is what the refinement metadata is, has no support requirements that I'm aware of. That means a reading system is compliant by doing absolutely nothing with any of it, which is typically how we've treated all metadata, bibliographic or rendering. That also means if we deprecate display-seq all reading systems that do nothing with it remain fully compliant with the specification.

**Comment by JayPanoz** [comment]
> That was part of the original problem. Most reading systems were using document order to give precedence to displaying creators, but one notable reading system was doing the reverse and there was nothing in the specification to say it was incorrect.

Which eventually led to some authors not using `display-seq` because it didn’t work or getting around “rendition issues” by putting both authors in the same `<dc:creator>` item – it can get political very quickly if a book was co-authored but only one name appears in the running head – or using `contributor` with an artificial `creator` e.g. “Collective.”

**Comment by dauwhe** [comment]
For reference, EPUB 3.1 [says](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-opf-dccreator)

>When determining display priority, Reading Systems must use the document order of creator elements in the metadata section, where the first creator element encountered is the primary creator. If a Reading System exposes creator metadata to the user, it should include all the creators listed in the metadata section whenever possible (e.g., when not constrained by display considerations).

The definition of  `display-seq` is in 3.0.1: http://www.idpf.org/epub/301/spec/epub-publications.html#display-seq

>  The display-seq  property indicates the numeric position in which to display the current  property relative to identical metadata properties (e.g., to indicate  the order in which to render multiple titles).                                      

> When the display-seq property is attached to some, but not all, of the members in a set, only the elements identified as having a sequence should be included in any rendering.

**Comment by dauwhe** [comment]
Does anybody know if there are existing reading systems that use `@display-seq`?

If so, do they refuse to display set members which don't have the attribute?

**Comment by RachelComerford** [comment]
Consensus from 5/17 meeting: Deprecate display-sequence and allow 3.2 RS’s to not support, if it exists, in content its order must match document order.

**Comment by mattgarrish** [comment]
I've deprecated the property here: https://idpf.github.io/epub-vocabs/package/meta/meta.html#sec-display-seq

Do we need to go so far as to say that sequencing must match document order? It's already deprecated, so better people just remove it than go back and re-sequence and leave it.

I don't see anything we need to do about reading systems in this issue, as they generally ignore this property anyway. If we add statement(s) they must use reading order for all package elements, that eliminates any interpretation issues. But I assume we deal with that in #992.

**Comment by GarthConboy** [comment]
We added the "if it exists, in content its order must match document order." after a fair amount of discussion... due to not wanting to allow have two possibilities of prioritization -- a document order one, and a display-seq one (that doesn't match document order) -- solved with adding the requirement that epubcheck can verify.

**Comment by mattgarrish** [comment]
> solved with adding the requirement that epubcheck can verify

Since reading systems will be required to use document order, all changing the semantics does is add an (unnecessary) additional error to implement in epubcheck. Why would I re-sequence the properties just to continue to have an error that their use is deprecated?

Wouldn't it be simpler just to craft one deprecation error message that explains that the property is ignored by reading systems?

**Comment by dauwhe** [comment]
Spec now reads:

> **Use of the display-seq property is deprecated.** Precedence is given to elements in a set based on their appearance in document order in the EPUB Package Document (i.e., the first element in document order has the highest priority).

Is this good enough for the spec, if not good enough for EPUBCheck?

**Comment by GarthConboy** [comment]
I'm okay with that for both – say document order, and epubcheck can complain about deprecated property.

**Comment by dauwhe** [comment]
CG consensus on the telecon today was that the current language is adequate.
