### ISSUE TITLE
Marc relator codes

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1043]
We show lots of examples of using Marc relators in package metadata. But we have no reference to the list of possible values, which led someone to complain on twitter. 

Related: has any reading system ever actually done anything with this sort of information?

**Comment by mattgarrish** [comment]
The marc URL got split out with the reserved prefixes: https://idpf.github.io/epub-prefixes/packages/
It's also now incorrect, as they changed the location from /vocabulary to /marc.

(Like I mentioned in #974, we should probably bring the list back into the specification, as it's not something we're likely to add to much anymore.)

It's still not an easy way to find the relators list, though, as it requires understanding how to craft a URL from a CURIE. We could add an informative reference to an example, but the value of the metadata of metadata in the package document remains questionable. We were on a much better track in trying to farm rich metadata out to external records.

**Comment by dauwhe** [comment]
Do any reading systems use this information, especially those oriented towards libraries? Overdrive, Axis360, Hoopla?

**Comment by mattgarrish** [comment]
> Do any reading systems use this information

One of the reading system survey questions about package metadata we included while preparing 3.1 was whether refines was made use of, and only a few people indicated use of role:

https://docs.google.com/document/d/1dv1357SIB1kFPSkuj_dtMD0PrzewcP7lqZJvtTYJpts/edit#heading=h.qyczb5b6111f

I didn't see any of the library systems represented in the answers, though.

**Comment by HadrienGardeur** [comment]
This is supported in Readium-2 where we map some MARC relator codes to specific schema.org terms.
For the rest of them, we take an approach very similar to EPUB with a generic contributor role + a role.

**Comment by dauwhe** [comment]
> The marc URL got split out with the reserved prefixes: https://idpf.github.io/epub-prefixes/packages/
> It's also now incorrect, as they changed the location from /vocabulary to /marc.

both http://id.loc.gov/vocabulary/ and http://id.loc.gov/marc/ result in 404 errors. 

The list is at 

http://id.loc.gov/vocabulary/relators.html

Are we using more than just the relators list for EPUB?

**Comment by mattgarrish** [comment]
Okay, that's weird. When I tried before I got a 404 on http://id.loc.gov/vocabulary/relators which is what marc:relators is supposed to expand to. Maybe it was just a temporary thing.

It's okay if the stem (http://id.loc.gov/vocabulary) doesn't result in a returned page, although it's not ideal.  Making CURIEs out of these URLs was a bit of a hack on our part to fit the data type model for the property attribute, not something other agencies planned for.

**Comment by dauwhe** [comment]
Right now our example 7 reads:

> The following example shows how to represent a creator as an author using a MARC relators term. 

I wonder if we can help make this more understandable by just hyperlinking "MARC relators" to http://id.loc.gov/vocabulary/relators.html

**Comment by dauwhe** [comment]
Closed with #1056
