### ISSUE TITLE
Highlight "EPUB 3" over specific revisions

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1045]
I've always found our use of version numbering within the specifications a bit confusing, as each revision often sounds like a new version rather than a continuation of EPUB 3 (this is true even for "3.0.1").

My thought is that we should look at revising some of the wording to highlight that all 3.x.x versions are "EPUB 3". To this end, I would change the overview to refer to EPUB 3 everywhere except for a line at the beginning that indicates that 3.2 is the latest definition of the standard.

We should similarly make "EPUB 3" the standard way of referring to the format, leaving 3.2 to document references and the changes document.

For example, this statement from the 3.2 document:

> This specification, EPUB 3.2, defines a distribution and interchange format for digital publications and documents.

Would be rewritten to:

> EPUB 3 defines a distribution and interchange format for digital publications and documents. This specification represents the second major revision of the standard.

Similarly, this:

> EPUB has been widely adopted as the format for digital books (ebooks), and EPUB 3.2 continues to increase the format's capabilities

Could be rewritten as:

> EPUB 3 has been widely adopted as the format for digital books (ebooks), and this revision continues to increase the format's capabilities

Thoughts welcome, though.

**Comment by GarthConboy** [comment]
No objections.

**Comment by RachelComerford** [comment]
Consensus from 5/17 meeting: highlight that all 3.x.x versions are "EPUB 3".  @GarthConboy and @dauwhe to review language

**Comment by dauwhe** [comment]
Closing, as this was fixed by #1046. Thanks Matt!
