### ISSUE TITLE
In Redium Reader CFI - is it possible to go exact CFI location in a reflowable document when search text location are multiple in a page

### ISSUE THREAD

**Issue by VaishNathani** [w3c/epub-specs#1050]
For example, using the readium reader 0.30, If I search for word "two" in my reflowable epub document, if there are 4 occurrences of word "two" on the page and I list 4 results in search result panel on right hand side, with the page number and small amount of text containing the searched word. ideally I should go correct location within the same page depending fragment of text surrounding word that I have searched for. Currently, if I click 2nd or 3rd or 4th search result in the panel, it always takes me to beginning part of the page and not to exact location where the searched word is.

Below is my code

  if (idref !== null) {
      this.ebook.reader.openSpineItemElementCfi(idref, cfi, this.ebook.reader);
}

If there are 4 results for word "two" on a single page, each click on search panel results should take me to right location on the page and not always to beginning of the concerned page. While my code takes me to the correct page each time, it does not take me to particular location within the particular page.

Is this possible? can anyone please guide me how or share a code snippet.

Thanks,
Vaishali

**Comment by JayPanoz** [comment]
Since this issue is related to Readium, it should be reported in https://github.com/readium/readium-shared-js/issues

**Comment by VaishNathani** [comment]
Okay, got it, @JayPanoz  I posted it there. Thanks

Here is the issue.

https://github.com/readium/readium-shared-js/issues/449
