### ISSUE TITLE
Scriptable components prefix

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1051]
The scriptable components spec apparently was never formally approved. I'm not aware of implementations. But the `epubsc` prefix is reserved in EPUB 3.2, and is supported by EPUBCheck. But the URL we provide for the prefix (`http://idpf.org/epub/vocab/sc/`) gives a 302 error for too many redirects.

What do we do? I'm tempted to remove this from 3.2, and file a bug on EPUBCheck.

**Comment by GarthConboy** [comment]
Agree on "never formally approved".  Don't know of implementations, though there were some early  prototypes.  I would tend to think removal from 4.2.3 (https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-metadata-reserved-prefixes) would be acceptable, as said are only conveniences.  Not a serious epubheck issue, regardless.

Brady, agree?

**Comment by bduga** [comment]
Seems reasonable to me to remove.

**Comment by dauwhe** [comment]
Closed with #1056
