### ISSUE TITLE
Core media types list could be better organized 

### ISSUE THREAD

**Issue by mustlaz** [w3c/epub-specs#1063]
The [core media type list](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-core-media-types) organization isn't very useful for the readers of the spec. Media types are currently grouped by the first segment of the media type itself rather than its functional category.

For instance, if I want to see which fonts I should support, the font list is split between the application & font types.

Proposal: Better group media types into the following categories:

- Document/ layout
- Font
- Image
- Video

**Comment by dauwhe** [comment]
Closed with #1069
