### ISSUE TITLE
Consider renaming road map to overview

### ISSUE THREAD

**Issue by mustlaz** [w3c/epub-specs#1064]
Section [road map](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-epub-roadmap) is describing the EPUB format in a human readable way and serves as the entry point to the specification.

The term road map is confusing and seems to imply a timeline.

A term like "Overview" would be represent the idea of the section.

**Comment by dauwhe** [comment]
Fixed with #1065
