### ISSUE TITLE
Reference to WebIDL is outdated

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1070]
The reference in Content Document 3.2 should be https://www.w3.org/TR/WebIDL-1/ rather than https://www.w3.org/TR/2016/CR-WebIDL-1-20160308/

**Comment by mattgarrish** [comment]
Are you reading 3.1 by any chance? I don't see a reference to the CR doc in 3.2. The reference we have resolves to a draft of WedIDL-2, though, which could arguably be changed to [[WEBIDL-1]].

**Comment by murata2makoto** [comment]
My mistake!  But I also think that we should reference [WebIDL-1](https://www.w3.org/TR/WebIDL-1/#Unforgeable).

**Comment by mattgarrish** [comment]
Let's leave this open, though, just in case WebIDL-2 makes it to rec before we publish.

**Comment by dauwhe** [comment]
I'd love the reference be to /TR/WebIDL/, but it seems SpecRef does not have an entry for this. 

Doesn't look like there will be a level 2 REC anytime soon. An attempt to do a FPWD last year was shut down--I get the impression we're in "living standards" territory here, and implementors are working from https://heycam.github.io/webidl/.

So I don't know what to do.

**Comment by mattgarrish** [comment]
We can always create our own entries in the biblio.js file, as I think our need to always reference the latest specification is unique, even if w3c now has a lot of TR links that facilitate it.

We might want to override CSS2, for example, as I was looking at it again and it's an alias for CSS21, which means it won't update. There's a separate entry for CSS22.

**Comment by mattgarrish** [comment]
Or we should confirm if aliases are removed and replaced with hard links when a new version is released (e.g., if CSS21 gets a dated reference and CSS22 becomes an alias of CSS2). I can't tell from the documentation what happens.

**Comment by dauwhe** [comment]
We have a conundrum. The current rec is https://www.w3.org/TR/WebIDL-1/. Looks like there won't be a WebIDL-2. The actual living standard, implemented by browsers and maintained, is   https://heycam.github.io/webidl/.

So is the goal of our reference to be stable, or to be accurate?

**Comment by dauwhe** [comment]
Closed via CG resolution. We're going with accurate :)
