### ISSUE TITLE
Broken Links - EPUB 3.2 Index

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#1073]
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#index

Following links result in 404 errors:
- accessibility
- accessible publications
- authoring and consumption
- discovery metadata
- distribution concerns
- optimized publications

@mattgarrish - Tzviya tells me there's a magic link checker? Was that run yet?

**Comment by RachelComerford** [comment]
Also:
[H264]
H.264 : Advanced video coding for generic audiovisual services. 2016-02-13. URL: https://www.itu.int/rec/T-REC-H.264-201602-P/en

in: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#informative-references

Seems to spin without connecting

**Comment by mattgarrish** [comment]
Not recently, no, but we have to run the link checker as one of the last steps before publishing, along with verifying against the pubrules checker. The link to that program is: https://validator.w3.org/checklink

Usually we generate a static snapshot before running the programs, but I think the link checker runs fine off the respec source (pubrules doesn't).

I'll start verifying the links, as I did a test and a lot of broken fragments were identified. We might have another case of lost IDs in the source.

**Comment by mattgarrish** [comment]
Regarding the H.264 spec, it looks like we have an old reference and the URL has been changed (looks like -P became -S once the version was superseded). 

The 2016-02 page is here: https://www.itu.int/rec/T-REC-H.264-201602-S

But the latest version is here: https://www.itu.int/rec/T-REC-H.264-201704-I

I assume we should update to the latter.

**Comment by mattgarrish** [comment]
Although, I think for this one we should use this page: https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=13189

That way we don't have to worry about the URL becoming invalid when a new revision is published. The referenced revision will still be available for download.
