### ISSUE TITLE
Possible type - epub3.2 references

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#1074]
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#references

[ContentDocs]
EPUB Content Documents 3. URL: http://www.idpf.org/epub3/latest/contentdocs

Should this say:
EPUB Content Documents 3.1 URL: http://www.idpf.org/epub3/latest/contentdocs

**Comment by RachelComerford** [comment]
Same in Packages?

[Packages]
EPUB Packages 3. URL: http://www.idpf.org/epub3/latest/packages

**Comment by mattgarrish** [comment]
They should be [[ContentDocs32]] to match this version. It looks like some /latest references slipped in when we reintegrated the core media types (when that section was separate, it made sense for it to always refer to the latest version).

Same thing for the packages spec ref, too.

**Comment by mattgarrish** [comment]
The inter-spec references should all be fixed now, plus any external links within the body. I've corrected all the /latest links and references, too.

**Comment by dauwhe** [comment]
You are too quick! Thanks.
