### ISSUE TITLE
how to reference epub accessibility?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1075]
The accessibility spec is in a separate directory from the 3.2 specs right now, and I'm not sure where it will ultimately be published (e.g., will it have a separate publishing space, or are all the epub specs published in the same place independent of how we structure them in the repository?).

Why this is a problem is that it's not clear how to reference this document from 3.2. The current references assume the specification is in the same directory, so they're all currently broken.

**Comment by avneeshsingh** [comment]
I think this question follows from the question, are we placing EPUB 3 family of specs in the same directory?
EPUB accessibility 1.0 is in EPUB 3 family of specifications but it is independent of version of EPUB 3.

**Comment by dauwhe** [comment]
Can we just move these to the epub32 directory? Is there anything stopping the CG from republishing EPUB a11y 1.0 as a final community group report when the rest of 3.2 is published? Then we could easily update in place for 1.1.

**Comment by mattgarrish** [comment]
The potential problem is that the accessibility spec is supposed to have some independence from the core specs so that it can be updated on a different cycle, as needed, and not to get confused as only applying to any one version of epub. If they'er all under a /epub32 path, we break that goal.

It would be good to get some clarity on how the specs are published, though, as I'm not even sure what urls the 3.2 specs will have. The directory structure we're using probably doesn't translate into the published urls, in which case it might not matter if they're together.

**Comment by clapierre** [comment]
Publishers are about to start getting certified as being accessible and the conformsTo link will be


The value of the conformsTo property must be one of the following IRIs:

http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-a

The EPUB Publication meets all accessibility requirements<http://www.idpf.org/epub/a11y/#sec-conf-epub> and achieves [WCAG 2.0]<http://www.idpf.org/epub/a11y/#refWCAG20> Level A conformance<https://www.w3.org/TR/WCAG20/#conformance-reqs>.

http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-aa

The EPUB Publication meets all accessibility requirements<http://www.idpf.org/epub/a11y/#sec-conf-epub> and achieves [WCAG 2.0]<http://www.idpf.org/epub/a11y/#refWCAG20> Level AA conformance<https://www.w3.org/TR/WCAG20/#conformance-reqs>.

http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-aaa

The EPUB Publication meets all accessibility requirements<http://www.idpf.org/epub/a11y/#sec-conf-epub> and achieves [WCAG 2.0]<http://www.idpf.org/epub/a11y/#refWCAG20> Level AAA conformance<https://www.w3.org/TR/WCAG20/#conformance-reqs>.

Do we need to update this to a W3C URL?


Thanks
EOM

Charles LaPierre
Technical Lead, DIAGRAM and Born Accessible
E-mail: charlesl@benetech.org<mailto:charlesl@benetech.org>
Twitter: @CLaPierreA11Y
Skype: charles_lapierre
Phone: 650-600-3301

**Comment by avneeshsingh** [comment]
I believe this can be handled by publishing an errata.

**Comment by mattgarrish** [comment]
I would leave the 1.0 links alone. We discussed this problem generally for EPUB in #998.

Changing only matters when we publish 1.1 and need a new identifier for conformance again.

But there's a case for not republishing a published specification here. And we'll need some way to reference the latest published version of the specification. I don't know if notes get paths like that.

**Comment by dauwhe** [comment]
I think we have consensus that an undated reference to EPUB A11Y is the way to go. We need to decide how we want to structure the web space of 3.2, and how it relates to EPUB A11Y.

**Comment by dauwhe** [comment]
For now, are we OK with a link from EPUB 3.2 to http://www.idpf.org/epub/latest/accessibility ?

Is the version in W3C space (https://www.w3.org/Submission/epub-a11y/) of any use?
