### ISSUE TITLE
Notes from Editorial review of Packages spec

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#1076]
http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html

3.4.7.1 The meta Element: In the phrase " It is replaced in EPUB 3 by the updated meta element, which uses different attributes and requires text content." the link to the "meta element" rwrongly refers to Section 5. EPUB Navigation Document
D.2.8 The heading "xml-record" should be corrected to "xmp-record". The same correction should be done for the "Name:" just below.
E.2.1 cover-image: The link to [EPUB3] in "Applies to" goes to Section H. References EPUB, but the link to IDPF's latest EPUB spec is broken (due to too many redirects)
E.2.3 nav: Should the [Packages] link really refer to the old version of the Packages document?

c/o Wolfgang Schindler

**Comment by mattgarrish** [comment]
I've corrected these in a couple of commits I made when I saw the email this morning.
