### ISSUE TITLE
Should media type of woff2 font be only font/woff2?

### ISSUE THREAD

**Issue by ghost** [w3c/epub-specs#1077]
From here https://www.w3.org/2002/06/registering-mediatype2014.html it seems not only `font/woff` but `font/woff2`, `font/snf`... are all proposed for woff2 and they are still in WD. Wonder if there is a tentative description saying media type of woff2 could be changed?

**Comment by mattgarrish** [comment]
I don't believe that's what is being indicated. A new "font" top-level media type is being defined in https://tools.ietf.org/html/rfc8081 but the WOFF 2 appendix used to contain declarations for various new font types, not just the one for WOFF 2 (e.g., "font/woff" is the new media type for WOFF 1.0, to replace application/font-woff).

If you look at the change notes, the registrations, excluding WoFF 2.0's, were removed in 2015 in deference to the RFC (looks like the w3c table is out of date).

But I think there's a case that our core media types should also accept the new font/* media types for the currently listed fonts if we're already including font/woff2.

**Comment by ghost** [comment]
My other question related to this is from RS actually just leave this to UA so what RS should do if media type publisher provided in book is not listed up in spec?

**Comment by dauwhe** [comment]
Can we do the following? 

### Open Type
application/vnd.ms-opentype
application/font-sfnt
font/otf

### TTF

application/font-sfnt
font/ttf

### WOFF
application/font-woff
font/woff

### WOFF2
font/woff2

**Comment by mattgarrish** [comment]
Works for me. We can revisit the "preferred" media types whenever font/* get wide use.

**Comment by murata2makoto** [comment]
[RFC 8081](https://tools.ietf.org/html/rfc8081) by Chris is a PROPOSED STANDARD of IETF.  It deprecates "application/font-woff" and "application/font-sfnts".

**Comment by dauwhe** [comment]
> RFC 8081 by Chris is a PROPOSED STANDARD of IETF. It deprecates "application/font-woff" and "application/font-sfnts".

I think being relatively permissive with our media types is reasonable. Will EPUB reading systems stop loading fonts someday if the package file uses `application/font-woff`?

**Comment by murata2makoto** [comment]
@dauwhe @svgeesus Should we at least deprecate the use of application/font-woff?

**Comment by mattgarrish** [comment]
Didn't we already agree not to deprecate media types because it will cause conflicts in the ecosystem between those who support older definitions of the standard and those who support new? We've been recommending application/font-woff since the release of 3.0, so, while probably not as prevalent as text/javascript, it's in the same boat.

The CMT table says that the first listed is the preferred media type, which would allow epubcheck to report a preference without causing errors. We can list font/woff first if that's appropriate.

**Comment by dauwhe** [comment]
Closed via #1104
