### ISSUE TITLE
Clarify dc:language does not affect rendering

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1078]
Similar to the [note we added in wpub](https://www.w3.org/TR/wpub/#language-and-dir-infoset), it would be good to state that the dc:language value(s) are not used in rendering the content.

**Comment by ghost** [comment]
Sorry I don't quite understand "`are not used in rendering the content`" here. I think there is use case that a reading system use this to inject web font to override system serif font in css.

**Comment by mattgarrish** [comment]
Sure, all I meant is, like the wpub note, that the values are not inherited by the content documents.

**Comment by JayPanoz** [comment]
> Sure, all I meant is, like the wpub note, that the values are not inherited by the content documents.

Yeah stating this explicitly is a good idea as it isn’t a given (clarification).

It’s worth mentioning there are existing cases in which it is “artificially” inherited and/or used for rendition though (title of the issue).

- https://gist.github.com/dvschultz/3a3c4836458aceca744d#file-bkcontentcleanup-L201
- https://help.apple.com/itc/booksassetguide/#/itccf6b30e09

**Comment by dauwhe** [comment]
Our spec [says](
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-opf-dclanguage):

> The [DC11] language element specifies the language of the content of the given Rendition.

The WPUB note referenced above says:

> It is important to differentiate the language of the publication from the language and the base direction of the individual resources that compose it. If such resources are, for example, in HTML, the language and direction need to be set in those resources, too. The language and base direction of the publication are not inherited.

Can we do something like:

> The [DC11] language element specifies the language of the content of the given Rendition. This value is not inherited by the individual resources of the Rendition, and does not affect the rendering of the content.

**Comment by dauwhe** [comment]
Closed via #1120
