### ISSUE TITLE
ban w3.org from custom collection identifiers?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1079]
In the nether regions of the spec where importance fades to irrelevance, I noticed this statement:

>  Custom roles MUST NOT incorporate the string "idpf.org" in the host component of their identifying IRI.

https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-collection-elem

Should we add "or w3.org" just to show we're serious about our turf?

**Comment by dauwhe** [comment]
How can I oppose an issue expressed so poetically? But say I want to define the parts of a book using a collection:

```xml
<collection role="https://www.w3.org/TR/dpub-aria-1.0/#doc-part">
        <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
            <dc:title>Part 1: Early Years</dc:title>
        </metadata>
        <link href="html/chapter-001.xhtml"/>
        <link href="html/chapter-002.xhtml"/>
        <link href="html/chapter-002.xhtml"/>
    </collection>
```

This seems semantically correct, doesn't cause harm to the ecosystem, and would be valid in 3.0.1. I don't see why this should be illegal in 3.2.

**Comment by mattgarrish** [comment]
Hm, I was going to say that the CG controls anything in idpf.org or w3.org, but that doesn't appear to be the case. The CG only owns the NMTOKEN values. Good show!
