### ISSUE TITLE
Link is missed for `Core Media Type Resource` in "Content Type Definition" 

### ISSUE THREAD

**Issue by ghost** [w3c/epub-specs#1080]
> Content Type Definition—The specification to which the given Core Media Type Resource has to conform.

Here seems link for `Core Media Type Resource` is missed. In above line `Core Media Type Resource` has link to "https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#dfn-core-media-type-resource"

**Comment by mattgarrish** [comment]
We only link the first instance of a term in a section to its definition, not every one, to avoid link overload.

**Comment by ghost** [comment]
ok I see. I will close this one. I am not very familiar with the editor rules here.
In that case for example in "4.2 Resource Locations" there are two "Remote Resources" both have link.

**Comment by mattgarrish** [comment]
Yes, that second one shouldn't be linked, but there's never been an effective way to ensure the links are being applied correctly beyond eyeballing them, so there will be inconsistencies. If you see an a linked definition, though, the rule is not to add another.
