### ISSUE TITLE
Indent is off in section "4.2 Resource Locations" in Firefox (v61.0.1, Windows 10) 

### ISSUE THREAD

**Issue by ghost** [w3c/epub-specs#1081]
> Audio resources MAY be located outside the EPUB Container.
>  Video resources MAY be located outside the EPUB Container.
>  Resources retrieved by scripts MAY be located outside the EPUB Container, but the [HTML] and [SVG] script elements MUST NOT reference Remote Resources to ensure availability at runtime (i.e., from their src or href attributes, respectively).

**Comment by dauwhe** [comment]
Interesting. The indents look good to me in Chrome/Mac but look weird in Firefox/Mac. Looking into it. 

https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-resource-locations

**Comment by mattgarrish** [comment]
I see the same thing in Chrome/Firefox on Windows, so must not be the O/S.

**Comment by dauwhe** [comment]
Respec is inserting the spans with the list marker. These float. It looks like some sort of line-height calculation is preventing these from stacking vertically in my firefox.

**Comment by dauwhe** [comment]
<img width="553" alt="screen shot 2018-07-31 at 3 30 04 pm" src="https://user-images.githubusercontent.com/5687700/43482590-22009dee-94d7-11e8-92ad-e7fdbea63bf7.png">

**Comment by mattgarrish** [comment]
There's code in one of the common/js files formatting those. The markers were a customization of the old docbook conversion. Feel free to play with it, as it's all our mods.

**Comment by mattgarrish** [comment]
I think it's the addition of overflow-wrap: break-word that's causing the problem. If I disable that (and word-wrap: break-word, which then gets enabled), the indenting goes away. It's the only significant difference between the respec-added styles and how they used to be formatted in IDPF.

But we might just get rid of the float on these. I can't see that it does much of anything, and that also stops the problem.

**Comment by ghost** [comment]
How do we generate html from github? I can take a look a bit later as well.

**Comment by ghost** [comment]
Sorry I forgot to add environment, just changed title

**Comment by mattgarrish** [comment]
W3C uses respec for authoring, but there's custom code to insert the clickable anchors in the conformance requirement lists here: https://github.com/w3c/publ-epub-revision/blob/master/epub32/spec/common/js/confreq-permalinks.js

The custom CSS for these (pulled over from the IDPF specs) is here: https://github.com/w3c/publ-epub-revision/blob/master/epub32/spec/common/css/common.css

Respec injects its own styles, so that's where the conflict appears to have come from, as the old IDPF specs don't exhibit this problem.

**Comment by ghost** [comment]
oic, thanks @mattgarrish, gonna check it out.

**Comment by mattgarrish** [comment]
Strip the float on this one and be done with it?
