### ISSUE TITLE
destructure 3.2 intro sections?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1084]
I don't see the value in separating Organization from the Introduction -- it's all intro material -- plus the titles get a bit confusing (an overview last, for example). What about merging them as follows:

1. Introduction
   1.1 Specifications
   1.2 Organization (previously Overview)
   1.3 Terminology
   1.4 Conformance

**Comment by dauwhe** [comment]
Yes! Much better.
