### ISSUE TITLE
Core media types support requirement is confusing

### ISSUE THREAD

**Issue by BCWalters** [w3c/epub-specs#1085]
> These resources are divided into two categories: those that EPUB Reading Systems have to support (Core Media Type Resources) and those that they do not (Foreign Resources).

This implies a "MUST" for reading systems to support all of the core media types. Many reading systems do not support PLS or media overlays, and it also contradicts other text in the spec:
> If it has the capability to render pre-recorded audio, it MUST support the audio Core Media Types and SHOULD support Media Overlays [MediaOverlays32].

Perhaps the intent is to say that reading systems and tools must allow all of these media types to be present without rejecting the entire publication. If so, the text should be clarified to state this explicitly.

**Comment by mattgarrish** [comment]
Hm, yes, I see what you mean. There are two things being rolled into one: media types that have to be supported and media types that are allowed in the container without fallback. PLS falls into the latter category, with media overlays, both of which are optional for RS support per their definitions (plus others like NCX fall into this group).

I think this statement needs to be stripped from 2.2:

> It MUST support all Core Media Type Resources.

as the requirement to support individual blocks of core media types are listed below that statement (or in more specific locations in their respective specifications). If there are any media types that "must" be supported that we lack a statement for, we should address those separately.

CMTs can then be clarified as being allowed without the need for fallbacks, but it probably requires some review across documents to ensure the same messaging is being used everywhere.

**Comment by murata2makoto** [comment]
I welcome this clarification.  So, CMTs are media types allowed in the container without fallback.  RS requirements are specified for each core or non-core media types.  Is this correct?

**Comment by mattgarrish** [comment]
> CMTs are media types allowed in the container without fallback. RS requirements are specified for each core or non-core media types.

Yes, we can't broadly say that support is required for CMTs, because even in 2.2 most of the requirements are conditional on the reading system having the capabilities (e.g., if it has a viewport, then it must support X, or if it has audio capabilities, then it must support Y). NCX is explicitly required to not be supported, further making a mess of the definition.

The only really consistent thread is that CMTs are allowed without fallback.

I also just noticed that the statement about video is reversed per this definition. It's not that we don't define any video as core media types, but that all video are considered core media types. It's support that is optional.

**Comment by mattgarrish** [comment]
We've drifted away from this original meaning over the years, but going back to 3.0 a CMT was defined as:

> Core Media Type Resource
> A Publication Resource that is a Core Media Type and may therefore be included in the EPUB Publication without the provision of fallbacks.
>
> Core Media Type
> A set of Publication Resource types for which no fallback is required. Refer to Publication Resources for more information.

I think we tried to simplify the dual requirements of support and fallbacks by combining both into the definition of core media type, but it only works for a smaller subset of resources that are listed in the table.

**Comment by dauwhe** [comment]
Closed via #1096
