### ISSUE TITLE
The optional links element in container.xml has no stated purpose or example

### ISSUE THREAD

**Issue by BCWalters** [w3c/epub-specs#1088]
[3.5.2.1 Container File (container.xml)
](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-ocf.html#sec-container-metainf-container.xml)

>The OPTIONAL links element identifies resources necessary for the processing of the OCF ZIP Container. Each of its child link elements MUST include an href attribute whose value identifies the location of a resource. Each link element also MUST include a rel attribute whose value identifies the relationship of the resource, and MAY include a media-type attribute whose value MUST be a media type [RFC2046] that specifies the type and format of the resource referenced by the link.

It's very unclear to readers why this links element exists and what it might be used for since the purpose isn't described and there are no examples of it.

**Comment by mattgarrish** [comment]
It was added to make the multiple renditions specification valid, but as multiple renditions haven't gained any real traction and are not part of the core specifications, there's no realistic example we can provide.

**Comment by mattgarrish** [comment]
Here's the theory behind the element: http://www.idpf.org/epub/renditions/multiple/#sec-4.4.4

**Comment by dauwhe** [comment]
Closed via #1106
