### ISSUE TITLE
Requirement for audio element in media overlays contradicts TTS section

### ISSUE THREAD

**Issue by BCWalters** [w3c/epub-specs#1089]
These two sections seem to contradict each other:
[3.2.4 Text-to-Speech](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-mediaoverlays.html#sec-tts)
>When a Media Overlay text element with no audio sibling element references an element within the target EPUB Content Document, the contents of that referenced element MUST be appropriate for rendering via TTS

[2.4.8 The audio Element](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-mediaoverlays.html#sec-smil-audio-elem)
>Usage
>A REQUIRED child of the par element unless its sibling text element refers to audio or video media, in which case it is OPTIONAL (see Embedded Media).

The audio element doesn't seem to be required when it's sibling points to text that can be read with TTS. Text in the audio element section should be tweaked to reflect that.

**Comment by mattgarrish** [comment]
Yes, that statement is definitely wrong. The par element definition is clearer on this:

> The audio element is optional only if its sibling text element refers to audio or video media (see Embedded Audio and Video), or to textual content intended for rendering via Text-to-Speech (TTS).
