### ISSUE TITLE
"change log" EPUB v3.1 - v3.2

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-specs#1097]
The [list of changes for `3.2`](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-changes.html) seamlessly include the [changes from `3.0.1` to `3.1`](http://www.idpf.org/epub/31/spec/epub-changes.html).

For example, "epubReadingSystem Object Clarifications":
`3.2`:
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-changes.html#sec-cdoc-rso

`3.1`:
http://www.idpf.org/epub/31/spec/epub-changes.html#sec-cdoc-rso

For those (like me) who would like to know what actually changed between `3.1` and `3.2`, would it be possible to explicitly annotate `3.2` changelog entries that are "inherited" from the `3.1` changelog? (if possible, with links / cross-references too?)

Thanks! :)

**Comment by GarthConboy** [comment]
Hmmm... a reason not to do this would be that if 3.1 is "withdrawn" it really ceases to exist.  That's why I kinda like 3.2 being the update from 3.0.1.

But reasonable people can have different views here!

**Comment by mattgarrish** [comment]
The issues we're addressing in this revision are also all marked with the 3.2 milestone in github, so if you just want to see what's been done post-3.1 you can have a look at: https://github.com/w3c/publ-epub-revision/issues?q=is%3Aissue+milestone%3A%22EPUB+3.2%22+is%3Aclosed

**Comment by danielweck** [comment]
Thanks @mattgarrish that's a useful "diff" tool indeed.
@GarthConboy I can go along with that rationale :)
Feel free to mark as resolved and close. Works for me.

**Comment by dauwhe** [comment]
Closed by CG resolution and consent of original reporter.
