### ISSUE TITLE
How to represent Kana for book title/author name/publisher name rather than using "file-as"?

### ISSUE THREAD

**Issue by ghost** [w3c/epub-specs#1098]
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-file-as
"file-as" is very convenient to add additional information on item, but it is pretty hard for Reading System to process.

For example following snippet from epub 3 spec "file-as" is used for different script.
```
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    …
    <dc:creator id="creator">Haruki Murakami</dc:creator>
    <meta refines="#creator" property="role" scheme="marc:relators" id="role">aut</meta>
    <meta refines="#creator" property="alternate-script" xml:lang="ja">村上 春樹</meta>
    <meta refines="#creator" property="file-as">Murakami, Haruki</meta>
    …
</metadata>
```
However in some Japanese book template we can see "file-as" is used for pronunciation information (Kana) 
```
<dc:title id="title">蜘蛛の糸</dc:title>
<meta refines="#title" property="file-as">クモノイト</meta>
```
And since they are all in "file-as" that RS could not process correctly to know which one is Kana which one is script. Do we have better way to define it rather just fall into "file-as" (more like a misc)?

**Comment by danielweck** [comment]
> For example following snippet from epub 3 spec "file-as" is used for different script.

Actually, in this particular case the `file-as` value ("Murakami, Haruki") refines the *same script* ("Haruki Murakami").

> However in some Japanese book template we can see "file-as" is used for pronunciation information (Kana)

Actually, in this particular case the `file-as` value ("クモノイト") refines a *different script* ("蜘蛛の糸"), respectively: BCP47 `ja-Kana` vs. `ja` (or `ja-Hani`, if I am not mistaken).

Or am I missing something? Thanks!

**Comment by ghost** [comment]
Yes just realized maybe following snippet would be better to make Kana more useful. Thanks @danielweck 

```
<dc:title id="title">蜘蛛の糸</dc:title>
<meta refines="#title" property="alternate-script" xml:lang="ja-Kana">クモノイト</meta>
```

And
```
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    …
    <dc:creator id="creator">Haruki Murakami</dc:creator>
    <meta refines="#creator" property="role" scheme="marc:relators" id="role">aut</meta>
    <meta refines="#creator" property="alternate-script" xml:lang="ja">村上 春樹</meta>
    <meta refines="#creator" property="alternate-script" xml:lang="ja-Kana">ムラカミ　ハルキ</meta>
    <meta refines="#creator" property="file-as">Murakami, Haruki</meta>
    …
</metadata>
```

**Comment by danielweck** [comment]
Yes, `alternate-script` makes more sense to me :)
