### ISSUE TITLE
Font resources out of EPUB container: impact on long-term accessibility

### ISSUE THREAD

**Issue by bitsgalore** [w3c/epub-specs#1101]
[Section 3.2 of the EPUB spec](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-foreign-restrictions):

> Font resources MAY be located outside the EPUB Container.

I 'm wondering about the rationale behind this change, as it would create a potential problem for long-term accessibility: once the externally hosted fonts are taken offline, the EPUB won't render as originally intended. This would be particularly problematic for memory institutions such as archives and (national ) libraries. If the adoption of externally-hosted fonts would catch on amongst the publishing industry, this could seriously complicate the efforts such institutions to ensure the long-term accessibility.

That aside, in the short run it would also affect offline viewing.

**Comment by jcsalomon** [comment]
As I understand it, the rationale is file size: a group of e-books might all use the same custom fonts without those files being stored multiple times on a space-limited device.

There should probably be a caution that such fonts ought not to be essential for reading the book, but the standard is perhaps not the place for this.

As for archives, I would recommend editing the files when they are archived to embed the fonts.

**Comment by ghost** [comment]
I think by "MAY be located outside the EPUB Container" we just provided an option.

Even though creator does not use webfont they don't know what font is installed in the platform that hosting Reading System. Which means, EPUB won't be rendered as originally intended anyway unless creator embed font file inside epub.
Yes referring to externally-hosted font in EPUB could effect on offline reading but if creator really want to care about offline reading then embedded font would be a good alternative.
To introduce external font is just add an option that creator can use.

**Comment by bitsgalore** [comment]
@jcsalomon Thanks for the explanation. 

As for your suggestion that archives embed the fonts themselves: this is unlikely to happen for a number of reasons. First of all it would raise ethical concerns, since as a national library our primary task is to *preserve* publications that are deposited to us. Trying to *improve* them (even by something seemingly innoceous as adding a font) is simply not our job, and  would even be detrimental to  our trustworthiness.

That aside, looking at the EPUBs that are currently deposited to us, there is already a wild variety of ways in which publishers implement (and sometimes abuse) the EPUB standards. The resulting lack of uniformity would seriously complicate any attempt to automatically "fix" things like missing fonts.

@rakutenjeff you're right of course that it's just an option, but  I'm slightly concerned that publishers may be tempted to use it by default.

**Comment by ghost** [comment]
Yes it make sense. I think this can be resolved in two ways.
1. use epubcheck (currently I did not see it) or any check tool to notice if there is web font used in contents.
2. maybe suggest CSS WG to add something say loading the style with alternative font when offline? In this case creator does not need to create two version of contents one for offline and one for online.

**Comment by danielweck** [comment]
@jcsalomon 
> As for archives, I would recommend editing the files when they are archived to embed the fonts.

I'd be concerned about potential legal implications (i.e. online vs. bundled fonts licensing terms).

**Comment by ghost** [comment]
@dauwhe

**Comment by JayPanoz** [comment]
> I'd be concerned about potential legal implications (i.e. online vs. bundled fonts licensing terms).

Had to deal for a very long while with that. In theory it is and could be in practice. 

Typically though, foundries/font providers have an “ebook-specific licence”, which explicitly tells you can’t use online/print/PDF/app, with the following MUSTs: 

1. font must be embedded;
2. font must be subset;
3. font must be obfuscated.

So if you find an “online font” whose licence is paid, chances are the publisher has pretty much done a breach of licensing conditions already. 

Mind you, not saying this couldn’t change at some point. 

Speaking of which, breach of license is already massive with embedded fonts†. A lot of the embedded fonts out there are unlicensed as they’re automatically output by authoring software for instance, and nobody checked whether it was permitted by the licence they already had. 

† Had a private joke with a few friends: “if a foundry checked ebooks licensing, it would probably become billionaire overnight.”

**Comment by laudrain** [comment]
For all the publishers of our group, I recommend no font embedding at all.
Only if 1) the author wants this specific font, 2) the publisher has paid the ebook specific licence.
Then for almost all our EPUB files, the reading experience rely on the reading system fonts that the user can choose at will.

**Comment by dauwhe** [comment]
@rakutenjeff wrote:

> maybe suggest CSS WG to add something say loading the style with alternative font when offline? In this case creator does not need to create two version of contents one for offline and one for online.

`font-family` can be used to provide fallbacks for web or system fonts that might not be available at all times:

```css
/* web font */
@font-face {
  font-family: Gentium;
  src: url(http://example.com/fonts/Gentium.woff);
}
/* embedded font, used if web font is not available */
@font-face {
  font-family: STIX;
  src: url../(fonts/STIXRegular.otf);
}

h1 { font-family: Gentium, STIX, serif; }

```

**Comment by ghost** [comment]
Yes the embedded font is added by author/publisher so we as RS don't mind if there is any embedded font inside and we don't check license for embedded font inside content.
In terms of letting user to choose which font to use Kobo has feature to let user (reader) select from some system fonts to override `Publisher Default` font.

**Comment by dauwhe** [comment]
> For all the publishers of our group, I recommend no font embedding at all.
> Only if 1) the author wants this specific font, 2) the publisher has paid the ebook specific licence.
> Then for almost all our EPUB files, the reading experience rely on the reading system fonts that the user can choose at will.

We embed fonts when we need glyphs that might not be built into reading systems. We always use open-source fonts for this. There is no archival or legal risk.

**Comment by ghost** [comment]
oh, yes font fallback should work. Thanks @dauwhe

**Comment by dauwhe** [comment]
I can't immediately find the discussion that led to this change in 3.1. But web fonts are ubiquitous these days, and forbidding their use creates more distance between EPUB and the rest of the web. Reading systems have no obligation to support remote fonts, and the use of fallback mechanisms for fonts in CSS is well known. I believe authors can understand the tradeoffs involved.

This does cause an issue for archiving, as do all remote resources such as video.

**Comment by dauwhe** [comment]
The CG discussed this on 23 Aug 2018, and resolved to close with no change. We acknowledge the potential issues with archiving, but feel that rendering issues can be adequately solved with font fallbacks.
