### ISSUE TITLE
Security implications of allowing scripts to retrieve resource outside the EPUB container?

### ISSUE THREAD

**Issue by bitsgalore** [w3c/epub-specs#1102]
From [Section 3.2](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-resource-locations):

> Resources retrieved by scripts MAY be located outside the EPUB Container

I do wonder about any potential security implications, as this would allow a script to retrieve ANYTHING, which sounds like something that could be easily be abused to create malicious EPUBs (e.g. a script could retrieve a malicious executable).

I'm not by any means an expert on this myself, but I do wonder whether scenarios like the above have been taken into conideration?

**Comment by dauwhe** [comment]
The part of the spec that discusses scripting does have a [section on security](
http://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-scripted-content-security)

There is some discussion of this in #837

**Comment by dauwhe** [comment]
Closed per CG resolution 23 August 2018.
