### ISSUE TITLE
Content document definition CSS?

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#1108]
In the Specs it says
EPUB Content Documents [ContentDocs32] — defines profiles of XHTML, SVG and CSS for use in the context of EPUB Publications.

However in the Organization it says

This content is built on the Open Web Platform and comes in two flavours: XHTML and SVG. Called EPUB Content Documents, these documents typically reference many additional resources required for their proper rendering, such as images, audio and video clips, scripts and style sheets.

So why is CSS called out as one of 3, but not included in the other directly.

**Comment by mattgarrish** [comment]
"EPUB Content Documents" is both a specification and a class of document types. In the first context you cite, the description is for the specification, whose primary focus is on those three major profiles.

But an EPUB Content Document as a concept is restricted to XHTML and SVG documents - the things you put in the spine. The second instance you've cited refers to those, so CSS is only listed in the supplementary resources that make them up.

**Comment by clapierre** [comment]
Ok, I buy that just is confusing, as why it wasn't called out.. not sure how to make it clearer.

**Comment by dauwhe** [comment]
At this stage, I don't see how we can change the name of either the concept or the spec. At least we're better off than the CSSWG, which has a hundred different meanings for "box".
