### ISSUE TITLE
Conformance and Discovery Requirements

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#1109]
In Section 1.1
EPUB Accessibility [EPUBAccessibility] — defines accessibility conformance and discovery metadata requirements for EPUB Publications.

This makes it sounds like its all about the metadata.
I suggest removing "metadata"

EPUB Accessibility [EPUBAccessibility] — defines accessibility conformance and discovery requirements for EPUB Publications.

**Comment by mattgarrish** [comment]
SGTM

**Comment by dauwhe** [comment]
Closed via #1114
