### ISSUE TITLE
Subsection and Section both called "Conformance"

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#1110]
1.4 Conformance

2. Conformance

I suggest 1.4 Conformance Statements

**Comment by dauwhe** [comment]
http://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#conformance

**Comment by mattgarrish** [comment]
1.4 is an auto-generated heading that respec injects. Might be easier just to rename the second section to "Conformance Classes". Same occurs in the Packages spec.

**Comment by dauwhe** [comment]
> "Conformance Classes"

Maybe "Conformance Criteria"?

**Comment by clapierre** [comment]
Works for me, although I got the Conformance Statements from another spec, not sure where now.

**Comment by dauwhe** [comment]
Closed via #1113
