### ISSUE TITLE
Version #'s in red

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#1111]
Why is the version and version # in red?

2.2
Backward Compatibility
  It MUST attempt to process an EPUB Publication whose version is lower than "3.0".
(3.0 is in red) (the word  "version" is not in red in this case)

Forward Compatibility
  It SHOULD attempt to process any given Rendition of an EPUB Publication whose Package Document version attribute designates a version higher than "3.0".
(both the word "version" and 3.0 are in red) 
Need to at least have some other indication other than color here if its important to call this out.

**Comment by mattgarrish** [comment]
Tags, classes, properties, values, etc. are tagged using the HTML ```code``` element which gets styled in red fixed-width font. I don't think there's anything more we can do in terms of semantic markup.

**Comment by dauwhe** [comment]
Note this is in the [reading system conformance](
http://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#sec-epub-rs-conf) part of the EPUB spec

**Comment by clapierre** [comment]
sure but then why wasn't "version" in red in 
Backward Compatibility
It MUST attempt to process an EPUB Publication whose **version** is lower than "3.0".

but was red in the 2nd case, seems like code element is missing here.

**Comment by mattgarrish** [comment]
It looks like that wording got changed in 3.1 - not for the better. It uses natural language instead of a reference to the "Package Document version attribute", hence the loss of a code tag. I'm fine making the two statements consistent again.

**Comment by dauwhe** [comment]
Closed via #1113
