### ISSUE TITLE
EPUB Packages 3.2 refers to the EPUB 3.1 Package Document Schema 

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1115]
The schema for Package Documents referred to in [Appendix A](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#app-package-schema) is in the EPUB 3.1 URL space: http://www.idpf.org/epub/31/schema/package-31.nvdl.

I'm not sure what the CG decided about maintaining schemas and making them normative or not (see discussion in #1024), but if this section holds then the schema should probably be moved along to the EPUB 3.2 space.

**Comment by murata2makoto** [comment]
I think that Annex A should be kept and the URL should be updated for the 3.2 version of the NVDL script.

**Comment by dauwhe** [comment]
Fixed via #1148
