### ISSUE TITLE
Consider removing the "EPUB3CG" pseudo-acronym in Package Document Appendix B

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1116]
Second paragraph of EPUB Packages Appendix B reads:

> The Package Document and its related standards are maintained and defined by the W3C’s EPUB 3 Community Group (EPUB3CG).

This probably comes from a direct porting of previous prose which referred to:

> the International Digital Publishing Forum (IDPF)

However, where "IDPF" was a commonly used acronym, I don't think "EPUB3CG" is used anywhere? For one thing, it's not used anywhere else in the spec.

I'd suggest removing this parenthesis, and maybe link to the CG's home page instead.

**Comment by dauwhe** [comment]
Fixed via #1119
