### ISSUE TITLE
Consider replacing "standard" with "specification" in EPUB Packages 3.2 Appendix B

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1117]
[Appendix B](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#app-media-type-app-oebps-package) reads:

> The Package Document and its related standards are maintained and defined by the W3C’s EPUB 3 Community Group

and later:

> There is no current provision in the EPUB Packages 3.2 standard for encryption, signing, or authentication within the Package Document format.

This was ported from old prose, but as the document is not on Rec Track, maybe it should be called a "specification" instead?

**Comment by dauwhe** [comment]
Fixed via #1119
