### ISSUE TITLE
Add a contact person for the Media Type registration?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1118]
The media type registration in EPUB Packages 3.2 [Appendix B](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#app-media-type-app-oebps-package) has a section called "Person & email address to contact for further information", coming from the template defined in [RFC4288](https://tools.ietf.org/html/rfc4288#section-4.10).

Our spec only puts the EPUB 3 CG public email address there; I don't know if naming a person is mandatory? Possibly we could use an "anonymous" position like "Chair of the EPUB 3 CG, public-epub3@w3.org".

**Comment by dauwhe** [comment]
We were following some examples from other W3C specs, which seem to use the public mailing list. See https://www.w3.org/2002/06/registering-mediatype2014.html for interesting information.

**Comment by rdeltour** [comment]
OK, sounds good. Feel free to close 😄
