### ISSUE TITLE
Hands off my application area!

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#1122]
Section 6.4, paragraph 1 of EPUB Content Documents 3.2 states: "... Reading Systems SHOULD NOT inject additional content such as border, margins, headers or footers into the Viewport or the application area surrounding the Viewport."

Emphasis on "the application area surrounding the Viewport."

This is immediately contradicted in 6.5.1: "When the ICB aspect ratio does not match the aspect ratio of the Reading System Content Display Area, Reading Systems MAY position the ICB inside the area to accommodate the user interface; in other words, added letter-boxing space MAY appear on either side (or both) of the content."

How is letterboxing not a margin? For that matter, why are we saying what an application can do outside of the viewport? Does that mean I SHOULD be removing the navigation buttons, menu bars, etc? Why?

**Comment by dauwhe** [comment]
We do give you some leeway in the next paragraph:

> The exposure of Reading System control widgets to the user is implementation-specific and not included in the above behavioral expectations.

Rewriting 6.4 to include letterboxing makes sense. 

I do think that there's some hope from publishers that fixed-layout content will use as much of the screen as possible. I know Liisa has been pushing for years for "full-bleed" images which would display edge-to-edge.

**Comment by bduga** [comment]
I was thinking just dropping " or the application area surrounding the Viewport." In terms of leeway, the whole thing is a SHOULD, so it is not a real requirement, but it doesn't seem like we really mean a RS should do that.

And @dauwhe when you say "full screen", do you mean screen or viewport? I guess my problem is saying what should happen outside the viewport. We could add text requesting the viewport take up as much space as possible, but that seems entirely unenforceable and not useful for the spec.

**Comment by dauwhe** [comment]
> And @dauwhe when you say "full screen", do you mean screen or viewport? I guess my problem is saying what should happen outside the viewport. We could add text requesting the viewport take up as much space as possible, but that seems entirely unenforceable and not useful for the spec.

I mean screen. I know we get into lots of trouble when talking about the area outside the viewport, and I agree the spec shouldn't go there now. I have no idea what to do about the use cases, though.
