### ISSUE TITLE
Should the cardinality of `authority` be extended to "zero or more"?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1126]
I'm no expert, but if the same subject is defined by several authorities, wouldn't it make sense to allow several `authority` properties on the same subject?

For instance, if the subject "Big white whales" is defined in both BIC and BISAC, the current cardinality or "zero or one" would require the following markup, which looks a bit awkward:

```xml
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    …
    <dc:subject id="subjectUK">Big white whales</dc:subject>
    <meta refines="#subjectUK" property="authority">BIC</meta>
    <dc:subject id="subjectUS">Big white whales</dc:subject>
    <meta refines="#subjectUS" property="authority">BISAC</meta>
    …
</metadata>

**Comment by dauwhe** [comment]
I don't think there will be much overlap between the code sets:

BIC: aquatic creatures
BISAC: NATURE / Animals / Marine Life

BIC: antiques & collectables: ceramics & glass
BISAC: ANTIQUES  & COLLECTIBLES / Glass  &  Glassware

Changing the cardinality might be a small gain for some likely rare situations of hand-authoring. If I'm scripting this stuff, I'm unlikely to check for a text match and then set up two refines pointing at the same element. And user agents would need to write something to handle this, if they indeed display this information at all.

**Comment by dauwhe** [comment]
Closed as no change via CG resolution 2018-09-13.
