### ISSUE TITLE
Not all the properties in the meta vocab must be used as refines

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1127]
The intro of the Metadata `meta` vocab says that all the properties must be used as refines. But some properties can also be used as primary expressions. This is for instance the case of `belongs-to-collection`, which can applies to the publication. See example 43.

Should we just get rid of the introductory conformance criteria altogether? maybe just informatively saying something along the lines of:

> Note that most of the properties defined in this section are used to define subexpressions.

**Comment by rdeltour** [comment]
I'll update PR #1125 when this is discussed and validated.

**Comment by mattgarrish** [comment]
That one is a bit of an outlier, as it was introduced in 3.0.1.

The MUST is useful as a validation trigger, so you don't leave meta properties floating around unattached to anything. Perhaps just mod it to "Unless indicated otherwise in its Extends field, each property MUST ... ". I can't see the vocabulary getting significant upgrades moving forward, so wouldn't expend too much energy on it.

**Comment by rdeltour** [comment]
> The MUST is useful as a validation trigger, so you don't leave meta properties floating around unattached to anything.

Right, on the other hand I think RS would ignore them and be just fine :-)

> Perhaps just mod it to "Unless indicated otherwise in its Extends field, each property MUST ... ".

SGTM.

> I can't see the vocabulary getting significant upgrades moving forward, so wouldn't expend too much energy on it.

Sure, agreed. The vocab was in my review assignment so I just started nitpicking as I read 😄. Feel free to close inconsequential issues as `wontfix`.

**Comment by mattgarrish** [comment]
> The vocab was in my review assignment so I just started nitpicking as I read

Sure, not a criticism of your issues at all. I meant we should do as little as possible here as I don't think it's an issue that's going to become more problematic. Our general approach these days is to farm metadata out to other standards.

**Comment by dauwhe** [comment]
Closed via #1125 and #1141
