### ISSUE TITLE
`source-of` definition and EPUB Accessibility requirements

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1130]
The definition of [`source-of`](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-source-of) says:

> This value SHOULD be set whenever pagination is included and the print source is known.

A couple comments:
- "pagination" here is unclear, does it mean the presence of page markers or the presence of page navigation?
- EPUB Accessibility says that `source-of` is a MUST when page navigation is provided; since EPUB Accessibility is a global SHOULD, this is compatible with the above statement. But maybe we can put a note or somehow refer to EPUB Accessibility here?

**Comment by mattgarrish** [comment]
> EPUB Accessibility says that source-of is a MUST when page navigation is provided

Well, it's a little more complicated than that. Technically, it only says that you need to identify the source. It doesn't require source-of, as refines was already toast in 3.1 when we did that spec and we avoided specific implementation details. You could identify the source in the accessibilitySummary or dc:description and be in compliance.

But we moved the accessibility-specific requirements over to the accessibility specification to avoid this kind of duplication. The revival of refines has unfortunately brought this one back. I almost tend to think we should drop the SHOULD entirely and leave it to the accessibility specification to handle this detail.

**Comment by rdeltour** [comment]
> I almost tend to think we should drop the SHOULD entirely and leave it to the accessibility specification to handle this detail.

SGTM, but with a note pointing to EPUB A11y spec to raise the reader's awareness.

**Comment by mattgarrish** [comment]
I'm wondering what we even do with this property, to be honest. It was something we made up to address the issue of where the pagination came from, but 3.1 already exposed that it's not viable in the long term. It might not even be a good idea to recommend its use, as it's not even all that user friendly.

I guess we can't deprecate it, but if we don't plan to use it a note that explains that _and_ links to the recommended technique should be added.

**Comment by dauwhe** [comment]
How about 

1. Delete "This value SHOULD be set whenever pagination is included and the print source is known."

2. Add a note pointing to EPUB a11y:

> NOTE: See [[EPUB A11Y Techniques]] for information on how to provide accessible page navigation.

**Comment by dauwhe** [comment]
Closed via #1138
