### ISSUE TITLE
6.5 Any value for epub:type allowed

### ISSUE THREAD

**Issue by jbcosta** [w3c/epub-specs#1131]
Consider inserting a link to EPUB Structural Semantics Vocabulary referenced 

EPUB 3.2 allows unprefixed values that are not part of the EPUB Structural Semantics Vocabulary to be used in the epub:type attribute.

Latest I can locate is from 2016  https://idpf.github.io/epub-vocabs/structure/

**Comment by dauwhe** [comment]
Link to what is being discussed: 
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-changes.html#structural-semantics

**Comment by dauwhe** [comment]
Closed via #1132
