### ISSUE TITLE
Which version of MathML does EPUB support?

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1133]
Our normative reference is to MathML 1.01, https://www.w3.org/TR/REC-MathML/, which dates from the previous millennia. 

With HTML and CSS, we have adopted the latest versions of those specs:

w3.org/TR/CSS
w3.org/TR/HTML

In the case of Math, that gives us https://www.w3.org/TR/MathML/, which is MathML 3.0 2nd edition, which has been a REC since 10 April 2014.

**Comment by dauwhe** [comment]
Further complicating the situation, some links in the spec go to a dated MathML 3 that is now officially outdated: https://www.w3.org/TR/2010/REC-MathML3-20101021/

**Comment by mattgarrish** [comment]
That 1.0 reference is just a respec conversion bug. We used [MathML] before coming to w3c-land and specref links that to the first version. It never would have triggered a problem to inspect. They can be updated to [MathML3]. Same with the dated links: TR/MathML3 them.

**Comment by dauwhe** [comment]
Cool. Will do. Thanks for the info!

**Comment by mattgarrish** [comment]
We have the same problem with the [SVG] reference going to 1.0. Needs to be [SVG2].

**Comment by mattgarrish** [comment]
And [SMIL] needs to be [SMIL3].

Otherwise, I just did a side-by-side comparison with the 3.1 references and the rest look correct.

**Comment by mattgarrish** [comment]
Closing as I've updated these in https://github.com/w3c/publ-epub-revision/commit/59e1f86d90ed5d2abf949649c2466d7243cc0a1e#diff-1c661e38a7df110148d499b17f4fe295
