### ISSUE TITLE
Acknowledgements for EPUB 3.2

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1147]
Right now we have an acknowledgments document with an inline issue:

> Acknowledgements to be completed before release.

I think it's now time to think about this :)

**Comment by dauwhe** [comment]
I can probably assemble a list of everyone who has commented on GitHub, emailed us, or been on a call. Does that sound like a reasonable strategy? I'm not sure that "signing up for the CG" is a high enough bar.

**Comment by dauwhe** [comment]
Here's a rough version of a list. Please add names!

Aaron Troia 
Adam Sobieski 
Alberto Pettarin
Andrew Gribben
Avneesh Singh
Ben Walters
Benjamin Young
Bill Kasdorf
Brady Duga
Carlos Araya 
Charles LaPierre
Daniel Glazman 
Daniel Weck
Dave Cramer
David Herron
Deborah Kaplan
Evan Owens
Franco Alvarado
Garth Conboy
Georg Stadler 
George Kersher
Greg Alchin 
Hadrien Gardeur 
Iris Febres
Ivan Herman
James Briano 
Jay Panoz
Jeff Buehler
Johan van der Knijff
John Costa 
Julian Calderazi
Ken Jones 
Krzysztof Zemczak
Laura Brady
Laurent Le Meur
Léonie Watson
Lloyd Rasmussen
Luc Audrain
Makoto Murata
Martin Kraetke
Mateus Teixera
Matt Curtis 
Matt Garrish
Mike Baker
Mustapha Lazrek
N. Erhan Uzumcu
Naomi Kennedy
Nick Ruffilo
Olaf Hoffmann
Peter Krautzberger
Rachel Comerford
Ric Wright 
Rick Johnson
Roman Deltour
Ruth Tait
Theresa O'Connor
Tobias Fischer 
Toshiaki Koike
Tzviya Siegman
Wolfgang Schindler
Zheng (Jeff) Xu

**Comment by mteixeira-wwn** [comment]
Simple correction to my name: Mateus Manço Teixeira
Thanks!

**Comment by dauwhe** [comment]
@mteixeira-wwn fixed via #1153 :)
