### ISSUE TITLE
decommission 3.1 vocabularies?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1161]
Now that we've added all the various vocabularies back as appendixes to Packages 3.2, it begs the question what we should do with the published versions we created for 3.1. These all refer back to the latest version of EPUB 3, so it'll be confusing to have two instances of the vocabularies floating around.

But do we: add a note that they are obsolete so that 3.1 remains functionally readable; remove them entirely and not care what it means to 3.1; or something else?

For reference, this affects:

- https://idpf.github.io/epub-vocabs/package/item/
- https://idpf.github.io/epub-vocabs/package/meta/
- https://idpf.github.io/epub-vocabs/package/link/
- https://idpf.github.io/epub-vocabs/rendition/
- https://idpf.github.io/epub-vocabs/package/itemref/
- https://idpf.github.io/epub-vocabs/overlays/

**Comment by dauwhe** [comment]
My initial thought would be to mark them as obsolete. Even if we want to pretend 3.1 didn't exist, the history of what we've done should remain available.

**Comment by dauwhe** [comment]
Is there some clever way to mark a spec as obsolete? Respec doesn't seem to have an appropriate status. Just add a note at the top?
