### ISSUE TITLE
Is it correct that fully qualified URIs are recommended for identifiers

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1164]
After saying that we don't place any further restrictions on idenfitiers, we place a pretty strong restriction on identifiers with this statement:

> It is strongly RECOMMENDED that the identifier be a fully qualified URI, however.

I have to assume this was meant to be "strongly encouraged" (or some other rfc waffle word) as I can't imagine we want epubcheck to actually emit warnings whenever identifiers are not fully-qualified URIs. It doesn't currently enforce this recommendation, and I would expect howls of protest if it did.

**Comment by dauwhe** [comment]
Fixed via #1178
