### ISSUE TITLE
mistagged normative keyword

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1167]
"may" needs to be capitalized in dc:type definition:

> but Authors may use any text string as a value

https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-opf-dcsubject

**Comment by mattgarrish** [comment]
"must" needs caps in the manifest fallbacks section:

> User agents must terminate the fallback chain at the first reference to a manifest item that has already been encountered.

**Comment by mattgarrish** [comment]
There are two normative keywords hiding in the last paragraph of the nav doc intro, too. The first "may" is a simple switch with "might", but the later "should" can be written out along the lines of:

> The use progressive enhancement [ContentDocs32] techniques for scripting and styling of the navigation document will help ensure that that the content retains its integrity when rendered in a non-browser context.

**Comment by dauwhe** [comment]
Fixed via #1176 and #1178
