### ISSUE TITLE
add nohighlight to dateTime format

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1169]
The expected last modified date template in the release identifier section has syntax highlighting applied to it making some of it bold and some not. We should add the respec class to prevent this. See https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#last-modified-date

**Comment by mattgarrish** [comment]
Example 25 a little further down would also benefit from the same after the markup sample.

**Comment by mattgarrish** [comment]
Also the expanded IRI in https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-property-syntax

**Comment by dauwhe** [comment]
Fixed via #1176
