### ISSUE TITLE
Remove pls: from namespace prefix table

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1173]
The only time pls: appears is in a reference to the grapheme element in the last bullet in 7.1.[1] We don't need a prefix to talk about this element in this one instance.

It's also incorrect for pls that the prefix is used in content documents and would have to be declared, as the mapping section suggests.[2] It's not. It's only ever used in pls documents.

[1] https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#confreq-pls-rs-casc
[2] https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-overview-pfx

**Comment by murata2makoto** [comment]
Agreed!

**Comment by dauwhe** [comment]
Fixed via #1182
