### ISSUE TITLE
drop unique directory recommendation from ocf?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1177]
While we sometimes have aspirational recommendations that can't be checked, we probably shouldn't have recommendations we simply never enforce. This currently qualifies as one:

> It is RECOMMENDED that the contents of the EPUB Publication be stored within its own dedicated directory under the Root Directory.

The question is whether epubcheck should begin reporting this, or whether the specification should knock this down from a normative statement?

**Comment by dauwhe** [comment]
I'd say knock it down. This doesn't serve an actual purpose.

**Comment by dauwhe** [comment]
Fixed via #1189
