### ISSUE TITLE
mix of normative requirement with informative schema

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1179]
I noticed we still have this statement in the packages specification:

> It MUST be valid to the Package Document schema, as defined in Appendix A, Package Document Schema, and conform to all content conformance constraints expressed in Package Document Definition.

Since the schema is non-normative (and not yet updated), this should probably just be stated as:

> It MUST conform to all content conformance constraints expressed in Package Document Definition. 
>
> Note
> Schemata that aid in validating these constraints are provided in Appendix A, Package Document Schema.

**Comment by murata2makoto** [comment]
Do we need any schema changes?  I checked "EPUB 3.2 Changes" but no changes appear to be required.  I also had look at github issues.  Some 3.1 changes should have been accompanied by schema changes, but we did not do it.  Thus, we do not have to revert any changes in 3.1.  Am I missing something?

**Comment by murata2makoto** [comment]
I am also not quite happy with "Schemata that aid in validating these constraints".  How about 

> Note
> Some of the content conformance constraints can be checked by validating content documents against the schemas provided  in Appendix A, Package Document Schema.

**Comment by mattgarrish** [comment]
> Do we need any schema changes?

Schematron changes, yes. I doubt there's much changed in RNC, no.

I don't mind the alternative wording. I had something like that originally, but thought it might be read negatively.

**Comment by dauwhe** [comment]
Adopted Makoto's language via #1182
