### ISSUE TITLE
Can you please remove me from “Acknowledgements and Contributors”?

### ISSUE THREAD

**Issue by JayPanoz** [w3c/epub-specs#1187]
First I only contributed issues so it’s not like I’ve been doing much work there and it feels like I don’t deserve to appear in this list.

Then seeing my name in this is kinda painful as I tend to associate this with a painful event. I mean, I’ve been offering to public-domain months of personal work for best practices and it turned into a huge drama with ad hominem and stuff that I couldn’t even understand in the public mailing list, which eventually led me to quit the Community Group because it was so taxing mentally, and minimise my contributions as much as possible.

For those 2 reasons, I’d like to be removed from this list. 

Thanks.

**Comment by JayPanoz** [comment]
It’s been months in the making BTW; I was raised to stand tall and stand strong for my beliefs. I don’t believe in this group anymore so this is a final call.

[edit] Wording as my intentions were poorly expressed in the first place.

**Comment by dauwhe** [comment]
Resolved via #1188
