### ISSUE TITLE
Reading system conformance for signatures

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1195]
OCF includes digital signatures. Are reading systems obligated to support this? Do they have to validate signatures? If the signature is invalid, must the reading system not allow the user to read the content? What if only some content is invalid?

**Comment by GarthConboy** [comment]
My answers to the above: No, No, No, N/A

**Comment by murata2makoto** [comment]
No for the first two questions.  For the 3rd question, I think that RSs should report errors but are not required to do so.

In the future, we might want to introduce a class of OPC processors that are required to reject EPUB publications containing invalid signatures.

**Comment by dauwhe** [comment]
So our position is that reading systems can ignore digital signatures? We should at least make that clear in the spec.

**Comment by llemeurfr** [comment]
> So our position is that reading systems can ignore digital signatures? 

It depends on what we really mean by that. The fact is that most reading systems don't handle digital signatures today. I even wonder if any RS supports that. 
But digital signatures are a way to stop undue modification of content, at any point in a distribution chain. If a provider takes the pain to add a signature to an EPUB file, there must be a reason. If the spec states that it's a proper behavior for reading systems to simply ignore the DS, we should rather suppress DS from the spec. 

I'd prefer the spec to state that RS SHOULD report an error if DS is erroneous. It MAY let the user read the publication after the user has been notified. 

Therefore,  RS may still decide that supporting DS is not needed depending their market, but at least the spec will be consistent.

**Comment by GarthConboy** [comment]
I'd be largely okay with that, but

`I'd prefer the spec to state that RS SHOULD report an error if DS is erroneous. It MAY let the user read the publication after the user has been notified.`

Is really saying that the RS MUST display a notification before displaying a bad-DS EPUB.  I prefer:

`I'd prefer the spec to state that RS SHOULD report an error if DS is erroneous. It MAY let the user read the publication.`

**Comment by dauwhe** [comment]
We should certainly allow signatures, as there might be some workflows and reading systems that actually use them. But I think we have an obligation to content authors to warn them that just adding a signature will have no effect unless a reading system chooses to implement something.  So in addition to Garth's text, I would add something like

> Note: Adding a digital signature is not a guarantee that an EPUB cannot be tampered with, since Reading Systems are not required to check signatures.

**Comment by dauwhe** [comment]
Closed via #1254
