### ISSUE TITLE
Path and File Names in OCF

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1196]
I have questions about two things in [this section](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-ocf.html#sec-container-filenames)

> The File Name restrictions described in this section are designed to allow Path Names and File Names to be used without modification on most commonly used operating systems. This specification does not specify how an OCF Processor that is unable to represent OCF File and Path Names would compensate for this incompatibility.

Why aren't we saying that a conforming OCF Processor must be able to support the file and path names we've defined? 

> NOTE: Some commercial ZIP tools do not support the full Unicode range and might support only the [US-ASCII] range for File Names. Authors who want to use ZIP tools that have these restrictions might find it is best to restrict their File Names to the [US-ASCII] range. If the names of files cannot be preserved during the unzipping process, it will be necessary to compensate for any name translation which took place when the files are referenced by URI from within the content.

I'm confused by the last sentence. It makes sense that if you know your zip tools don't support non-ASCII filenames to, well, use filenames that contain only ASCII. I don't see how you "compensate" for  name translations. Are we suggesting that people use non-ASCII file names with a zip processor that doesn't support them, and then guess at the unzipped names, and adjust internal references accordingly?

**Comment by mattgarrish** [comment]
> Why aren't we saying that a conforming OCF Processor must be able to support the file and path names we've defined?

Wouldn't that be setting up the possibility that some platforms simply cannot process EPUB files, since it's beyond the control of the author or developer what the OS can handle?

In those cases, and in the case of zip tools that can't handle the full unicode range, the problematic characters can be swapped out/replaced in order to continue processing, but I'm not sure we can state how that must be done.

The one consideration when an ocf processor makes such file/path names changes, though, is that it also has to ensure that those changes made in unzipping are also reflected in the EPUB content so that it doesn't break links/embedded content/etc. That's what the last note is getting at.

**Comment by dauwhe** [comment]
Is this one scenario? Author creates ZIP on platform that doesn't support unicode filenames (the author could mitigate this and epubcheck does warn on this). In this case the reading system is faced with a ZIP that has corrupted filenames. We're saying non-normatively that if the reading system wants to attempt to repair the filenames, it should also repair any internal references to these files. 

Is there a second scenario where the source EPUB is fine, but the platform the reading system is on has a bad zip implementation?

**Comment by mattgarrish** [comment]
> We're saying non-normatively that if the reading system wants to attempt to repair the filenames, it should also repair any internal references to these files.

I imagine (I wasn't there when ocf was written) dealing with the problematic cases was considered an unproductive use of time, hence the sort of hand-waving that there are possible problems but the spec isn't going to spend time solving them. I don't have any issue making it a normative statement that if file name changes are made, the ocf processor MUST ensure that any URI references in the content are also updated. I'm just not sure we can go any deeper into how that's done than is already there, as it seems potentially both platform and processor dependent.

I'd just be hesitant to turn this section into a requirement that the authored names must be supported/preserved by the ocf processor. An ocf processor should be free to do whatever it needs to process the epub, including changing file names/paths for any reason whatsoever.

I recall Readium was renaming and flattening the structure of EPUBs in the chrome app as one example of why flexibility is needed. I imagine there would be problems for authoring tools if we came down too strictly, too. (e.g., what renaming would they be allowed to do to an existing source)

**Comment by murata2makoto** [comment]
First, the use of non-ASCII characters should be encouraged rather than discouraged.

Second. less is more.  Implementers might try some error recovery, but it should be outside the scope of the OCF specification.

Therefore, I propose to drop 
> This specification does not specify how an OCF Processor that is unable to represent OCF File and Path Names would compensate for this incompatibility.

and the entire note.  At least, the last sentence in the note got to be dropped.

**Comment by danielweck** [comment]
> I recall Readium was renaming and flattening the structure of EPUBs in the chrome app as one example of why flexibility is needed.

I am not aware of this. Could you elaborate?

**Comment by mattgarrish** [comment]
> Could you elaborate?

May not be the case anymore, certainly, but I have memories from very early on of digging into the stored epubs on the file system to do some rapid debugging and finding they were restructured and renamed.

At any rate, the point is that any RS, authoring tool, processing tool, etc. shouldn't be bound to the authored representation, as that's really outside of the scope of OCF. The file naming guidance is to avoid problems, not to restrict the processor.
