### ISSUE TITLE
Preserving details of ZIP inside reading systems

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1199]
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-ocf.html#confreq-zip-preserve says:

>   It is not a requirement that OCF Processors preserve information from an OCF ZIP Container through load and save operations that is not defined within the OCF Abstract Container; in particular, an OCF Processor does not have to preserve CRC values, comment fields or fields that hold file system information corresponding to a particular operating system (e.g., External file attributes and Extra field).

What is the motivation for this? I assume that there is information in any ZIP file that is not needed by an EPUB Reading System. But this seems to be touching on how a reading system might be working internally. This doesn't appear to be testable. Is this useful information for implementors? Could this be turned into a note? Can it just be deleted?

**Comment by mattgarrish** [comment]
I'd think it's valuable to say, as it seems relevant to authoring tools, at the very least. An authoring tool should have the freedom to modify non OCF-relevant ZIP fields however it pleases, regardless of what was in the epub at load time.

It's a "clarification" per the intro to the list, so it's not something that needs testing.

**Comment by dauwhe** [comment]
This almost feels like our first mention of editing tools :)

**Comment by mattgarrish** [comment]
Ya, that's why "ocf processor" is a thing more so than "reading system" in that spec. It could be an authoring tool, some processor in a pipeline, etc. Whatever happens upon the unwitting epub in its journeys gets the freedom to tweak its zip fields.
