### ISSUE TITLE
Error handling in OCF: Reading System obligations

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1200]
The OCF spec makes several demands on reading systems, often using the phrase

> OCF Processors MUST treat any other values as being in error.

Does this mean that the OCF processor must terminate processing of the EPUB, and not display it to the reader? Must a reading system also alert the reader that there is a problem with the EPUB?

**Comment by GarthConboy** [comment]
My 2-cents re the above questions: Yes, No.

Reading System is quite broad -- there may well be no reader to alert on the ingest side.

**Comment by bduga** [comment]
And these restrictions are not on Reading Systems, they are on OCF Processors, so even harder to specify error reporting. Although, in practice, I doubt any OCF processor is actually verifying all this.

**Comment by dauwhe** [comment]
> And these restrictions are not on Reading Systems, they are on OCF Processors, so even harder to specify error reporting.

I'm learning the hard way that most of the reading system constraints in EPUB are untestable and unobservable. The reading system is not just a black box, it's a black hole :)

**Comment by GarthConboy** [comment]
As it should be!  :-)  And inscrutable too!

**Comment by mattgarrish** [comment]
> The reading system is not just a black box, it's a black hole :)

Yup, it's an application. It's not like standardizing HTML, where there is a single expected display model, but more like expecting the browsers themselves to all be identical.

**Comment by llemeurfr** [comment]
I have a different take at EPUB reading systems: IMO they are quite similar to web browsers  -> their job is to render the best they can the content that they process. 
On the other side EPUBCheck is similar to an XML validating parser: it's job is to alert producers and block invalid content to be published.  
Both are OCF processors, but with very different goals.
