### ISSUE TITLE
Reading system response to malformed mimetype file

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1201]
OCF has many musts about the mimetype file, but nothing is said about how errors are handled by reading systems. 

Should a reading system attempt to process an EPUB where the mimetype is capitalized, or has a byte order mark? Do we remain silent on this? 

For fun, I made an EPUB with mimetype string `application/epub+ziP`. iBooks wouldn't open it; ADE 3.0 and AZARDI did open it.

**Comment by murata2makoto** [comment]
Since media types are case-insensitive, I think application/epub+ziP is allowed.

Since media types are required to consist of US-ASCII characters, I do not think that the BOM should be mentioned.

**Comment by ghost** [comment]
What is RS supposed to do when encounter mimetype file says "application/wrong+mimetype"?

**Comment by mattgarrish** [comment]
> What is RS supposed to do when encounter mimetype file says "application/wrong+mimetype"?

I don't see that as within the scope of OCF to delve into. It does whatever the programmer wants it to do whenever the processor discovers any file that doesn't conform to OCF.

**Comment by mattgarrish** [comment]
> Since media types are case-insensitive, I think application/epub+ziP is allowed.

The spec states that the mime type is case-sensitive:

> The contents of the mimetype file MUST NOT contain any leading padding or white space, MUST NOT begin with the Unicode signature (or Byte Order Mark), and the case of the media type string MUST be exactly as presented above.

**Comment by mattgarrish** [comment]
(For the record, that sentence is a really ugly mash-up of requirements that should be split into a list in a future version, and no MUST should ever use such vague language as "presented above".)

**Comment by JayPanoz** [comment]
Somehow related and may apply to other issues as well: https://www.albertopettarin.it/blog/2014/06/08/epub-reading-systems-vs-invalid-ocfs.html

**Comment by dauwhe** [comment]
Great link! Thanks, Jiminy!

**Comment by llemeurfr** [comment]
Let's bring a smile to Alberto Pettarin -> suppress the mimetype file :-)
