### ISSUE TITLE
Can OCF ZIP Container be split?

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1202]
Spec says, 

> OCF ZIP Containers MUST NOT use the features in the ZIP application note [ZIP] that allow ZIP files to be split across multiple storage media. OCF Processors MUST treat any OCF files that specify that the ZIP file is split across multiple storage media as being in error.

There appear to be two related features in ZIP (see section 8 of the ZIP spec). We prohibit "spanned" ZIP files. But what about "Split" ZIP files?

> 8.2.1 File splitting is a newer derivation of spanning.  
      Splitting follows the same segmentation process as
      spanning, however, it does not require writing each
      segment to a unique removable medium and instead supports
      placing all pieces onto local or non-removable locations
      such as file systems, local drives, folders, etc.

**Comment by GarthConboy** [comment]
By my read of like likes of: http://kb.winzip.com/kb/entry/86/ -- one would still end up with multiple ".zip" files in the "split" case... so, I get to "No".

**Comment by murata2makoto** [comment]
In the case of Open Packaging Conventions (a part of OOXML), the "Disk number start", "Number of this disk", "Number of the disk with the start of the central directory " "Number of the disk with the start of the zip64 end of central directory", "Total number of disks", "Number of this disk",　”Number of the disk with the start of the central directory" fields are required to be specify 1.  This approach might be more explicit.
