### ISSUE TITLE
Clarify that XML reference is to whitespace

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1213]
As noted in https://github.com/w3c/epubcheck/issues/936#issuecomment-453867318 , the following sentence is ambiguous:

> Reading Systems MUST trim all leading and trailing white space from the element value, as defined by the XML specification [XML], before processing the value.

The XML spec defines what white space is, not how to trim it. The sentence would probably be better expressed as:

> Reading Systems MUST trim all leading and trailing [white space](https://www.w3.org/TR/xml/#white) [XML] from the element value before processing the value.

**Comment by murata2makoto** [comment]
"element  value" is never defined.  I would like to use "the content of an element", since it is the term in XML.

**Comment by mattgarrish** [comment]
> "element value" is never defined.

We clarified this in 3.1 at the beginning of the package definition:

> When an element defined in this section has mandatory text content, that content is referred to as the value of the element in the explanatory descriptions.
