### ISSUE TITLE
Does the use of (deprecated) `bindings` constitute an acceptable fallback mechanism?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1215]
Now that `bindings` is deprecated, should we keep considering its use as a valid fallback for an `object` of unknown type? Or should we it be reported as a `WARNING` too, expecting the author to provide a fallback through other means (like `object`'s inner content model)?

We're reaching the "best practice" domain here, but we're looking for guidance for what to do in EPUBCheck. Currently, EPUBCheck will not report the sole use of `bindings` as a missing fallback, i.e. it is accepted as a valid fallback mechanism.

**Comment by mattgarrish** [comment]
Until it's taken out of the specification, it's a valid fallback mechanism. The major deterrents against using it are the lack of support and inability to get publications with warnings through vendor channels.

This is where we really need to get a general documentation site off the ground, as there is rarely ever one alternative approach to recommend that works for everyone. Making epubcheck emit best practices just makes my spidey sense tingle.

**Comment by dauwhe** [comment]
Do we need to do anything to the spec?

**Comment by mattgarrish** [comment]
Not unless we decide that deprecated features no longer fulfill their designated purpose.
