### ISSUE TITLE
xml:base attribute

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1217]
So... EPUB Reading Systems [MUST support](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#confreq-rs-xml-base) the XML Base specification, which defines the `xml:base` attribute.

>  It MUST be a conformant application as defined by [XMLBase].

But... browsers have deprecated and removed support for `xml:base`. Blink removed it in 2015, Firefox a bit later. It's still normatively referenced in W3C HTML5, but only allowed in the XHTML serialization. Use counters on the web put its usage at essentially zero. It sounds like it was removed from SVG. It was removed from the DOM spec. It's not in WHATWG HTML5. 

Is this allowed by any of the XML docs used by EPUB?

**Comment by murata2makoto** [comment]
SVG 2 (CR) does not have xml:base, but SVG 1.1 (REC) does.

**Comment by dauwhe** [comment]
Should we add a non-normative note saying that support is required due to SVG 1.1, but that the feature is being removed from both html and svg, and advise people to avoid it?

**Comment by murata2makoto** [comment]
>Should we add a non-normative note saying that support is required due to SVG 1.1, but that the feature is being removed from both html and svg, and advise people to avoid it?

I do not understand why such a statement is needed.  It is certainly allowed in SVG, and will probably be never removed.  Does XHTML5 really disallow this attribute?  (I opposed to xml:base, but it has been there for a long time.)

**Comment by dauwhe** [comment]
> I do not understand why such a statement is needed. It is certainly allowed in SVG, and will probably be never removed. Does XHTML5 really disallow this attribute? (I opposed to xml:base, but it has been there for a long time.)

It has been removed from SVG2, WHATWG HTML5 (all serializations), and the DOM spec. Browsers don't support it. It remains in SVG 1.1 and in the XHTML serialization of W3C HTML5. If I was building a reading system today, I would not want to have to support this. I think a note is reasonable warning that this feature is unlikely to work as advertised, even if technically supported by the spec.

**Comment by murata2makoto** [comment]
Has it been removed from WHATWG HTML?  The spec is silent about it.  One could argue that xml:base is allowed since the use of XML is allowed.  WHAG DOM is also silent.   Since resolution of relative references is not specified as part of WHATWG DOM, one could argue that xml:base is allowed.

**Comment by iherman** [comment]
The latest official HTML Rec [says](https://www.w3.org/TR/html52/dom.html#the-xmlbase-attribute-xml-only):

> The xml:base attribute may be used on HTML elements of XML documents. Authors **_must not use_** the xml:base attribute on HTML elements in HTML documents.

(emphasis is mine). At the minimum, if we mention `xml:base`, this should be emphasized, and the advice should probably be _not_ to use it. 

---

Indeed, the WhatWG version does not even mention it in the [relevant section](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element). With the new relationships between W3C and the WhatWG shaping up there is a high probability that this will be the next official release of HTML at W3C, too.

---

The WhatWG DOM spec indeed does not mention `xml:base`. However, it does speak about the document base URL, which is, after all, what counts. It [defines](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#document-base-url) how one gets it:

> The document base URL of a Document object is the absolute URL obtained by running these steps:
> 1. If there is no base element that has an href attribute in the Document, then return the Document's fallback base URL.
> 2. Otherwise, return the frozen base URL of the first base element in the Document that has an href attribute, in tree order.

I.e., the DOM says that `xml:base`, even if it is there, _**will not be processed**_ to obtain the base URL of the document.

**Comment by murata2makoto** [comment]
@iherman 
Thanks for your investigations.  I agree that browser engines are unlikely to use xml:base for computing the base URI.

I agree to introduce a note to discourage the use of xml:base within HTML and SVG. 

Should we drop this sentence? 
> It MUST be a conformant application as defined by [XMLBase].

Since xml:base might have been used in non-HTML XML documents of EPUB, I do not want to entirely drop it.  But lifting this requirement for HTML and SVG is fine.

**Comment by dauwhe** [comment]
Closed via #1253
