### ISSUE TITLE
Update CFI to remove 3.1 reference

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1220]
@murata2makoto has pointed out that we still have a hard-coded reference to EPUB 3.1 in the EPUBCFI specification (in the [terminology](http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-terminology)). Even though we don't reference this specification anymore, older versions of EPUB still do.

We should update the document to use a "latest" reference ( [EPUB 3] -> /latest/epub ).

It might be worth considering an in-place edit for this one, given the minor nature of the change.

**Comment by dauwhe** [comment]
Sounds like a good idea. Do you have access to the source doc on idpf.org? We should probably have a copy in our repo.

**Comment by mattgarrish** [comment]
I believe I still have access, yes, but have been on the road all day today. I'll convert the doc and push it to the repository when I have a minute. So long as we update the idpf server to redirect, it shouldn't be a problem to reissue in place but with a new hosting in w3c. I was thinking we could just note the change in the status section.

Or we could always just issue a 1.1.1, come to think of it. We don't have the same overhead, and if all we're doing is fixing one reference I can't see it being contentious. We don't reference it anymore, after all.

**Comment by murata2makoto** [comment]
CFI 1.1 is going to be an ISO/IEC standard.  I would like to address this issue in that standard as well as IDPF CFI 1.1.

**Comment by dauwhe** [comment]
Fixed with #1230
