### ISSUE TITLE
Are remote scripts or resources not allowed in script element?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1225]
This statement is proving confusing for validation:

> Resources retrieved by scripts MAY be located outside the EPUB Container, but the [HTML] and [SVG] script elements MUST NOT reference Remote Resources to ensure availability at runtime (i.e., from their src or href attributes, respectively).

You can't access via script the contents of a file that is referenced via an href or src attribute, at least not without an xhr request, so what availability are we talking about, and why are such references more important to not be remote when in a script element?

Are we maybe mixing in a restriction on remote javascripts, but nothing says that scripts can be remotely hosted so it's not valid to do no matter what we say here.

My inclination is to remove everything after the first comma:

> Resources retrieved by scripts MAY be located outside the EPUB Container.

If someone wants to use a script tag to reference a remote resource and jump through hoops to get it, such is their right.

**Comment by dauwhe** [comment]
Closed via #1232
