### ISSUE TITLE
Missing restriction on link relationships

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1228]
The following statement was removed from the various link relationships during the 3.1 revision because the `refines` attribute was removed:

> Exntends: Only applies to the Publication. must not be used when the refines attribute is present.

We didn't add it back as part of reintegrating `refines`.

**Comment by murata2makoto** [comment]
Good catch!

**Comment by mattgarrish** [comment]
All credit to @rdeltour for this one... :)
