### ISSUE TITLE
iframes and internal HTML documents

### ISSUE THREAD

**Issue by JayPanoz** [w3c/epub-specs#1238]
So question… 

Looks like some authoring tools have been using a hack to get their [HTML interactive widgets into EPUB3](https://github.com/readium/readium-js-viewer/issues/723) and get around the “XHTML restriction.” And [it’s been going for a very long time](https://forums.tumult.com/t/howto-get-hype-output-into-a-fixed-layout-epub-on-an-ipad/2457).

Basically, the sole purpose of the XHTML document is to embed an `iframe` pointing to an internal HTML document (exported from authoring tools such as Adobe Animate, Tumult Hype, etc.) so that the spine item is XHTML and it doesn’t raise epubcheck errors. That’s… quite a hack in my book.

Unsurprisingly, this creates compatibility issues amongst Reading Systems, as some will render the HTML in the `iframe` OK, others will try to render it as XHTML and break on errors, etc.

Should this be restricted?

My worry is that it’s been implemented in a popular authoring tool (InDesign) for years so there are (valid EPUB) files using this hack in the wild. But on the other hand, compatibility is really bad in real life – that’s a nasty hack after all.

**Comment by OmarCur** [comment]
Hi Jay,

our main workflow for epub3 content creation would be.
create the document in Adobe InDesign.
create the interactivity in Adobe Animate, small applet like animations. Export as OAM.
Place the OAM files in the Adobe Indesign document and export as Epub3 fixed layout.

Basically, they are interactive versions of explanatory graphics in books.

We encounter huge compatibility issues with this setup and the only reader that "correctly" shows them in the Chrome Readium extension (which is discontinued).

**Comment by OmarCur** [comment]
I think i just wrote a reply but does not show up here, do you see it?

**Comment by JayPanoz** [comment]
@OmarCur Yeah I can see it. Thanks for your input and clarifications. 👍

**Comment by mattgarrish** [comment]
> so that the spine item is XHTML and it doesn’t raise epubcheck errors. That’s… quite a hack in my book.

It is a hack if the HTML document itself doesn't have a fallback, as that would be a hole in epubcheck. If an `iframe` references a foreign resource, which is what html is, it would have to provide a manifest fallback to be conforming. We already have that requirement here: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-foreign-restrictions-manifest

I think this would be better opened in epubcheck.

If the hope is to get HTML supported in reading systems, we tried again in the 3.1 revision and it went nowhere.

**Comment by rdeltour** [comment]
Yes it sounds like a shortcoming in EPUBCheck, more than a spec bug. I'm surprised since I thought the fallbacks mechanisms were properly checked, but maybe there's a mishap with `iframe` resources.

> My worry is that it’s been implemented in a popular authoring tool (InDesign) for years so there are (valid EPUB) files using this hack in the wild.

That can be a real concern indeed. Does anyone have an idea of how widely this is used?

**Comment by JayPanoz** [comment]
> It is a hack if the HTML document itself doesn't have a fallback

If we’re talking about `fallback` attribute for the HTML `item`, no there isn’t any. 

I corrected the [original sample so that it can pass EPUBCheck validation here](
https://www.dropbox.com/s/ssuwv96sohco1sr/test__created-with-epubcheck.epub?dl=0) if you need a sample/test file. 

> If the hope is to get HTML supported in reading systems, we tried again in the 3.1 revision and it went nowhere.

As far as I’m concerned, I have absolutely no hope about that so wasn’t my intention. Not in the slightest.

> Does anyone have an idea of how widely this is used?

Well the thing is as soon as InDesign does something, it can become widely used real quick. I can’t define “widely” though, I don’t have data – but significant enough that it had impacts on ReadiumCSS for instance.

And good luck making them correct that. I tried for some HTML/CSS issues in reflow, they promised an engineer would take a look, and then 2 hours later, they wanted +1s on uservoice to even take a look at the feedback – note their go-to answer to (compatibility) issues reported in their help forum is “Use Readium or iBooks, it works in those apps” so there’s probably not much to expect in the first place.

**Comment by JayPanoz** [comment]
Moved to epubcheck repo so closing this issue here – please feel free to reopen if needed.

**Comment by dauwhe** [comment]
Reopening for discussion of whether the EPUB spec should allow HTML without fallback in iframes. We have consensus that EPUBCheck should not report this as an error, to avoid breaking existing content in the wild.

**Comment by dauwhe** [comment]
CG consensus is to not change this in the spec.
