### ISSUE TITLE
Limit the FXL SVG restrictions to top-level SVG content docs

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1239]
Currently section 6.5.2 Expressing in SVG seems to apply to all SVG Content Documents. That includes SVG that are embedded as images in XHTML, or in iframes, or referenced in other SVGs.

If I understand correctly this section is primarily meant for ensuring that the SVG scales properly in the initial viewport of Reading Systems, so I don't think it is relevant to embedded SVGs, only to top-level SVGs (i.e. SVGs in the `spine`).

**Comment by mattgarrish** [comment]
> so I don't think it is relevant to embedded SVGs, only to top-level SVGs

Right, that's what the definition of a fixed-layout document states:

> Fixed-Layout Document
> An EPUB Content Document directly referenced from the spine that has been designated pre-paginated in the Package Document, as defined in The rendition:layout Property [Packages32].
> The dimensions to use for rendering Fixed-Layout Documents are defined in Fixed Layouts [ContentDocs32].

Would changing the first link from "SVG Content Documents" to the definition help? (e.g., "SVG Fixed-Layout Documents")

**Comment by mattgarrish** [comment]
Fixed by #1245.
