### ISSUE TITLE
Clarify the definition of Content Documents

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1240]
I'm likely splitting hairs, but it doesn't feel right that the definition of [Content Documents](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#dfn-epub-content-document) depends on _conformance_. 

The def currently reads:
> A Publication Resource that conforms to one of the EPUB Content Document definitions (XHTML or SVG).

Taken literally, it implies that non-conforming XHTML is not a Content Document, problem solved 🙃.

Maybe this can be clarified a little to remove any ambiguity? This is low priority.

**Comment by mattgarrish** [comment]
Since I suspect I know where you're going with this (svg fonts), what about:

> A Publication Resource with an XHTML or SVG media type that contains all or part of the content of an EPUB Publication (i.e., the textual, visual and/or audio content). These resources have to conform to their respective XHTML or SVG definitions to be used in the `spine` or be referenced from another EPUB Content Document.
>
> An EPUB Content Document is a Core Media Type Resource, so can be included in the EPUB Publication without the provision of fallbacks.

That would make conformance dependent on usage, and also note the required conformance when they are used as "content" documents.

**Comment by rdeltour** [comment]
> That would make conformance dependent on usage,

and would incidentally make it difficult to differentiate in EPUBCheck, which would likely treat all the OPF items as Content Docs (as it does today), but I think we can live with it.

**Comment by murata2makoto** [comment]
> Taken literally, it implies that non-conforming XHTML is not a Content Document,

Sure.  It is not a content document.  What's wrong about this?

Standards define conformance.  Certainly, non-conformant things exist in the real world.  But I do not believe that standards should be concerned with non-conformant things.

**Comment by rdeltour** [comment]
> > Taken literally, it implies that non-conforming XHTML is not a Content Document,
> 
> Sure. It is not a content document. What's wrong about this?

Maybe it's just me… I feel like defining the concept in terms of whether it is conforming or not feels backwards to me. It basically means that terminology only applies to _conforming_ instance, making statements like "your Content Document is non-conforming to EPUB" actually contradictory.

I'd prefer if conformance was left to the related "Conformance" (or "Conformance classes") sections of the spec, rather than part of the terminology itself.

But again, it's really low priority, so let's not waste too many brain cycles on this 😊

**Comment by murata2makoto** [comment]
@rdeltour 

I have also been a bit annoyed by the term "conform" as part of definitions.  To me, it suggests that there are something conformant and something non-conformant.    I have not seen any definitions developed by ISO that use the term "conform".  But, as you say, this is not the most important issue now.

**Comment by mattgarrish** [comment]
> To me, it suggests that there are something conformant and something non-conformant.

This is what we've discovered, though. An SVG document that doesn't follow the content document requirements could still be a valid font resource, but the specification never accounted for this.

At this time, epubcheck doesn't differentiate, but it could be that a font runs afoul of the content restrictions some day. As noted already, it's not critical to solve now but a bit of a logic problem for the future.

**Comment by dauwhe** [comment]
Closed via #1255
