### ISSUE TITLE
Reconsider deprecating display-seq

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1242]
This property is proving to be pretty commonly used. It was all over epubcheck's internal tests, in the epub 3 samples, and has been [reported to be widely used in Japan](https://github.com/w3c/epubcheck/issues/990).

Looking at the specification, while we made document order the defining method for creator precedence, there isn't a rule that says this is true everywhere (which maybe should be changed, but for another day).

Given that it's a pretty harmless piece of metadata, perhaps we should just note in the property description that it is only intended to apply where other ordering rules are not already defined, and leave it at that?

**Comment by toshiakikoike** [comment]
Thank you for the thread.
I support this change for it will solve the current concern in w3c/epubcheck#990

**Comment by dauwhe** [comment]
Closed via #1243
