### ISSUE TITLE
trailing whitespace in mimetype file

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1250]
In testing EPUBCheck 4.2, I found several errors on old EPUB 2 files around the mimetype. I tracked them down to mimetype files that contained a linebreak **after** the required string. 

We are certainly less specific about trailing whitespace than leading whitespace. Should we mention this in the spec? Does this actually break the magic number? 

Bad EPUB:

<img width="195" alt="Screen Shot 2019-03-26 at 2 59 19 PM" src="https://user-images.githubusercontent.com/5687700/55025689-d3b61800-4fd7-11e9-9273-f2c90a6525b5.png">

Good EPUB:

<img width="191" alt="Screen Shot 2019-03-26 at 2 59 28 PM" src="https://user-images.githubusercontent.com/5687700/55025724-e4668e00-4fd7-11e9-8698-2499ba3f5790.png">

**Comment by mattgarrish** [comment]
I think epubcheck enforces this, but the spec should say no leading or trailing whitespace. One more reason to break up that awful run-together sentence of requirements.

**Comment by dauwhe** [comment]
@mattgarrish your wish is my command

https://github.com/w3c/publ-epub-revision/issues/1206#issuecomment-476339458

**Comment by dauwhe** [comment]
Closed via #1251
