### ISSUE TITLE
Accessibility Hazards from Reading Systems

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1263]
As a content author, can I say an EPUB is free from various accessibility hazards without knowing if the reading system might introduce hazards? For example, can page turn animations created by a reading system be a `MotionSimulationHazard`?

**Comment by clapierre** [comment]
I would say yes you can claim that this EPUB contains no Hazards within the content itself.  Hazards within EPUB would mean if you have embedded audio/video that would have Sound, Flashing or MotionSimulations.  If a reading system introduces these elements outside of the EPUB that would be outside of the scope of what you are claiming within the EPUB itself.

Thanks
Charles

**Comment by dauwhe** [comment]
Thanks Charles!
