### ISSUE TITLE
Meta-issue for mechanics of publishing EPUB 3.2 

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1264]
I thought it might be useful to have a place to talk about issues surrounding the  publication of EPUB 3.2 as a final community group note. Some things to think about:

 * Unlike most CG notes, EPUB 3.2 consists of multiple documents, has includes, etc.
 * We have links to the EPUB A11Y specs. There was an email a while ago about those being broken from the current draft specs. Is there a larger question of where EPUB A11Y should live? Right now the official version is a W3C Member Submission? https://www.w3.org/Submission/epub-a11y/
 * Do we have any say about the folder structure of the final publication? 
 * See #1224 for linking to SSV
 * See #1192 for where schemas live

**Comment by mattgarrish** [comment]
> * Unlike most CG notes, EPUB 3.2 consists of multiple documents, has includes, etc.

It won't have includes when we publish, as we'll have to generate a static document from respec. The multiple documents all need to all be together under the same epub32 folder, but that's the same as with previous versions.

> We have links to the EPUB A11Y specs.

I updated these a while back to the idpf.org /latest link to work around this issue, and match what we have for the [EPUB Accessibility] reference. The idpf.org documents are still the official documents, as far as I'm aware. The member submissions were just that - inputs to future development within w3c. But, at any rate, if we actually publish a 1.1 in w3c we can always adjust the /latest link to point to it and everything keeps working.

> Do we have any say about the folder structure of the final publication?

So long as we stay in w3.org/publishing, I thought we were fine? Didn't we resolve on something like /publishing/epub/32 so we could always publish the other specs under /epub? @iherman?

There was also a question of whether we should also re-publish CFI 1.1 to remove the EPUB 3.1 reference, either in-place on IDPF.org or as a 1.1(.1) note in this group.

> See #1224 for linking to SSV

In addition to republishing all those, we need to figure out what we're doing about the vocabs that have been reintegrated. EPUB 3.1 references them, so we shouldn't just drop them, but we probably need a note at the top of each that indicates they are no longer current.
