### ISSUE TITLE
SHA spec only available on wayback machine

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1274]
Link checking finds that the generated URL for the Secure Hash Standard [[!FIPS-180-4]] gives a 404 error, and the document is only available through the Wayback Machine at https://web.archive.org/web/20161126003357/http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf

This is sad.

**Comment by dauwhe** [comment]
Ah, there's a DOI at http://dx.doi.org/10.6028/NIST.FIPS.180-4 which works

**Comment by mattgarrish** [comment]
Was the site maybe just down earlier? The URL seems fine to me now.

**Comment by dauwhe** [comment]
> Was the site maybe just down earlier? The URL seems fine to me now.

Me too. I wonder if the link checker is weird with PDFs?

**Comment by mattgarrish** [comment]
It does have its limitations; don't take everything it reports at face value.
