### ISSUE TITLE
Missing reference HTML+RDFA?

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epub-specs#1279]
https://www.w3.org/publishing/epub32/epub-contentdocs.html#sec-xhtml-sementic-enrichment-rdfa

notes:
"
... any usage MUST conform to the requirements defined in [[!HTML+RDFA]].
"
Is it intended, that the reference is missing?
If so, how to conform to such a requirement?

**Comment by laudrain** [comment]
@Doktorchen good catch! There is a document HTML+RDFA: https://www.w3.org/TR/html-rdfa/
@dauwhe, @mattgarrish ?

**Comment by dauwhe** [comment]
It was a typo in the reference. It should have been [[HTML-RDFA]] instead of [[HTML+RDFA]].

Now fixed in Editor's Draft by #1280.
