### ISSUE TITLE
EPUB 3.2 title of initial report page

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epub-specs#1281]
The initial page of the final report
https://www.w3.org/publishing/epub32/
has the title 'EPUB 3.2 Changes' (content of the element title)
Is this intended?
Another page of the project contains the changes separately:
https://www.w3.org/publishing/epub32/epub-changes.html
This is a little bit confusing.

**Comment by dauwhe** [comment]
Fixed here with #1282; need to talk to Ivan to update the published version.

**Comment by iherman** [comment]
I am here:-) I see that the index.html file has been updated in the snapshot on the repo. Should I go ahead and update the file in its w3c place?

**Comment by dauwhe** [comment]
> I am here:-) I see that the index.html file has been updated in the snapshot on the repo. Should I go ahead and update the file in its w3c place?

That would be most wonderful :)

**Comment by iherman** [comment]
@dauwhe which files should I update? Only `index.html`?

**Comment by dauwhe** [comment]
Sorry, @iherman I was at the dentist. Yes, only `index.html`.

**Comment by iherman** [comment]
@dauwhe done.
