### ISSUE TITLE
add technique about nav doc and spine order matching

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1287]
Depending on the resolution to #1283, we should consider a clarifying technique about these being in sync.

**Comment by dauwhe** [comment]
[WCAG techniques](https://www.w3.org/WAI/WCAG21/Techniques/general/G64.html) say much the same thing:

> Check that the values and order of the entries in the table of contents correspond to the names and order of the sections of the document.

**Comment by mattgarrish** [comment]
Closing as this is now duplicated by #1430.
