### ISSUE TITLE
Predicting the future in TOC Nav

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1293]
[This](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-package-nav-def-model) seems slightly odd:

> EPUB specifications MAY introduce further restrictions on the content model defined above for nav elements in the EPUB Navigation Document.

Do we have such plans? Do we really want to possibly invalidate many existing nav docs? Do we have enough experience with `nav` that we're less worried now, and could remove this statement?

**Comment by mattgarrish** [comment]
That's the general production rule for all nav elements, not just the _toc_.

The statement at the end was to clarify that extension specifications can define stricter content models, which would still conform to the definition, but they can't create looser ones, which wouldn't. I think there's at least one specification out there that defined a custom nav element with a stricter model - region nav comes to mind.

But, that para used to say "IDPF specifications MAY introduce...". Looks like a global swap out to "EPUB" has made that statement a bit... odd.

**Comment by murata2makoto** [comment]
I think that we should delete this sentence.

**Comment by mattgarrish** [comment]
Just bumped into this paragraph again and it's definitely confusing. I'm fine with deleting it.

**Comment by mattgarrish** [comment]
Closing as it looks like this was already removed in https://github.com/w3c/epub-specs/pull/1448.
