### ISSUE TITLE
Remove advice on HTML file extension

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1294]
I thought we had discussed this, but I can't find an issue.

[Content Docs](https://www.w3.org/publishing/epub32/epub-contentdocs.html#sec-xhtml-conf-content) says

> The XHTML Content Document filename SHOULD use the file extension .xhtml

I think we should delete this sentence, and remove the corresponding test from EPUBCheck. I think this annoys users without helping anyone else. And if you use file extensions to tell you anything about a file, you're going to have a bad time.

**Comment by mattgarrish** [comment]
Maybe we should do this across the board. We also recommend file extensions for the package document, svg, pls lexicons and smil files.

**Comment by dauwhe** [comment]
> Maybe we should do this across the board. We also recommend file extensions for the package document, svg, pls lexicons and smil files.

Yes!

**Comment by mattgarrish** [comment]
Ya, I wanted to remove these while retooling the conformance sections, but didn't want to get bogged down in a conformance change. I'll open a PR.

**Comment by mattgarrish** [comment]
Proposed Solution

Remove the recommended file extensions for Package Documents, XHTML Content Documents, PLS Lexicons and Media Overlay Documents.

Add a note in the package document definition section to refer to the media type registration for more info about file properties.

**Comment by dauwhe** [comment]
Did some testing. Made the "Ivan nightmare" file where an XHTML content document used the file extension `.svg`. The resulting EPUB gives a warning in EPUBCheck, of course, but works in:

1. Apple Books
2. Calibre
3. Adobe Digital Editions 3.0
4. Thorium

Interestingly, when I tried to convert the EPUB to a non-EPUB format, the conversion tool complained.

**Comment by mattgarrish** [comment]
Epubcheck doesn't inspect the content to verify the media type, so it's the easiest to fool. Faking media types was a periodic suggestion in the idpf forums for avoiding fallback requirements.
