### ISSUE TITLE
"dc:" not defined in reserved prefixes but broadly used

### ISSUE THREAD

**Issue by llemeurfr** [w3c/epub-specs#1296]
In [Reserved Prefixes](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-metadata-reserved-prefixes) (as in the now obsolete [EPUB 3.0.1 reserved prefixes document](https://idpf.github.io/epub-prefixes/packages/)), "dc:" is not defined (as prefix for `http://purl.org/dc/elements/1.1/`).

But it is still used 132 times in the specification. Shouldn't it be a reserved prefix? 
I'm pretty sure that all reading systems consider it already defined and I guess EPUBCheck does the same.

**Comment by rdeltour** [comment]
> But it is still used 132 times in the specification. Shouldn't it be a reserved prefix?

If I’m not mistaken (I’ve not counted nor inspected every occurence), `dc` is mostly used as an **XML namespace** prefix for element names (for elements in the Dublin Core Metadata Element Set, DCMES). In this case the prefix must be declared using the regular XML namespace declaration (`xmlns:dc="http://purl.org/dc/elements/1.1/"`).

For these elements, it won’t be of any use to include `dc` in the Reserved Prefix spec, which only applies to the prefixes used in the [property datatype](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-property-datatype) (the type used in the `property` attribute of the Package Doc `meta` element, for instance).

> I'm pretty sure that all reading systems consider it already defined and I guess EPUBCheck does the same.

EPUBCheck will report an XML prefix if it is not properly declared; and if I remember correctly it will also report undeclared prefixes used property attributes.

So maybe everything’s right? Or are you saying `dc` **as a property prefix** is broadly used?

**Comment by mattgarrish** [comment]
> Or are you saying `dc` **as a property prefix** is broadly used?

`dc` as a prefix is prohibited:

> For future compatibility with alternative serializations of the Package Document, a prefix for the Dublin Core /elements/1.1/ namespace [DCTERMS] MUST NOT be declared in the prefix attribute.

https://www.w3.org/publishing/epub3/epub-packages.html#sec-prefix-attr

The reserved prefixes are like we've declared a sort of quasi context file for the package document properties expressed in the `meta` and `link` tags (not for XML). There was an (untested) underpinning to the metadata that would have allowed translation to RDFa/json-ld/microdata, for example, although the need to do that kind of translation hasn't yet materialized.

**Comment by llemeurfr** [comment]
Oups @rdeltour you're right such reserved prefixes are only used for expressing values of an attribute in situations where `dc:` is not useful. 
Thanks to @mattgarrish for the extra-explanation. 
I will close this issue then.
