### ISSUE TITLE
EPUB 3.0.1 spec in idpf.org was gone?

### ISSUE THREAD

**Issue by babatakao** [w3c/epub-specs#1301]
Since idpf.org website seems gone, I couldn't find the available EPUB 3.0.1 spec page.

The latest spec, https://www.w3.org/publishing/epub3/epub-overview.html , references it. 

> [Publications301]
> EPUB Publications 3.0.1. URL: http://www.idpf.org/epub/301/spec/epub-publications.html

Are there any plan to migrate older specs to ther w3.org domain?

**Comment by dauwhe** [comment]
The company that was hosting idpf.org had some server problems. The W3C is working to fix it.
