### ISSUE TITLE
technique for describing covers

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1305]
An outcome of https://github.com/w3c/pub-manifest/issues/145 is that we don't provide specific guidance for describing covers. Something we should consider adding with the next techniques update, with a potential eye to later making more formal.

**Comment by mattgarrish** [comment]
I'm not sure this makes sense to begin within the techniques document. Guidance on how to write meaningful descriptions is a complex topic, and I'm worried about internationalization issues even if we try to limit the scope of what we're standardizing to how to present titles, authors, etc.

I'd propose we close this and if there's interest in trying to define a single technique for covers that we find another forum to try and begin developing it.

/cc @avneeshsingh @GeorgeKerscher @clapierre @gregoriopellegrino

**Comment by clapierre** [comment]
For our GCA work we have come up with how we would like our publishers to describe the cover image depending on the title, author, editors etc that present on the cover but this I would think would be in a best practice document.  I have also consulted with others who do alt-text descriptions for their feedback.  But as Matt points out it may be different in other countries although I suspect the majority of what we have done could be used in other countries.  Happy to share our template with others or as part of a best practice guide to get a broader audience approval.

**Comment by mattgarrish** [comment]
> but this I would think would be in a best practice document

Right, this is more of a quality issue than a technical one. Absolutely worth doing, but we should vet techniques in the real world for a while before moving them into standards documents. The techniques may be advisory, but they're still going to be viewed as official recommendations.

**Comment by avneeshsingh** [comment]
From specs point of view, we just need to highlight that there is a way to provide string for alttext of cover image in the package file.
Everything else should go to best practices.

**Comment by mattgarrish** [comment]
> we just need to highlight that there is a way to provide string for alttext of cover image in the package file

Right, and we have issue #1300 to address this requirement in the specification.

> Everything else should go to best practices.

Instead of closing, would it make sense to also transfer this to the CG for the a11y task force to take up when it has time?
