### ISSUE TITLE
Revision of Namespace prefix mapping in the spec

### ISSUE THREAD

**Issue by wonsuk73** [w3c/epub-specs#1307]
Section 1.4 Namespace prefix mapping of the spec use "http://www.idpf.org/2007/ops" as a URI for "epub" prefix. Issue is "http://www.idpf.org/2007/ops" URI doesn't exist any more. So it seems that we need to revise this URI based on W3C, e.g. "http://www.w3.org/2007/ops".
What do you think?

**Comment by murata2makoto** [comment]
Old XMLers like me firmly believe that namespace URIs do not have to be referenceable.  Thus, I see no reasons to change this namespace URI.  That said, it might be a good idea to put something at the original URI.

**Comment by wonsuk73** [comment]
@murata2makoto Thanks for your comment. By the way I guess we need to think about W3C's position in ebook industry. It means IDPF had been merged into W3C. So W3C started to lead ebook standards. In this context, if we have a chance to revise URI info based on the domain, it's good timing. What's your view?

**Comment by murata2makoto** [comment]
Good URIs do not change.  I vaguely remember that this is the position of W3C.  If we change this URI, a lot of applications will crash.

**Comment by wonsuk73** [comment]
@murata2makoto Thanks! I got it. Let's have feedbacks from other members in the group!

**Comment by iherman** [comment]
> Good URIs do not change. I vaguely remember that this is the position of W3C. If we change this URI, a lot of applications will crash.

yes, @murata2makoto is absolutely right. That URL should exist on its original place, we will have to take care of this.

Thanks, @wonsuk73, for having pinged us on this!

**Comment by llemeurfr** [comment]
> Let's have feedbacks from other members in the group!

I agree with @murata2makoto that a. namespace uris don't require dereferencability; this is a good to have, not a must have. b. namespace uris cannot change because this would mean changing the identity of all "epub" prefixed xml elements, which means all applications parsing EPUB would break.  

But yes, as @iherman states, since W3C handles the idpf.org domain name now, it will be good to plug some information at the "http://www.idpf.org/2007/ops" URL.

**Comment by wonsuk73** [comment]
@iherman, Thanks for clarification! and @llemeurfr Thanks for your feedback and your valuable comment. I agreed with giving some information at the "http://www.idpf.org/2007/ops" URL to remove confusion from readers of this spec. @iherman What do you think?

**Comment by dauwhe** [comment]
The namespace cannot change. We will not break every single EPUB. 
<img width="1348" alt="Screen Shot 2019-12-09 at 7 36 10 AM" src="https://user-images.githubusercontent.com/5687700/70436133-9787f200-1a56-11ea-92cc-3268d6d7506d.png">

Here's what the IDPF page at that URL looked like at one point many years ago. I have no opinion on what to do with that page.

**Comment by mattgarrish** [comment]
There are various others, too - opf, encryption, embedding, metadata, etc. Are we going to enumerate them all and put pages at them, too?

Most have probably never had anything at them, but if we just want to put up minimal pages that confirm they they are namespace URIs in EPUB, that seems in keeping with what other namespaces do.

**Comment by iherman** [comment]
@mattgarrish is there a list of those namespace URL-s somewhere? We should do then all in once (I am also fairly neutral as for the content of those files; a minimal content is fine with me).

**Comment by wonsuk73** [comment]
@mattgarrish I am fine with a minimal content as well.

**Comment by mattgarrish** [comment]
> is there a list of those namespace URL-s somewhere?

No, unfortunately. I'll comb through the various specs and put a list of what I find in here.

**Comment by mattgarrish** [comment]
On the bright side, I couldn't find any more than the ones I mentioned above:

- http://www.idpf.org/2007/ops
- http://www.idpf.org/2007/opf
- http://www.idpf.org/2016/encryption
- http://www.idpf.org/2013/metadata
- http://www.idpf.org/2008/embedding (algorithm identifier)

Looking at some other namespace pages, probably all we need is a simple template like:

OPS Namespace

The namespace http://idpf.org/2007/ops is used in the following EPUB specifications:

- [Open Publication Structure 2.0.1](http://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm)
- [EPUB Packages 3](https://www.w3.org/publishing/epub3/epub-packages.html)
- [EPUB Media Overlays 3](https://www.w3.org/publishing/epub3/epub-mediaoverlays.html)

For more information about the development of EPUB, refer to [Publishing@W3C](https://www.w3.org/publishing/).

For more information about XML namespaces, refer to [Namespaces in XML](https://www.w3.org/TR/REC-xml-names/).

**Comment by iherman** [comment]
@wonsuk73 @murata2makoto the

http://idpf.org/2007/ops/

is live now.

**Comment by wonsuk73** [comment]
@iherman Thanks!
