### ISSUE TITLE
exempt html link from fallback requirements?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1312]
Epubcheck has crafted an interesting approach to validating adobe page template declarations whereby you only have to have a manifest fallback if there isn't also a css style sheet declaration in the html file. It doesn't match any prose from the specification, however, and I'm not entirely sure it even makes a lot of sense to require a css declaration/fallback.

I don't know if page templates are used any more, but it got me wondering why we treat linked resources In xhtml docs as publication resources at all. We don't treat package linked resources that way.

Right now, we only exempt linked resources if rel="pronunciation" is specified, but is there any reason not to extend the same to all resources referenced from `link`?

**Comment by mattgarrish** [comment]
> but it got me wondering why we treat linked resources In xhtml docs as publication resources at all

Just to be clear here, I'm not suggesting we go as far as requiring they not be listed in the manifest, only that there doesn't seem to be a need for them to have fallbacks. We should just broaden the exemption to all link elements.

**Comment by dauwhe** [comment]
I'm trying to figure out when this might come up. There's lots of web usage of `link` for things like `rel=preload` but it seems unlikely that the link would be to a foreign resource.

**Comment by mattgarrish** [comment]
Right now it would rationalize allowing page templates without fallbacks and remove the need for a special case for pls lexicons.

More generally, it avoids this ever becoming an issue moving forward when it doesn't need to be. If we envision HTML pages being translated to EPUB, it doesn't put any potential barriers in the way of the various icon links that exist, for example.

**Comment by dauwhe** [comment]
Closed via #1651
