### ISSUE TITLE
Include some illustrations in Package Rendering Metadata

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1314]
We should have some illustrations of  these very visual properties, as a way of making the spec more understandable.

**Comment by iherman** [comment]
Before I get carried away and do unnecessary things, you are referring to [package rendering vocabulary](https://w3c.github.io/epub-specs/epub33/core/#app-rendering-vocab), right? Ie, to illustrate paginated, scrolled-continuous, and scrolled-doc
