### ISSUE TITLE
Copy-editing error in EPUB Accessibility 1.0 document

### ISSUE THREAD

**Issue by Loyal-Planetarian** [w3c/epub-specs#1315]
As of 22 April 2020, the EPUB Accessibility 1.0 document (http://idpf.org/epub/a11y/accessibility.html) contains a copy-editing error in the third paragraph of Section 3.1:

Users need to be able to gauge the usability of an EPUB Publication when they purchase, borrow or otherwise obtain it, a determination that requires knowing **the any** affordances made to meet the accessibility requirements.

I suggest removing the word "the" (indicated in boldface above) and retaining the word "any."

Kind regards,
Erik Bjørn Pedersen
Victoria, B.C., Canadas

**Comment by mattgarrish** [comment]
Thanks for the report. The typo you've noted is fixed in the forthcoming ISO version of the specification, and the original 1.0 version will be updated to reflect the ISO document during the next revision.

**Comment by mattgarrish** [comment]
The new accessibility document to be used for this revision is based on the ISO text and incorporates this fix, so this issue is no longer applicable. Suggest we close.
