### ISSUE TITLE
There is a typo in EPUB Open Container Format (OCF) 3.2

### ISSUE THREAD

**Issue by JackieFei** [w3c/epub-specs#1317]
https://www.w3.org/publishing/epub3/epub-ocf.html#sec-container-filenames

3.4 File Names

```VERTICAL LINE: \ (U+007C)```

should be

```VERTICAL LINE: | (U+007C)```

**Comment by mattgarrish** [comment]
Yes, thanks, looks like a copy/paste error when it was added to the list in 3.2.
