### ISSUE TITLE
Simplify media overlay requirement

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1318]
Came across this while going through the document:

> The media-overlay attribute MUST NOT be attached to manifest item elements that do not reference EPUB Content Documents.

https://www.w3.org/publishing/epub/epub-mediaoverlays.html#sec-package-including

In the interests of clarity, it could do without the not/not: "The media-overlay attribute MUST only be attached to manifest item elements that reference EPUB Content Documents."

**Comment by murata2makoto** [comment]
Is the media-overlay attribute required for manifest item elements that reference EPUB content documents?

**Comment by mattgarrish** [comment]
Yes, that requirement is just above:

> If an EPUB Content Document is wholly or partially referenced by a Media Overlay, then its manifest item element [Packages32] MUST include a media-overlay attribute.
