### ISSUE TITLE
Media overlay playback class names only a should?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1319]
Also ran across these somewhat contradictory statements:

> Visual rendering information for the currently-playing EPUB Content Document element MAY be expressed in the CSS Style Sheet using author-defined classes. These author-defined class names SHOULD be declared in the Package Document metadata using the metadata properties active-class and playback-active-class.

https://www.w3.org/publishing/epub/epub-mediaoverlays.html#sec-docs-assoc-style

The first sentence is clear that you don't have to supply the classes if you don't want, but the "should" in the second sentence is unclear. It could be read as contradicting the first (you should specify them), being non-committal about where to declare them (should be in the package document, but could be elsewhere?), or non-committal about the names (you should use these property names, but could use others?).

I expect, of course, it's none of the above and this could be reworded as a "must":

"When used, author-defined class names MUST be defined in the Package Document using the active-class and playback-active class properties."

**Comment by GarthConboy** [comment]
And there is a lot of "in the wild content" that (erroneously) expects:
```
<meta property="media:active-class">-epub-media-overlay-active</meta>
<meta property="media:playback-active-class">-epub-media-overlay-playing</meta>
```
to come for free.  And, I bet more than one Reading System applies these styles regardless of whether they are specified (as does ours).

**Comment by mattgarrish** [comment]
Ya, it probably doesn't help to have [the note](https://www.w3.org/publishing/epub/epub-mediaoverlays.html#issue-container-generatedID-1) that says the names can be anything before [the example](https://www.w3.org/publishing/epub/epub-mediaoverlays.html#example-5). Skimmers might be more likely to notice it if were to immediately follow the example declarations.

Making this a normative statement would also help, and could be part of requiring the css file with the declarations be attached to each affected content document.
