### ISSUE TITLE
Rules for active-class and playback-active-class

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1320]
Looking at validation, I see a couple of underspecified areas around the use of the properties:

- should there be a requirement that every content document include the style sheet with the definitions so that the classes can be applied? The spec isn't clear what will happen if you put the classes in their own style sheet but don't declare it in the content document(s). Does the reading system harvest the styles and apply them into the documents, and how would it go about doing that?
- should we care about multiple declarations? For example, should there be a warning/info message to the user that they potentially duplicated their definitions, or do we let them silently cascade like any other CSS?
- also, if you declare the properties but don't include the named css classes in your style sheet, is that an error/warning/info?

**Comment by mattgarrish** [comment]
To confirm my first question, the rendering section says:

> During Media Overlays playback, Reading Systems with a Viewport SHOULD add the class names given by the metadata properties active-class and playback-active-class to the appropriate elements in the EPUB Content Document.

So noting the requirement to declare the css file with the declaration(s) would seem to be in order.

**Comment by marisademeglio** [comment]
I would call it a warning if you declare the properties but don't associate style information. The spec doesn't prohibit it but it also sounds like an accidental omission to me. 

If you don't declare the properties at all, that's ok. It's not required to associate visual information with the MO presentation.

I think multiple declarations would silently cascade, as we state that "The class names chosen can be used along with any supported CSS features."

**Comment by mattgarrish** [comment]
> The spec doesn't prohibit it but it also sounds like an accidental omission to me.

I think this knocks off my two main concerns, which are really the same looking again at this, as if we had a requirement to attach the associated style sheet to each content document referenced from an overlay, then the lack of a CSS declaration would get raised by consequence.

It means we can't just look for a CSS declaration, but also have to look inside to see that it has relevant style info.

Agree with doing nothing about cascading. We'd have to look for two identical rules, as some cascading would naturally be valid.
