### ISSUE TITLE
Fragment identifiers in media overlay attributes

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1321]
First, for `epub:textref` and `src`, the specification uses these definitions:

> The relative IRI reference [RFC3987] of the corresponding EPUB Content Document, including a fragment identifier that references the specific element as per the [XPTRSH].

I read this as a fragment identifier is required (but it might be better to say "including a REQUIRED fragment identifier..."). epubcheck currently doesn't check if the fragments are specified, which I assume just needs fixing, but I'm curious how to interpret an empty fragment like `chapter01.xhtml#`: is that valid?

An empty fragment isn't associated with any element, as far as I understand; it just [results in a scroll to the top of the document](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier) in browsers with a null target element. So should the prose say a "non-empty fragment identifier" and an error be thrown if one is encountered?

Second question is whether fragment identifiers are disallowed on audio elements? The specification doesn't say anything about them on audio/src, and epubcheck attempts to resolve the fragments even though it's not clear when they would ever be useful or wanted.

Seems like epubcheck should issue an error that fragments aren't allowed on audio and skip trying to resolve the references, but, again, it would help if the specification stated this explicitly.

**Comment by marisademeglio** [comment]
To me, the spec is clear on this. There are two different ways that `src` is defined, depending on the element it appears on.

* text src: IRI including fragment identifier
* audio src: IRI

I don't think it hurts to be more explicit though, if you think it would be helpful.

**Comment by mattgarrish** [comment]
Right, the main question I had about `text` was the empty fragment. We can tweak the wording about the requirement, but I wanted to be sure that an empty fragment is disallowed even though it's a valid fragment identifier. My assumption is it is invalid, otherwise what is a reading system supposed to do with: `chapter01.xhtml#` ?

The audio question is just a validation question about how much we care about the form of the IRI, since a fragment identifier is just an optional component of one. I was wondering what weirdness might result if a media fragment were attached, in particular. Should a reading system respect the fragment? What do you make of clipBegin and clipEnd in that scenario?

That's why I was wondering if it should be explicitly disallowed, at any rate.

**Comment by marisademeglio** [comment]
So for `text`, it says
> The relative IRI reference [RFC3987] of the corresponding EPUB Content Document, including a fragment identifier that references the specific element 

I would read that to mean that if the fragment identifier does not reference a specific element, then it doesn't meet this definition and is invalid. 

And for `audio`, it says
> The relative or absolute IRI reference [RFC3987] of an audio file. 

Which I guess does not exclude the IRI having a fragment. Reading systems likely aren't expecting it, though, so maybe it's a warning -- not illegal as per the spec, but not recommended.

**Comment by mattgarrish** [comment]
> I would read that to mean that if the fragment identifier does not reference a specific element, then it doesn't meet this definition and is invalid.

Ya, I think I'm fine for having an error in epubcheck at this point.

The reference to xptrsh is both helpful and unhelpful in this case. It enforces that the reference can't be empty:

> If no element information item is identified by a shorthand pointer's NCName, the pointer is in error.

But if we were to actually implement validation based on xptrsh we wouldn't allow valid references into xhtml content documents since there's no requirement to use NCName-compliant IDs anymore.

I guess the reference is there because you could use epubcfi, but we might want to reconsider whether it's necessary.

**Comment by mattgarrish** [comment]
I think we ended up not needing to change anything for this. I'm going to open a separate question about the references to xptrsh.
