### ISSUE TITLE
Clarify media overlays accessibility requirement application

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1328]
The ISO rewrite of the document changed the media overlays playback requirement to normative but without adding anything more than the original.

Regardless, we may want to further clarify that media overlays are not required for conformance. The normative condition only applies if they are used.

**Comment by murata2makoto** [comment]
Should we then introduce conformance classes?  Or, is that too much?

**Comment by mattgarrish** [comment]
My preference would be to keep things simple. We only want to reinforce that we're not requiring media overlays in order to conform. I think that can be done with some basic prose.

**Comment by mattgarrish** [comment]
Proposed Solution

Add the following note to the section on meeting the media overlays requirement:

"This criterion does not require Authors to include Media Overlays in their EPUB Publications, only that they conform to these requirements when present."
