### ISSUE TITLE
Clarify reading system / ocf processor

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1329]
There's a sometimes confusing mix of these two terms in OCF. There are reading system requirements, but often the requirements themselves reference what OCF processors have to do.

Might be helpful to drop OCF processor as a term and simply add a note/section that explains that an application that is not handling the container for rendering purposes (i.e., is not a full-fledged reading system) can ignore any related requirements.

**Comment by murata2makoto** [comment]
Practically, I do not think that OCF will be used for something different from EPUB.  If this is the case, there are no advantages in distinguishing reading systems and OCF processors.

**Comment by mattgarrish** [comment]
> I do not think that OCF will be used for something different from EPUB

Right, it's essentially forbidden by the specification since 3.0.1, as the container.xml file has to point to EPUB renditions.
