### ISSUE TITLE
Editorial comments on the 'relationships to other specifications'

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1351]
Two editorial comments on [§1.3 in Core](https://w3c.github.io/epub-specs/epub33/core/#sec-intro-relations) 

1. The text says, e.g., for HTML:

> This specification does not reference a specific version of W3C [HTML], but instead uses an undated reference that will always point to the latest recommendation.

However, a somewhat similar situation occurs with the CSS snapshot, which has a yearly update and which has an undated reference that we use in the spec. Should we use the same type of text, for the sake of consistency, for CSS?

2. There is no reference to MathML in this section. Discussions have also started to re-open the MathML WG; shouldn't we refer to the latest version of MatML the same way as we do for HTML, CSS, or SVG? I.e., shouldn't we add the same subsection in §1.3 for MathML?

**Comment by mattgarrish** [comment]
We only inerit mathml through html. That's why we didn't define a specific section for it. HTML and SVG are content document formats and we were profiling CSS for the longest time.

**Comment by mattgarrish** [comment]
> This specification does not reference a specific version of W3C [HTML], but instead uses an undated reference that will always point to the latest recommendation.

Isn't this in need of change, too? We now reference WHATWG HTML. It might need to say we reference "HTML the ever-living" (replaced by whatever is appropriate to explain the lack of versioning now).

**Comment by iherman** [comment]
> We only inerit mathml through html.

Same as CSS...

> That's why we didn't define a specific section for it. HTML and SVG are content document formats and we were profiling CSS for the longest time.

But we do not profile it any more; we refer to an external, living document...

**Comment by iherman** [comment]
> > This specification does not reference a specific version of W3C [HTML], but instead uses an undated reference that will always point to the latest recommendation.
> 
> Isn't this in need of change, too? We now reference WHATWG HTML. It might need to say we reference "HTML the ever-living" (replaced by whatever is appropriate to explain the lack of versioning now).

You are probably right that we have to use the standard 'html' reference (like in the Publication Manifest) leading to the WHATWG 'living standard'.

**Comment by mattgarrish** [comment]
> But we do not profile it any more; we refer to an external, living document...

Right, but we also stripped it down to explain that we still maintain some properties separately from CSS. It's debatable how much we need it as a special relationship section.

What unique relationship do we have to MathML that isn't already covered by HTML, though? What stops us from having to create relationships to every format that is a core media type, in other words?

**Comment by mattgarrish** [comment]
I think it's fine to point out anything we need to about embedded MathML/SVG within the HTML section, though, if that works for you. Saying that HTML in turn references the current versions of both so these grammars may also change isn't a bad thing. That's essentially how we handle the oddities of scripting in EPUB (but that is only detailed in the RS specification).

But MathML isn't even a core media type, so it's just odd to me to claim a direct relationship. The only way you get it in EPUB is through the HTML spec.

We definitely should look at our MathML references separately from this. We changed from the non-specific TR/MathML URL to /TR/MathML3 around the time of the merger, so could be chalked up to a bad port of the reference in respec. They should match the HTML reference.

**Comment by iherman** [comment]
> I think it's fine to point out anything we need to about embedded MathML/SVG within the HTML section, though, if that works for you. 

Probably does (although I have to see exactly what you mean by this),

> Saying that HTML in turn references the current versions of both so these grammars may also change isn't a bad thing. That's essentially how we handle the oddities of scripting in EPUB (but that is only detailed in the RS specification).
> 
> But MathML isn't even a core media type, so it's just odd to me to claim a direct relationship. The only way you get it in EPUB is through the HTML spec.
> 
> We definitely should look at our MathML references separately from this. We changed from the non-specific TR/MathML URL to /TR/MathML3 around the time of the merger, so could be chalked up to a bad port of the reference in respec. They should match the HTML reference.

+1 to this, too.

(It is a separate question why MathML is not a core media type. AFAIK, MathML is used to exchange mathematical formulae, and not only to _display_ them, which would make it a bona fide target for being a core media type of its own right. Maybe @TzviyaSiegman or @BillKasdorf can tell us whether this is indeed something that could be useful for scholarly publishing.)
