### ISSUE TITLE
javascript media types in §3.1.2

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1353]
The spec lists two media types:

- application/javascript
- text/javascript

the second one is listed as obsolete in RFC4329; on the other hand, it lists application/ecmascript as valid and text/ecmascript, too,as obsolete.

I would propose to allow for all four, but marking the text/* as obsolete (ie, discourage authors to use it)

**Comment by mattgarrish** [comment]
This only applies to the package document declaration. You can use any media type in the actual html files. Do we really need to have four possibilities? It's more likely to cause issues with older reading systems.

**Comment by iherman** [comment]
If it is only for package document, then we should probably say that the one that authors SHOULD use is application/javascript but make a note that the other three are acceptable, but not RECOMMENDED to be used. Newer content following this would work with older and newer RS-s, older contents will also be handled.

The current text does put application/javascript and text/javascript on equal footing, and that contradicts RFC4329...

**Comment by mattgarrish** [comment]
> The current text does put application/javascript and text/javascript

Because up until 3.2 only text/javascript was allowed and exists in a lot of EPUBs that publishers don't want rejected from vendors because it's no longer recommended (i.e., warning). It's not about providing complete coverage of all possible media types, as there are [10+ other ways of indicating a javascript](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#JavaScript_types).

Adding more without addressing the whole issue of core media types just provides another angle of rejection from vendors who don't update their validation every time there's a new specification.

**Comment by iherman** [comment]
I think we can forget about the historical stuff as listed in [full list of js references](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#JavaScript_types). Let us consider RFC4329 which lists four or these, and that is already quite enough :-)

There are several issues

- `application/ecmascript`, per RFC4329, is perfectly o.k. even if not widely used. I do not think we should disallow something that is standard compliant
- We should have some way to push our authors to use `application/{javascript,ecmascript}` and not their text equivalent. We may hit the problem that future web cores or other javascript tools may have issues with `text/*`, and we want to avoid that

We may list all four as possibilities, without formally designating `text/*` as wrong (ie, epubcheck should not flag their usage), but add an editorial note to make it clear that authors should not (as opposed to _SHOULD NOT_) use these, because they are considered to obsolete.

Would that work?

**Comment by mattgarrish** [comment]
I just think this is more important an issue for content (where you're not bound to the validation/CMT constraints of the package) and potentially more problematic than it's worth for the package on its own.

But it's not a hill I'm going to die on, as the hackneyed saying goes, as I'm more interested in solving non-content document CMTs more broadly so we don't continue to run into this problem going forward.

**Comment by OriKuttner** [comment]
It's been a long time I have written in this list but I followed it.
It think we should encourage in some way application/javascript so maybe
just write that application/javascript is the recommended method today.
I understand that we can not just say SHOULD use application/javascript.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by dauwhe** [comment]
I don't have any particular interest in “encouraging” the use of a particular media type. What is defined in the package document doesn't matter for script execution! But I worry that we disallow the perfectly valid `application/ecmascript`. I would propose adding this.

**Comment by mattgarrish** [comment]
> `application/ecmascript`. I would propose adding this.

I can live with this, since it's at least a recommended media type. Adding an obsolete media type to match a mistaken use of an obsolete media type is bad form.

Since we're adding other new media types, I suppose the pain of rejection from old validators is no more or less than for the others.
