### ISSUE TITLE
What’s the recommended way to denote a collection?

### ISSUE THREAD

**Issue by jenstroeger** [w3c/epub-specs#1356]
Suppose I have a book “The Eye of the World” which belongs to the collection “[The Wheel of Time](https://en.wikipedia.org/wiki/The_Wheel_of_Time)”. How would I express the collection/series in a single book’s metadata, perhaps similar to the [ONIX codelist 148](https://onix-codelists.io/codelist/148)?

The [`<dc:type>`](https://www.w3.org/publishing/epub3/epub-packages.html#sec-opf-dctype) doesn’t provide a “collection” or some such in its [type registry](https://idpf.github.io/epub-registries/types/). If it did, I’d probably refine it like so:
```xml
<dc:title>The Eye of the World</dc:title>
<dc:type id="dc-type">Collection</dc:type>
<meta refines="#dc-type" property="collection-type" scheme="onix:codelist148">10</meta>
<meta refines="#dc-type" property="???">The Wheel of Time</meta>
```
It looks like https://github.com/w3c/epub-specs/issues/326 is a relevant discussion and two years old, though it doesn’t seem to come to a definite conclusion other than @jcsalomon’s [recommendation](https://github.com/w3c/epub-specs/issues/326#issuecomment-441413635)?

**Comment by llemeurfr** [comment]
Here is in practice what Readium developers decided to map (from EPUB 2 and EPUB 3 to the internal Readium WP Manifest). 

https://readium.org/architecture/streamer/parser/metadata.html#collections-and-series

This is implemented in the Readium Desktop (-> Thorium Reader) and Readium Mobile toolkits

**Comment by jenstroeger** [comment]
Thank you, @llemeurfr! So, based on the information you linked to the example would have to be:
```xml
<dc:title>The Eye of the World</dc:title>
<dc:type id="dc-type">Collection</dc:type>
<meta refines="#dc-type" property="collection-type">series</meta>  <!-- Or: "collection" -->
<meta refines="#dc-type" property="belongs-to-collection">The Wheel of Time</meta>
<meta refines="#dc-type" property="file-as">Wheel of Time, The</meta>
<meta refines="#dc-type" property="dcterms:identifier">urn:isbn:1234567890</meta>  <!-- Duplicate of the <dc:identifier> element? -->
<meta refines="#dc-type" property="group-position">Book 1</meta>  <!-- Is this a free text value? -->
```
Is this correct?

**Comment by JayPanoz** [comment]
@jenstroeger The doc was written following the examples in the [EPUB Packages 3.2 spec](https://www.w3.org/publishing/epub3/epub-packages.html#sec-group-position). 

So as an example: 

```
<metadata>
    …
    <meta property="belongs-to-collection" id="c01">
        The Lord of the Rings
    </meta>
    <meta refines="#c01" property="collection-type">set</meta>
    <meta refines="#c01" property="group-position">2</meta>
    …
</metadata>
```

I’m not sure why you have a `dc:type` but that will make the parsing fail because `refines` don’t apply to the meta itself. 

Notes: 
- `collection-type` can be `series` or `set` (and not `collection`, which is internal mapping to RWPM);
- `group-position` is a number which can be decimal-separated.

**Comment by jenstroeger** [comment]
Thank you @llemeurfr and @JayPanoz, figured it out and it’s all working now 👍

**Comment by jenstroeger** [comment]
For future reference: [EPUB Packages 3.3 spec](https://www.w3.org/TR/epub-33/#sec-belongs-to-collection).
