### ISSUE TITLE
OPF namespace document

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1360]
At the moment `http://www.idpf.org/2007/opf`, if dereferenced, yields a 404. I realize that there is no obligation in XML that the namespace URL would be dereferencable, but it is probably of a good practice to do (see, for example, the [SVG Namespace URL](https://www.w3.org/2000/svg). We should do that...

**Comment by dauwhe** [comment]
Are there server logs that show how often people try to reach that URL?

**Comment by mattgarrish** [comment]
I must be going crazy as I'm sure we did exactly that a number of years back when we added http://www.idpf.org/2013/metadata

**Comment by iherman** [comment]
> Are there server logs that show how often people try to reach that URL?

Probably not very often. But it is a small and one time effort, and it does make things nicer...

**Comment by mattgarrish** [comment]
I finally found my sanity on an old laptop. We did make pages post-merger, so I wonder if they got deleted during that whole transition off the idpf server.

Attaching the placeholder pages if you want to go to the effort of restoring them to their rightful paths.

**Comment by iherman** [comment]
O.k., got them. I will find out the way to get these to the idpf web site, and I will then close this issue.

Thx @mattgarrish!

**Comment by iherman** [comment]
The namespace documents are now alive (and all redirected to documents on `https://www.w3.org/ns/epub/...`.
