### ISSUE TITLE
Value of "refines"

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1361]
The current text says:

>**refines**
> Identifies the expression or resource augmented by the element. The value of the attribute must be a relative IRI [RFC3987] > referencing the resource or element being described.

Is the relative IRI true? All the examples I have seen for refines is actually a fragment ID, with the ID referring to a meta element. We would have to find the exact formalism, but I do not think I can say `refines="../otherpackage/#otherid"`, can I?

**Comment by iherman** [comment]
Actually, the same comment may be true for other cross references within the package...

**Comment by mattgarrish** [comment]
> but I do not think I can say `refines="../otherpackage/#otherid"`, can I?

You can, but I'm not sure that we've defined reasons for doing so. (Maybe somewhere out in an extension spec?)

All it means is you're asserting some property about the resource.

**Comment by iherman** [comment]
You mean this is allowed? I mean it is allowed per the letter of the text today, but has it ever considered as a valid reference?

**Comment by mattgarrish** [comment]
Ya, if I remember correctly, it's the hacky equivalent of using `about` or `resource` in RDFa to set the subject.

**Comment by mattgarrish** [comment]
I'm still kind of torn on this. This was actually what got us into trouble in the first place, now that I think back on it.

We were planning a kind of RDFa lite in the package document, but then were told [our hacky use of `about`](http://idpf.org/epub/30/spec/epub30-publications-20110516.html#attrdef-meta-about) to point to IDs was not in keeping with RDFa. From that was born `refines`, where if you actually needed RDFa you could swap out the ID with the resource.

I guess the one feasible, if highly unlikely, case for leaving it as-is would be that not every resource has to be listed in the manifest. In that case, there won't be an ID to reference so you'd have to make a statement about the resource by putting in its path. Now what on earth you'd be saying about a resource not listed in the manifest... ?

**Comment by mattgarrish** [comment]
I don't know if this would have survived, but here's an example of a spec-defined use for relative paths in `refines`: http://idpf.org/epub/do/#h.vb4juhsy12yy

**Comment by mattgarrish** [comment]
For this, what if we just recommend referencing publication resources by their manifest ID?

That would match what authors will already do in probably all cases.

**Comment by iherman** [comment]
> For this, what if we just recommend referencing publication resources by their manifest ID?
> 
> That would match what authors will already do in probably all cases.

I think that would be way cleaner, and I do not think it would break any existing case.

@wareid @dauwhe @shiestyle wdyt?
