### ISSUE TITLE
reading progression direction?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1362]
The [Publication Manifest](https://www.w3.org/TR/pub-manifest/#reading-progression-direction) has introduced the metadata on reading progression direction, alongside the document language. To quote from that spec:

> The reading progression direction establishes the reading direction from one resource to the next within a digital publication. It is used to adapt such publication-level interactions as menu position, touch gestures, swap direction, and tap zones for next and previous page.

I wonder whether we should not introduce the same element, alongside `dc:language`. 

(Note that language alone does not necessarily define the direction; there are languages, like Azeri, that have Latin, Cyrilic and Arabic ways of writing, yielding different directions...)

**Comment by mattgarrish** [comment]
That's the equivalent of EPUB's [`page-progression-direction` attribute](https://w3c.github.io/epub-specs/epub33/core/#attrdef-spine-page-progression-direction) on the spine, I believe.

**Comment by iherman** [comment]
Ah. Indeed. But is an attribute on the spine the right place for this? It sounds something for the overall rendition, including for resources that would be accessed separately (data files, graphics files,...)

Anyway. We may want not to rock the boat...

**Comment by dauwhe** [comment]
> Anyway. We may want not to rock the boat...

Although I'm all in favor of [Rock the Vote](https://www.rockthevote.org/), let's not rock this particular boat. Anyway, I'm not sure how this would apply to items that are not in the spine. And I've not heard of any problems in this area.

**Comment by mattgarrish** [comment]
Ya, this is the kind of change that would break things.

Unlike pub manifest, everything you can reach in the reading order in EPUB has to be in the spine. Any other resources are embedded within those, so I think we're pretty safe.

**Comment by iherman** [comment]
Ok, I accept this and closing...
