### ISSUE TITLE
Resource location URL-s

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1364]
In [§3.2 Resource Locations](https://w3c.github.io/epub-specs/epub33/core/#sec-resource-locations) the text relies on the tacit fact that a relative URL in a content document refers to a resource located in the EPUB Container. I think this should be made somewhat more explicit and make it also clear that the base for the relative URL is the container HTML/SVG file. All this sounds obvious, but is worth specifying.

Let alone the fact that the situation _may_ be distorted. A sneaky author may do the following:

```html
<html>
    <head>
        <base href="https://my.sneaky.site.org/">
    </head> 
    <body>
        <audio src="audio/cho01.mp4">
    </body>
</html>
```

`audio/cho91.mp4` is then a remote resource so the definition must refer to this possibility.

(I wonder whether this case is not a potential security issue, b.t.w., that is worth mentioning.)

**Comment by mattgarrish** [comment]
These details are covered in the OCF spec, specifically in [section 6.2.3](https://w3c.github.io/epub-specs/epub33/core/#sec-container-iri):

> For relative IRI references, the Base IRI [RFC3986] is determined by the relevant language specifications for the given file formats.

and:

> All relative IRI references MUST resolve to resources within the OCF Abstract Container (i.e., at or below the Root Directory).

**Comment by mattgarrish** [comment]
Cross-referencing to this section would certainly be useful to do.

**Comment by iherman** [comment]
Note also that the usage of the `<base>` element is not mentioned in the OCF section either...

**Comment by mattgarrish** [comment]
Not specifically, no, as it covers all technologies, but it's part of resolving the base IRI for HTML.

As far as I'm aware, epubcheck would catch the case you mention above and flag it as a remote resource.

**Comment by iherman** [comment]
> As far as I'm aware, epubcheck would catch the case you mention above and flag it as a remote resource.

O.k., that is good. But let us cross-reference. In a linear read the issue may arise for the reader.
