### ISSUE TITLE
(Purely editorial) describing refines for meta

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1365]
While reading through the chain of descriptions/references in, say, the [`<dc:creator>` element](https://w3c.github.io/epub-specs/epub33/core/#sec-opf-dccreator) I hit the sentence:

> The `file-as` property MAY be attached to include a normalized form of the name, and the alternate-script property to represent a creator's name in another language or script.

The problem is that the text does not say (only the example does) that 'attaching a property' means using the `<meta>` element via the `refines` attribute using a, well, property. There is reference to the [definition of `file-as`](https://w3c.github.io/epub-specs/epub33/core/#file-as) which has then a reference somewhere to the `<meta>` element, but it is bit up in the section hierarchy.

There is a description for the `<meta>` element [§4.2.3.3.4](https://w3c.github.io/epub-specs/epub33/core/#sec-meta-elem) but I did not find the expression "attach a property to an element" there either. This usage of `<meta>` is all over the place in the section on metadata, so I believe this terminology should be made more explicit.

**Comment by mattgarrish** [comment]
Yes, "attached" is best kept for attributes. "Associated" would probably make more sense for the `refines` linkage. We can hyperlink "associated" to the `refines` attribute to make it clear what that means, too.
