### ISSUE TITLE
(Editorial) placement of the rendering metadata

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1377]
There is some sort of an inconsistency of the placement of the rendering metadata vocabulary in [§4.3.3](https://w3c.github.io/epub-specs/epub33/core/#sec-package-metadata-rendering) whereas all the other vocabularies are defined as part of [Appendix B](https://w3c.github.io/epub-specs/epub33/core/#app-vocabs). I believe the rendering metadata should be moved to Appendix B.

**Comment by mattgarrish** [comment]
I'm not sure I agree, as we've tried various permutations of treating it like a vocabulary only to frustrate people trying to find information (in 3.0.1 the property declarations were a separate vocabulary, in 3.1 they were moved to an external document, and in 3.2 the were merged back into the implementation details).

Like the issue I just opened for the nav doc, I wonder if we should deemphasize the vocabulary aspect and merge with the content document section into a new top-level section on fixed layouts (i.e., restore it back closer to the original [separate specification](http://idpf.org/epub/fxl/) it was before we had to dice it to fit in the core specs).

That still leaves the general properties, but perhaps those can go into the appendix. (For consistency, we might get away with listing all the rendition properties but for the fixed layouts reference back into the new section for the actual details of their use.)

**Comment by iherman** [comment]
What I am really worried about is the inconsistency; I do not really have a strong opinion as for where the various vocabulary specification live within the document. (I am mildly in favour of keeping them in the text, actually, rather than an Appendix.) But there is no reason I would see to treat the rendering vocabulary differently.

**Comment by mattgarrish** [comment]
> But there is no reason I would see to treat the rendering vocabulary differently.

We've been there and done that and all it led to was confusion and complaints.

The fixed layout properties aren't just "a vocabulary" but arguably the key component of understanding fxl. The rest of the vocabularies are just simplistic tables that mention the property and where/how to use it, as they don't impact the rendering of the publication.

That's one of the reasons the vocabularies ended up outside the specification in the first place. We used to have them integrated in the body but they bogged down reading the specification. We moved them out of the way to simplify comprehension (and to avoid some logical inconsistencies that we've given up trying to be consistent about), but that led to complaints the fxl properties were too integral to have the information hived off. In the end, they all came back in at the end of their respective specifications 

What we have now may not meet the perfect bar of spec purity, but practically it's the place we've found the broadest agreement. I don't see a happy outcome where we bog the body back down with vocabularies or make it more difficult to locate FXL information.

Reconstituting a single FXL section should have greater benefits, in my opinion, as that's the last piece of fragmentation that has frustrated people. A little logical inconsistency doesn't bother me anymore with this being at least the fourth time I've had to try and reconfigure the vocabularies.

**Comment by iherman** [comment]
> Reconstituting a single FXL section should have greater benefits, in my opinion, as that's the last piece of fragmentation that has frustrated people.

What would that mean? Having an FXL section on the top level, collecting all FXL related information? If that works it may be a perfect, imho, and I agree it is fine if that creates inconsistency v.a.v. the vocabulary
