### ISSUE TITLE
Explanation needed for flow-scrolled-doc

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1378]
There is a statement in the [§4.3.3.3.1.3 on rendering properties](https://w3c.github.io/epub-specs/epub33/core/#layout-property-flow-overrides) that I do not understand and may need explanation:

> **flow-scrolled-doc**  
> Indicates the Author preference is to provide a scrolled view for overflow content, and each spine item with this property is to be rendered as a separate scrollable document.

This is a property for a spine item. How can one spine item control the flow of other items? 

Actually, although the definition is somewhat clearer for

>**flow-scrolled-continuous**  
> Indicates the Author preference is to provide a scrolled view for overflow content, and that consecutive spine items with this property are to be rendered as a continuous scroll.

What this seems to say is that putting this property on a spine element _turns all the spine items from that point into scroll_. Although strange, but at least it is well-defined. Specifically, this means that, in example 32 the item c01 is also rendered with a scroll, right?

Although... I presume if one of the consecutive spine items has `flow-paginated` set then this predominates.

I must admit I would expect these properties to be applicable on a single item only, ie, the one it is issued on. But as this is not the case, more explanation and possibly examples are needed imho.

**Comment by mattgarrish** [comment]
> This is a property for a spine item. How can one spine item control the flow of other items?

I'm not sure I'm following. The definition says (adding emphasis):

> and each spine item *with this property* is to be rendered as a *separate* scrollable document.

That means the document is loaded in the (appropriate) viewport and made to scroll until the end. When you swipe to the next content document there's no lingering effect. That document could scroll again, or it could be paginated, all depending on what global or spine-override is in effect on it.

The `flow` property isn't only for fixed layout pages, if that helps explain it. You could set a reflowable chapter to scroll instead of paginate.

> What this seems to say is that putting this property on a spine element _turns all the spine items from that point into scroll_.

No, it means that all consecutive spine items with this override are treated as one long scroll (i.e., each new document is added to the bottom of the scroll as you go). Only when you've reached the end of the set of spine items will some other flow effect take over.

Putting it on one item doesn't make any real sense, as far as I understand the property, as it's basically the same as using `flow-scrolled-doc`.

But this value/override was a bit rushed in 3.0.1 as it was not part of the original FXL model. I'm not sure how well implemented it is or what issues this kind of scrolling has on navigating (particularly the override model).

**Comment by mattgarrish** [comment]
But, I do agree in a more general sense that more explanation is needed for the rendering metadata. I don't think there's enough clarity both in terms of visualizing what these properties do individually and in relation to each other. Synthetic spreads and flow can get wildly confusing.

**Comment by murata2makoto** [comment]
@mattgarrish 

>But, I do agree in a more general sense that more explanation is needed for the rendering metadata. 

In the RS spec?

**Comment by mattgarrish** [comment]
> In the RS spec?

Yes, that's where it would likely make the most sense. We can always reference authors across for more information.

**Comment by iherman** [comment]
> **flow-scrolled-continuous**
> Indicates the Author preference is to provide a scrolled view for overflow content, and that consecutive spine items with this property are to be rendered as a continuous scroll.

Ah, now I understand. All spine items that are continuous are collected into _one_ continuous scroll. I somehow did not understand it.

Some examples, with figures, could really help, the section is a bit confusing. If we agree with the content, I may play with some figures.

At some point you mentioned that FXL may deserve its top level section and I think I do agree with that. At that point we can see the details...

**Comment by shiestyle** [comment]
I think “flow-scrolled-continuous” will be also used for vertical scrolled Manga like ‘Webtoon’.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-10-28-epub#section3) on 2021-10-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 3. Flow Control.

_See github issue [epub-specs#1378](https://github.com/w3c/epub-specs/issues/1378)._




**Dave Cramer:** this issue originally came from Ivan that we have rendering properties for authors to express if content is paginated or scrolled.  
… we have two types of scrolled - one continuous one where all documents scroll and scrolled-doc where each document scrolls but you transition between them.  
… you can set these globally for all spine items and also override them per spine item.  
… I believe this was clarified in the issue discussion but there was some appetite to have better images and descriptions of this in the spec.  
… the larger point is how do these things interact with synthetic spreads and that gets complicated.  

**Matt Garrish:** That sounds generally correct.  
… The interactions between these fixed layout properties are confusing.  
… We (probably) originally envisioned them as global.  
… We aren't even sure if this even work (eg scrolled).  

**Dave Cramer:** do all the possible combinations of these properties make sense.  

**Hadrien Gardeur:** it's worth pointing out that scrolled continuous is not the most implemented feature - it is difficult to implement - it is a useful feature for certain types of publications but it's questionable whether the author or the user should control - webtoons are an example of where it gets tricky on how to control as the author intent is arguably more important.  

**Shinya Takami (高見真也):** in Japan we need scrolled continuous for webtoons and Apple reading system handles it - I don't know any use cases for scrolled-doc.  

**Dave Cramer:** I wonder if this is a case for writing a grid of test possibilities and see what happens - maybe this will reveal what makes sense and what doesn't and what has actually been implemented.  

**Hadrien Gardeur:** aside from webtoons is manga let user decide if they want to use spreads or paginated view or scrolled continuous - not something the content needs except for webtoons - also used as an easy way of reading manga - need to distinguish author and user preference and that's where our issue is - if it is important it shouldn't be overridden.  

**Wendy Reid:** this falls into the same category of potential spec overreach as the fxl orientation properties - we had good intentions in providing the option for authors to specify landscape orientation but user choice comes above all else - whatever the user wants to do should is paramount.  
… do we need all these options?.  

**Dave Cramer:** I have seen interesting uses of odd combinations of the properties - some educational material uses synthetic spreads to put a graphical page on one side and a scrolling doc in the other side so they can read about the graphic while still being able to view it - not sure I want to lose possibilities.  

**Charles LaPierre:** with orientation you can't force displays as it affects the accessibility of the document - user needs to be able to override.  

**Dan Lazin:** Dave wrote a [nice summary of what epub is](https://github.com/w3c/epub-specs/blob/main/epub33/explainers/EPUB33-explainer.md) for the TAG - that reading systems have tended to give preference to users should also be in it - there is still a lot of disagreement about what epub is and should be so we should try to agree on what the fundamental difference is between epub, html, and pdf.  

**Theresa O'Connor:** you said users come first in epub but that's also the priority of constituents on the web.  
… you're saying that web page rendered in browsers implement their own UI while epubs rely on reading system chrome - browser UI provides similar control but not akin to applications.  

**Dave Cramer:** when I author an epub I do not provide a way to change fonts or move page to page - completely dependent on reading system UI - when I make a web page I decide how it works.  

**Hadrien Gardeur:** even when the user doesn't override any setting the reading system injects a lot of script and styling - quite different from web in that regard.  
… always in constant negotiation between what the publisher wants, what the reading system has to do, and what the user wants.  

**Dave Cramer:** it doesn't feel like we're reaching a resolution on the issue - I think testing is key here to figuring out what we support.  

**Theresa O'Connor:** another example of browsers doing invasive things by default on behalf of users is text auto-sizing on mobile browsers - very complicated and invasive and has lots of effects on page that the author doesn't intend but the user wants.  

**Shinya Takami (高見真也):** I agree user should be able to select rendering - for webtoons we have to put in this property otherwise the images are not connected smoothly - maybe we could use new metadata for webtoons or discuss another solution.  

**Charles LaPierre:** for a scrolled doc couldn't we mark it at-risk if we don't have implementations?.  

**Dave Cramer:** yes, that's what we want to find out but we can't make them at-risk in advance of knowing - also have to make sure we don't break existing epubs.  

**Hadrien Gardeur:** one last note to say that we're in the middle of implementing this in readium - presentation API to combine these things together and figure out what gets precedence - it is pretty complex in fxl but user settings in general also are - adding any feature requires figuring out all the interaction and we haven't always done that in the past.  

**Dave Cramer:** if there is anything in the spec that doesn't make sense please open issues.  

</details>

**Comment by iherman** [comment]
Re-reading after several months, and also considering that the general principles are now illustrated by a series of figures in [§D.4.1.1](https://w3c.github.io/epub-specs/epub33/core/#flow) I think it is o.k. now.

I withdraw and close the issue...
