### ISSUE TITLE
Move navigation document out of packages section

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1383]
Now that the specifications are merged, there isn't the same need to shoehorn the nav doc definition into either the Packages or Content Documents sections, where it's never perfectly fit.

Is it time to promote it to a co-equal section, placed after content documents?

**Comment by murata2makoto** [comment]
Looks sensible to me.  But I think that now is the time to introduce more about required or recommended behaviors of RSes about navigation documents.  For example, George argued that spine items not reachable from navigation documents should be displayable.  I also think that structural navigation (e.g., go to the previous sibling from the current location) should be documented.   Does this proposed change make it easy to write down such required or recommended behaviors?

**Comment by mattgarrish** [comment]
I don't think it makes changes easier or harder; it just helps clarify the core features of the specification. If we need to add more requirements, those can always be requested.

And if we move ahead with this, I'd also update the RS spec to promote the same section there (the experiment I did only tweaked the core spec).
