### ISSUE TITLE
CSS Writing Modes reference

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1389]
[§5.3.3.1 CSS Writing Modes](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes) refers to [CSS-Writing-Modes-3-20151215](https://w3c.github.io/epub-specs/epub33/core/#bib-css-writing-modes-3-20151215) which is now outdated. I would think we should refer to [css-writing-modes-3](https://www.w3.org/TR/css-writing-modes-3/) to refer to the latest version...

**Comment by iherman** [comment]
Actually, the same comment applies to other CSS modules in the same section: undated references should be used to ensure referring to the latest version.

I realize there that some mapping may go wrong in newer versions of the respective CSS modules, which may require future versions to of the EPUB document to be upated. But the current approach "baking in" outdated CSS document version is probably not a good idea (and I suspect will also be rejected by future document reviews.)

**Comment by dauwhe** [comment]
Given the dramatic changes that CSS Writing Modes went through, we had to point to a very specific version or else nothing would make sense. We can of course re-evaluate that now that CSS Writing Modes is a **W3C RECOMMENDATION**!!!!

**Comment by murata2makoto** [comment]
[§5.3.3.1 CSS Writing Modes](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes) is for the -epub- prefix.  I believe that many EPUB publications in Japan used this prefix while CW was a WD.  These EPUB publications will not go away.  I thus oppose to any changes.

**Comment by toshiakikoike** [comment]
Probably the most influential is,
 "-epub-text-combine"

Especially for those produced around 2011-2013, it is specified as follows.

```
.tcy {
  -epub-text-combine:horizontal;
}
```
This is expected to be treated as 
 "text-combine-upright: all;"

**Comment by iherman** [comment]
> [§5.3.3.1 CSS Writing Modes](https://w3c.github.io/epub-specs/epub33/core/#sec-css-prefixed-writing-modes) is for the -epub- prefix. I believe that many EPUB publications in Japan used this prefix while CW was a WD. These EPUB publications will not go away. I thus oppose to any changes.

@murata2makoto nobody proposed any changes, let alone removal, of those features. But the current text is, at least as far as I am concerned, extremely confusing.

**Comment by murata2makoto** [comment]
@iherman 

>@murata2makoto nobody proposed any changes, let alone removal, of those features. But the current text is, at least as far as I am concerned, extremely confusing.

Referencing the latest version only is a big change.

**Comment by dauwhe** [comment]
Note: `text-combine-upright: digits` has been moved to CSS Writing Modes Level 4

**Comment by dauwhe** [comment]
Closed via #1655
