### ISSUE TITLE
Introductory part of Media Overlays and the Audiobook spec

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1394]
The introductory part of [§6](https://w3c.github.io/epub-specs/epub33/core/#sec-overlays-introduction) talks about the possibility of using EPUB as some form of audiobooks (if I understand the text correctly, it is a bit vague). I wonder whether some words and reference to the Audiobooks standard should be added into the text to clarify the relationships. I am sure this question will come up frequently...

**Comment by wareid** [comment]
I'll propose some text in PR to try and clarify this!
