### ISSUE TITLE
(minor) is the description of the `xml-signature` vocabulary item correct?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1397]
The [current definition](https://w3c.github.io/epub-specs/epub33/core/#sec-xml-signature) includes the sentence:

> Identification of XML signatures will be addressed in a future version of EPUB.

Isn't it correct that the future is here:-) and we should refer to the [section on `signature.xml`](https://w3c.github.io/epub-specs/epub33/core/#sec-container-metainf-signatures.xml) instead?

**Comment by iherman** [comment]
Related issue: [Example 89](https://w3c.github.io/epub-specs/epub33/core/#example-89) uses the `xml-signature` element. I am not sure it is o.k. to use a deprecated property in an example...

**Comment by mattgarrish** [comment]
> Isn't it correct that the future is here:-) and we should refer to the [section on `signature.xml`](https://w3c.github.io/epub-specs/epub33/core/#sec-container-metainf-signatures.xml) instead?

I believe that's the past.

See, for example: https://github.com/w3c/epub-specs/issues/678#issuecomment-200869885

**Comment by iherman** [comment]
Ah, it was discussed before! Did not realize that, sorry.

We can close this. My comment on not using it in an example still holds, though.

**Comment by mattgarrish** [comment]
> My comment on not using it in an example still holds, though.

Agree with removing.

Practically, the whole definition table should be removed and a pointer back to 3.0 given for more information, since that was the last time it was defined in the specification (and valid).

**Comment by mattgarrish** [comment]
And the same should be done for all the other deprecated properties.

Not sure why we didn't give them the same treatment as the deprecated features.
