### ISSUE TITLE
[meta] create labels for conformance changes + summary in PR comments

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1408]
It would be neat to have labels to quickly identify PRs impacting conformance statements. For instance `conformance-content` and `conformance-rs`. Ideally the PR maintainer (hi @mattgarrish 😁) would add a quick summary as a comment before merging.

The idea is to facilitate the compilation of impactful changes. That can be helpful when tools like EPUBCheck or production tools start to update to EPUB 3.3 (just asking for a friend 😉).

Or maybe a change document is being edited in parallel already? 
In any case, sorry for being a little late in the game.

**Comment by wareid** [comment]
I am a big fan of this idea but @mattgarrish we should discuss incase this accidentally increases workload, then we can figure out how to make it manageable.

**Comment by mattgarrish** [comment]
Any change that impacts conformance requirements is a "substantive change" so has to be added to the [change log](https://w3c.github.io/epub-specs/epub33/core/#change-log). Those entries are linked to their respective issues which in turn are linked to the PRs that close them.

We could add more labels, but we have an awful lot of labels already. Most of what is being done right now is editorial (shuffling, clarifying, that sort of stuff)..

**Comment by mattgarrish** [comment]
Closing this as we have the change log and linkage between PRs. There may be more labels coming before long, too.
