### ISSUE TITLE
Remark on 'base' may have to be moved into the content spec

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1415]
In [§2](https://w3c.github.io/epub-specs/epub33/rs/#sec-rs-conf-general) of the RS document, under "XML Processing" there is a note:

>  Note: [HTML] and [SVG] are removing support for [XMLBase]. Authors are advised to avoid using this feature.

I would think this remark should be moved to the content document. RS must be conformant to XML Base I would think.

**Comment by dauwhe** [comment]
Lots of context here https://github.com/w3c/epub-specs/issues/1217

**Comment by mattgarrish** [comment]
Ya, I missed that inline note about authoring. Should be in the core spec.
