### ISSUE TITLE
Usage of WebIDL, Appendix A in RS.

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1420]
The RS document includes a separate section [§A JavaScript epubReadingSystem Object](https://w3c.github.io/epub-specs/epub33/rs/#app-epubReadingSystem), and this section is normative (it is not defined as non-normative). WebIDL is considered (these days) as _defining browser features_. In the present situation what that would mean is that to pass the CR criteria _**we would have to prove at least two browser implementations using this interface**_.

We probably do not want to do that, we cannot expect reading systems to implement a RS. This section must therefore be marked as non-normative. 

(We should also check with browser implementers whether the interface definition is valid and useful.)

**Comment by mattgarrish** [comment]
> we would have to prove at least two browser implementations using this interface

Reading systems have to extend JS for this, yes, so we'd have to show that you can access the object within html documents within a reading system. That is the normative requirement.

But we have a deferred issue about dropping RSO: https://github.com/w3c/epub-specs/issues/716

**Comment by iherman** [comment]
We used WebIDL in the JSON-LD 1.1 spec. It was used to define an interface to JSON-LD processing in a programming language independent way, but there is no requirement in JSON-LD11 to have any processing implemented in browsers. On the other hand, the current view for many is that WebIDL _must be used for browser interfaces only_. This view of the world led to formal objections at the time of our Proposed Recommendation of JSON-LD1.1, and we had to do some last minute kludge to get the documents published.

If indeed the resolution of #716 is to keep the interface, either in its current or some restricted form, I believe we should do an editorial change and define the interface using some other formalism. We should simply keep away from WebIDL just for our own sanity.

**Comment by mattgarrish** [comment]
> I believe we should do an editorial change and define the interface using some other formalism

But it's a javascript interface? It's to allow authors to query the reading system from within javascript. What other than WebIDL would you use for that?

Have a look at example 2:

```
var feature = "dom-manipulation";
var conformTest = navigator.epubReadingSystem.hasFeature(feature);
alert("Feature " + feature + " supported?: " + conformTest);
```

**Comment by iherman** [comment]
> But it's a javascript interface? It's to allow authors to query the reading system from within javascript

I do not have a satisfactory answer :-(

The interface is very small. We can simply define it in Javascript, or Typescript to get the type annotations, or something similar.

**Comment by mattgarrish** [comment]
Well, my preference would be to drop it if we can.

**Comment by iherman** [comment]
Just to move ahead with this:

The most obvious thing to avoid further issues is to make appendix A non-normative and forget about it for now...

**Comment by mattgarrish** [comment]
Didn't you write the WebIDL definition for this @danielweck ? Any thoughts on this issue?

I'd say stay the course if we're not deprecating some or all of the object, otherwise you're changing a normative requirement over a definition.

**Comment by iherman** [comment]
> Didn't you write the WebIDL definition for this @danielweck ? Any thoughts on this issue?
> 
> I'd say stay the course if we're not deprecating some or all of the object, otherwise you're changing a normative requirement over a definition.

If we stay normative, we must change the WebIDL into something else. Otherwise, we may find ourselves in trouble.

**Comment by mattgarrish** [comment]
> Otherwise, we may find ourselves in trouble.

Can we ask the TAG to look at the use of webidl as part of their review? Is that who would take issue with it? That would at least clear up whether reading systems as html user agents count as implementations or whether webidl requires browser implementations.

**Comment by iherman** [comment]
> > Otherwise, we may find ourselves in trouble.
> 
> Can we ask the TAG to look at the use of webidl as part of their review? Is that who would take issue with it? That would at least clear up whether reading systems as html user agents count as implementations or whether webidl requires browser implementations.

Not necessarily a TAG question. At this moment there is no clear-cut decision on this but, for some, a WebIDL specification (mainly those that have a `[Exposed=(Window)]` annotation is so closely bound to the browser world that they regard such a specification as being considered to be a _MUST_ for a compliant browser to implement. (Which is not our intention.) That is why there was a formal objection against a specification at the Proposed Recommendation vote, and we had to do something not really clean to dissipate this problem. I just want to avoid finding ourselves in a similar situation down the line.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#section3) on 2021-04-08

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#resolution1):  Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL***

<details><summary><i>View the transcript</i></summary>

### 3. WebIDL/epubReading System 

_See github issue [#1610](https://github.com/w3c/epub-specs/issues/1610), [#1420](https://github.com/w3c/epub-specs/issues/1420), [#716](https://github.com/w3c/epub-specs/issues/716)._




> *Wendy Reid:* See [relevant section in the core spec](https://www.w3.org/TR/epub-rs-33/#app-epubReadingSystem)

**Ivan Herman:** we have a separate section with a small webIDL describing the RSO  
… i have two questions  
… first, should it be normative? (it currently is)  
… second, if normative, we may run into the problem that webIDL is considered by browser implementors as something they have to implement  
… other specs I've worked on have used webIDL, and it has gotten us into trouble  
… I'd prefer to avoid this if possible  
… the spec also calls it a JS epubReadingSystem object, but webIDL is supposed to be language independent  

**Dave Cramer:** is there something in W3C policy that says if you use webIDL then all browsers must implement it?  

**Ivan Herman:** no, BUT i'd rather not get into this type of discussion about down the line  
… some other people might disagree with me and say that implementation is required. We do not want this discussions with the AC at voting time.  

**Brady Duga:** i think webIDL is for things intended to be implemented by browsers  
… but it does seem to be a normative requirement because of statements that we make later on in the appendix  

**Wendy Reid:** can someone please explain the importance of webIDL?  

**Brady Duga:** we were just trying to describe the RSO stuff using webIDL  

**Tzviya Siegman:** one of our goals is the define the role of the RS more clearly, and I'm not sure that this section does that?  

**Dave Cramer:** I think it does, webIDL is the industry standard for describing APIs  

**Garth Conboy:** maybe we can just describe it in JS?  

**Ivan Herman:** I think yes  

**Garth Conboy:** so webIDL might be fine to use, but if JS is also fine to use, then maybe we can resolve this small thing by just using JS  

**Matt Garrish:** some time back there was also discussion about maybe dropping RSO entirely...  

**Ivan Herman:** if we turn that section into informative only, then that allows us to bypass formal objections down the line?  

**Dan Lazin:** are we currently just discussing the question of how to DOCUMENT RSO? And how widely implemented is it?  

**Dave Cramer:** some do, some don't  

**Garth Conboy:** do we care about the requireness of this given that support isn't unanimous  

**Brady Duga:** not sure how common this is. We should write a test and try it in some RSes  
… has anyone in this call implemented it?  
… yes it is normative now, and there are MUST statements that point to this, but on the other hand we might spend a lot of time on this only to find out that no one really uses it  
… if no one implements this, then we can decide whether to drop it or make it non-normative etc.  
… and publishers should tell us if they use JS in their epubs, and if yes, then have they relied on this being available  

**Dave Cramer:** we've used this because of the state of epub interoperability  
… we use this to figure out which RS our epub is in  
… e.g. UA sniffing  

**Dan Lazin:** speaking of interop, one of the testing questions is: When we identify that not RS currently supports, e.g. Opus, does that mean that it ought not to be a core media type?  
… my feeling is that giving guidance on where we want to go is a pathway towards future interop  
… but when we mandate things that are not widely used, that leads RS implementors to not know what to trust  
… and I'm happy to write a test about this  

**Ken Jones:** a lot of FXLs with interactive content rely on scripting, so this is important  

**Dave Cramer:** it is possible to support scripting without relying on epubReadingSystem Object  

**Ivan Herman:** for now, do we say that this thing should be implemented by RS?  
… the other possibility is that we keep as normative requirement, but flag as at risk  

**Avneesh Singh:** +1 to ivan, flag at risk and keep as normative requirement for now

**Ivan Herman:** I'm leaning towards the second option, plus, rewording the section using JS  

> **Proposed resolution: Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL** *(Wendy Reid)*

> *Garth Conboy:* +1

> *Gregorio Pellegrino:* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Deborah Kaplan:* +1

> *Masakazu Kitahara:* +1

> *Avneesh Singh:* +1

> *Dan Lazin:* +1

> *Ben Schroeter:* +1

> *Matthew Chan:* +1

> *Ivan Herman:* +1

> *Tzviya Siegman:* +1

> *George Kerscher:* +1

> *Charles LaPierre:* +1

> ***Resolution #1: Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL***

</details>
