### ISSUE TITLE
Proposal: Compatible Features to add to Unsupported Features

### ISSUE THREAD

**Issue by shiestyle** [w3c/epub-specs#1424]
For some features which may be deprecated, we want to clarify what we expect reading systems or EPUBCheck to behave for the specs.
There are some features that we expect reading systems to continue to support and EPUBCheck will not mark as Error.
So, can we add a new type like Compatible Features for 'align-x-center' or 'epub-' CSS types, for example.

- Compatibility Features [New]
 Authors are 'strongly RECOMMENDED not to use'
 Reading Systems 'SHOULD support'
 EPUBCheck: expected to be marked as Info

- Deprecated Features
 Authors are 'strongly RECOMMENDED not to use'
 Reading Systems 'MAY support'
 EPUBCheck: expected to be marked as Warning

- Legacy Features
 Authors 'MAY include'
 Reading Systems 'MUST NOT support'
 EPUBCheck: expected to be marked as Error

**Comment by mattgarrish** [comment]
> * Compatibility Features [New]
>   Authors are 'strongly RECOMMENDED not to use'
>   ...
>   EPUBCheck: expected to be marked as Info

Shouldn't the authoring requirement only be advisory if validation isn't expected to flag these as warnings? If these are needed to ensure operation in older reading systems, strongly recommending they not be included is maybe too forceful.

The recommendation sounds like it should be to use these only in conjunction with whatever new preferred method is available.

Or is this only to try and grandfather old content that used these features?

> * Legacy Features
> ...
>   EPUBCheck: expected to be marked as Error

For the record, legacy features are not errors. They are only reported if used invalidly.

**Comment by toshiakikoike** [comment]
For example, about "rendition:align-x-center", I think the following is appropriate;
EPUBCheck: expected to be marked  as Warning

But, about -epub- prefix, I hope EPUBCheck no errors and warnings.

**Comment by dauwhe** [comment]
> But, about -epub- prefix, I hope EPUBCheck no errors and warnings.

Agree.

**Comment by shiestyle** [comment]
We discussed this in Japanese community and we got no objection to close.
