### ISSUE TITLE
Clarify pagebreak in spec 

### ISSUE THREAD

**Issue by edent** [w3c/epub-specs#1437]
I think the specification around pagebreak is ambiguous. I would like to clarify it for readers and publishers.

It currently says:

> **pagebreak**
>  *  A separator denoting the position before which a break occurs between two contiguous pages in a statically paginated version of the content.
>  *  HTML usage context: phrasing and flow content, where the value of the carrying elements title attribute takes precedence over element content for the purposes of representing the pagebreak value

https://github.com/w3c/epub-specs/blob/8b7e0966b14d0ab65a693fc7d1c63e822ed1879b/epub33/core/vocab/structure.html#L2355

I recently purchased an eBook which has this markup:
```html
<span id="pg5" epub:type="pagebreak">‘But</span> of course!’
```

Throughout the book, the first word, or first letter, on a page is wrapped with ` epub:type="pagebreak"`.  When I tried to view it in a popular eReader, the words in the span didn't render. This is expected behaviour because, normally, the contents of that element would be a page number.  See https://github.com/koreader/koreader/issues/6894

A few other rendering engines (like Kindle) did display the text.

Judging from the example ePubs, I suspect that the intent of this part of the spec is that the content of that element must *only* contain a page number.  That won't necessarily be an integer, it could be `Page 42` or `ⅩⅬⅡ`. But the default assumption should be that it is *metadata* and may not be displayed to a user.

I think that the spec should say something like this:

"Element content *should* be empty. If element content is not empty, the content *must* be text relating to the page number. Not all clients will display pagebreak metadata."

**Comment by mattgarrish** [comment]
I'm not sure we want to recommend visible or invisible page numbers, as there are legitimate reasons for both, but we have improved the requirement for `doc-pagebreak` along similar lines for the next version. It now reads:

> Authors MUST ensure the name of the page break is an end user-consumable page number that identifies the page that is beginning so that assistive technologies can announce the page as needed (e.g., in a command to identify the current page).

We definitely should port that wording back here.

**Comment by dauwhe** [comment]
Should we use more of the language from DPUB-ARIA 1.1? It looks rather more informative than what we have in `core/vocab/structure.html` right now?
