### ISSUE TITLE
Mention multiple renditions without describing them in detail

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1442]
The merged text (#1438) completely disallows multiple renditions.  

I propose to replace 

> An EPUB Publication is represented by a Package Document

by

> An EPUB Publication is typically represented by a single Package Document

I also propose this paragraph.

> EPUB 3.2 allows an EPUB publication to be represtened by more than one Package Document.  EPUB 3.3 continues to allow such EPUB publications.  However, detailed descriptions of such EPUB publications are removed from this document but are moved to "EPUB Multiple-Rendition Publications 1.1" (WG Note).

**Comment by mattgarrish** [comment]
I'd recommend waiting until I have some additional fixes in place before merging the proposed PR. I just haven't had as much time as I expected while on the road. They should address these concerns.

**Comment by murata2makoto** [comment]
I oppose to closing this issue without waiting Matt has "some additional fixes in place before merging the proposed PR."  The currently merged change is far from being satisfactory.

**Comment by mattgarrish** [comment]
Have you had a look at https://github.com/w3c/epub-specs/pull/1448 ? That was the updated version of the pull request.

I incorporated both items you raised here. This sentence:

>An EPUB Publication is typically represented by a single Package Document

is in organization section: https://w3c.github.io/epub-specs/epub33/core/#sec-intro-spec-org

There's also a note that multiple package documents are allowed in the package document introduction: https://w3c.github.io/epub-specs/epub33/core/#sec-package-intro

The section on the container.xml file also has a note pointing to the multiple renditions specification: https://w3c.github.io/epub-specs/epub33/core/#sec-container-metainf-container.xml

I also made a number of other editorial fixes to make clear that multiple renditions are allowed, as detailed in the pull request text.

If there are additional issues you'd like to address, it would help if you could open new issues for them.

**Comment by murata2makoto** [comment]
@mattgarrish Sorry for my oversight.  I was not aware of #1448.  I withdraw my opposition and will look into it.
