### ISSUE TITLE
Adding JSON-LD for the structural semantics?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1446]
(This is minor comment)

The core spec refers to RDFa and Microdata as means to semantically enrich the XHTML content. Shouldn't we add, for completeness, the possibility of using a `<script>` element with JSON-LD for the same purpose? The usage of JSON-LD has come to the fore lately through its adoption for schema.org metadata, alongside RDFa and microdata...

**Comment by dauwhe** [comment]
I would feel better about this if there was any evidence that such metadata has actually been used by any reading system...

**Comment by mattgarrish** [comment]
It's also not an extension of HTML that we need to explicitly allow. That section isn't meant to cover anything that HTML makes possible.

Now that we reference the whatwg spec, there's actually a good argument to remove the microdata section since microdata is integrated into the whatwg document.

We could always add a clarifying note to the RDFa section about why the other technologies are not listed.

**Comment by iherman** [comment]
> I would feel better about this if there was any evidence that such metadata has actually been used by any reading system...

I agree with that, but the same question arises with RDFa or microdata... The issue is completeness.

**Comment by iherman** [comment]
> It's also not an extension of HTML that we need to explicitly allow. That section isn't meant to cover anything that HTML makes possible.
> 

Ah. I must admit that I missed the exact positioning of this section which indeed makes my original issue moot.

> Now that we reference the whatwg spec, there's actually a good argument to remove the microdata section since microdata is integrated into the whatwg document.

Indeed. (That is probably what made me go wrong.)

> We could always add a clarifying note to the RDFa section about why the other technologies are not listed.

+1. 

@mattgarrish do you want me to do a PR on these things? I hate to dump everything on your back...

**Comment by iherman** [comment]
B.T.W., the right reference for RDFa should probably be this: https://www.w3.org/TR/rdfa-in-html/ (or both).

**Comment by mattgarrish** [comment]
> do you want me to do a PR on these things? I hate to dump everything on your back...

No worries. I've finally got a mostly-free day to catch up on things. I'll take a look at the big renditions PR that is open and see if it's worth trying to do this now or if it's better to wait a few days until we can get that one merged to avoid conflicts.
