### ISSUE TITLE
What does it mean to have a "primary" dc:title? 

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1460]
[Spec says](https://w3c.github.io/epub-specs/epub33/rs/#title-order) 

>   Reading Systems MUST recognize the first title element in document order as the main title of the EPUB Publication (i.e., the primary one to present to users). This specification does not define how to process additional title elements.

As I try to write a test for this, what do we mean by "primary"? Would it be simpler to say that the first `dc:title` element must be displayed first?

**Comment by mattgarrish** [comment]
> Would it be simpler to say that the first `dc:title` element must be displayed first?

Display prioritizes visual access. An RS with an audio interface may not display anything but also needs to meet this requirement.

**Comment by dauwhe** [comment]
> Display prioritizes visual access. An RS with an audio interface may not display anything but also needs to meet this requirement.

I would expect an audio rendition would speak the primary title first?

**Comment by dauwhe** [comment]
Perhaps this?

> Reading Systems MUST recognize the first title element in document order as the main title of the EPUB Publication, and present it to users before other title elements. This specification does not define how to process additional title elements.

**Comment by mattgarrish** [comment]
> I would expect an audio rendition would speak the primary title first?

Right, that's why various presentational wordings are a little non-committal. "Presenting" and "rendering" are non-specific about how it happens.

> Reading Systems MUST recognize the first title element in document order as the main title of the EPUB Publication, and present it to users before other title elements.

Sounds fine to me.
