### ISSUE TITLE
Possible ambiguity in section 3.4.3.2.1 The identifier Element

### ISSUE THREAD

**Issue by OriKuttner** [w3c/epub-specs#1461]
In EPUB Packages 3.2 in section 3.4.3.2.1 the id element is said to be optional, however the language later is:
"The metadata section MUST include an identifier element that contains an unambiguous identifier for the Rendition. This identifier MUST be marked as the Unique Identifier via the package element unique-identifier attribute."

So the id is not optional, it is the id marked as unique-idnetifier.

I guess the meaning is that if there are more then one dc:identifier elements, the id is optional.
So I think the language should be clearer.

**Comment by dauwhe** [comment]
I think you mean "id attribute is said to be optional" ? 

Yes, it looks like at least one identifier must have the id attribute to link to the package's unique-identifier attribute. But other dc:identifier elements are not required to have an id attribute. 

I'll see if we can clarify the text a little bit. The examples are all good; it's tricky to write the definition list to cover this circumstance.

**Comment by OriKuttner** [comment]
Yes,
That is what I mean.
We can say that at least one dc:identifier must have an id attribute.

**Comment by mattgarrish** [comment]
> it's tricky to write the definition list to cover this circumstance

The precedent is to use "conditionally required". It would then require some elaboration on the condition, so also add a parenthetical to the description:

> This identifier MUST be referenced as the Unique Identifier in the package element's unique-identifier attribute (i.e., via the value of its `id` attribute).
