### ISSUE TITLE
(I18n) Missing hreflang attribute

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1488]
The [i18n self test](https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec/_edit) says:

> Attributes that express the language of external resources should not use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes, but should use a different attribute when they represent metadata (which indicates the intended use of the resource rather than the language of a specific range of text). <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">more</a>

This may be relevant for the [`link` element](https://w3c.github.io/epub-specs/epub33/core/#sec-link-elem). Should we add a `hreflang` attribute (like in HTML)?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#section6) on 2021-02-04

List of resolutions:

- ***[Resolution No. 6](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#resolution6):  Close 1488, accept PR 1497***

<details><summary><i>View the transcript</i></summary>

### 6. Missing `hreflang` attribute 

_See github issue [#1488](https://github.com/w3c/epub-specs/issues/1488)._




**Dave Cramer:** 1488  
… missing `hreflang` attribute  
… *see issue*  
… there is a PR from Matt  

_See github pull request [#1497](https://github.com/w3c/epub-specs/pull/1497)._




**Dave Cramer:** PR 1497  
… this is designed for the links in the package file  
… if we're linking to external metadata, we can determine the language of the file  
… consistent with other vocabularies  
… this would be new, and wouldn't break anything  
… any comments?  

**Ben Schroeter:** Trying to understand the usage of this?  

**Dave Cramer:** Say you have a multi-lingual epub, multiple metadata records  
… norwegian canadian dictionary that has one record in norwegian and one in canadian english  
… if the UI is set in one language, it can know to present the correct metadata to the user  
… the RS doesn't have to determine the vocab from the resource, it can determine before download  
… a hint  

**Ben Schroeter:** Ok  

**Dave Cramer:** I'm not aware of a RS that does this  

**Brady Duga:** You can link to external metadata records? /sarcasm  

**Dave Cramer:** We can write a test for it, but no RS will test it  

**Ben Schroeter:** And where will you find a Norwegian-Canadian dictionary...  

**Brady Duga:** This PR does add another untestable conformance requirement  

**Dave Cramer:** I feel we're a little bit stuck here  
… it's an i18n best practice  
… if we say we're going to have linked metadata, we should have this  
… we put this in, we get tests, the concept gets marked as at-risk at CR  
… I think we should accept the PR, then see what testing shows us  

> **Proposed resolution: Close 1488, accept PR 1497** *(Wendy Reid)*

> ***Resolution #6: Close 1488, accept PR 1497***

**Dave Cramer:** Progress!  
… on i18n issues at least  
… thanks everyone  

> *Teenya Franklin:* goodnight

**Dave Cramer:** see you all in the comment section  

> *Dave Cramer:* RRSAgent: draft minutes

> *Dave Cramer:* RRSAgent: bye

---


</details>

**Comment by murata2makoto** [comment]
I do not like the hreflang attribute.  Metadata or HTTP headers for the referenced contents should specify the used language.

I know that this is not always possible.  But hreflang is not a solution but a hack.
