### ISSUE TITLE
(i18n) Assuming direction from language

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1490]
The [i18n self test](https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec/_edit) says:

> Do not assume that direction can be determined from language information. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_lang">more</a>

Maybe worth adding such a warning in the package specification. At this moment there is none.

**Comment by mattgarrish** [comment]
> Maybe worth adding such a warning in the package specification.

This becomes unnecessary to state if PR #1498 is incorporated, correct?

By defining the process for "auto" (including no or an invalid value), it shouldn't leave this open as an option.

**Comment by iherman** [comment]
I believe that is true, because #1498 gives an explicit determination of the direction without relying on language.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#section4) on 2021-02-04

List of resolutions:

- ***[Resolution No. 4](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#resolution4):  close 1490 because mooted by PR 1498***

<details><summary><i>View the transcript</i></summary>

### 4. Assuming direction from language 

_See github issue [#1490](https://github.com/w3c/epub-specs/issues/1490)._




**Dave Cramer:** 1490, do not assume that direction can be assumed from language information  
… but then we have PR 1498  

_See github pull request [#1498](https://github.com/w3c/epub-specs/pull/1498)._




**Brady Duga:** If we accept 1498, we don't care about this, according to the comments  

**Dave Cramer:** Not to mention the i18n folks who have commented  
… this one is kind of moot  

**Brady Duga:** Will not fix, obsolete  

> **Proposed resolution: close 1490 because mooted by PR 1498** *(Dave Cramer)*

> ***Resolution #4: close 1490 because mooted by PR 1498***

</details>
