### ISSUE TITLE
(i18n) 'auto' value for the 'dir' attribute?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1491]
The [i18n self test](https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec/_edit) says:

> Values for the default base direction should include left-to-right, right-to-left, and auto. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_values">more</a>

We do not have this for `dir`, there is a `default` for `page-progression-direction`. We could be inspired by the [HTML specification](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute).  Note that the behavior of `dir` can also be modeled (or referred to?) the HTML spec.

**Comment by mattgarrish** [comment]
Looks like this was deferred because no one was asking for it at the time: https://github.com/w3c/epub-specs/issues/57

**Comment by iherman** [comment]
This may be related, actually, to #1494: the value of `auto` may mean to rely entirely on the content of the string, directed by the UNICODE rules. In other words, if there is an agreement of #1494 that the attribute value wins in priority, `auto` may mean what is said now. It would then also make sense to say explicitly that `auto` is the default value (something that, I believe, is not specified anywhere).

**Comment by xfq** [comment]
FYI - the i18n WG is working on a centralized definition of ltr/rtl/auto that specs can refer to (see also the discussions in https://github.com/w3c/manifest/pull/926 ).

**Comment by iherman** [comment]
Thanks @xfq.

@mattgarrish, looking at the text in https://github.com/w3c/manifest/pull/926#issuecomment-686573631 (provided by @r12a) do you think it would be possible to reuse this, although the text would have to be spread over the content and RS specs? It would also mean introducing the term `auto`, and would also close #1494.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#section1) on 2021-02-04

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#resolution1):  Add the default value of `auto` to the `dir` element, resolved 1491 and 1499***

<details><summary><i>View the transcript</i></summary>

### 1. What should be the default value for the dir attribute 

_See github issue [#1499](https://github.com/w3c/epub-specs/issues/1499), [#1491](https://github.com/w3c/epub-specs/issues/1491)._




_See github pull request [#1498](https://github.com/w3c/epub-specs/pull/1498)._




**Dave Cramer:** Also going to talk about 1491 because they're related  
… there is also a PR addressing this (#1498)  
… most of the i18n issues we face are in HTML, SVG, CSS, where we rely on those specs  
… our area of influence is the package doc  
… the `dir` attribute  
… it doesn't have a default value  
… some guidance from i18n says we should have a default of `auto`  
… lets the system decide what to do, which depends on them, and can be overwritten by `rtl` or `ltr`  
… we have a PR open to address this  
… Matt has added this  
… is this a good idea and will it break anything  
… `ltr` = left to right  
… `rtl` = right to left  

**Brady Duga:** I think there is some history we want to keep with HTMLs LTR by default  
… for our case it makes sense to use `auto` because that's how things work now  
… the default is `auto`  
… HTML doesn't have a default, but the root is LTR, but it also has more complex inheritance  

**Dave Cramer:** I don't want to worry about the HTML situation  
… there are complexities  
… it seems to me that adding auto is risk free as a default  
… I can't imagine writing a test where something would happen  

**Brady Duga:** The scarier thing is the inherent directionality of the text winning over the `dir` attribute  

**Dave Cramer:** I wonder that too  
… went down a rabbit hole  
… stared into the abyss...  

**Brady Duga:** If there's an inherent directionality, it wins over `dir`, `dir` might mean nothing  

**Dave Cramer:** base paragraph direction over the bits of text within  
… atomic elements of the package file that have no instructions  
… instinct to have auto as a nice to have  
… doesn't change existing behaviour  
… the only person who needs to worry is the tester  
… I would propose we resolve to add the auto value  
… does anyone object  

> **Proposed resolution: Add the default value of `auto` to the `dir` attribute, resolved 1491 and 1499** *(Wendy Reid)*

> ***Resolution #1: Add the default value of `auto` to the `dir` element, resolved 1491 and 1499***

**Dave Cramer:** We got it! Moving on to 1494  

</details>
