### ISSUE TITLE
(i18n) Additional 'refines' values?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1493]
The [i18n self test](https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec/_edit) says:

> Provide a span-like element that can be used for any text content to apply information needed for internationalization. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#plain_span">more</a>

It is not possible to provide such structures: all relevant elements have been defined by DCMI, and this specification cannot change them. The additional concerns related to internationalization and localization, e.g., alternate scripts or sorting information, are provided by the `refines` mechanism,  see [example in the spec](https://w3c.github.io/epub-specs/epub33/core/#sec-opf-dccreator). Do we need more values for `refines`, e.g., related to translations? Or at least making it clear in the spec that such values can also be used?

**Comment by mattgarrish** [comment]
> Or at least making it clear in the spec that such values can also be used?

Adding more properties to the meta vocabulary has become something of a method of last resort. The idea was that we would only document common patterns: https://idpf.github.io/epub-guides/package-metadata/

I'd probably wait for someone to raise a pressing case that needs addressing. Whenever we open this door it's hard to shut again, and much of our metadata already goes unused in reading systems.

**Comment by dauwhe** [comment]
Discussed by the WG on 2020-02-04. We agree with Matt's comment, and that there is nothing for the WG to do here.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#section3) on 2021-02-04

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#resolution3):  Close 1493 as we cannot fix this issue***

<details><summary><i>View the transcript</i></summary>

### 3. Additional 'refines' values? 

_See github issue [#1493](https://github.com/w3c/epub-specs/issues/1493)._




**Dave Cramer:** We'll resolve by PR  
… 1493, `<span>` should provide data for the interpretation of text  
… we are stuck with the DC terms language  
… which we can't control  
… we've used "refines" before  
… there's a lot of examples from Japan regarding sorting and pronunciation of names  
… we can't make this change to EPUB  
… we have these mechanism  
… if there's an important use case comes up that doesn't fit with what we already have  
… we'll address it, but we shouldn't try to create something without that information  

**Brady Duga:** I agree with Matt  

**Dave Cramer:** Me too  
… anyone else?  
… I would propose we close the issue, there's nothing for us to do here  

> **Proposed resolution: Close 1493 as we cannot fix this issue** *(Wendy Reid)*

> ***Resolution #3: Close 1493 as we cannot fix this issue***

</details>
