### ISSUE TITLE
(i18n) Relationship between dir and the content

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1494]
The [i18n self test](https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec/_edit) says:

> Specify that consumers of strings should use  heuristics, preferably based on the Unicode Standard first-strong algorithm, to detect the base direction of a string _**except where metadata is provided**_. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a> (emphasis is mine, I.H.)

This requirement seems to be contradicted by the spec. At the moment, the [EPUB 3.3 spec says](https://w3c.github.io/epub-specs/epub33/core/#attrdef-dir)

> Inherent directionality specified using [Unicode] takes precedence over this attribute.

The way I can read this is that the first-strong algorithm in Unicode wins over the value of the `dir` attribute. 

That would certainly be wrong; the [Publication Manifest example](https://www.w3.org/TR/pub-manifest/#example-2-set-the-language-and-the-base-direction-of-a-string) shows the situation where the value of `dir` must be followed in contrast to the first strong algorithm.

Maybe that was not the intention in the EPUB spec, but then it needs clarification.

**Comment by OriKuttner** [comment]
Why do you see this? it says: *except where metadata is provided*
So I think metadata wins over.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by iherman** [comment]
Here is the full [section on the `dir` attribute in the 3.3 version](https://w3c.github.io/epub-specs/epub33/core/#attrdef-dir):

>**`dir`**
> Specifies the base text direction of the content and attribute values of the carrying element and its descendants.
> 
> Inherent directionality specified using [Unicode] takes precedence over this attribute.
>
> Allowed values are `ltr` (left-to-right) and `rtl` (right-to-left).

Where do you see the "except where metadata is provided" note?

(I would be happy to be proven wrong!)

---

It is the same as in the [3.2 version](https://www.w3.org/publishing/epub3/epub-packages.html#attrdef-dir), i.e., this is not a matter of editorial issue when 3.3 was created out of the 3.2 specs.

**Comment by mattgarrish** [comment]
This goes back to the original 3.0 specification. I don't have any insight into the specifics of it (probably came from the EGLS group?), but I'm not sure I read it the same way.

What it seems to be saying to me is that if there is strong directionality in the text, that has precedence -- just because `dir` says the text is ltr, for example, doesn't mean that setting overrides an rtl run within it. I don't expect the intent was that if you find any directionality at the text level that supersedes the attribute.

But, in any case, it could certainly stand for clarification.

**Comment by mattgarrish** [comment]
What about wording more along these lines:

"If an element mixes text runs with different directionalities, the [Unicode] directionality of a text run takes precedence over the `dir` attribute where they differ."

**Comment by OriKuttner** [comment]
I think the dir attribute should take precedence.
As someone who uses RTL language (Hebrew) every day, I think the unicode
directionality is not always good enough.

**Comment by iherman** [comment]
> I think the dir attribute should take precedence.

I agree. I also think that this is the advice given by the i18n experts at W3C.

Switching on the I18n label to request an input from the i18n people

**Comment by iherman** [comment]
> What it seems to be saying to me is that if there is strong directionality in the text, that has precedence -- just because `dir` says the text is ltr, for example, doesn't mean that setting overrides an rtl run within it. I don't expect the intent was that if you find any directionality at the text level that supersedes the attribute.

The [example in the pub manifest](https://www.w3.org/TR/pub-manifest/#example-2-set-the-language-and-the-base-direction-of-a-string) is exactly the case where this would go wrong. The first strong directionally would be given by the letter 'H' and you _need_ the extra metadata to overwrite this to get the Hebrew text right.

**Comment by murata2makoto** [comment]
> I don't have any insight into the specifics of it (probably came from the EGLS group?), but I'm not sure I read it the same way.

I am afraid that I have no ideas.    [The recommendations from the EGLS subgroup](https://www.asahi-net.or.jp/~eb2m-mrt/epub/rec2WG.html) does not mention the dir attribute.

**Comment by matial** [comment]
The spec is not clear, but the requirement is simple IMHO. The dir attribute should be used to specify what Unicode (UAX #9 - Unicode Bidirectional Algorithm)) calls the paragraph direction (also called "base direction"), no less no more. The base direction does not override the inherent direction of text runs within the element but affects how those runs are ordered relatively to each other for display.

**Comment by r12a** [comment]
For determining the base direction of strings or inline insertions, the i18n WG recommends that first-strong heuristics be used by default to detect base direction, but those heuristics fail if a string begins with a character which has an opposite direction to the string as a whole (such as a book title in Arabic that begins with 'HTML').  For those cases there needs to be a way to explicitly override the heuristics, which is what the `dir` attribute does.

The `dir` attribute is also useful for setting a direction that will be inherited through a whole document or sections of a document, eg. at the top of an HTML file.

Setting a `dir` attribute is an explicit choice, and must therefore always override the application of heuristics unless the `auto` value is set.

hth

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#section2) on 2021-02-04

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#resolution2):  Fix 1494 by removing the untrue statement about the relationship between `dir` and the underlying text***

<details><summary><i>View the transcript</i></summary>

### 2. Relationship between dir and the content 

_See github issue [#1494](https://github.com/w3c/epub-specs/issues/1494)._




**Dave Cramer:** i18n self test says *what is in the ticket*  
… spec specifies that directionality in unicode takes precedence  
… over the `dir` attribute  
… Matt says if there's strong directionality in the text, that takes precedence  
… `dir` doesn't control everything  
… see [r12a's comments](https://github.com/w3c/epub-specs/issues/1494#issuecomment-772459326)  
… what Richard says there makes sense  
… we need to remove that line in the spec stating that unicode directionality takes precedence  
… it would conflict with the guidance from Richard  
… address the issue by having Matt removing that bit and clarifying the text  
… the relationship between the string and the dir attribute  
… any opposition?  

**Ben Schroeter:** The change being that `dir` wins?  

**Dave Cramer:** Removing the line that says strings can override `dir`  

**Brady Duga:** I don't think anyone knows what it means  
… `dir` sets the base direction  
… but it has nothing to do with unicode for instance  
… the unicode API does that  
… we're reaching  
… we should just say "this is what `dir` does"  

**Dave Cramer:** This is a lesson, if you get that deep into it, it's confusing  

> **Proposed resolution: Fix 1494 by removing the untrue statement about the relationship between `dir` and the underlying text** *(Wendy Reid)*

> ***Resolution #2: Fix 1494 by removing the untrue statement about the relationship between `dir` and the underlying text***

</details>
