### ISSUE TITLE
(i18n) What should be the default value for the dir attribute

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1499]
At the moment, the default value for the `dir` attribute in the package file does not seem to be explicitly stated. It should.

There seem to be two possibilities:

1. The defaults value is `auto` (being introduced in #1498 to be in line with i18n tests), which means that the directionality of the metadata item solely depends on the standard BIDI algorithms on Unicode characters
2. The default value is `ltr`, to be in line with the default value of the `dir` attribute of HTML, CSS, and SVG.

Item (2) would be better, otherwise it may be confusing. The question is whether this would disrupt current reading systems...

**Comment by bduga** [comment]
It seems if we want to be in keeping with HTML we should not have a default value, since HTML explicitly does not have a default value for dir. See https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute `The attribute has no invalid value default and no missing value default.` On the other hand, since dir can't be applied to any parent elements here (I think), perhaps ltr is close enough, since unspecified in HTML will generally inherit the parent setting, which will be ltr if nothing else was specified.

**Comment by bduga** [comment]
And it looks like `auto` is the default in the current pull request, which seems to make more sense than ltr.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#section1) on 2021-02-04

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-04-epub#resolution1):  Add the default value of `auto` to the `dir` element, resolved 1491 and 1499***

<details><summary><i>View the transcript</i></summary>

### 1. What should be the default value for the dir attribute 

_See github issue [#1499](https://github.com/w3c/epub-specs/issues/1499), [#1491](https://github.com/w3c/epub-specs/issues/1491)._




_See github pull request [#1498](https://github.com/w3c/epub-specs/pull/1498)._




**Dave Cramer:** Also going to talk about 1491 because they're related  
… there is also a PR addressing this (#1498)  
… most of the i18n issues we face are in HTML, SVG, CSS, where we rely on those specs  
… our area of influence is the package doc  
… the `dir` attribute  
… it doesn't have a default value  
… some guidance from i18n says we should have a default of `auto`  
… lets the system decide what to do, which depends on them, and can be overwritten by `rtl` or `ltr`  
… we have a PR open to address this  
… Matt has added this  
… is this a good idea and will it break anything  
… `ltr` = left to right  
… `rtl` = right to left  

**Brady Duga:** I think there is some history we want to keep with HTMLs LTR by default  
… for our case it makes sense to use `auto` because that's how things work now  
… the default is `auto`  
… HTML doesn't have a default, but the root is LTR, but it also has more complex inheritance  

**Dave Cramer:** I don't want to worry about the HTML situation  
… there are complexities  
… it seems to me that adding auto is risk free as a default  
… I can't imagine writing a test where something would happen  

**Brady Duga:** The scarier thing is the inherent directionality of the text winning over the `dir` attribute  

**Dave Cramer:** I wonder that too  
… went down a rabbit hole  
… stared into the abyss...  

**Brady Duga:** If there's an inherent directionality, it wins over `dir`, `dir` might mean nothing  

**Dave Cramer:** base paragraph direction over the bits of text within  
… atomic elements of the package file that have no instructions  
… instinct to have auto as a nice to have  
… doesn't change existing behaviour  
… the only person who needs to worry is the tester  
… I would propose we resolve to add the auto value  
… does anyone object  

> **Proposed resolution: Add the default value of `auto` to the `dir` attribute, resolved 1491 and 1499** *(Wendy Reid)*

> ***Resolution #1: Add the default value of `auto` to the `dir` element, resolved 1491 and 1499***

**Dave Cramer:** We got it! Moving on to 1494  

</details>

**Comment by iherman** [comment]
I believe this Issue can also be closed, @mattgarrish @wareid ?

**Comment by iherman** [comment]
Closing.
