### ISSUE TITLE
epub:type="cover" and ARIA-role "doc-cover" – possible contradiction in specs?

### ISSUE THREAD

**Issue by ThomasR128** [w3c/epub-specs#1507]
- The [EPUB Structural Semantics to ARIA Roles Mapping Guide](https://w3c.github.io/publ-cg/guides/aria-mapping.html#mapping-table) maps epub:type="cover" to role="doc-cover"
- The [EPUB Type to ARIA Role Authoring Guide](https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-mappings) has "No role" for epub:type="cover" but maps role="doc-cover" to the manifest property "cover-image" and elaborates [here](https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-mappings).

The former documents is the older of the two but since it is linked from [EPUB@W3C](https://w3c.github.io/publ-cg/#guides) I am slightly confused what document to follow.

**Comment by mattgarrish** [comment]
Looks like someone copied the guides with the intention of publishing them in the community group, but that version is out of date (and only a draft.) The mapping guide was merged into the second document you've referenced a long time back.

That [IDPF version](https://idpf.github.io/epub-guides/epub-aria-authoring/) is the most up-to-date one.

If in any doubt about where the ARIA roles can be used, see the [ARIA in HTML](https://www.w3.org/TR/html-aria/) document. It defines the authoritative list of elements the roles can be used on.

> it is linked from [EPUB@W3C](https://w3c.github.io/publ-cg/#guides)

That document is out of date, as well. It still refers to the EPUB community group and makes no mention of the 3.3 revision. I'm not sure it even belongs under the CG anymore.

Might be a good idea to take all those pages down until we can figure out who owns what and there's a proper plan to update/republish them.

**Comment by ThomasR128** [comment]
@mattgarrish Thanks for clarifying. A clean-up would be most welcome, although I understand that after the merger there are more urgent issues to resolve. For a newbie like me however, it is a bit confusing when some (IDPF) pages clearly state they're obsolete and redirect, some are but don't and others (apparently) are still valid… 😀

**Comment by mattgarrish** [comment]
> For a newbie like me however, it is a bit confusing

It's confusing even for old-timers like me! :)

Whenever the 3.3 revision is completed, a lot more of the IDPF repositories will become obsolete and hopefully will be shut down/redirected -- the structure vocabulary, core media types, reserved prefixes and metadata vocabularies are being reintegrated into the core spec. We'll also have to find a W3C home for the registries.

The guides are the only outlier, I believe. I'm fine with having them in the CG repository, but it requires updating the stale versions currently housed in the repository and coordinating a shutdown of the IDPF repository. Until then, this is just going to cause confusion.

**Comment by iherman** [comment]
@mteixeira-wwn @rakutenjeff see https://github.com/w3c/epub-specs/issues/1507#issuecomment-776243467. Maybe it is still time to discuss it later today on the CG call?

**Comment by ghost** [comment]
Yes of course. I will add to today's agenda.
Can anyone familiar with this thread also join our today's PCG meeting?
Sorry I probably should read through and understand this quickly but filled with other meeting from now until PCG meeting...

**Comment by mattgarrish** [comment]
Sorry, not sure I can make the calls today. I have a conflicting call at the 11 time slot and the later call collides with family responsibilities.

The issue isn't too complicated, though. It's just a question of which guides are still relevant, where should they be hosted and how do we get them formally published/maintained by the CG.

Assuming the IDPF repository gets abandoned in the process, redirects just need to be placed on the existing versions to the new CG versions.

**Comment by ghost** [comment]
Thanks for briefing.

Yeah, it's publ-cg and idpf guides. How can we clean this up in the CG (publishing-cg). Something like following might need to happen in my mind:

1. Who should redirecting idpf guide or repository 
2. Can we move publ-cg guides to publishing cg repo and who should we contact

We can have discussion later in our call and share update here if we have discussed.

**Comment by ghost** [comment]
Publishing CG had meeting today where we discussed about maintenance of document. As @jccr just linked to here the PCG task force https://github.com/w3c/publishingcg/issues/10 he is leading will be able to keep maintaining document.
