### ISSUE TITLE
(i18n) Using a "should" for a valid language tag?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1509]
The i18n check says:

> Specifications should require content and content authors to use "valid" language tags.

At this moment, we say that the language tags MUST be well-formed, but we do not say anything about validity. While I agree with this, I wonder whether we should not put a _SHOULD_ for the author using a valid language tag.

**Comment by mattgarrish** [comment]
I'm not a good judge of this, as it potentially adds a warning for publishers that wasn't there before.

epubcheck rollouts are generally slow, so it's conceivable (if maybe not highly likely) that content gets trapped between changes to the IANA registry and updates to epubcheck if this is a recommendation.

We might only want to make this advisory?

**Comment by dauwhe** [comment]
Related: #1325

**Comment by iherman** [comment]
Ah: looking at https://github.com/w3c/epub-specs/issues/1325#issuecomment-675419374 (thanks @dauwhe) the advice of the i18 people is:

> Specifications MAY require that language tags be valid.

which is a bit weaker than the formulation in the self-test. @mattgarrish your point on epubcheck is well taken; maybe an advisory note in the spec would be indeed more appropriate.

**Comment by dauwhe** [comment]
As an EPUB author, what I want from EPUBCheck is to be alerted if my language tag is bad. 

I'm wary of having MUST or SHOULD because that risks EPUBCheck rejecting previously-valid EPUBs. 

Can we spec this so that it results in an informative message from EPUBCheck? Something like "I do not recognize this language tag" ... easy to check against a list of the most common language tags, hard to definitively state a tag is bad.

**Comment by mattgarrish** [comment]
> Can we spec this so that it results in an informative message from EPUBCheck?

Typically that's where we fall over into strongly "advising" or "encouraging" authors to do something. A best practice that we can validate as a usage or info message.

Interestingly, respec has a [best practice class and summary](https://respec.org/docs/#best-practice-documents).

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-18-epub#section2) on 2021-02-18

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-18-epub#resolution2):  Close issue 1509 with no action***
- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-18-epub#resolution3):  close issue 1508, won't fix***

<details><summary><i>View the transcript</i></summary>

### 2. Remaining i18n issues 

_See github issue [#1508](https://github.com/w3c/epub-specs/issues/1508), [#1509](https://github.com/w3c/epub-specs/issues/1509)._




**Wendy Reid:** 2 i18n issues remain after the review  

**Dave Cramer:** the two issues are pretty intertwined  
… i18n should require valid lang tags  
… there is a formal grammar which describes the formal structure of language tags  
… so, well-formedness  

> *Leonard Rosenthol:* I believe that lang is ISO 3166

**Matt Garrish:** we enforce well formed, but nothing about validity  

**Dave Cramer:** a valid tag is one which matches the actual languages  
… so should we require lang tags to be valid?  
… and what should RS do when faced with invalid lang tag?  
… not want to make requirement more stringent  
… hard to check validity of lang tags  
… its a list of strings that changes over time  
… burden on epubcheck  
… also, there could be existing epub with well formed but invalid lang tags - a change could cause those epubs to fail epubcheck  
… should having a valid lang tag just be a best practice?  
… so epubcheck would just flag it as an informative warning  

> *Wendy Reid:* leonardr:

**Leonard Rosenthol:** [here's the info](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang  
… BCP-47 is the technical spec, you can validate against that if you want  
… but i think we should do what HTML does, no more, no ness  

**Matt Garrish:** some of this came up in epubcheck itself, when someone complained that there was no check for lang validity  
… also, the epubcheck folks seemed to say that it would be a hard thing to implement  
… and unless there is some critical function, a RS is going to ignore this  
… and there are currently no critical functions that rely on this very general metadata  
… nothing bad comes of this lang tag not being specified properly  
… in pub manifest we said that well-formedness is good enough  

**Wendy Reid:** also, we'd run into issues with testing this if we wanted to make this stricter  

**Dave Cramer:** matt has more or less convinced me that this isn't broken  

> *Brady Duga:* +1 to not broken

**Dave Cramer:** ... the costs of fixing it are higher than the purely theoretical benefits of conforming to broadly worded i18n guidelines

**Dave Cramer:** i propose that we close this without fixing  

**Matt Garrish:** something like WCAG could have stricter rules about lang tags, but for us its not a critical piece of metadata  

**Ben Schroeter:** i like the idea of doing some sort of warning in epubcheck  
… also, i don't want to tell RS what to do in general  
… RS want to be as lax as possible when it comes to what they will ingest  
… they don't want to keep content authors off their RS  

> **Proposed resolution: Close issue 1509 with no action** *(Wendy Reid)*

> *Marisa DeMeglio:* +1

> *Ben Schroeter:* +1

> *Matthew Chan:* +1

> *Wendy Reid:* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> *Shinya Takami (高見真也):* +1

> ***Resolution #2: Close issue 1509 with no action***

**Dave Cramer:** for 1508 (i.e. question of what RS should do with poorly-formed lang tag)  

**Dave Cramer:** there was a suggestion that the RS treat the lang as "und" (i.e. undefined)  
… that to me is a satisfactory solution to this somewhat theoretical problem  

> *Leonard Rosenthol:* +1

> **Proposed resolution: Close issue 1508, add text to RS specification instructing reading systems to treat a poorly-formed language tag as "und" (undefined)** *(Wendy Reid)*

**Brady Duga:** is this yet another untestable assertion?  
… should we tell RS what to do with this at all?  

**Matt Garrish:** i suggested the "und" thing because i thought we'd done this in pub manifest as well  
… but i think we actually went back and decided to remain silent on it  
… "we're not going to define what it means for the RS"  

**Dave Cramer:** testing it would require reading the minds of the RS  
… what we're actually using the lang tag for is trying to guess at page progression direction?  
… how would we know if the RS is actually doing this?  
… so maybe another "close, won't fix"?  

**Ben Schroeter:** if we feel the RS wants some sort of guidance we could change the proposal to say "suggest"  
… but i'm also happy to drop it  

**Matt Garrish:** i think there's something worrisome about RS determining lang for the author  
… i'd rather RS do nothing  

**Dave Cramer:** would also add that RS don't seem to be looking for guidance  

> **Proposed resolution: close issue 1508, won't fix** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Brady Duga:* +1

> *Wendy Reid:* +1

> *Matthew Chan:* +1

> *Matt Garrish:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #3: close issue 1508, won't fix***

</details>

**Comment by r12a** [comment]
> which is a bit weaker than the formulation in the self-test. @mattgarrish your point on epubcheck is well taken; maybe an advisory note in the spec would be indeed more appropriate.

@iherman we have different guidance for specifications (which MAY require validity) and for content authors (who SHOULD use valid subtags).  So there's no mismatch between the two pieces of advice you mention above.

In terms of use of valid subtags, i don't think a tag will become invalid over time - it may be deprecated, but remains valid.  So @mattgarrish does that ease your fears about slow epubcheck rollouts?  (Although, i'd have also expected a checker to pull the list of valid subtags from IANA on a regular or check by check basis.)

**Comment by mattgarrish** [comment]
> So @mattgarrish does that ease your fears about slow epubcheck rollouts?

No, the issue cuts both ways. New tags are just as problematic, as if content doesn't validate it gets rejected by vendors.

But what's changed between [this discussion](https://github.com/w3c/bp-i18n-specdev/issues/36) and now?

Valid dc:language tags are no more important for epub than they are for publication manifest, which was modeled on the epub package document. A reading system might use them for optimizations, but there aren't any critical uses of the value.

If we're going to introduce stricter validation after all these years, it would be helpful to justify why we require it. If publishers get their books rejected for sale because of this validation, we need an explanation why this is a good thing.

> i'd have also expected a checker to pull the list of valid subtags from IANA on a regular or check by check basis

I don't know how viable this is for epubcheck given its use in automated ingestion systems. It also presents a barrier for publishers getting it installed on internal systems. Vocabularies have always been internalized to avoid reading external content. @rdeltour would be able to speak better to how realistic such an approach would be, though.

**Comment by iherman** [comment]
@r12a, further to what @mattgarrish said:

>  (Although, i'd have also expected a checker to pull the list of valid subtags from IANA on a regular or check by check basis.)

we are under a very special set of constraints. epubcheck is a java program that an EPUB vendor may download and install as part of their systems and they use, e.g., when they include a new EPUB instance into their vendor's portfolio. There is no requirement at that point that epubcheck should be online; it is just a program ran as part of an internal workflow. On the other hand, many of these vendors would simply (and automatically) reject an EPUB instance if it does not pass epubcheck. (It is as if, God forbid, a browser accepted only a fully valid HTML page…). In other words, a vendor may update the epubcheck code when a new version is issued (let us hope:-) but, between two epubcheck releases, that piece of software may not even see the external world...

**Comment by mattgarrish** [comment]
> On the other hand, many of these vendors would simply (and automatically) reject an EPUB instance if it does not pass epubcheck.

Right, and this is a big problem we need to avoid except in critical cases. That's why our charter says:

> Any existing valid EPUB 3.2 should remain valid under EPUB 3.X, unless it relies on features discovered to have serious issues (such as a security bug).

Why I'm wary of this is that we've tried to incorporate dynamic vocabularies in the past and it hasn't worked out well. We used to require strict validation of the terms in the structure vocabulary, for example, but when we periodically added new terms no one could use them as it often takes months or more before vendors will deal with integrating a new version of epubcheck. The same happened with our list of reserved prefixes, some of which still aren't accepted by major vendors, I believe.

**Comment by dauwhe** [comment]
This is one of those times I wish we had data. What percentage of existing EPUBs have well-formed but invalid language tags? I would expect that the number is quite small. What fraction of those EPUBs would provide a better user experience if the language tag was valid? Is there an EPUB in the wild with a well-formed but invalid language tag, no page-progression-direction attribute, that is currently rendered with the wrong PPD but would render correctly if the language tag was fixed? I find this hard to imagine. 

The costs here are [1] potentially rendering existing content invalid and [2] requiring expensive development and ongoing maintenance for EPUBCheck. The benefits here are likely to be minimal.

**Comment by rdeltour** [comment]
I second what has been said on EPUBCheck: the main issue is in its usage, which is often offline and not always regularly updated.
But if the IANA registry isn’t updated too frequently, it would be reasonable to keep EPUBCheck in sync. Does anyone know if the registry is rather stable or regularly updated?

Reporting it as an informative message in EPUBCheck (as proposed in previous calls) sounds like the safest approach to me.

**Comment by dauwhe** [comment]
The working group resolved again to close this issue with no change. We are OK with requiring language tags to be well-formed only.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-29-epub#section3) on 2021-04-29

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-29-epub#resolution1):  Close issue 1509***

<details><summary><i>View the transcript</i></summary>

### 3. SHOULD for "valid language tags" 

_See github issue [#1509](https://github.com/w3c/epub-specs/issues/1509)._




**Dave Cramer:** during i18n review, we saw that some specs use SHOULD for validity of language tags  
… we don't say anything about validity  
… and we had a previous resolution to close issue without forcing validity  
… part of consideration was not increasing complexity for epubcheck  
… I also feel this will affect a diminishing number of epubs that have well formed yet invalid lang tags  
… given that RS don't tend to do much that lang tag info anyway  

**Ben Schroeter:** can we clarify difference?  

**Dave Cramer:** it follows the normal pattern e.g. `en-US`  
… `qq-ZQ` would also be well formed, if most likely invalid  

**Shinya Takami (高見真也):** if RS cannot recognize the tag, its still okay in many cases  
… so i think validation is not mandatory  

> **Proposed resolution: Close issue 1509** *(Wendy Reid)*

> *Dave Cramer:* +1

> *Dan Lazin:* +1

> *Shinya Takami (高見真也):* +1

> *Wendy Reid:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Ben Schroeter:* +1

> *Brady Duga:* +1

> ***Resolution #1: Close issue 1509***

</details>
