### ISSUE TITLE
Restrictions on container-constraints scripts: can we use iframe attributes instead?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1523]
The current spec says, in [§3.4.2](https://w3c.github.io/epub-specs/epub33/core/#sec-scripted-container-constrained):

> A container-constrained script _MUST NOT_ contain instructions for modifying the DOM of the parent Content Document or other contents in the EPUB Publication. It also _MUST NOT_ contain instructions for manipulating the size of its containing rectangle.

The problem with these statements is that I do not see how this can be tested. I presume epubcheck would be unable to do that, it would require to understand the behavior of the script.

I am out of my comfort zone here, but I was wondering whether a radical change in handling this makes sense. Looking at the [iframe `sandbox` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) isn't it possible to replace these restrictions (or make it more precise) by applying constraints on the attributes the `<iframe>` element should or should not use? _That_ can be tested by epubcheck, and it would probably mean a much cleaner declarative approach anyway...

Cc @danielweck @rdeltour @bduga @HadrienGardeur 

---

Admin: this was originally raised as a comment in https://github.com/w3c/epub-specs/pull/1519 but, on @mattgarrish advise, it is raised as a separate issue.

ping  @dauwhe @wareid

**Comment by mattgarrish** [comment]
May be a case that sandboxing wasn't well supported when we added the restrictions.

So long as "allow-same-origin" isn't also enabled (which is itself a validation warning), the end result should be the same. There are browsers it won't work on, but it's certainly more testable.

This looks like it was part of the discussion that led to the text: https://github.com/w3c/epub-specs/issues/91

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-15-epub#section4) on 2021-04-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 4. Restrictions on container-constraints scripts 

_See github issue [#1523](https://github.com/w3c/epub-specs/issues/1523)._




**Dave Cramer:** this refers to scripts that run inside iframes  
… we say that such scripts should not modify parent in DOM or other documents in publication, must not modify the size of its containing rectangle  
… the idea is that container-constrained scripts should stay in their containers  
… Ivan was wondering whether using attributes to do this would accomplish the same thing, and be checkable by epubcheck  
… i looked into the sandbox attribute, but nothing seemed like a perfect match for what we want to achieve  

**Brady Duga:** i don't think sandbox is appropriate here, its for security and we're concerned with layout  
… the fact that the script cannot touch things outside of yourself, is by definition  
… if you do touch outside things, no longer are you "container-constrained"  
… so maybe rewrite this language as defining what it is  
… "a container-constrained script is... doesn't affect things outside itself, etc."  
… and anything not contained is considered spine level  

**Dave Cramer:** but then who's responsibility is it to enforce that? The RS?  

**Brady Duga:** this is being done for publishers because we want to enable some scripting without breaking the content  
… if they chose to ignore this and the content breaks, then they'll just learn to stop  

**Dave Cramer:** Ivan was also concerned about this from a testing perspective  
… can't reasonably write a validator to check every javascript for whether or not it goes outside its container  
… but what we are leaning towards almost seems to move that section into the definitions  
… maybe we can take this back to Ivan and Matt?  

**Brady Duga:** you could almost just turn that paragraph into a bullet point  

**Dave Cramer:** or just say "container-constrained script does NOT... etc."  

**Wendy Reid:** okay, so maybe no proposal for now, and we can just comment on the github ticket  

**Marisa DeMeglio:** what do people use container-constrained scripts for?  
… widgets?  

**Brady Duga:** yeah, some little interactive thing. 3D model, for example  

</details>

**Comment by iherman** [comment]
My original proposal with iframe attributes do not carry here, so closing.
