### ISSUE TITLE
EPUB3 overview: duplicated paragraph

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1524]
https://www.w3.org/TR/2021/NOTE-epub-overview-33-20210112/
End of section 1.2.2:

The structure and semantics of Navigation Documents are specified in the relevant section of [EPUB-33].

The structure and semantics of Navigation Documents are defined in specified in the dedicated section of [EPUB-33].

**Comment by iherman** [comment]
Thank you, @emuller-amazon. I have taken care of it in the [editor's draft](https://w3c.github.io/epub-specs/epub33/overview/#sec-nav-nav-doc); the document will be republished at some point in the following weeks, when this change will become final on the published version.

Thanks again.
