### ISSUE TITLE
Recommend to embed fonts

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1525]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-resource-locations

The note after example 2 says:

> Authors are encouraged to locate audio, video, and script resources inside the EPUB Container whenever feasible to allow users access to the entire presentation regardless of connectivity status.

I think the same applies to fonts. I would also suggest to:

- move the note before the examples, just after the list of exceptions
- make it ordinary text

**Comment by iherman** [comment]
> https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-resource-locations
> 
> The note after example 2 says:
> 
> > Authors are encouraged to locate audio, video, and script resources inside the EPUB Container whenever feasible to allow users access to the entire presentation regardless of connectivity status.
> 
> I think the same applies to fonts. 

It makes sense. However, see below.

> I would also suggest to:
> 
> * move the note before the examples, just after the list of exceptions
> * make it ordinary text

That makes indeed sense, too. However, if the first note is placed right after the bullet items, then it may become unnecessary to list the items again, and it is enough to say something like

“Authors are encouraged to locate these resources inside the EPUB Container whenever feasible to allow users access to the entire presentation regardless of connectivity status.”

**Comment by mattgarrish** [comment]
I think this is fine.

This used to be a formal recommendation to include the listed resources, so I believe fonts were omitted because they aren't essential to the presentation in the same way the other three are (i.e., the content is still available but just defaults to the next available font). When we switched to guidance, I don't think we reconsidered the list.

**Comment by dauwhe** [comment]
I'm a little wary of extending this to fonts. Licensing for web fonts is likely going to be very different than licensing for embedded fonts. There are good reasons to embed fonts, and good reasons not to. I don't think we need to be in the business of providing guidance for this in the specification.

**Comment by mattgarrish** [comment]
> There are good reasons to embed fonts, and good reasons not to.

True. It's only guidance about how to ensure the full presentation is available, though, so maybe the note could become a statement that whether this is feasible for fonts will depend on their licensing?
