### ISSUE TITLE
EPUB3.3: swap sections 2.3.2.1 (package element) and 2.3.2.2 (shared attributes)

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1526]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-shared-attrs

i.e. make Shared attributes the first section, then package element, then metadata, etc.

**Comment by mattgarrish** [comment]
Sounds fine to me. Some of the shared attributes are available on the package document, so makes sense to encounter them first.
