### ISSUE TITLE
<link> precedence

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1530]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-link-elem

Example 22 introduces the notion of precedence among <link> elements. "The following example shows a remote record that has higher precedence than a local record, ..."

First, if there is a precedence, then it should be introduced in the text, not in an example.

Second, two <link> elements many be entirely unrelated (e.g. rel="record" and rel="voicing"), so there is no precedence between them. Which begs the question: what make one link take precedence over another? same @rel value?

**Comment by mattgarrish** [comment]
This looks like a quirk of pulling the reading system requirements into a separate document. The context of this [applying to rel=record](https://w3c.github.io/epub-specs/epub33/rs/#conf-metadata-link) is in the other document. We do need a non-normative explainer in the authoring spec, although linked records haven't exactly panned out in the real world.

**Comment by mattgarrish** [comment]
This should have been closed with #1555 if I hadn't messed up the linkage....
