### ISSUE TITLE
Ambiguous "it"

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1532]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-item-elem

Example 26: "The following example shows a link to a local version of the audio file. Because audio files are not EPUB Content Documents, it requires a fallback to an EPUB Content Document (it also has to be listed in the spine)."

The first "it" clearly refers to the `<item>` of the example. But was does the final "it", in the parenthetical, refer to? Same as the first, i.e. the `<item id='audio01'>`, or the `<item id='audio01-xhtml'>` ?

**Comment by mattgarrish** [comment]
"It" refers to the audio file as you can't link to a local resource that isn't listed in the spine. Agree it's convoluted.

Might be clearer to rewrite it as:

"For this link to be valid, the audio file has to be listed in the spine and requires a fallback to an EPUB Content Document in its manifest declaration."

Plus also add an example of the spine entry for completeness.
