### ISSUE TITLE
itemref properties: sentence is unclear

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1533]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-itemref-elem

The last paragraph just before the example is:

>All applicable descriptive metadata properties defined in the Spine Properties Vocabulary SHOULD be declared.

What does that mean?

**Comment by mattgarrish** [comment]
Looks like it's missing something like "for each `itemref` element in its `properties` attribute" on the end (but could use a better rewrite than that).

I wonder what value this recommendation even provides, though?

Given the only properties are `page-spread-right` and `page-spread-left`, their presence is untestable. Only the author would ever know if they should have been set.

It also contradicts (and doesn't mention) the fixed layout equivalents for which there is no recommendation to set.

I'd suggest we just drop the sentence.
