### ISSUE TITLE
Nit: section D.6.1.1 "non-normative"?

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1534]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#itemref-properties-vocab-about

> _This section is non-normative._

If that statement refers do section D.6.1.1., is it really necessary? If it refers to an enclosing section, is it true?

**Comment by mattgarrish** [comment]
> is it really necessary?

Unfortunately, as far as I'm aware. Informative sections have to be marked as informative, even if the label is almost longer than the text in some of these vocabularies.

What we could do instead is drop the Overview parent section and merge the two subsections under the "About this Vocabulary" heading.  That way we could drop the informative label, as the referencing prose would justify it being normative.

It would probably also make the structure simpler if we drop the "XX Properties" sections that wrap the terms. With the exception of the link vocabulary, which actually defines two different sets of properties, these sections are redundant with the vocabulary heading.

All this extra structure made more sense when these were vocabularies were defined in standalone documents.

**Comment by iherman** [comment]
> What we could do instead is drop the Overview parent section and merge the two subsections under the "About this Vocabulary" heading. That way we could drop the informative label, as the referencing prose would justify it being normative.

+1 to that, but I could even consider going a bit further: is there a real sense of having these “About this vocabulary” sections in the first place? All the text in the Overview section could simply be an introductory section in the 'main' section (D.6 in this case) and then get to the real “meat“. Ie:

> D.6 Spine Properties Vocabulary
>
> The properties in this vocabulary are usable... they are referenceable using the base IRI https://...
>
> The following tables define properties for use in the itemref element...
>
> D.6.1. page-spread-left
>
> ...
>
> D.6.2 page-spread-right
> ...

I guess the same structure could be used for all the vocabularies

WDYT?
