### ISSUE TITLE
Something is missing in "EPUB Navigation Document"

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1536]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-nav

The pieces we have:

> The EPUB Navigation Document is an XHTML Content Document

> restrictions on <nav> elements with epub:type

What I don't see is any description of the content of the `<body>`. Can it have something else than one or more `<nav epub:type='...'>`? Must it have at least one? Must it have a `<nav epub:type='toc'>`? exactly one? at most one? Can the `<nav epub:type='...'>` be inside other elements?

**Comment by emuller-amazon** [comment]
In fairness, some of the restrictions are listed along the way "toc nav MUST occur exactly once", etc. But not all the questions are answered, and it would be nice to have a Content Model "blue box" for the <body> element.

**Comment by dauwhe** [comment]
Good point. Something like this to replace the first two paras? 

> Every EPUB Publication must have an EPUB Navigation Document, which serves as the primary human- and machine-readable global navigation layer, thereby ensuring increased usability and accessibility for the user.

> The EPUB Navigation Document is an XHTML Content Document, which must include one `nav` element with `epub:type='toc'`. It may contain one each of other specialized `nav` elements, such as `page-list` or `landmarks`. These special `nav` elements have additional restrictions on their content beyond those defined in [[HTML]], in order to facilitate the machine-processing of its contents. There are no other restrictions on the structure or content of the EPUB Navigation Document.

**Comment by iherman** [comment]
@dauwhe  like to text; I would use them  to replace the first three paragraphs of the current [§4.1](https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-nav-intro)? Is that your intention as well?
