### ISSUE TITLE
Non characters in file names

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1538]
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-container-filenames

If you exclude "Non characters in Arabic Presentation Forms-A (U+FD00 ... U+FDEF)", then you ought exclude all non characters. <http://www.unicode.org/faq/private_use.html#nonchar4>

**Comment by dauwhe** [comment]
U+FFFE and U+FFFF are already forbidden, as are U+FFFFE, U+FFFFF, U+10FFFE, and U+10FFFF. 

So I guess that leaves 28 more non-characters to forbid? 

Don't make me create tests for all of this!

**Comment by iherman** [comment]
@llemeurfr you probably looked into this when you edited the LPF document... any help on this?

**Comment by llemeurfr** [comment]
LPF relies on zip, and zip is not precise at all on this subject. This is why we ended up with this note: 

The zip specification has few constraints on the characters allowed for file and directory names. When crafting such names, authors must be careful to use characters which allow a broad interoperability among operating systems

**Comment by iherman** [comment]
At the end of the day, EPUB also relies on Zip, doesn't it? So we may have to do the same and that is that...
