### ISSUE TITLE
[EPUB Accessibility Guidelines] Distribution section – question on second bullet point

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1574]
The second bullet point says:

> they must include accessibility metadata in the record format required for distribution of an EPUB Publication when such metadata is supported by the format.

Does it means metadata in ONIX or MARC? Maybe we can list those formats as examples.

**Comment by mattgarrish** [comment]
> Does it means metadata in ONIX or MARC? 

Yes, but we had to write ONIX out of the bullet as part of the ISO process. I believe it was because of the open-ended nature of the possibilities.

> Maybe we can list those formats as examples.

I'm personally fine with that so long as we don't have to keep flip-flopping in the future.

**Comment by avneeshsingh** [comment]
it is ok to mention ONIX, MARC etc. as examples
