### ISSUE TITLE
Author definition question

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1575]
The various specifications often refer to the concept of "Author", the definition of which can be found at the link https://www.w3.org/TR/epub/#dfn-author

- Perhaps it might make sense to make it explicit that a publisher is an author (as understood in the spec)?
- Maybe adding "For example, the publisher" to the end of the definition.

**Comment by mattgarrish** [comment]
There's been a long-running desire to find an alternative for "author" given its obvious confusion with the person who wrote the content.

I wonder if it would make sense to finally resolve on another term, like "EPUB Creator", to additionally get us out of this rabbit hole once and for all?

**Comment by mattgarrish** [comment]
Closing with #1577
