### ISSUE TITLE
Question about the layout example.(Undefined Attributes?)

### ISSUE THREAD

**Issue by RealXuChe** [w3c/epub-specs#1596]
In the XHTML part of [this](https://www.w3.org/publishing/epub3/epub-packages.html#fxl-ex1) example, I found the line `<meta name="viewport" content="width=1200, height=900"/>` doesn't seem to meet the specification.

As defined in the [spec](https://www.w3.org/publishing/epub3/epub-packages.html#sec-meta-elem), the `meta` element doesn't have attribute `name` and `content`. 

I've searched for the attributes but found no clue. Does anyone know where this is defined?

**Comment by mattgarrish** [comment]
> I've searched for the attributes but found no clue. Does anyone know where this is defined?

The viewport is defined in the xhtml document, so it's using the [`meta` tag](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element) defined in the html specification.

There used to be a way to define the [viewport in the package metadata](https://www.w3.org/TR/epub-33/#viewport), but it was deprecated a few revisions back.

**Comment by mattgarrish** [comment]
Closing this issue as there's nothing to fix.
