### ISSUE TITLE
Contradiction between "must" and "advisory"?

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1601]
https://w3c.github.io/epub-specs/epub33/rs/#sec-opf-dclanguage says `The language(s) of the EPUB Publication specified in language elements are advisory. Reading Systems MUST use the language information associated with a resource to determine its language.`

This seems contradictory. In normal use, "advisory" means non-binding, whereas MUST is binding.

**Comment by dauwhe** [comment]
My understanding is that "advisory" applies to the `dc:language` element in the package file. The "resource" here refers to (for example) HTML files. The reading system MUST obey the language in `<html lang="en-CA">`.

**Comment by dlazin** [comment]
Ah! That makes sense upon explanation, but is unclear to a non-expert. Can we rephrase?

**Comment by dauwhe** [comment]
> Ah! That makes sense upon explanation, but is unclear to a non-expert. Can we rephrase?

Yes we can!

**Comment by dlazin** [comment]
Related (and a little clearer): `The language identified in an hreflang attribute is not authoritative. Language information defined in a linked resource determines its language.`
https://w3c.github.io/epub-specs/epub33/rs/#conf-metadata-link

**Comment by iherman** [comment]
> The reading system MUST obey the language in `<html lang="en-CA">`.

I guess this is also true for the `xml:lang` attribute in the package file, isn't it?

**Comment by mattgarrish** [comment]
> I guess this is also true for the `xml:lang` attribute in the package file

Yes, I believe the original prose cited was lifted from the `hreflang` definition in the HTML spec when we were looking at this during the i18n review.

It might be clearer to have a section on language and publication resources so that we're not having to say the same thing in every case.

**Comment by iherman** [comment]
> > I guess this is also true for the `xml:lang` attribute in the package file
> 
> Yes, I believe the original prose cited was lifted from the `hreflang` definition in the HTML spec when we were looking at this during the i18n review.
> 
> It might be clearer to have a section on language and publication resources so that we're not having to say the same thing in every case.

Yes. Furthermore, looking at the original problem of the issue (which is in a section on metadata only, ie on dc: language, the second sentence should simply removed. It is irrelevant in the given context.
