### ISSUE TITLE
"CSS Style Sheets" is redundant :)

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1603]
https://w3c.github.io/epub-specs/epub33/rs/#sec-css is "CSS Style Sheets." Of course, CSS stands for Cascading Style Sheets, so that's Cascading Style Sheets Style Sheets :)

Can we do either "CSS" or "Cascading Style Sheets" or similar?

**Comment by dauwhe** [comment]
Yes, I would propose that the section title be "Cascading Style Sheets (CSS)" and then use CSS alone in text.

**Comment by mattgarrish** [comment]
> and then use CSS alone in text

Doesn't this somewhat contradict the [CSS spec itself](https://www.w3.org/TR/CSS22/syndata.html#charset)?

**Comment by dlazin** [comment]
Touché!

However (arguably):
1) EPUB is a writer's world and CSS is not; we can do better.

2) I think they are (maybe?) making a distinction between CSS the standard and CSS documents; they are calling CSS documents "CSS style sheets". Since we are not *specifically* referring to the style sheet documents (ours can be read either way), I don't think we need the distinction/repetition.

**Comment by dauwhe** [comment]
I think that the CSSWG is using that phrase in a very specific sense. A "CSS style sheet" is a sequence of CSS rules conceived of as a unit. Perhaps we can rewrite this to avoid the problem. We're asking reading systems to support CSS, which extends far beyond just parsing CSS style sheets.

**Comment by mattgarrish** [comment]
> A "CSS style sheet" is a sequence of CSS rules conceived of as a unit.

Right, doesn't this equate with any parsing requirements on the RS? That's what has me a little concerned with a blanket change to "CSS". I'd have to look at the section again, though. Maybe "style sheets" only come in on the authoring side.

It's not a title change itself that bothers me, as I don't care either way about that. I'm just not comfortable with the idea of talking about CSSes or having to expand the term every time when "css style sheet" is a common term.

It can't be any worse than SVG graphics, after all... ;)

**Comment by dauwhe** [comment]
> It can't be any worse than SVG graphics, after all... ;)

Excellent point.

**Comment by iherman** [comment]
I have the impression that many users of SVG or CSS do not really know what those acronyms stand for. It is an abuse of the language, true, but I believe these terms have become words in their own right... which is part of the evolution of a language.

I would not touch it. 

Caveat: I am not a native English speaker...

---

(A funny example of this situation is the word "PIN". In Dutch, for example, this English acronym has become a… verb, with a conjugation following the formal Dutch grammar, meaning to take money out of the wall.)

**Comment by dlazin** [comment]
Rough consensus here seems to be that the current language is OK. Should we close this issue, or bring it to a meeting? I still think it's unnecessarily redundant — either CSS or Cascading Style Sheets or Cascading Style Sheets (CSS) would work with no problem — but this is also not a critically important issue.

**Comment by iherman** [comment]
I would propose to close it (note that the latest version of the RS already incorporated the [proposal](https://github.com/w3c/epub-specs/issues/1603#issuecomment-812684573) of @dauwhe).

**Comment by dlazin** [comment]
Almost! Great to see that change. However, the core spec still uses the old name: https://w3c.github.io/epub-specs/epub33/core/#sec-css

Can we change it to match?

**Comment by iherman** [comment]
See #1621
