### ISSUE TITLE
Letting users override CSS "as desired" is unclear

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1605]
https://w3c.github.io/epub-specs/epub33/rs/#confreq-css-user-styles says `It SHOULD allow users to override the EPUB Creator's style sheets as desired.`

First, `SHOULD` seems too aggressive here. If an RS doesn't want to, isn't that an OK decision? I recommend dropping to `MAY`.

Secondly, "as desired" suggests letting users upload their own stylesheets, or at least suggests nothing in particular. I think we mean "should let users change font size, dark mode, and maybe a couple other things like line-spacing or paragraph justification."

At most, that handful of options should (maybe) be `SHOULD`, and most other properties `SHOULD NOT` be user-overrideable; it's way too hard for a publisher to ensure their book won't break if users can override arbitrary (or just different) properties in different RSes.

Can we consider dropping to `MAY`, and rephrase "as desired" to be more specific, possibly adding a list of `SHOULD NOT`s?

**Comment by Doktorchen** [comment]
If a user changes much more than font-size, this user takes the control over the complete style sheet results.

It would have been a good idea to require by CSS already
a) authors to switch off user-agent stylesheets
b) users to switch off user-agent stylesheets and author stylesheets

Currrently for EPUB it is in practice more a problem, that several user-agents do not respect the priorities of author-stylesheets resulting in nonsens-displays, if everything is mixed up.
And different from users authors have no control, which user-agent is used, therefore no chance to care about such problems.

**Comment by iherman** [comment]
What about something like:

> It _MAY_ override the EPUB Creator's style sheet as a result of user interaction.

This means that the possibility of simply "upload" a style sheet is not present, and that the control is in the interactive possibilities offered by the RS. Ie, at the end of the day, it is the RS's responsibility to decide which part of the Creator's CSS is really overwritten.

**Comment by dlazin** [comment]
That looks good to me, or maybe better "It MAY override parts of the EPUB Creator's style sheet as a result of user interaction." That makes clear that we're not talking about discarding the *whole* style sheet.
