### ISSUE TITLE
Support for fixed layouts

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1606]
I'm concerned this issue got buried in the text for last PR for the reading system specification, so I'm going to ask it more directly: is support for fixed layouts optional, recommended or required?

In whittling down the conformance requirements that were just pointers to sections, there was nothing that required or even recommended support for fixed layout rendering.

The only statement we had is that reading systems must [process the metadata as defined in the fxl metadata section](https://www.w3.org/publishing/epub3/epub-packages.html#confreq-rs-epub3-fxl-meta).

But what does it mean to process the metadata but not have to support the rest of fixed layout rendering? If you parse the metadata and ignore it are you compliant?

Now that the sections are merged, the path to support is less convoluted, but is it optional as the previous spec seemed to suggest through a lack of a rendering requirement or is support required as the metadata statement sort of hinted at?

**Comment by OriKuttner** [comment]
I think it should be optional as FXL is much more complicated and most
publications are reflowable.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by mattgarrish** [comment]
I honestly don't remember anymore what the intention was when we integrated. I was surprised to find support wasn't at least recommended, though.

At the very least, it has to be viewport-dependent if it is a requirement since it's a visual rendering feature.

**Comment by mattgarrish** [comment]
Doing some sleuthing back to 3.0.1, it looks like the intention was to require support. We originally had this bullet following the requirement to process metadata:

> For fixed layouts expressed using the rendition:layout property, it must determine the rendering dimensions as defined in Fixed-Layout Documents [ContentDocs301] .

That bullet appears to have moved to the content documents section and lost its direct tie to the metadata over the various rewrites of how the ICB is determined.

But it's hard to argue that if you have to process the metadata and you have to get the dimensions then you don't have to render the content.

**Comment by mattgarrish** [comment]
I'm going to set the requirement back to required (when there is a viewport) in the interests of erring on the side of required support, but we should clear this up formally.

**Comment by iherman** [comment]
> But it's hard to argue that if you have to process the metadata and you have to get the dimensions then you don't have to render the content.

Indeed. 

Let us follow the cow path here: if we take the latest generation of RSs: do they implement FXL? Do we create problems if we clearly state that FXL implementation is required?

(Kindle is an odd man out. I presume (do not know) that it does not implement it, but it is not sure whether Kindle should be considered as a bona fide EPUB reader anyway.)

**Comment by mattgarrish** [comment]
Basic fxl has been well supported, although the only [reference I can cite](https://web.archive.org/web/20161021184112/http://epubtest.org/testsuite/epub3/feature/fixed-layout-support/) is a bit old now.

Where fxl support becomes a bit wonky is when you get into interactions between the various other properties.

I think I've found an authoritative answer to this question in https://github.com/w3c/epub-specs/issues/391

@GarthConboy's last para in his comment there is:

> As discussed on the EPUB 3.0.1 call today (and the consensus of those on the call) is that FXL support should not be a "should" -- so, the above second  bullet should be modified to make only "rendition:flow" a should, but leave support for Fixed Layout metadata in the preceding "must" category.

That's probably where my memories of it being recommended come from, but it makes sense that if we actually want publishers to be able to use fixed layouts it's kind of essential that all reading systems be expected to support them.

**Comment by GarthConboy** [comment]
I agree with that "Garth" guy.  :-)

FXL support should be required.   Certainly on these Reading Systems that are rendering visually via some sort of view-port.  

And, in answer to @iherman 's above, I'm pretty sure Kindle supports FXL EPUB, through it's normal round-around fashion.  I'd love @dauwhe to confirm that for sure.

**Comment by iherman** [comment]
> And, in answer to @iherman 's above, I'm pretty sure Kindle supports FXL EPUB, through it's normal round-around fashion. I'd love @dauwhe to confirm that for sure.

I would then be in favor of making FXL a requirement for reading systems.

**Comment by OriKuttner** [comment]
If this is a requirement, I guess that many reading systems will be
declared non-conformant.

**Comment by iherman** [comment]
> If this is a requirement, I guess that many reading systems will be declared non-conformant.

Yes, that is true and there is a trade-off to be discussed.

Is this a unique case of FXL? Aren't there many widespread features in the current spec (or maybe even 3.2) that are not implemented in all RSs? Do all of them implement, for example, CSS in its full glory, or correct SVG, or...?

**Comment by mattgarrish** [comment]
> Aren't there many widespread features in the current spec (or maybe even 3.2) that are not implemented in all RSs?

Yes, when we abandoned epubtest.org (which itself wasn't a full set of tests) I don't believe there were any reliable claims of 100% conformance.

There may be specific fxl properties that are poorly implemented and will need review as we get testing feedback, but I'm satisfied with this overall being a requirement.

I'm going to close the issue as my concern has been addressed. If anyone wants to take up a new issue for themselves please feel free to do so.
