### ISSUE TITLE
FXL and the HTML details element

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/epub-specs#1607]
I know some people have wanted to do tables as fixed layout or as images. If this is done, one approach would be to use the HTML details element and its summary to provide the table in proper XHTML. This could be positioned immediately below the item. I expect that other structures  could use this approach for accessibility. This is one of the recommended techniques for extended descriptions. We have this demonstrated in our epubtest test books found at:

http://www.epubtest.org/test-books

I don't know how effective this approach would be for a title that was primarily FXL.

**Comment by dauwhe** [comment]
I think the details element is incompatible with fixed layout. By its very nature it demands that the layout changes when the element is expanded (often a problem even in reflowable books). What happens to a details element at the bottom of an FXL page? For FXL, would you need some sort of script that created a popup above the FXL content?

**Comment by dauwhe** [comment]
Since this is unlikely to work in FXL, and isn't something the spec is able to control, I'm going to close the issue.
