### ISSUE TITLE
OPTIONAL should not be capitalized in epubReadingSystem.hasFeature()

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1611]
https://w3c.github.io/epub-specs/epub33/rs/#app-ers-hasFeature-desc says `The OPTIONAL `version` parameter is included for querying custom features that could change in incompatible ways over time. The return value indicates support only for the specified version of the feature.`

But this is referring to optionality from the caller's perspective, not the implementer's perspective. I believe that all-caps OPTIONAL should be reserved for features that a Reading System may or may not implement; in this case, I believe the Reading System MUST implement the `version` parameter, and an EPUB author may or may not use the parameter.

Therefore (assuming my understanding is correct), I think OPTIONAL should not be capitalized in this case.

**Comment by dlazin** [comment]
Similarly, I suggest lowercasing "should not" in the following sentence: `EPUB Creators SHOULD NOT include the version parameter when querying features defined in this specification — these features are considered versionless. If a Reading System supports a feature defined in this specification, it MUST ignore any supplied version parameter and return a true value.` (This use of MUST, however, does apply to RS implementation, and should remain all-caps.)

Here, SHOULD NOT is not describing behavior of an RS or an individual EPUB, but rather a creator, which I believe is outside the scope of the spec. (For a counterexample, see `EPUB Creators and Reading System developers must be aware of the security issues that arise when scripted content is executed by a Reading System.`, which does not capitalize "must.")

**Comment by iherman** [comment]
I agree, @dlazin, see PR #1615
