### ISSUE TITLE
Some apparent normative statements do not have all-caps control words

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1612]
This is a megabug for apparent normative statements in the 3.3 spec that do not have all-caps control words like MUST. These look to me like they are *supposed* to be normative statements and thus should gain such a word. Conversely, anything here that is truly not supposed to be a normative statement should probably be rephrased to make clear that it's non-normative.

1. `The language identified in an hreflang attribute is not authoritative. Language information defined in a linked resource determines its language.` (also discussed in https://github.com/w3c/epub-specs/issues/1601). This seems like two normative statements — hreflang SHOULD NOT be used? and resource language MUST be used? https://w3c.github.io/epub-specs/epub33/rs/#conf-metadata-link
2. `Reading System [note: should be plural] do not have to use or present linked resources, even if they recognize the relationship defined in the rel attribute.` Same section as above.
3. `When the default value of the page-progression-direction attribute is specified, the Reading System can choose the rendering direction. The default value MUST be assumed when the attribute is not specified.` I think the second statement only makes sense if the first is also MUST. (Otherwise we're requiring RSes to use `default`, but not requiring that `default` do anything.) https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-spine
4. `In addition to the requirements in § 9. Processing Structural Semantics, a Reading System has to process the epub:type attribute as follows in XHTML Content Documents: It MUST ignore semantics expressed on the [HTML] head element or its descendants.` Should "has to" become MUST? If so, there are ~10 instances of "has to" in the spec that should change in sync ... but that suggests this wording may be intentional. https://w3c.github.io/epub-specs/epub33/rs/#sec-xhtml-structural-semantics
5. `The default global value is reflowable if no meta element carrying this property occurs in the metadata section [EPUB-33].` This feels as if it should be rephrased to address the RS: "If no meta element... the RS MUST apply a global default..." If so, there are ~4 intances of "default global value" in the spec that should change in sync. https://w3c.github.io/epub-specs/epub33/rs/#layout
6. `The rendition:page-spread-* properties take precedence over whatever value of the page-break-before property [CSSSnapshot] has been set for an XHTML Content Document.` Seems like it could have a MUST. https://w3c.github.io/epub-specs/epub33/rs/#page-spread
7. `For the rendition:flow-scrolled-continuous property, the scroll direction is defined relative to the block flow direction of the root element of the XHTML Content Document referenced by the itemref element [EPUB-33]. The scroll direction is vertical if the block flow direction is downward (top-to-bottom). It is horizontal if the block flow direction of the root element is rightward (left-to-right) or leftward (right-to-left).` This seems like maybe 2 or 3 normative statements. https://w3c.github.io/epub-specs/epub33/rs/#flow

**Comment by iherman** [comment]
See PR #1616
