### ISSUE TITLE
Question: how to mark up multi-lingual metadata?

### ISSUE THREAD

**Issue by jenstroeger** [w3c/epub-specs#1626]
Suppose the publication’s language is, say, Spanish such that the OPF would roughly look like:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" xml:lang="es" prefix="schema: http://schema.org/ a11y: http://www.idpf.org/epub/vocab/package/a11y/#">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    ...
    <dc:language>es</dc:language>  <!-- Primary language. -->
    ...
    <!-- Note the accessibility summary in English! -->
    <meta property="schema:accessibilitySummary">This publication is awesomely accessible with all the bells and whistles. And a dash extra!</meta>
    ...
  </metadata>
   ..
</package>
```
Now, for example the `meta` element contains the accessibility summary in English — would I need to add an `xml:lang="en"` attribute? The [spec](https://www.w3.org/TR/epub-33/#sec-meta-elem) allows that attribute but I didn’t see further mention of it.
```xml
    <meta property="schema:accessibilitySummary" xml:lang="en">This publication is awesomely accessible with all the bells and whistles. And a dash extra!</meta>
```
Would the same hold for other metadata elements, like [`dc:title`](https://www.w3.org/TR/epub-33/#sec-opf-dctitle)?

**Comment by mattgarrish** [comment]
> would I need to add an `xml:lang="en"` attribute?

Yes, language is inherited from the nearest `xml:lang` attribute, which allows you to override the global language `es` you've specified on the root package element.

The [processing of the `xml:lang` attribute](https://www.w3.org/TR/xml/#sec-lang-tag) comes from the XML specification so we don't redefine it in EPUB, only allow its use.

**Comment by iherman** [comment]
@jenstroeger was this question answered for you? Can we close this issue?
