### ISSUE TITLE
Encoding of the path names

### ISSUE THREAD

**Issue by xfq** [w3c/epub-specs#1630]
https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames

There are restrictions on length of the file name and path name, as well as the encoding of the file name, but the encoding of the path name is not specified.

**Comment by mattgarrish** [comment]
This looks like an oversight, as it doesn't make a lot of sense to only define an encoding for the file name.

The bullet should probably be:

> Path and File Names MUST be UTF-8 [[!Unicode]] encoded.
