### ISSUE TITLE
Circumflex character escaping

### ISSUE THREAD

**Issue by bvandorn** [w3c/epub-specs#1640]
The terminal symbols for escaped special characters includes `( circumflex , equal )` https://github.com/w3c/epub-specs/blob/fa5e0f8ea58e0de87f356c89b73a2990a596fb8c/archive/epubcfi/index.html#L423-L432

However, the requirements describing which characters *MUST* be escaped with a circumflex does not include equal https://github.com/w3c/epub-specs/blob/fa5e0f8ea58e0de87f356c89b73a2990a596fb8c/archive/epubcfi/index.html#L615-L635

Should equal (=) be considered a character that must be escaped?

**Comment by iherman** [comment]
@bvandorn this WG does not (at least currently) works on EPUBCFI. That may change in the future, but at this moment that document is frozen...

**Comment by mattgarrish** [comment]
Equals definitely appears to be an omission from the text list, so in this case go with the ebnf.

We should put the abandoned label on this in addition to closing so it can be resurrected later if we return to CFIs.

**Comment by bvandorn** [comment]
Thanks all
