### ISSUE TITLE
Is our requirement on (scripting) origin normative or not?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1659]
At the moment, the RS document says, in [$15.1](https://w3c.github.io/epub-specs/epub33/rs/#sec-scripted-content-security):

> Reading Systems must behave as if a unique origin [[URL](https://w3c.github.io/epub-specs/epub33/rs/#bib-url)] were allocated to each EPUB Publication. Adopting this approach will isolate publications from each other, thereby limiting access to cookies, DOM storage, etc.

This statement is in a non-normative section and "must" is used as opposed to "_MUST_". As this is the only place this restriction is mentioned, the conclusion is that the requirement is not normative for Reading Systems.

The (normative) [EPUB Content section §3.4](https://w3c.github.io/epub-specs/epub33/core/#sec-scripted-support) says:

> Reading Systems are required to behave as though a unique [origin](https://url.spec.whatwg.org/#origin) [[URL](https://w3c.github.io/epub-specs/epub33/core/#bib-url)] has been assigned to each EPUB Publication.

It says "required" and not "_REQUIRED_" but that is fine, even if the intention is that this feature would be non-normative; after all, the requirement should indeed be in the RS spec and not in the content. However, the reader of the Core spec may believe that this is the only reason that the term is as is, but that the Reading System is indeed _REQUIRED_, ie, that it is a normative requirement. As most of the authors will not read the RS document, this may lead to false expectations. 

Two fundamental question: is the requirement, whereby RS-s must ensure a unique [origin](https://url.spec.whatwg.org/#origin) for all scripts in content documents:

1. **normative**
    - in this case the statements should be added into a normative section of the RS document (because we forgot to do that)
2. **informative**
    - in this case the statement in the Content document should be changed to something that conveys the information that it is by means sure that this restriction is applied. For example:
    > Reading systems may behave as though a unique [origin](https://url.spec.whatwg.org/#origin)"

**Comment by iherman** [comment]
As far as I am concerned, I would seriously consider making this requirement normative.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-07-epub#section2) on 2021-05-07

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-07-epub#resolution1):  Make statement in issue 1659 normative***

<details><summary><i>View the transcript</i></summary>

### 2. is our scripting requirement normative? 

_See github issue [#1659](https://github.com/w3c/epub-specs/issues/1659)._




**Dave Cramer:** right now RS spec has non-normative section on security and privacy  
… in here is where we have the statement that RS must behave as though each epub is its own origin  
… but this is the cornerstone of our security model  
… so should it be normative?  

**Ivan Herman:** yes  
… the question is whether putting that as a normative requirement now would create backwards compat issues for existing RS  

**Laurent Le Meur:** for Readium, no, there will be no problem  
… for other RS, not sure at all, because there is extra effort to do this  
… not sure that RMSDK for example has this possibility  
… if we make this normative, could this invalidate existing readers (e.g. eINK readers)?  

**Dave Cramer:** not sure if any RS is compliant to that extent  

**Ivan Herman:** what we can do is declare as normative today, but put it as "at risk feature" when we go to CR  
… so if it turns out to create huge problems that implementations cannot handle, then we can remove it from normative section (and keep it as informative)  

**Dave Cramer:** we already have at least one implementation  
… fairly confident we can get at least one more  

**Laurent Le Meur:** usually user storage is the issue  
… and for user storage there is a simple test we can do (i.e. if one epub can store something that another reads)  

**Tzviya Siegman:** i think Ivan's "at risk feature" is a good process solution  
… maybe also add an informative note with it to explain the history (and why we're marking it "at risk")  

**Dave Cramer:** if epub 3.3 becomes REC, and there are some RS that don't separate epubs from each other, I don't see how that's any different from the last 20 years  
… doesn't affect validity of epubs  
… this is about what RS do, and we know that they make their own choices about what to implement  
… prefer not to call this out as "at risk"  

**Ivan Herman:** agreed. Withdrawing my earlier proposal.  
… is there any serious epub out there that will become unreadable if we change to normative status?  

**Dave Cramer:** i see backwards compatibility issue, but if that book is doing something sketchy from security POV, we don't have to maintain compatibility for it  

**Ivan Herman:** right, so my question is about valid epubs only  

> **Proposed resolution: Make statement in issue 1659 normative** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Ivan Herman:* +1

> *Tzviya Siegman:* +1

> *Toshiaki Koike:* +1

> *Wendy Reid:* +1

> *Masakazu Kitahara:* +1

> *Dave Cramer:* +1

> *Matthew Chan:* +1

> *Bill Kasdorf:* +1

> *Dan Lazin:* +1

> *Gregorio Pellegrino:* +1

> ***Resolution #1: Make statement in issue 1659 normative***

</details>

**Comment by danielweck** [comment]
> Reading Systems are required to behave as though a unique origin [URL] has been assigned to each EPUB Publication.
> Reading Systems must behave as if a unique origin [URL] were allocated to each EPUB Publication.

Hello :)

I think that the formulation of Reading System requirements should be more detailed, in the spirit of providing useful guidance to implementers. Here is what I have in mind (first stab):

* Reading System implementations must assign publications a unique “origin”, in order to enable a secure isolated context for each individual publication (e.g. to prevent scripts in one publication from accessing data stored by another publication).
* All content documents of a given publication must inherit the publication’s unique “origin”, as per the definition of “origin” for Web contents (https://html.spec.whatwg.org/multipage/origin.html#origin). Examples of Web APIs that are tied to the concept of “origin” include LocalStorage and IndexedDB, which EPUB content documents can interact with via scripting.
* Reading Systems that allow users to add/remove publications from a managed library (aka “bookshelf”) may maintain the publication’s unique origin when the publication is removed and subsequently re-imported into the content library. Conversely, Reading Systems may create a new unique origin for every newly-added publication.
* The unique origin for a given publication (and by extension, for all its content documents) must be preserved across "renders", i.e. when closing / re-opening publications, or when navigating back-and-forth between documents within an opened publication.
* Reading Systems must ensure that the data tied to specific origins (e.g. LocalStorage, IndexedDB) is preserved between "renders". Reading System implementations that integrate the capabilities of web browser engines (e.g. embedded webview component) would typically use the provided cache/persistence APIs in order to ensure that origin-bound data is preserved. This specification does not mandate particular mitigation strategies for dealing with size limitations (e.g. cache invalidation, storage reset), but merely recommends following best practices as used in the Open Web Platform.
* In the absence of reliable Web origin (e.g. HTTP URL scheme + host + port), Reading Systems must uniquely identify publications in order to assign individual and persistent origins. The heuristics may include a combination of:
  * `dc:identifier` and/or other publication metadata (caveat: in practice, these types of identifiers may in fact not guarantee globally-unique identification, thus why it is recommended to combine multiple techniques)
  * filesystem path (e.g. if a Reading System imports publication assets into some kind of internal implementation-dependent library/bookshelf folder)
  * publication container checksum (e.g. zip archive CRC computation, based on directory entries)
  * etc. (in other words, this specification does not mandate a particular implementation technique, but merely provides guidance to implementors)

**Comment by iherman** [comment]
Hey @danielweck :-)

First of all, thanks for chiming in!

I have just created (a few hours ago) the PR https://github.com/w3c/epub-specs/pull/1671. The only goal of that PR is to formulate the normatively required part of all this (the unique origin). I would love if you could check whether what is there is correct and to see whether anything is missing.

The question is where and how to put all these (great!) points. We could put them as part of (and probably as a subsection) of the security considerations (which are guidelines for implementers in fact), and I am happy to do that if you think that is the best place, although I may make the text a bit more succinct. But are we sure whether that is indeed the best place (I wonder, for example, whether the heuristics for the unique origin should not be put as a note right where the normative statements are).

WDYT?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-21-epub#section3) on 2021-05-21

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-21-epub#resolution3):  get rid of the hand-waving in PR 1671 on the origin issue***

<details><summary><i>View the transcript</i></summary>

### 3. Is our scripting requirement normative? 

_See github pull request [#1671](https://github.com/w3c/epub-specs/pull/1671)._




_See github issue [#1659](https://github.com/w3c/epub-specs/issues/1659)._




**Dave Cramer:** Security and Privacy - trying to bring more rigor  

**Ivan Herman:** Unique origin (per epub) is something we have already decided  
… Implementing that resolution I hit two things  
… one editorial, one serious  
… There was a statement which said roughly "you should have a unique origin, but if you can't then do some hacks" (non-normative)  

> *Dave Cramer:* [https://w3c.github.io/epub-specs/epub33/rs/#sec-scripted-content-security](https://w3c.github.io/epub-specs/epub33/rs/#sec-scripted-content-security)

> *:* domain isolation is the most effective way to secure EPUB Publications in Web-based Reading Systems, it is not always a realistic option. Web-based Reading Systems must still maintain isolation in such cases, which may require limiting access to scripting APIs that allow client-side data storage and access.”

**Ivan Herman:** Didn't know what to do with that statement  
… I kept it to security and privacy, but there was a long thread of discussion on the request about what to do with it  
… General hand waving over what to do if you can't handle origins  
… There are several options about how to write it  
… but is tending towards the recommendation to dump it entirely  
… since it is now required to support origin  

**Brady Duga:** to add context, we did not have requirement around origin in the past  
… when we added that requirement, we needed to take out the lines that said it wasn't required. We have to revisit whether this isn't required if we take this out  

**Dave Cramer:** My instinct is to keep the normative requirement and get rid of the hand-waving  
… acknowledging that the architecture of some RSes might have issues with this  
… Don't see the need for the spec to recognize that  
… I would hope there are some tests that check the spirit of this  
… Really don't want cross-script data sharing  
… The web way to do that is to use distinct origins  
… If a RS can pass those tests then I am happy with it, regardless of how it is actually implemented  

> **Proposed resolution: get rid of the hand-waving in PR 1671 on the origin issue** *(Ivan Herman)*

> *Brady Duga:* +1

> *Ivan Herman:* +1

> *Tzviya Siegman:* +1

> *Dave Cramer:* +1

> *Toshiaki Koike:* +1

> *Matt Garrish:* 0

> *Gregorio Pellegrino:* +1

> *Ben Schroeter:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #3: get rid of the hand-waving in PR 1671 on the origin issue***

**Ivan Herman:** Then there was also a more editorial question  
… the entire section has been enriched with more comments  
… but those items, while interesting, are not related to security and privacy  
… comments are around keeping data, which may be correct but is not S&P related  
… Is there a place to move this to? eg general best practices for scripting  
… if yes, then we should keep and enhance, otherwise we need to drop them  

**Dave Cramer:** I don't think we should do something like that (best practices)  
… These seem out of scope for the spec  
… Presumably people will figure it out  

**Brady Duga:** All of these comments are around preserving data, but the spec does not require that  
… you don't have to use web storage, etc  
… It would be tricky to write tips and tricks for specs that are not required  

> *Tzviya Siegman:* This is very niche - tips for supporting optional specs on top of optional features.

**Dave Cramer:** Don't feel qualified to recommend implementation details to devs  
… Seem to be drifting away from core responsibilities of the spec, would prefer fewer words here  

**Ivan Herman:** Essentially in agreement  
… Don't need a formal resolution (this isn't a normative statement), but will go ahead and remove those items  

**Hadrien Gardeur:** Question about previous item: have we discussed what APIs can be used?  
… Is there a policy or rough idea about our position?  

**Brady Duga:** historically, we've viewed scripting as experimental. We've left it up to authors, publishers, systems to decide what to support. It's a strange place to allow third party to decide what to do with user data. It's a scary place to be, and I don't think we should put into spec.  

**Ivan Herman:** An analogy - no one specifies which APIs must be implemented by a browser  
… It is rare (never?) to require specific API implementations  
… Just like a browser, it is up to RS authors to decide what they will implement  

</details>
