### ISSUE TITLE
Use of cautions and warnings

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1660]
We used to have a caution class in IDPF for some messages about lack of support and future invalidity with respect to html and svg. See, for example, http://idpf.org/epub/31/spec/epub-contentdocs.html#sec-svg

It appears a couple of the cautions got turned into warning classes when we translated the documents, which, despite being undocumented, respec turns into red warning boxes: https://w3c.github.io/epub-specs/epub33/core/#sec-reserved-prefixes

We should harmonize all these instances, but the questions this raises for me are:

1) Is a "warning" an appropriate replacement for a "caution" or does it sound too severe? (Should we add a custom script to change the titles and backgrounds to cautions?)
2) Should we be relying on an undocumented feature? (Would be good to ask if it's legit but forgotten in the documentation, or likely to be dropped in the future.)
3) Should we use notes and avoid the issue entirely, or does that minimize the message too much?

**Comment by mattgarrish** [comment]
I also discovered there's an "advisement" class.

Have asked about these classes in https://github.com/w3c/respec/issues/3503

**Comment by iherman** [comment]
I must admit I did not know about this built-in behaviour either...

I believe that the current 'warning' is "over the top": it should be reserved to situations where a specific features may have, say, security implications. This is not our case. As, (seeing https://github.com/w3c/respec/issues/3503#issuecomment-831011421) this seems to be a feature built-in the core TR style sheets, I do not think we should change the outlook pragmatically (besides, we may, either now or in the future, hit a situation where the current warning style _is_ the appropriate one!).

I would be in favour of either use a note, or come up with our own style and class name for 'caution'.

**Comment by mattgarrish** [comment]
> I do not think we should change the outlook pragmatically

Right, I wasn't even aware there were organization-specific styles. For all I knew, we just "use respec".

Sounds like we'd need to request a new caution style, too, so maybe we should just go with the existing "advisement" class? They're just notes we want to draw a little extra attention to, after all.

**Comment by iherman** [comment]
> Sounds like we'd need to request a new caution style, too,

There is absolutely nothing wrong if we define our own class in our own css file. Whether respec will take over later, all the better, but we should not have a dependency on this...

**Comment by mattgarrish** [comment]
> There is absolutely nothing wrong if we define our own class in our own css file.

Right, but is it okay to define something like a new caution box on our own?

I'm happy to do it if we can, but I was assuming a new type of alert box would fall into the [process for approving new designs](https://github.com/w3c/tr-design/#process-for-approving-a-new-design). That makes it sound like we'd have to request approval from the director.

**Comment by iherman** [comment]
> I'm happy to do it if we can, but I was assuming a new type of alert box would fall into the [process for approving new designs](https://github.com/w3c/tr-design/#process-for-approving-a-new-design).

I believe that is necessary if we want that style sheet to become part of the common style used by all TR-s.

Let us just do it. If we get a snap on our fingers, then we can modify that, but I do not expect that to happen.
