### ISSUE TITLE
Update reference for Accessibility to latest working version 1.1

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#1676]
Currently:
[EPUB-A11Y-10]
EPUB Accessibility 1.0. Matt Garrish; George Kerscher; Charles LaPierre; Avneesh Singh. IDPF. 05 January 2017. URL: http://idpf.org/epub/a11y/accessibility-20170105.html
[EPUBContentDocs-301]

Should be

[EPUB-A11Y-11]
EPUB Accessibility 1.1. Matt Garrish; George Kerscher; Charles LaPierre; Gregorio Pellegrino; Avneesh Singh. W3C. 23 February 2021. W3C Working Draft. URL: https://www.w3.org/TR/epub-a11y-11/

**Comment by mattgarrish** [comment]
Is this in reference to the reading system specification, @clapierre ?

If so, that reference is removed in the current editor's draft (when we added an accessibility section to the document). The TR document will be updated when we re-publish.

**Comment by clapierre** [comment]
OK, yes it was sorry.  I was looking I guess at an old draft you sent out.

[EPUB Reading Systems 3.3](https://www.w3.org/TR/2021/WD-epub-rs-33-20210406/)

**Comment by mattgarrish** [comment]
Ya, we'll be republishing again soon, hopefully.
