### ISSUE TITLE
SVG core media type: only content document, or also inline image?

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1684]
https://w3c.github.io/epub-specs/epub33/core/#cmt-svg lists `SVG Content Documents` as a core media type, but all other images are (of course) not called Content Documents. This implies to me that SVGs need *only* be supported as Content Documents, not as inline images like GIFs, JPEGs, etc.

Should this list both SVG and SVG Content Documents, for clarity?

**Comment by mattgarrish** [comment]
Although "SVG Content Document" sounds like it's required to be a standalone in-spine document, that's not actually the case.

The section defines the profile of SVG used in EPUB. A SVG content document can be either a top-level content document, in which case it's in the spine, or an embedded one, but the requirements don't change.

The same is true for including XHTML. An XHTML content document can be top-level or it can be embedded via an iframe.

If we list "SVG" on its own, it sounds like we also support SVG that doesn't conform to the requirements of the specification.

Maybe adding a parenthetical after would help: "SVG Content Document (Top-level and Embedded)" ?

**Comment by dlazin** [comment]
> The section defines the profile of SVG used in EPUB. A SVG content document can be either a top-level content document, in which case it's in the spine, or an embedded one, but the requirements don't change.

OK, I see. I clicked through to https://w3c.github.io/epub-specs/epub33/core/#sec-svg and didn't understand that because the intro says `Although EPUB Creators typically use XHTML Content Documents as the top-level document type, the use of SVG Content Documents is also permitted.` That implies that we're talking only about top-level documents.

I think it would be more valuable to clarify *that* section, then, although clarifying both would be nice too.

**Comment by dauwhe** [comment]
Don't we have three cases? 

1. SVG Content documents
2. SVG as image referenced from `img`
3. SVG embedded in HTML via `svg` element. 

3 is covered by the HTML spec. 1 is covered by EPUB now. I do think we could clarify that 2 is also fine.

**Comment by mattgarrish** [comment]
> I do think we could clarify that 2 is also fine.

We cover this scenario in the embedding section:

> XHTML Content Documents support the embedding of SVG document fragments [SVG] by reference (embedding via reference, for example, from an img or object element) and by inclusion (embedding via direct inclusion of the svg element in the XHTML Content Document).
> 
> The content conformance constraints for SVG embedded in XHTML Content Documents are the same as defined for SVG Content Documents in § 3.2.3 Restrictions on SVG.

https://w3c.github.io/epub-specs/epub33/core/#sec-xhtml-svg

(It was a compromise on naming so that we didn't have to create two sections.)
