### ISSUE TITLE
What is package document's dir attribute supposed to affect?

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1689]
https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-base-dir says:

> If the dir attribute is set and indicates a base direction of ltr or rtl, Reading Systems MUST override the bidi algorithm per the higher-level protocols defined in [BIDI], setting the paragraph embedding level to 0 if the base direction is ltr, or 1 if the base direction is rtl.

This appear to be referring specifically to `<package ... dir="rtl">`; https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-i18n addresses other uses of `dir`.

But it's not clear to me what RSes are supposed to do (practically) with an explicitly set `dir` attribute. Is `<package ... dir="rtl">` supposed to apply to the whole book, even if the XHTML files themselves don't set it? Is it supposed to indicate only that the `dir` applies to package-level fields, like `title` and `creator`?

I have tested an EPUB with `<package ... dir="rtl">` in Apple Books, Google Play Books, and Thorium, and none of them appear to do anything. Title and book content all remain LTR (because the book is English).

If I set `<html ... dir="rtl">` in any of the XHTML files, then the RSes faithfully reverse the body-text direction as expected, but it's not clear what the package declaration is supposed to do.

I recommend we clarify the language and consider this statement at risk because it doesn't seem to be widely implemented (unless I completely misunderstand it).

**Comment by dlazin** [comment]
The section above also says: 

> Otherwise the base direction is auto, in which case Reading Systems MUST determine the text's direction by applying the Unicode Bidi Algorithm, beginning with Rule P2 of [BIDI].

But P2 says:
> P2. In each paragraph, find the first character of type L, AL, or R while skipping over any characters between an isolate initiator and its matching PDI or, if it has no matching PDI, the end of the paragraph.

What is a "paragraph" from the perspective of a package document? It's clear how to apply this rule in an XHTML Content Document, but not the Package Document.

**Comment by iherman** [comment]
> But it's not clear to me what RSes are supposed to do (practically) with an explicitly set `dir` attribute. Is `<package ... dir="rtl">` supposed to apply to the whole book, even if the XHTML files themselves don't set it? Is it supposed to indicate only that the `dir` applies to package-level fields, like `title` and `creator`?
> 

The answer to your question is that the value of `dir` is only relevant for the textual content _within the package document_. Ie, just like `xml:lang`, it does not, and should not affect the content documents which should set these values explicitly. The behaviour of RSs that you describe is therefore correct.

The content spec says, in the definition of [`dir`](https://w3c.github.io/epub-specs/epub33/core/#attrdef-dir) 

> Specifies the base direction [BIDI] of the carrying element and its descendants.)

I agree that this aspect is not explicitly described in the RS specification; do you think we should add an editorial warning?

**Comment by mattgarrish** [comment]
> `dir` is only relevant for the textual content _within the package document_.

Right, I don't believe any specification with a `dir` attribute defines it as applying to linked documents.

But we could harmonize the definition better with xml:base, as dir doesn't currently mention text:

> Specifies the base direction [BIDI] of the carrying element and its descendants.

compared with:

> Specifies the language used in the contents and attribute values of the carrying element and its descendants...

So both definitions might better say:

"Specifies the XXX of the textual content and attribute values of the carrying element and its descendants"

**Comment by dlazin** [comment]
> The answer to your question is that the value of `dir` is only relevant for the textual content _within the package document_. Ie, just like `xml:lang`, it does not, and should not affect the content documents which should set these values explicitly. The behaviour of RSs that you describe is therefore correct.

Does that mean that `<package ... dir="rtl">` should result in the title and/or creator being rendered RTL? If so, none of Apple Books, Play Books, or Thorium is doing so (I put punctuation in an English title to see if the punctuation was moved; this works as a test in the content docs but has no effect in the title or creator).

Unless I misunderstand, I think this statement is at risk due to lack of implementation.

**Comment by mattgarrish** [comment]
> Does that mean that `<package ... dir="rtl">` should result in the title and/or creator being rendered RTL?

Should, yes, but we also only just added the requirements for `dir` in 3.3. It may take some time to see implementations given that we're still only at the draft stage.

> Unless I misunderstand, I think this statement is at risk due to lack of implementation.

I wouldn't worry too much about trying to figure out what is at-risk yet, as we still need to bring in the folks from Asia (and elsewhere) where changes in directional runs may be a more common issue to deal with. There are a lot of reading systems out there, so finding a couple that do the right thing is often not that hard.

I think we also need to be careful with metadata that reading system use is not the sole determining factor of its implementation, too. Meta information is important for publishers and used in internal workflows and content management systems, independent of how reading systems use it. I don't know how we capture that, though, other than surveying publishers to see if they use metadata (which we've already done in the past, so probably doesn't warrant doing again).

**Comment by iherman** [comment]
@dlazin, should we close this issue? I am not sure there is any immediate action to be done on the document; the CR period will reveal whether the implementation follow the feature, but that is still down the road.

**Comment by dlazin** [comment]
Yes, I think this was handled well enough by https://github.com/w3c/epub-specs/pull/1694.
