### ISSUE TITLE
CSS properity

### ISSUE THREAD

**Issue by prithiviclteam** [w3c/epub-specs#1701]
Hi Team,

We have using  **unicode-bidi:bidi-override;** this properity in CSS its showing below error.

ERROR(CSS-001): 95156_EPUB.epub/EPUB/styles/styles.css(1649,1): The "unicode-bidi" property must not be included in an EPUB Style Sheet.

Please check and advice how to handle this type of CSS, we are using Fixed layout epub for alignment.
 

Thanks,
Prithiviraj M

**Comment by iherman** [comment]
@prithiviyaso is this an error raised by epubcheck? A particular reading system?

**Comment by iherman** [comment]
In any case, the EPUB 3.2 specification is [clear](https://www.w3.org/publishing/epub32/epub-contentdocs.html#sec-css-content-conf): the `unicode-bidi` property is disallowed:

>A conformant CSS style sheet MUST meet all of the following criteria:
>
> * It MAY include any CSS properties, with the following exceptions:
>     * It MUST NOT use the direction property [CSS-Writing-Modes-3]. Use the [HTML] `dir` attribute to set the inline base direction.
>    * It MUST NOT use the unicode-bidi property [CSS-Writing-Modes-3]. Use [HTML] `bdo` elements and `dir` attributes to control bidirectionality.

The error message is therefore correct, wherever it comes from...

**Comment by prithiviclteam** [comment]
It show error using epubchecker,

**Comment by iherman** [comment]
> It show error using epubchecker,

And, as I said in https://github.com/w3c/epub-specs/issues/1701#issuecomment-860755724, epubcheck is correct. Note that this restriction is also in place for the upcoming 3.3 version of EPUB.

**Comment by prithiviclteam** [comment]
OK! Thank you for your comments.
