### ISSUE TITLE
Editorial comment on §3 of the core spec.

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1704]
At the moment, [§3](https://w3c.github.io/epub-specs/epub33/core/#sec-contentdocs) of the core spec is entitled "EPUB Content Documents" and has the following subsections: XHTML Content Documents, SVG Content Documents, Cascading Style Sheets (CSS), Scripting, and Pronunciation Lexicons. Per definition, [Content Documents](https://w3c.github.io/epub-specs/epub33/core/#dfn-epub-content-document) only include XHTML and SVG, but the current structure of §3 may be misread, giving the impression that CSS, PLS, and scripts are also content documents.

The simplest is to gather the CSS and Scripting (and maybe MathML?) into either a separate top section, or a subsection of §3, under some title (I am not sure how to formulate it, something like "Embedded file formats", or "Included file formats", or something similar. That would make things clearer imho.

**Comment by OriKuttner** [comment]
Lets just write "Other file formats" as the other files SVG, CSS, Scripts
etc. are very different from each other, they are not real content.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by mattgarrish** [comment]
The key for CSS and Scripting being coequal with the XHTML and SVG definitions is that they aren't specific to either.

Maybe they could be grouped under a "Shared Resource Requirements" heading?

**Comment by mattgarrish** [comment]
"Common" might be better in this case than "Shared".
