### ISSUE TITLE
PLS processing inconsistencies

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1705]
Recording this from #1690 to look at again after splitting PLS out to a note.

The PLS reading system requirements:

- confuse the reading system as the text-to-speech engine, and are too simplistic as a definition of how to write a tts engine that supports pls
- are contradictory - pls defines how to select lexemes (first preferred otherwise first in document order) that a conforming tts engine has to follow, not last in document order regardless of preference as we define
- stray into areas the reading system can't control - precedence of lexicon/ssml will be controlled by the tts engine (this is where our ssml definition is similarly underspecified)
- don't even clearly define that you have to obtain and use the linked lexicons

We would have been better off saying only that a reading system:

- must use a PLS-compliant text-to-speech engine to render xhtml content documents
- must initiate the text-to-speech engine using all PLS lexicons linked to from the xhtml content document

**Comment by iherman** [comment]
@mattgarrish shouldn't we close this issue by virtue of having now a separate note to work on?
