### ISSUE TITLE
Are SSML attributes allowed on SVG?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1710]
Is there a reason we only define them for XHTML given that they could be put on text/tspan elements in SVG?

The one awkward part is that you can't define lexicons in SVG since it lacks a link element, but there's no reason you can't use SSML or CSS Speech in SVG.

**Comment by iherman** [comment]
> The one awkward part is that you can't define lexicons in SVG since it lacks a link element, 

Actually, not sure it does, see [§5 HTML metadata elements](https://www.w3.org/TR/SVG2/struct.html#HTMLMetadataElements) in the SVG spec. The text does say:

> For user agents that support HTML…

But that is certainly the case for Reading Systems. There is also an example in [§6.3 ](https://www.w3.org/TR/SVG2/styling.html#LinkElement) using the `<link>` element to import a CSS style sheet. We can certainly rely on the same mechanism to import lexicons.

**Comment by mattgarrish** [comment]
> Actually, not sure it does, see [§5 HTML metadata elements](https://www.w3.org/TR/SVG2/struct.html#HTMLMetadataElements) in the SVG spec.

Ah, nice! I was looking at the element index and it wasn't listed there. Wish that index included everything.

> We can certainly rely on the same mechanism to import lexicons.

Even better case for questioning why we didn't include the TTS enhancements for SVG.
