### ISSUE TITLE
Add TTS examples

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1712]
We don't provide any examples of how to use/define ssml attributes, lexicons or css speech properties.

**Comment by murata2makoto** [comment]
This SSML example is quoted from a report of a Japanese ministry.  It is assumed that the html element specifies ssml:alphabet="x-JEITA".

```
<span id="_vsn_1" ssml:ph="ﾓﾘ/ｵ'ｰｶﾟｲﾄ/ｿ'ｰｾｷﾜ/ｱ'ｻﾏﾃﾞ/ｶﾀﾘｱ'ｯﾀ." >
森鷗外と漱石は朝まで語り合った。
</span>
```

This PLS example is also quoted from another report of the same ministry.

```
<lexicon
 version="1.0"
 alphabet="x-JEITA"
 xml:lang="jp"
 xmlns="http://www.w3.org/2005/01/pronunciation-lexicon">
 <lexeme>
 <grapheme>近衛文麿</grapheme>
 <phoneme>コノエ/フミマロ</phoneme>
 </lexeme>
 <lexeme>
 <grapheme>東久邇宮</grapheme>
 <phoneme>ヒガシ/クニノミヤ</phoneme>
 </lexeme>
</lexicon>
```

**Comment by mattgarrish** [comment]
Is it okay to use these examples in our document?

**Comment by mattgarrish** [comment]
I found on the ministry website that they want any reproduction cited using the ministry's name and the source url. I've created some alternatives instead to avoid this.
