### ISSUE TITLE
SSML and PLS do not have to be used together

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1713]
Although SSML and PLS can be used together, there is nothing wrong in using SSML only or using PLS only.  For example, the biggest textbook publisher in Japan uses SSML only.   I can also imagine that PLS without SSML is very useful for novels having hard-to-read main character names.  

But the wording now (e.g., the third para in the introduction) makes people think that both should be used together.  Please improve the text for avoiding this misinterpretation.

**Comment by mattgarrish** [comment]
Right, I was only getting at the genesis of PLS as a vocabulary language for SSML; I didn't mean to infer they have to be used together. See if the new wording in https://github.com/w3c/epub-specs/pull/1700/files#diff-a64c81b68a10aef7ac71af3d9a43d852e2ce2d28d29decd417cdf1db67aca22fR64 is better (W3C documents appear to be down right now so the preview is broken).
