### ISSUE TITLE
TTS "reformulation"

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1717]
The current text says, in [§1.1](https://w3c.github.io/epub-specs/epub33/tts/#overview):

> This document represents an attempt to reformulate these technologies so that they can be authored in EPUB Content Documents.

Is the term “reformulate” correct and/or acceptable here? To my ears, it sounds as if this document attempted to re-define SSML or PL, which is not the case. Would not something be better:

> This document proposes connections to these technologies so that they can be authored in EPUB Content Documents.

**Comment by mattgarrish** [comment]
I think it's reasonably accurate for SSML, since we're defining a new way of implementing the technology. What we're doing is SSML-like but is a new way of applying the technology.

I agree it's less applicable to PLS, as we're not doing anything in that case except defining how to link the lexicons.

I don't know if "connections" quite captures these distinctions, either. Maybe we should avoid trying to find a common thread for them and just change the sentence to:

"This document represents an attempt to enable their authoring and rendering in EPUB Content Documents."

**Comment by iherman** [comment]
> "This document represents an attempt to enable their authoring and rendering in EPUB Content Documents."

Go for this. It is reasonably neutral and precise enough.

**Comment by iherman** [comment]
Actually... drop the attempt. This does not sound good in a document like this one. Maybe 

> This document proposes an approach to enable their authoring and rendering in EPUB Content Documents.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-24-epub#section2) on 2021-06-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 2. Text-To-Speech 

_See github issue [#1715](https://github.com/w3c/epub-specs/issues/1715), [#1717](https://github.com/w3c/epub-specs/issues/1717)._




**Wendy Reid:** last week we discussed what to do with PLS and SSML in the spec. We aren't getting rid of them, but are separating them into their own separate document.  
… the issues were just doing this  

**Matt Garrish:** yes, we pulled them out, and added a little intro type prose  
… we talked about what to name these documents in one of the issues  
… but like we said last time, these parts just felt a little underspecified (and still do)  

**Wendy Reid:** I started doing a little bit of research into what RS might have implemented TTS, this is ongoing  

**Matt Garrish:** DAISY has some readers that can do TTS, but even when it comes to PLS they don't implement it exactly as per spec  
… about naming, we were going for something that tied it to our spec, but also gave it a 1.0 version number  

**Ben Schroeter:** VitalSource has TTS, but not sure if they use SSML and PLS  

**Brady Duga:** same with us, but we just use OS level TTS functionality  

</details>
