### ISSUE TITLE
[EPUB 3.3] [question] Difference between Text-To-Speech and Assistive Technologies

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1727]
When the specification talks about Text-to-Speech (TTS), do we mean the one in assistive technologies (screenreaders) or the one in reading applications? Or both?

Normally the screenreader returns to the user semantic constructs, alternate text, etc. to the user, while the TTS in reading applications reads the text only.

I think it might be helpful to make this more explicit in https://www.w3.org/TR/epub-33/#dfn-text-to-speech

**Comment by mattgarrish** [comment]
> do we mean the one in assistive technologies (screenreaders) or the one in reading applications? Or both?

Only in the reading system, as the term is only used in the media overlays section now.

Even the TTS note is only about the reading system, as what AT do is out of scope. They may use the enhancements, too, but what general screen readers do is not something we can really influence.

We can probably amend the definition in the core spec to:

"The rendering of the textual content of an EPUB Publication **_, by a Reading System,_** as artificial human speech using a synthesized voice."

And add another paragraph to the tts note overview explaining that AT are not in scope.

**Comment by murata2makoto** [comment]
Do we really need this term here?  I am asking since SSML and PLS will be moved to a different note.  We need TTS here only for defining MO.

**Comment by mattgarrish** [comment]
> Do we really need this term here?

Probably not. I think we can link the current uses to the TTS section in media overlays and integrate the term there.
