### ISSUE TITLE
[EPUB 3.3] [explanation] Foreign Resources and fallbacks

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1728]
As a non-english speaker I find difficulty in understanding the sentence.

> EPUB Creators MAY include Foreign Resources without a fallback provided they do not reference them from spine itemref elements or directly render them in their native format in EPUB Content Documents (e.g., via [HTML] embedded content and [SVG] image and foreignObject elements).
> https://www.w3.org/TR/epub-33/#sec-foreign-restrictions

Perhaps a rephrase can be thought of?

**Comment by mattgarrish** [comment]
What if we break it apart and tweak it a little:

> EPUB Creators MAY include Foreign Resources without fallbacks provided they:
>
> - do not reference the resources from spine itemref elements; and
> - do not embed them directly in EPUB Content Documents (e.g., via [HTML] embedded content and [SVG] image and foreignObject elements).

**Comment by gregoriopellegrino** [comment]
Fine for me
