### ISSUE TITLE
[EPUB 3.3] [suggestion] Cover info in metadata section

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1731]
I know that the cover image is not defined in the `metadata` section of the `opf` file, but in the `manifest` with the property `cover-image`.

I think some people not familiar with the EPUB format and specs might look for how to express this information in the `metadata` section of the specification (for all intents and purposes he cover is a «metadata» of the publication).

Maybe add a note about it that links to the explanation of the `cover-image` property?

**Comment by mattgarrish** [comment]
What if we flesh out the sentence that requires specifying all applicable properties:

> EPUB Creators MUST declare all applicable descriptive metadata properties for each Publication Resource in this attribute (e.g., if the resource is the cover image, contains scripting, or references remote resources).

(We can hyperlink the actual spec prose to each term.)

**Comment by iherman** [comment]
> What if we flesh out the sentence that requires specifying all applicable properties:
> 
> > EPUB Creators MUST declare all applicable descriptive metadata properties for each Publication Resource in this attribute (e.g., if the resource is the cover image, contains scripting, or references remote resources).
> 
> (We can hyperlink the actual spec prose to each term.)

Do you mean adding this note in https://www.w3.org/TR/epub-33/#attrdef-properties ? 

I actually wonder whether such a text should not be added in the [definition of the item element](https://www.w3.org/TR/epub-33/#sec-item-elem), or maybe even the [intoduction](https://www.w3.org/TR/epub-33/#sec-package-intro). I think @gregoriopellegrino's comment is indeed correct, namely that term 'metadata' may usually be understood more widely than in our spec (the `cover-image` value is just an example, the same could be said about the `mathml` value, for example).

**Comment by mattgarrish** [comment]
> Do you mean adding this note in https://www.w3.org/TR/epub-33/#attrdef-properties ?

No.

> I actually wonder whether such a text should not be added in the [definition of the item element](https://www.w3.org/TR/epub-33/#sec-item-elem),

That's where the sentence on declaring the properties is. It's a couple of paragraphs below this: https://w3c.github.io/epub-specs/epub33/core/#attrdef-item-properties

**Comment by mattgarrish** [comment]
> namely that term 'metadata' may usually be understood more widely than in our spec

Sure, but everything in the package document is metadata about something. 😉 

EPUB 2 made a mess of things by not defining how to specify a cover, which ended up with it done in a meta element. The only reason we have the legacy opf2 meta element is to allow compatibility of covers for older reading systems, so if we need a pointer that's probably a better place to put it than generally in the metadata section. If readers have a preconception, that's probably it.

**Comment by iherman** [comment]
> > Do you mean adding this note in https://www.w3.org/TR/epub-33/#attrdef-properties ?
> 
> No.
> 
> > I actually wonder whether such a text should not be added in the [definition of the item element](https://www.w3.org/TR/epub-33/#sec-item-elem),
> 
> That's where the sentence on declaring the properties is. It's a couple of paragraphs below this: https://w3c.github.io/epub-specs/epub33/core/#attrdef-item-properties

Ah, o.k., I misunderstood. Adding that additional example that you propose in https://github.com/w3c/epub-specs/issues/1731#issuecomment-871815875 sounds good to me.
