### ISSUE TITLE
[EPUB 3.3] [question] rendition:orientation for reflowable EPUBs

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1734]
While I am aware that these properties are defined in the Fixed Layout EPUB section, I realized that some of them can also be used to describe reflowable EPUBs (e.g. `rendition:layout` which defines if a content is reflowable or fixed layout).

The question is: does `rendition:orientation` only apply to fixed layouts or also to reflowables?

https://www.w3.org/TR/epub-33/#orientation

**Comment by mattgarrish** [comment]
> The question is: does `rendition:orientation` only apply to fixed layouts or also to reflowables?

The rendition vocabulary is split into properties that can be used in both (https://www.w3.org/TR/epub-33/#sec-rendering-general) and properties that are only for fixed layouts (https://www.w3.org/TR/epub-33/#sec-rendering-fxl).

Orientation is not one of the general properties.

**Comment by iherman** [comment]
@gregoriopellegrino can we close this then?

**Comment by gregoriopellegrino** [comment]
Yes, thank you
