### ISSUE TITLE
[EPUB 3.3] [question] The par element represents phrases?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1739]
The specification says:

> The par element represents phrases
> https://www.w3.org/TR/epub-33/#sec-media-overlays-structure

If I understand well with a <par> element you can also identify subsets of a sentence or non-textual elements (images, etc.). Maybe it's just a translation misunderstanding: in Italian sentence and phrase are the same thing.

**Comment by mattgarrish** [comment]
Technically a phrase is a part of a sentence. See for example https://dictionary.cambridge.org/dictionary/english/phrase

But a `par` could be many things, as you say. It could represent a word, a phrase, a sentence, or even a paragraph or more of text. It could identify an audio/video element to initiate, or it could be an image to voice the alt text for. It all depends on what the text and optional audio elements reference.

Any thoughts on how we might rephrase this @marisademeglio ?

**Comment by avneeshsingh** [comment]
Historically "phrase" comes from DAISY specifications.
It would be good to clarify somewhere in Media Overlays specs that audio can be synchronized with phrase, sentence, chunk of text like a paragraph or an image.

**Comment by gregoriopellegrino** [comment]
It seems to me that it is indicated further on, but maybe specifying in this section will help.

**Comment by marisademeglio** [comment]
Ok good idea, we can remove the idea of "phrase" from the normative text and instead say that a `par` represents a segment of content within a document. Is there a more elegant way to put that though? 

We can also emphasize some common practices in an informative example, e.g. to point out that a `par` is typically a relatively short piece of content such as a sentence or an image; and also that a sequence of `par`s tends to represent contiguous segments within a single document. 

Just like how for the navigation document, we don't say that list items are for linking to chapters, but in the examples, we refer to chapters and sections.
