### ISSUE TITLE
[EPUB 3.3] [suggestion] Move note about epub:type and ARIA role

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1740]
Perhaps it might make sense to anticipate the note about the difference between epub:type and ARIA role from [C.2 The epub:type Attribute](https://www.w3.org/TR/epub-33/#sec-epub-type-attribute) to [C.1 Introduction](https://www.w3.org/TR/epub-33/#sec-structural-semantics-intro)

**Comment by mattgarrish** [comment]
My concern with moving it to the intro is that people tend to skip introductions. The links to the `epub:type` attribute definition in the body will also go to C.2, so having it in that section ensures the note has the widest visibility.

I don't like the placement of it in C.2 right now, though. It might be better placed right after the definition table.

**Comment by iherman** [comment]
@gregoriopellegrino would you close this if you are satisfied?

**Comment by gregoriopellegrino** [comment]
What about writing it twice, or at least mention in C.1 with a link to the note in C.2?

The Latins said "repetita iuvant" (repeating does good) 😄
