### ISSUE TITLE
[EPUB 3.3 RS] [question] Relationship to HTML

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1770]
The specifications say:

> This specification does not require EPUB Reading Systems to support scripting, HTML forms or the HTML DOM. Reading Systems conformant with this specification are only expected to be able to process a conforming EPUB Content Document. As support for scripting and HTML forms is not compulsory, a conformant Reading System may not be a fully-conformant HTML user agent. (https://www.w3.org/TR/epub-rs-33/#rel)

I wonder: can not supporting HTML DOM create problems for accessibility? Maybe for ARIA attributes? Maybe HTML DOM would need to be supported if the application has a viewport?

**Comment by iherman** [comment]
> I wonder: can not supporting HTML DOM create problems for accessibility? Maybe for ARIA attributes? 

In theory, a reading system is free to define its own way of handling the HTML content which is _not_ replicating the DOM. I agree that is a very remote possibility, and probably it would be a highly incomplete reading system with accessibility issues.

I guess what we are really saying here is that the RS specification does not dictate any specific implementation approach, nor does it define conformance in terms of a DOM. Testing means testing the visible effect of rendering.

**Comment by mattgarrish** [comment]
Ya, this was about flexibility of implementation. You don't necessarily need the DOM to expose a document to the accessibility APIs, but it probably is a whole lot simpler for web content.

If there's ever a successor of UAAG, that's probably where a requirement like this would belong.

**Comment by gregoriopellegrino** [comment]
Perhaps we could insert a note saying that regardless of technology choices, developers should consider not only the visual rendering of content, but also semantic and accessibility information.

What do you think? Too much?

**Comment by mattgarrish** [comment]
Maybe we could mention it in the accessibility section? We already note UAAG there.

Add another bullet about properly exposing publications to accessibility APIs, perhaps?
