### ISSUE TITLE
[EPUB 3.3 RS] [question] Internationalization

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1771]
The specification says that Reading Systems must process the primary attribute for the language of the content (https://www.w3.org/TR/epub-rs-33/#sec-epub-rs-i18n).

It might make sense to point out that the language of individual parts (words, sentences, paragraphs) is also important, especially for accessibility?

**Comment by iherman** [comment]
Wouldn't that mean repeating definitions and specifications from the HTML/SVG/EPUB 3.3 Content recommendations? We should avoid doing that, it is a very slippery slope in my view, and would easily bloat the document.

**Comment by mattgarrish** [comment]
Can't this be achieved by striking "primary" from this sentence:

> A Reading System MUST process, for all Publication Resources, the attributes that set the <strike>primary</strike> language for the documents' contents, when applicable.

I think the confusion here is that "primary" seems to suggest the RS can stop processing after finding the first language defined.

**Comment by gregoriopellegrino** [comment]
Good for me!
