### ISSUE TITLE
[EPUB 3.3 RS] [suggestion] Unique Identifier

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1772]
The specs say: 

> Determining whether two EPUB Publications with the same Unique Identifier represent different versions of the same publication, or different publications, may require inspecting other metadata, such as the titles or authors. (https://www.w3.org/TR/epub-rs-33/#sec-pkg-doc-pub-identifiers)

Perhaps the date metadata can also be flagged as significant in distinguishing a publication, in particular the [last modified date](https://www.w3.org/TR/epub-33/#sec-metadata-last-modified).

**Comment by OriKuttner** [comment]
Last modification servers as version identifier.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by mattgarrish** [comment]
We dropped discussion of the release identifier because it's not proven useful in practice. It can be listed as another suggestion, but I don't see a benefit in trying to resurrect the concept beyond that.
