### ISSUE TITLE
[EPUB 3.3 RS] [question] Prevent scripts from invoking the audio/video playback

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1777]
In the specifications I find the point:

> Prevent scripts embedded within the EPUB Content Document from invoking the JavaScript audio/video playback API (i.e., authored as part of the default behavior). (https://www.w3.org/TR/epub-rs-33/#sec-embedded-media)

I understand the request, but it's not very clear to me how developers can implement this (I can't think of a pure JavaScript solution, but I'm not an expert in the field).

Perhaps it makes sense to flag this in the EPUB 3.3 specification for content producers? That is, that those who create an EPUB with MOs that also contain audio and video must not include JavaScript that invokes this multimedia content.

**Comment by dauwhe** [comment]
I believe this is a requirement for reading systems rather than developers. Autoplay video etc. would make it impossible for media overlays to function, so it is the responsibility of the reading system to block this. They are not limited to a pure JS solution, for example :)

**Comment by mattgarrish** [comment]
> Perhaps it makes sense to flag this in the EPUB 3.3 specification for content producers?

We do recommend not doing this in the audio/video section:

> EPUB Creators SHOULD avoid using scripts to control playback of referenced embedded EPUB Content Document media, as this might conflict with Media Overlays playback behavior.

https://w3c.github.io/epub-specs/epub33/core/#sec-emb-audio-video

**Comment by gregoriopellegrino** [comment]
Fine
