### ISSUE TITLE
[EPUB 3.3 RS] [suggestion] Introduction to Accessibility

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1778]
The first paragraph says:

> The primary focus of this specification is on how to process and render EPUB Publications and Reading Systems generally have little influence over the accessibility of the underlying content that they render (i.e., the accessibility is determined both by the capabilities of the technologies used and how they are taken advantage of by EPUB Creators). So long as Reading Systems fully and accurately support EPUB's required technologies, there should not be issues in the content rendering itself. (https://www.w3.org/TR/epub-rs-33/#sec-accessibility)

I think this is correct as long as the reading solution uses a webview to display the content, if other techniques are used it is likely that semantic, language, alternative text attributes could be ignored when the content is presented to the user.

**Comment by iherman** [comment]
This is the same issue as what you referred to in #1770, right? In both cases, what we are saying is that EPUB is so much rooted in HTML & friends, that, in practice, an RS ought to be a full HTML & CSS & SVG &... rendering engine. But we do not dictate what implementation technique is to be used exactly.

I guess I am not sure what changes this leads to in the RS text...

**Comment by dauwhe** [comment]
> I think this is correct as long as the reading solution uses a webview to display the content, if other techniques are used it is likely that semantic, language, alternative text attributes could be ignored when the content is presented to the user.

The spec says "…fully and accurately support EPUB's required technologies". If a reading system tries to implement EPUB without a web view, and fails to take accessibility into account, then it is by definition not fully and accurately supporting EPUB's required technologies. 

> I guess I am not sure what changes this leads to in the RS text...

I have the same question. I feel our requirement is worded accurately.

**Comment by mattgarrish** [comment]
I'll add to the chorus here and only add that if you "fully and accurately" support rendering in some other way, wouldn't there equally be no accessibility issues? It's not a webview itself that makes content accessible but how the content is supported and exposed.

**Comment by gregoriopellegrino** [comment]
Ok, I understand.

One question remains for me: what are the "required technologies"? Are they defined in the specifications?

**Comment by iherman** [comment]
> One question remains for me: what are the "required technologies"? Are they defined in the specifications?

Hm. It may indeed be seen a bit sloppy... I would think the right wording might be something like

> So long as Reading Systems fully and accurately support EPUB's documents as defined in [[EPUB-33]]…

is probably more precise. That being said, this text is in a non-normative section, which means that a bit of sloppiness may be o.k. if it makes the content a bit more readable...

**Comment by dauwhe** [comment]
> One question remains for me: what are the "required technologies"? Are they defined in the specifications?

I would say yes, the specification is largely devoted to describing the required technologies of HTML, XML, etc. Given this is non-normative as Ivan mentions, I think we can close this issue.
