### ISSUE TITLE
How to identify WCAG A or AA with conformsto

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/epub-specs#1791]
In conformance reporting section there is a note:
https://w3c.github.io/epub-specs/epub33/a11y/index.html#sec-conf-reporting-pub

NOTE
An EPUB Publication that only meets WCAG conformance requirements (i.e., does not fully conform to this specification) can use a WCAG conformance URL (e.g., "https://www.w3.org/TR/WCAG21/" for [WCAG21]) with the confomsTo property.

It works for conveying the conformance to WCAG, but how can it further convey the level of conformance i.e. A, AA or AAA.
Also, there is a typo in conformsto in the text copied above.

**Comment by mattgarrish** [comment]
> how can it further convey the level of conformance i.e. A, AA or AAA

It can't, at least not until the new identifiers we requested for the three levels are added in WCAG 2.2. You could write the level in the summary, but otherwise it's not a problem we can solve.

**Comment by mattgarrish** [comment]
If we add that WCAG doesn't provide a mechanism for identifying the level in the URL and it would have to be specified in the summary, is that enough to close this @avneeshsingh ?

**Comment by avneeshsingh** [comment]
Is there a WCAG issue that we can point to, mentioning that this is work in progress.

**Comment by mattgarrish** [comment]
I requested IDs in https://github.com/w3c/wcag/issues/1575 to be able to reference the specific levels from our specification, and it's been implemented for 2.2, but they're not an official way of citing WCAG. They also follow the pattern "cc1_A", so they're not terribly meaningful.

Is this a problem we need to solve given that the author has chosen not to conform to our specification?

**Comment by mattgarrish** [comment]
We may want to consider removing this note entirely. It was sort of workable in the 1.0 version because we were only endorsing a specific version of WCAG, but why are we listing the 1.1 URL when 1.0 and soon 1.2 can be conformed to?

We're also not using URLs anymore, so it's odd to suggest a URL as an alternative. It probably leads to misapplication in a meta element instead of a link.
