### ISSUE TITLE
Rendition:flow diagrams have identical captions but different images

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1878]
In [D.4.1.1](https://w3c.github.io/epub-specs/epub33/core/#flow), Figure 1 and Figure 2 have identical captions but a different image:

> Figure 1 Rendering of an EPUB publication with a single spine item, and with the `rendition:flow` set to `paginated`.

> Figure 2 Rendering of an EPUB publication with a single spine item, and with the `rendition:flow` set to `paginated`.

What distinction are we trying to illustrate here? Is figure 2 supposed to be for multiple spine items?

**Comment by mattgarrish** [comment]
> Is figure 2 supposed to be for multiple spine items?

Ya, that looks like a possible copy-paste typo to me. The second figure is clearly showing multiple spine items, which the alt text confirms by talking about progression across documents.

**Comment by iherman** [comment]
Yep, that was a bug created by yours truly. See #1886 

Thanks!

**Comment by iherman** [comment]
Actually, the caption for the last figure was also wrong...
