### ISSUE TITLE
[EPUB Accessibility 1.1] refines examples and EPUB 2

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#2042]
In the document examples [6](https://www.w3.org/TR/epub-a11y-11/#example-expressing-the-evaluation-date), [7](https://www.w3.org/TR/epub-a11y-11/#example-expressing-a-basic-credential) and [8](https://www.w3.org/TR/epub-a11y-11/#example-a-remotely-hosted-accessibility-report) show metadata with the `refines` attribute. This attribute does not seem to be compatible with EPUB 2. What to do in this case?

Still many publications in EPUB 2 are available in the market (some even fairly affordable) and it is not certain that they will be upgraded to EPUB 3 soon.

For `a11y:certifierCredential` and `a11y:certifierReport` I don't see big problems (if there are not more than one in a file), but for the certication date (`dcterms:date`) having the metadata without `refines` be very ambiguous. Is there another way? May we add a note to use the example only in EPUB 3?

Do we put a note for all examples?

**Comment by mattgarrish** [comment]
There's nothing we can do to work around it. You can't structure the data, or chain it like in EPUB 3, so you have to live with ambiguities.

It's not a unique problem for the accessibility metadata, so I don't know that we need to call it out. I expect anyone trying to process EPUB 2 metadata is aware of the flaws. A human reading it, on the other hand, will figure out the association by proximity of the statements.

**Comment by mattgarrish** [comment]
Maybe we can note this in the "application to older versions" section rather than put notes everywhere that epub 2 metadata is not very expressive.
