### ISSUE TITLE
OPF 2.0.1 references dtb:id

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#237]
```
OPF 2.0.1, s. 2.4.2, seventh bullet:

The list of required metadata provided in 
http://www.niso.org/workrooms/daisy/Z39-86-2005.html#NavMeta does not apply to 
EPUB; the only required meta is that which contains a content reference to the 
OPF unique ID. For backwards compatibility reasons, the value of the name of 
that meta remains dtb:id

This should be "dtb:uid" as there is no "dtb:id" property in DAISY 3.
```

Original issue reported on code.google.com by `mgarrish` on 17 Aug 2012 at 4:36

**Comment by dauwhe** [comment]
I see two possibilities: just close saying we won't fix this, or publish OPF 2.0.2 with the change. There doesn't seem to be a mechanism for errata in IDPF procedures. Are there other options?

**Comment by mattgarrish** [comment]
Can we add an errata link without doing a new revision @mgylling ?

It would be nice to leave a record of it, but I knew this issue was destined to rot on the vine when I opened it.

**Comment by mattgarrish** [comment]
I guess I'll just close this off as won't fix.

One person stumbled on it in almost ten years of epub 2's existence, and epubcheck already does the right thing.
