### ISSUE TITLE
define scope of search

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#298]
```
from Index WG (wish list not essential): Enable definition of scope of search 
(limit to one content document, index, etc.)
```

Original issue reported on code.google.com by `trsieg...@gmail.com` on 8 Mar 2013 at 5:27

**Comment by mattgarrish** [comment]
@TzviyaSiegman is this relevant anymore? Is the request to add something to the core specs about RS search functionality? If so, that's probably out of scope.

**Comment by TzviyaSiegman** [comment]
@mattgarrish this goes back to index WG hopes and dreams. It is out of scope.
