### ISSUE TITLE
[iso-part1-#48] Replace "author" with another term

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#401]
```
Issue:

Can we use a different term instead of “Author” as this is a public 
document and seems to lean on self-publishing?

Referenced Section:

https://epub-revision.googlecode.com/svn/trunk/build/301/spec/epub30-overview.ht
ml#sec-accessibility

ISO Suggested Solution:

Replace “author” with “creator” or “vendor”

```

Original issue reported on code.google.com by `mgarrish` on 17 Oct 2013 at 2:29

**Comment by mattgarrish** [comment]
Reopening as we deferred a decision on this in 3.0.1, so technically the issue should have stayed open.

I don't see that we should address this in 3.1 as the term is too entrenched in the epub 3.x specs, but it's an issue we return to for epub 4 (and possibly the web friendly format).

**Comment by mattgarrish** [comment]
Suggest we defer this again. Will require too many changes to too many specifications for a 3.x revision.

**Comment by mattgarrish** [comment]
Closing this as something we're never destined to change in 3.x. This can be taken up for EPUB 4, but author is also common w3c terminology.
