### ISSUE TITLE
Nav doc allows for empty sub-lists

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#464]
```
There does not seem to be a prohibition on empty lists in the nav doc. For 
instance, this is legal:

<ol><li><span>Entry</span><ol></ol></li></ol>

It's not clear what the correct behavior is in this case - there are no 
sub-items for the text "Entry" to be the heading for. I have specifically seen 
it in this (entirely legal) case:

<ol><li><span><a href="...">Entry</a></span><ol></ol></li></ol>

It *looks* like whoever made this thought the anchor needed to be in a span, 
but then epub check (or something) complained that it was illegal to have a 
span with no ol after it, so they added an empty ol. This looks like a simple 
misunderstanding, but it leads to a very confusing case for developers. Since 
list items already can not be empty, nor can anchors or spans, it seems like 
adding a requirement for lists themselves to have at least one item would make 
sense. This would at least make the expected implementation clear (if 
unexpected for the author).

```

Original issue reported on code.google.com by `d...@google.com` on 20 Aug 2014 at 9:54

**Comment by TzviyaSiegman** [comment]
It would be helpful to allow <span>s (or perhaps other tags) in the nav toc, but the current allowed construct is rather inflexible and assumes that all text in a TOC is part of the list. I am looking for a way to include author information in some TOCs, as in the following (invalid) item:
<li><a href="chapter.xhtml#fundamentals">Fundamentals</a><span>by Jane Doe</span></li>
I see many books with contributed chapters, and it would be useful to be able to id the author in the TOC. I think it would be OK for the <span> to be ignored by widgets and displayed in the rendered TOC. This will allow for including pieces of information in the TOC that are neither leaf nor branch.

**Comment by mattgarrish** [comment]
Proposed Solution:

Update to require at least one list item.
