### ISSUE TITLE
proposal: grayscale reinterpreted as "foreground-scale"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#466]
```
Pretty much any ebook with grayscale images needs the ability to request that 
those images be reinterpreted as "foreground-scale." I.e. it needs the ability 
to have its grayscale images match the current foreground/background color 
scheme for text.

This would be similar to setting fill=currentColor for an SVG element.

I describe the feature at greater length in the following blog post:

http://dencklatronic.blogspot.com/2014/09/the-web-needs-bitonal-images.html

Although this feature could, and perhaps should, be implemented in HTML, CSS, 
or in an image format, this feature is more sorely needed in the EPUB context 
than in the general web context.

The reason it is more needed in EPUB is that only in the EPUB context are 
user-selected foreground/background color schemes so important.

Note: I've already proposed this feature on the IDPF forum:

http://idpf.org/forum/topic-1789

but I'm proposing this feature here as well based on the forum suggestion by 
Matt Garish.

```

Original issue reported on code.google.com by `Ben.Denc...@gmail.com` on 7 Oct 2014 at 7:15

**Comment by mattgarrish** [comment]
Given the current and future goal of alignment with the open web platform, recommend we close this issue as rejected. If this feature is needed, it needs to be advanced in W3C.

**Comment by iherman** [comment]
This should be brought to the CSS WG (I presume), via the DPUB IG at W3C. Indeed, the DPUB IG collects use cases for the CSS WG of this sort... (see, eg, [1])

[1] https://www.w3.org/TR/dpub-css-priorities/

/Cc @dauwhe

**Comment by bdenckla** [comment]
Based on @iherman's suggestion above, I made my inkscale proposal at https://lists.w3.org/Archives/Public/public-digipub/2016Jul/0000.html.

My hopes are not high though... things seem pretty dead on that list. My post was the first in about 3 months.
