### ISSUE TITLE
Apple iBooks display-options orientation *lock*

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#477]
```
http://www.idpf.org/epub/fxl/#mappings

In the "Apple Fixed-Layout" section, "orientation (landscape-only | 
portrait-only | none)" should be "orientation-lock".
```

Original issue reported on code.google.com by `daniel.weck` on 11 Nov 2014 at 9:00

**Comment by mattgarrish** [comment]
Proposed Solution:

Fix as noted.

**Comment by mattgarrish** [comment]
Closing this as won't fix.

The FXL note is marked as superseded, and we didn't port the mapping table forward as it was only intended for early transition.
