### ISSUE TITLE
Add data-nav to item properties vocab

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#487]
```
The region-based navigation spec added the "data-nav" document type, but the 
property for identifying in the manifest is currently only defined in that spec.

The term should be defined in the item properties vocab in Publications with a 
pointer to the region-based spec.
```

Original issue reported on code.google.com by `mgarrish` on 15 Dec 2014 at 3:14

**Comment by mgylling** [comment]
Proposed resolution: do not add data-nav at this time as AHL specs are not being referenced from 3.1. Having data-nav defined only in RBN is good enough in the interim.

**Comment by mattgarrish** [comment]
I don't see the need to keep this issue open anymore. As originally proposed by Markus, the semantic is fine defined where it is. I don't see this becoming part of the core.
