### ISSUE TITLE
repeated landmarks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#491]
```
There is nothing in the spec to suggest that the same landmark (same 
semantic/same href) should not be repeated. As a result, it's been noted that 
epubcheck doesn't generate an error when this happens.

Since repeated landmarks serve no purpose, and if the list were presented to 
the reader to choose from it would lead to confusion, we should probably note 
it as frowned upon in the spec.
```

Original issue reported on code.google.com by `mgarrish` on 22 Jan 2015 at 6:32

**Comment by mattgarrish** [comment]
Suggest we add the following paragraph after the example:

The landmarks nav MUST NOT include multiple entries for the same resource, or fragment thereof, with the same relationship.

**Comment by mgylling** [comment]
Proposed resolution: add the following text after the example in the [landmarks](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-nav-def-types-landmarks) section:

"The landmarks nav MUST NOT include multiple entries for the same resource, or fragment thereof, with the same relationship."

Note that this is potentially a backwards incompatible change. But the landmarks nav was never intended to contain semantic duplicates.

**Comment by mattgarrish** [comment]
Added restriction against duplicate landmarks. See the second last paragraph in the definition:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#sec-nav-landmarks

Please close this issue if no other changes are required.
