### ISSUE TITLE
drop rs support requirement level for multiple rendition publications

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#501]
```
Second concern from the meeting was that "must" support for the spec is 
problematic, since the spec is not yet a recommendation.
```

Original issue reported on code.google.com by `mgarrish` on 26 Feb 2015 at 9:00

**Comment by mattgarrish** [comment]
New FXL accessibility requirements were added and requirement for support for multiple renditions reduced to a should as discussed on 3/12 and 3/19 telecons.
