### ISSUE TITLE
are all renditions required to conform to edupub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#523]
```
Is it valid to have one edupub-conformant rendition packaged with a regular 
epub 3 rendition?

Another example: the inaccessible fxl requirement to include an "accessible 
version" doesn't say the accessible version has to conform to edupub.
```

Original issue reported on code.google.com by `mgarrish` on 14 Mar 2015 at 2:11

**Comment by mattgarrish** [comment]
Added requirement that all renditions conform to reflowable or fxl requirements as resolved on the 3/26 telecon.

Ability to include inaccessible renditions was removed when support for multiple-rendition publications was reduced to should.
