### ISSUE TITLE
glossdef usage context clarity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#525]
```
It's been noted that the current word is confusing. Missing "is" in first 
sentence.
```

Original issue reported on code.google.com by `mgarrish` on 14 Mar 2015 at 3:17

**Comment by mattgarrish** [comment]
This issue may be obsoleted depending on whether implied contexts are removed.

**Comment by mattgarrish** [comment]
Need to review removing as part of the ARIA harmonization.

**Comment by TzviyaSiegman** [comment]
See https://github.com/IDPF/epub-revision/issues/526, similar wording recommendation

**Comment by TzviyaSiegman** [comment]
Recommendation: Change usage context for glossdef to Glossdef should be used only when the element to which it is applied is NOT a <dd> child of <dl epub:type="glossary">, in which case it is implicit.

**Comment by mattgarrish** [comment]
Term has been updated per glossterm:
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#glossdef

Please close this issue if no other changes are necessary.
