### ISSUE TITLE
rearnotes/footnotes mismatch between specs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#528]
```
We added implied contexts for edupub, but kept the original usage contexts from 
the SSV.

As a result, we mentioned ol/ul as implying footnote/rearnote, but the usage 
context for footnotes/rearnotes only suggeests using on sectioning content.
```

Original issue reported on code.google.com by `mgarrish` on 14 Mar 2015 at 3:41

**Comment by mattgarrish** [comment]
Now that we've removed the implied contexts, is it still desirable to apply footnotes/endnotes directly to a list, or do we preserve the original sectioning element context?

Granted, these aren't hard rules, so you could apply them to lists, but wondering if it's a practice we want to call out?

If so, I believe there are a number of other plural forms only list section/sectioning content, so we should consider if they all need updating to add grouping content?

**Comment by mattgarrish** [comment]
Closing as this was addressed by removing the implied contexts.

**Comment by mattgarrish** [comment]
Closing this issue as resolved on the 2016-02-04 telecon.

The change to ARIA role impacts the use of these roles on lists, and it's not clear if such usage is considered detrimental to AT, so leaving the usage context unchanged.
