### ISSUE TITLE
cannot set image size by relative size ( em, % )

### ISSUE THREAD

**Issue by toshiakikoike** [w3c/epub-specs#536]
When I wish to display the image by relative size, for example, width 12em, there are some problems.

style1:
width:12em;height:auto; max-width:100%; max-height:100%;
If ICB's height is short, do not keep aspect retio.

style2:
width:12em;height:37.6em;
If ICB's height is short, the image out of ICB. (depend on RS. On Readium, the same as style1.)

style3:
width:auto;height:auto;max-width:100%;max-height:100%
keep aspect retio, within ICB, but cannot set width:12em.

sample epub:
https://github.com/toshiakikoike/epub_file/blob/master/imgsz_problem.epub

screeen shot:
<img src="https://raw.githubusercontent.com/toshiakikoike/epub_file/master/imgsz_problem.jpg"/>

**Comment by dauwhe** [comment]
I don't believe this is an EPUB spec issue. As far as I can tell, both reading systems and browsers are doing what you've asked in each of these cases. With a relative unit like the `em`, you can't really know if the viewport is going to be large enough for a 12 x37,6 em image. And so each of these options takes a different approach: [1] distorting the image, [2] keeping the size but not show all of the image, or [3] scale the image proportionally but make it small enough to fit.

Viewport-relative units like `vh` and`vw` may work better for your particular needs.
