### ISSUE TITLE
When is a DO educational?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#550]
In 10.2 we state for DO collections:

In addition to the required metadata defined in [DistributableObjects], each collection must describe its object according to the metadata requirements in 8. Metadata, and include an identifier dc:type element [Publications301] with the value "edupub".

Does this mean that if I embed a DO from another source that wasn't created specifically for edupub that I have to modify its metadata to add a dc:type and accessibility info?

Not sure how to make this make more sense. Reducing to a "should" might avoid errors on DOs not created by the author.

/cc @mgylling

**Comment by BillKasdorf** [comment]
I suggest that we relax the requirement and instead add a Note to this effect:

Note: Care should be taken, when embedding a DO from a non-EDUPUB source into an EDUPUB, that doing so does not make the resulting EDUPUB invalid. It may be necessary to make some modification (perhaps to metadata) to such an external DO to ensure that the EDUPUB is still conformant.

**Comment by mattgarrish** [comment]
Sorry I missed this part of the call today, but what I was going to call out as an example is scriptable components. We fully expect these to be embedded, and they are a kind of DO, but not necessarily made just for edupub content.

For these, we don't expect the person using the ESC to monkey with the metadata just because they're adding to their edupub-compliant epub, right? (We're very silent on what is a valid or invalid ESC for edupub, but that's probably a separate issue.)

Using what you have, what if we keep the requirement but twist it around like so:

To indicate that a Distributable Object conforms to this profile, its collection must describe the object according to the metadata requirements in 8. Metadata and include an identifier dc:type element [Publications301] with the value "edupub".

NOTE
As Distributable Objects are used for many purposes (in both EDUPUB and EPUB content), and not all Distributable Objects are created by the Author, not all will be identified as conforming to the EDUPUB profile. It is the Author's responsibility to ensure that that any Distributable Objects that do not identify as conformant do not invalidate the content.

We lose validation of the metadata, since we can't tell which are supposed to conform, but that was problematic to begin with.

**Comment by BillKasdorf** [comment]
This seems okay to me.

The simple example Markus mentioned on the call yesterday was a DO that is simply an image. While it may not have been created originally as an EDUPUB DO, it does no harm when embedded in an EDUPUB EPUB so it seems excessive to require the recipient (who, in the wording of the spec, is the Author) to modify its metadata. But if I'm reading it correctly, your proposed wording does not actually require that to be done. That is, the statement (prior to the Note) correctly says that _to indicate that it conforms to the profile_ it must have the required metadata (which is correct); but in Markus's example, there is really no need to indicate that it conforms to the profile, and since it does not invalidate the recipient EPUB when embedded, no action needs to be taken in that case to modify the metadata.

Have I got that right?

If so, then +1 to your proposal.

--Bill K

**Comment by mattgarrish** [comment]
Right, same idea. I used ESC as I think we'll see them being made for EPUB but used in EDUPUB, but even something as trivial as an image shouldn't require the person importing the content to rework its metadata simply because it was created outside an EDUPUB context.

What I'm suggesting is that instead of saying all collections must contain the metadata, it becomes a choice. If you want to indicate conformance, here's how you do it, but it's not required.

If that's still a bit nuanced, how about the following (which also replaces the current final paragraph):

To simplify (re)use and integration in workflows, distribution channels and other EDUPUB Publications, a Distributable Object whose content conforms to this profile MAY be identified as such by including in its collection the metadata requirements defined in 8. Metadata plus an identifier dc:type element [Publications301] with the value "edupub".

As Distributable Objects are created and consumed for many purposes, it is not a requirement that all Distributable Objects in a Rendition be identified as conforming to the EDUPUB profile. EPUB Publications conformant with this profile MAY include any other type of Distributable Object provided the resulting Rendition(s) remain conformant to the requirements of this specification.

**Comment by BillKasdorf** [comment]
We're absolutely on the same screen ;-) and I think you've nailed it.--Bill

**Comment by mattgarrish** [comment]
Fixed in the last draft as noted.
