### ISSUE TITLE
metadata does not allow version

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#553]
In the multiple renditions spec, only the unique-identifier and prefix attributes are called out as allowed on the metadata element in the metadata.xml file.

For completeness of expressions and future compatibility, we should not be calling out specific attributes but allow all attributes on the package element to be used on the metadata element.

**Comment by murata2makoto** [comment]
Agree to allow all attributes of the package element.  But what does the version attribute 
mean?  The version of EPUB (e.g., 3.1) or the version of AHL Multiple Renditions (e.g., 1.0)?

**Comment by mattgarrish** [comment]
For consistency, I don't think we should change the attribute. It's important information to know, and it doesn't solve the problem of knowing whether the EPUB conforms to the multiple renditions spec or not (all you potentially know at the point of reading the metadata file is that you have a file type of application/epub+zip). You'd have to infer from there being multiple rootfiles that 1.0 means AHL.

If we need to specify the MR version, I'd rather add a version property into the metadata itself, something like:

&lt;meta property="ahl:version">1.0&lt;/meta>

That way if we intergate later with OCF and no longer need, we can just deprecate/obsolete this property and the EPUB version attibute remains synchronized with the package.

**Comment by mattgarrish** [comment]
As per today's teleconference, no attribute/property will be added.
