### ISSUE TITLE
Ambiguity in interpretation of definition for epubcfi character offset

### ISSUE THREAD

**Issue by mark-buer** [w3c/epub-specs#555]
Hello,
This issue concerns the definition of "Character Offset" from the epubcfi specification.

As present, the [specification states](http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-terminating-char):

> For XML character data, the offset is zero-based and always refers to a position between characters, so 0 means before the first character and a number equal to the total UTF-16 length means after the last character. A character offset value greater than the UTF-16 length of the available text must not be specified.

Searching on the internet, it appears that the term "UTF-16 length" has no universally unambiguous definition.

Since this is a web technology, one can _assume_ (with knowledge of relevant standards) that the intended meaning was _probably_ "UTF-16 code unit length".

I suggest that the wording of the epubcfi specification be altered so as to be explicit about the meaning of offsets and lengths. One such wording might be:

> For XML character data, the offset is zero-based and always refers to a position between characters, so 0 means before the first character and a number equal to the total UTF-16 **_code unit_** length means after the last character. A character offset value greater than the UTF-16 **_code unit_** length of the available text must not be specified.

An alternative would be to defer (and refer) such a definition to other standards.
For two such external definitions, see
[DOM - Living Standard](https://dom.spec.whatwg.org/#concept-CD-data), and
[HTML5 - A vocabulary and associated APIs for HTML and XHTML](http://www.w3.org/TR/html5/infrastructure.html#encoding-terminology).

The epubcfi specification must be unambiguous on this point else interoperability issues may arise.

**Comment by mark-buer** [comment]
Any progress on this?

There is a big difference between the character offsets being defined in terms of UTF-16 code units or in terms of UTF-16 code points. Clarification on this matter would be greatly appreciated.

**Comment by mattgarrish** [comment]
Your thoughts on this @danielweck?

**Comment by iherman** [comment]
I am really not an expert on the matter, just flagging an additional possible reference:

http://www.w3.org/TR/charmod-norm/

(It is still a draft, though)

**Comment by danielweck** [comment]
Thanks for the notification @mattgarrish .

Yes, it is also my understanding that CFI "character offsets" are expressed relative to the number of 16-bits _code units_ within the strings of characters encoded as UTF-16, not in terms of the actual number of _code points_ (which are commonly referred-to as Unicode "characters").

This way, the processing of surrogate pairs (i.e. two 16-bits code units) for code points outside of Unicode BMP (Basic Multilingual Plane) must be explicit (no implicit normalization / conversion), which is compatible with the DOM Ranges API ( http://www.w3.org/TR/DOM-Level-2-Traversal-Range/ranges.html#Level-2-Range-Position-h3 ), and the Javascript String API (e.g. `.length`, `.substr()`, see http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-string-type + http://www.ecma-international.org/ecma-262/6.0/#sec-string-objects, and `.charAt()` http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.charat vs. `.codePointAt()` http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.codepointat ). 

Additional literature on the subject:
https://mathiasbynens.be/notes/javascript-encoding
http://www.2ality.com/2013/09/javascript-unicode.html

Popular library to deal with Unicode in Javascript:
https://github.com/bestiejs/punycode.js#punycodeucs2

In other words, a CFI library (such as Readium's own https://github.com/readium/readium-cfi-js ) effectively treats strings of characters as though they were encoded using `UCS-2` (16-bits / 2-byte Universal Character Set), unaware of sequences of UTF-16 surrogate pairs potentially contained within.
Note that CFI "assertions" for text locations / ranges (i.e. based on the aforementioned CFI character offsets, which are counts of UTF-16 code units) are URI-escaped via UTF-8 encoding. See:
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-text-location
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-epubcfi-escaping

So, back to the proposed specification updates:

http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-terminating-char

> For XML character data, the offset is zero-based and always refers to a position between characters, so 0 means before the first character and a number equal to the total UTF-16 length means after the last character. A character offset value greater than the UTF-16 length of the available text must not be specified.

May I suggest the following edits? (I added a non-normative note)

> In this specification, the definition of an "offset" within XML character data is based on the UTF-16 text encoding, whereby each "character" (Unicode code point) may be represented using a single 16-bit code unit, or two units (surrogate pairs, for Unicode characters outside of BMP / Basic Multilingual Plane) [ http://www.unicode.org ]. A CFI "character offset" is a zero-based number that refers to a position _between_ UTF-16 code units. Here, the "length" of the text is the total count of 16-bit units. Offset zero therefore means _before_ the first 16-bit unit, and a number equal to the "length" of the text means _after_ the last 16-bit unit. An offset value greater than the "length" of the text must not be specified. NOTE: note to implementors: counting the number of text "characters" based on UTF-16 _code units_ (instead of Unicode _code points_) is compatible with the DOM Range model [ http://www.w3.org/TR/DOM-Level-2-Traversal-Range/ranges.html#Level-2-Range-Position-h3 ], and with the ECMA / Javascript String API [ http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-string-type ]. 

Thoughts welcome.
Dan

**Comment by mark-buer** [comment]
@danielweck 
The edits you are suggesting look good.
I think they nicely remove the ambiguity of code-unit vs code-point.
With these changes, there'd be little excuse for someone misunderstanding the spec and generating incompatible paths.

I'm pleased you didn't say "it's code-points!", because that would've really ruined my day (we have a lot of libraries and EPUBCFI range instances that assume the UTF-16 code-unit interpretation).

Thanks.

**Comment by mattgarrish** [comment]
Proposed Solution:

Incorporate Daniel's edits.

**Comment by danielweck** [comment]
@mattgarrish could you please incorporate the proposed prose changes into the editor's draft:
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-terminating-char
Let me know when and I will review.
Many thanks!

**Comment by mattgarrish** [comment]
I've updated the prose as requested in the commit noted above. Please close this issue if no other changes are needed.

**Comment by danielweck** [comment]
Fixed in https://github.com/IDPF/epub-revision/commit/fa803ce4b04ac666b1f9a4df3b2ae02d419510b6

**Comment by tkanai** [comment]
I'm afraid that the change would introduce a backward compatibility issue.

**Comment by danielweck** [comment]
CC @iherman  @azaroth42

Informational follow-up regarding UTF16 code _unit_ vs. Unicode code _point_ (see my complete comment above https://github.com/IDPF/epub-revision/issues/555#issuecomment-144962949 ):

Interestingly, in the W3C "web annotation" selectors specification (editor's draft dated 18 August 2016, see http://w3c.github.io/web-annotation/selector-note/index-respec.html#TextQuoteSelector_def ):

'the selection of the text must be in terms of unicode code points (the "character number"), not in terms of code units (that number expressed using a selected data type). Selections should not start or end in the middle of a grapheme cluster.'

'This Selector describes a range of text by recording the start and end positions of the selection in the stream. Position 0 would be immediately before the first character, position 1 would be immediately before the second character, and so on. The start character is thus included in the list, but the end character is not.'

Side note: is a "grapheme cluster" a Unicode surrogate pair, or a higher-level construct such as Japanese Ruby character annotation? I'm not sure. Anyway, I digress...

So, the W3C spec. differs from EPUB-CFI, and this may eventually need to be investigated in relation to a possible update of "Open Annotation in EPUB" ( http://www.idpf.org/epub/oa/ ).

From a technical perspective, I would have thought that relying on UTF16 code _units_ would facilitate internal processing given the direct compatibility with the DOM Range model ( http://www.w3.org/TR/DOM-Level-2-Traversal-Range/ranges.html#Level-2-Range-Position-h3 ), and with the ECMA / Javascript String API ( http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-string-type ), for example to support surrogate pairs at the low-level encoding layer. But then, as Unicode code _points_ are directly supported by other relevant string processing libraries / browser APIs, maybe this indeed makes more sense in the general Open Web Platform.

Any thoughts?

(for further discussions about W3C Web Annotation, see https://github.com/w3c/web-annotation/issues/350 )

**Comment by murata2makoto** [comment]
Grapheme clusters are defined by [Unicode® Standard Annex 29](http://www.unicode.org/reports/tr29/).  A base character followed by combining characters is a single grapheme clust.er.  An idegraphic character followed by an ideographic variation selector is a grapheme cluster.

**Comment by danielweck** [comment]
Thank you @murata0204
So the conformance rule "selections should not start or end in the middle of a grapheme cluster" would have to be enforced using a specialised Unicode library (e.g. JS Punycode). Anyway, there's more information in the W3C discussion thread, if anybody is interested to follow-up on this: https://github.com/w3c/web-annotation/issues/350
