### ISSUE TITLE
require selection attributes on 2..n rootfile elements?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#556]
The last bullet in 3.5 reads:

If no rendition namespaced attributes are found, move to the preceding rootfile element and continue the evaluation process.

While this makes sense for processing multiple rendition pubs that don't conform to this specification, shouldn't we also state somewhere that only the default rendition's rootfile can be specified without at least one rendition attribute to be conformant with this spec? Right now we only say that container documents may include these attributes.

It seems to run counter to having attributes for selection to not require they be implemented.

/cc @murata0204 @mgylling

**Comment by murata2makoto** [comment]
A proposed solution is available at:

https://github.com/murata0204/epubcheck/commit/0274af749f79727512f8e573d07d4126bd539525

**Comment by mattgarrish** [comment]
Proposed text has been integrated, reducing requirement to "should".
