### ISSUE TITLE
multiple-rendition identifier?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#557]
Somewhat related to the other issue I opened, should we consider a dc:type identifier for the metadata.xml file?

Right now, we don't have a good way of determining whether a publication conforms to this specification. The use of selection attributes would be a strong hint, but it's currently not required that they be set. The presence of the metadata.xml file similarly doesn't equate to implementation of the specification.

Adding something like &lt;dc:type>multiple-renditions&lt;/dc:type> to metadata.xml would remove any ambiguity.

Or is there an expectation that that the MRP spec will be integrated into OCF, and remove having to allow for non-conforming implementations as also valid?

/cc @murata0204 @mgylling

**Comment by mattgarrish** [comment]
Closing this issue, as we are requiring selection attributes now. Remove the ambiguity I was seeing.

**Comment by mattgarrish** [comment]
+1 to integrating.

This issue was more about trying to solve ambiguities on the MRP spec end, which would have been a poor solution. @murata0204 is working on a new schematron that will verify that at least one selection attribute is present on the second and all subsequent rootfile elements. That can be used as a trigger for validation, although it's still unclear if there are multiple renditions and none have selection attributes if the publication represents a broken implementation or a non-conforming one.

**Comment by rdeltour** [comment]
> @murata0204 is working on a new schematron (...). That can be used as a trigger for validation

Unfortunately a schematron report cannot be used directly as a trigger for other validation in EpubCheck, at least in the current state of things.

In v4.0, I systematically enable the MRP checks whenever it is a 3.0 publication _and_ it has multiple OPFs. I know it's not a strict interpretation of the spec, but I had no simple way of "detecting" MRP so I went ahead, assuming non-MR EPUBs with multiple OPFs were not common practice in the real world.

(I know this is the wrong forum too, but it's FYI).

**Comment by mattgarrish** [comment]
Sorry, "that" wasn't a reference to the schematron itself but the inclusion of the selection attributes. If you find them, then the publication can be assumed to conform and you could trigger validation.

It might be dangerous to blanket check based on the presence of multiple rootfiles. It was noted during development of the spec that multiple renditions are already produced in another fashion (I believe in Japan, but I can't remember the context anymore) . That's why the spec treads around requiring conformance and encourages people to move over to this model.

**Comment by rdeltour** [comment]
> "that" wasn't a reference to the schematron itself but the inclusion of the selection attributes.

OK.

> It was noted during development of the spec that multiple renditions are already produced in another fashion

Interesting. I'll see if I can easily add a way to peek-parse these attributes to enable safer MRP detection.

**Comment by murata2makoto** [comment]
Although I modified the Schematron schema for mandating selection attributes, I think 
that it will be clearer if we mandate the verison attribute at the root of metadata.xml.  

If we integrate multiple renditions as part of EPUB 3.1, the version attribute 
should specify "3.1".  If not, the version attribute should specify "1.0", which 
is the version of the multiple rendition specification.
