### ISSUE TITLE
Clarify spec about the presence of `link` resources in the container

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#559]
Section [3.4.9 The `link` element](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-link-elem) says:

> The href attribute of the link element identifies the location of the resource — inclusion of which is optional in the container file.

My take on it is that this was added to allow  `link` to point to remote resources, but that on the other hand any resource represented by a relative URI must:
- resolve to a location **inside** the container
- actually **exist** in the container

A counter use-case might be a scenario where an authoring system uses `link` elements to store locations of authoring-time resources, which are then excluded from the OPF at build time, while keeping the `link` element. I don't believe this is the case in any real-world system, but it's a possible legitimation of missing resources in the OCF.

In any case, the spec s/b clarified IMO.

/cc @mattgarrish @mgylling

**Comment by mattgarrish** [comment]
Maybe I'm not following exactly, but if the resources are to be stripped, why wouldn't the links also be stripped, too? What would be the case for links remaining after the resources are gone?

And if the resources haven't been stripped, then the resources should be present, right?

**Comment by rdeltour** [comment]
> Maybe I'm not following exactly, but if the resources are to be stripped, why wouldn't the links also be stripped, too? What would be the case for links remaining after the resources are gone?

One reason why links wouldn't be stripped w/b if they'd be used in later re-import in the authoring system. But I dunno, it's really just a use case off the top of the mind when searching for a legitimate explanation, with no real-life backing.

As mentioned above, my first interpretation is that the resource _SHOULD_ be declared. IMO that should be what the spec says, but we need to make sure we're true to the original intent and do not reject actual real-world counter cases.

**Comment by mgylling** [comment]
@rdeltour am I reading this right that your request is a statement in the spec that and relative URI in link must resolve to a resource within the container?

**Comment by mattgarrish** [comment]
@rdeltour Can we resolve this by adding a paragraph like the following to the end of "3.3 Relative IRIs for Referencing Other Components" in OCF:

All relative IRI references must resolve to resources within the OCF Abstract Container (i.e., at or below the Root Directory).

http://www.idpf.org/epub/31/spec/epub-ocf.html#sec-container-iri

**Comment by rdeltour** [comment]
@mattgarrish the proposed statement looks good to me, I like the generic aspect of it. 
The "link element" in Packages has been reworded too, so the original ambiguity has been removed.

Btw, this issue may not be the right place –and I'm not up-to-date on the remote resources stuff–, but the Packages doc currently looks odd:

> Linked resources must not be listed in the manifest unless they are also Publication Resources

and right after

> Linked resources that are not Publication Resources are...

**Comment by mattgarrish** [comment]
Yes, I've done some rewriting of that prose in issue #721. That particular section now reads as follows:

Linked resources are not Publication Resources and must not be listed in the manifest. A linked resource may be embedded in a Publication Resource that is listed in the manifest (e.g. an EPUB Content Document could also contain a metadata record serialized as [RDFa11] or [JSON-LD]), in which case it must adhere to Core Media Type requirements.

**Comment by mattgarrish** [comment]
Proposed solution: add paragraph as mentioned above.

**Comment by mattgarrish** [comment]
Paragraph above has been added:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-ocf.html#sec-container-iri

Please close this issue if no other changes are needed.
