### ISSUE TITLE
Require IDX package conformance in EDUPUB?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#560]
EDUPUB only references EPUB Indexes in section [4.4. Structural Semantics](https://docs.google.com/document/d/1jlwEZf7svl04S4wjCCtnGt9JP_VMzMT5U6oymWseqoU/edit#heading=h.n08zwgom1kdv) as the master definition of the index structural semantics terms (for use in `epub:type`).

However, EPUB Indexes also includes a set of conformance criteria for Package Documents on the [identification of an indexes](http://www.idpf.org/epub/idx/epub-indexes.html#s2.3), e.g. to declare which Content Documents make an Index, via the `index` property on OPF `item`s, or via the `index` collection, etc.

If EDUPUB adopts EPUB Indexes, it should probably normatively reference these requirements too.

/cc @mattgarrish @mgylling

**Comment by mattgarrish** [comment]
As resolved on the 2016-02-04 telecon, I've noted that there are identification requirements beyond using the semantics.

The Indexes and Dictionaries semantic sections already had notes to refer to their respective specifications for definitions and usage of the terms, so I appended: ", including Package Document identification requirements required when including xxx".
