### ISSUE TITLE
Allow `collection` and `link` element to be intertwined in a collection?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#562]
The [`collection` content model](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-collection-elem) says `link` elements must follow `collection` child elements.

However, some specs do introduce the notion of significant ordering, in which case it could be useful to allow intertwined `link` and `collection` elements, to represent an ordered tree.
For instance, the IDX group had this in mind to represent an Index content:

``` xml
   <collection role="index">
      <collection role="index-group">
         <link href="subjectIndex-a01.xhtml" />
         <link href="subjectIndex-a02.xhtml" />
         <link href="subjectIndex-a03.xhtml" />
      </collection>
      <link href="subjectIndex-b.xhtml" />
      <collection role="index-group">
         <link href="subjectIndex-c01.xhtml" />
         <link href="subjectIndex-c02.xhtml" />
         <link href="subjectIndex-c03.xhtml" />
      </collection>
      <link href="subjectIndex-d.xhtml" />
      <link href="subjectIndex-e.xhtml" />
      ...
   </collection>
```

This is illegal in the 3.0.1 spec, but maybe this limitation s/b revisited?

**Comment by mattgarrish** [comment]
We had the links following to match the spine idea that initially influenced adding collections.

I don't think the restriction is required, but it would mean that all the existing specs that rely on a package doc-like structure will need validation to enforce that links come after collections. That could be a bit problematic, since the related specs are written relying on the current ordering.

**Comment by mattgarrish** [comment]
Looking at the above, what is it supposed to represent?

It's not a spine, since epub spines don't allow grouping, so is it just a representation of the grouping for machine processing?

If so, why are semantics skipped? Shouldn't it be a collection of objects:

``` html
   <collection role="index">
      <collection role="index-group">
         <link href="subjectIndex-a01.xhtml" />
         <link href="subjectIndex-a02.xhtml" />
         <link href="subjectIndex-a03.xhtml" />
      </collection>
      <collection role="index-group">
         <link href="subjectIndex-b.xhtml" />
      </collection>
      <collection role="index-group">
         <link href="subjectIndex-c01.xhtml" />
         <link href="subjectIndex-c02.xhtml" />
         <link href="subjectIndex-c03.xhtml" />
      </collection>
      <collection role="index-group">
         <link href="subjectIndex-d.xhtml" />
      </collection>
      <collection role="index-group">
         <link href="subjectIndex-e.xhtml" />
      </collection>
      ...
   </collection>
```

**Comment by rdeltour** [comment]
Yeah TBH I don't remember the rationale for ex 40. The idea was probably to save a few elements with implicit semantics, but on second read I believe using explicit `index-group` makes more sense (it's also how I suggested to fix #561).

**Comment by TzviyaSiegman** [comment]
@rdeltour and @mattgarrish is this still relevant? Please clarify if it is.

**Comment by mattgarrish** [comment]
The current content model assumes package document-like uses for collection. If we want to leave it as a free-form extension point, we should change to allow interleaving.

But if we do that, we'd have to update all the specifications that rely on the restricted content model. For that pain of implementing alone, I'd vote to just leave it as is.

**Comment by rdeltour** [comment]
I agree with @mattgarrish. Given that the current content model seems to be OK for everyone, I'd suggest to leave it as is too. We'll "just" need to fix the invalid example in the _indexes_ spec.

**Comment by mattgarrish** [comment]
I can put an erratum up for the indexes spec. using the example above for now.

**Comment by mgylling** [comment]
Proposed resolution: twofold: 
1) do not change the collection content model at this juncture
2) publish an errata for the indexes spec example 40.

**Comment by mattgarrish** [comment]
Erratum has been published. Closing the issue.
