### ISSUE TITLE
Clarify the rule on OCF resources not declared in Package Documents?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#563]
Strictly speaking, EPUB 3.0.1 says this is allowed (or rather, it doesn't say otherwise). However, people (legitimately IMO) asked that EpubCheck reports that as warnings.

Can the spec try to be clearer on which resource it allows being undeclared? e.g. introduce a safe place to put such resources, like in a top-level directory which doesn't contain a Package Document, and disallow undeclared resources in other locations.

See also the thread ["validation issue with ancillary resources"](https://groups.google.com/forum/#!topic/epub-working-group/68KK1NJMv9E) in the `epub-working-group` mailing list, and also idpf/epubcheck#58

**Comment by mattgarrish** [comment]
Now that we're saying foreign resources are allowed without fallbacks so long as they aren't used in the direct rendering does that make this issue go away?

There's no need to hide a foreign resource to avoid a fallback requirement anymore, in other words, so we should report "other stuff" as warnings by requiring all resources be listed in the manifest unless they have a specific spec exemption somewhere.

It might need to be run past the ESC group, though, as they're using that exemption to hide configuration files, but I don't think they need to do that with this change, either.

**Comment by mgylling** [comment]
@rdeltour: in addition to the changes Matt reference above, we also have a [suggestion for a property](https://docs.google.com/document/d/1pi-ZrhJVySiy8EF90kB6wVtnZtQGWgNXS4lcdzMg-DY/edit#bookmark=id.win3lhhl55ht) to help EpubCheck distinguish between intentional and non-intentional files in the package.

**Comment by mattgarrish** [comment]
Closing this issue as the working group resolved on the July 6 call not to change the rules but that epubcheck should be changed to only emit a info message about resources that are not in the manifest, linked or "manifest free" (rendition mapping doc).
