### ISSUE TITLE
Make Multiple Renditions built-in the OCF spec in 3.1?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#566]
See also #557

**Comment by murata2makoto** [comment]
Integration will makes specification development easier.  But I have mixed 
feeling here.  We might make the bar too high or make some important 
features optional (i.e., they do not have to be supported).  But publishing 
a separate specification has the same effects.

**Comment by mattgarrish** [comment]
Closing this as a duplicate, as issue #635 blanket addresses all the modular specs.
