### ISSUE TITLE
Version attribute in the rendition mapping document

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#568]
EPUB Multiple-Rendition Publications 1.0 introduces a new document for representing the mapping of renditions.  But there are no mechanisms for specifying the version of the EPUB Multiple-Rendition Publications specification.  AFAIK, IDPF has introduced a version attribute for all such additional XML documents.

**Comment by mattgarrish** [comment]
We kept the ability to include meta tags so as not to prevent the inclusion of metadata about the file. We could require a version be set easily enough that way.

**Comment by mattgarrish** [comment]
"version" has already been logged in the whatwg wiki for web applications. It might be better to use a name that is unlikely to ever cause conflict, even though the mapping document is technically never  going to be rendered as html. For example, a clearer indicator might be:

&lt;meta name="mapping-doc" content="1.0"/>

/cc @mgylling

**Comment by mattgarrish** [comment]
After discussion, we've decided to use the name "epub.multiple.renditions.version".
