### ISSUE TITLE
Deprecate "rendition:spread" value "portrait"

### ISSUE THREAD

**Issue by GarthConboy** [w3c/epub-specs#570]
I can't see any cases where synthetic spreads would make sense in portrait only.

Seems as though "none", "both", and "landscape" are the only rational choices.

There is some implementation burden and symmetry just for that sake is likely not warranted.

**Comment by dauwhe** [comment]
One thing that came up in the original discussions is that there are some print books that are very tall and narrow (Zagats, wine guides, etc.) and that a synthetic spread could naturally fit on a portrait device (especially one with a 4:3 ratio).

**Comment by GarthConboy** [comment]
Though, for the likes of Zagats, the logical setting would be "both" -- I don't think that's a case for portrait only.  Agree?

**Comment by GarthConboy** [comment]
Proposed resolution: deprecate "portrait" value, leaving "none", "both", and "landscape" as the valid values.

**Comment by mattgarrish** [comment]
Removed portrait from the list of allowed values[1] and added as deprecated in the appendix.[2] Also removed rendition:spread-portrait from allowed spine overrides.[3]

The rendition vocabulary has been similarly updated to note the value[4] and property[5] are deprecated.

Please review and close if no further changes are needed.

[1] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#fxl-property-spread-values
[2] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#fxl-property-spread-portrait
[3] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#fxl-property-spread-overrides
[4] https://idpf.github.io/epub-vocabs/rendition/#sec-spread
[5] https://idpf.github.io/epub-vocabs/rendition/#sec-spread-portrait

**Comment by GarthConboy** [comment]
LGTM
