### ISSUE TITLE
clarify metadata for embedded previews

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#571]
The specification currently doesn't indicate where the metadata is obtained.

Since distributable objects and scriptable components, which also use collections, require metadata to be included in the collection, it would probably be helpful to indicate in section 3.6 that for previews the RS is expected to reuse what is in the package metadata section, except for the identifier.

Otherwise, we have a requirement to include a different identifier in collection metadata but no clear statement that that doesn't mean also duplicate all the metadata there.

/cc @murata0204 @mgylling

**Comment by murata2makoto** [comment]
Should we go further?  At least, we have to copy the prefix attribute of 
the package element.

Here is a list of more actions.

Copying the version attribute of the package element, if any.
Not copying the unique-identifier attribute
Copying the prefix attribute of the package element, if any
Copying the xml:lang and dir attribute of the collection element, if any
Copying the id attribute of the collection element, if any
Copying the metadata elements of the collection element, if any
Creating a manifest from the collection having role="manifest"
Creating a spine from the link child elements of the collection element having role="preview""
Copying collection elements not having  role="manifest"

**Comment by mattgarrish** [comment]
Maybe we could leverage the distributable object spec, since it defines a lot of this already, but in terms of creating from the collection's metadata.

**Comment by mattgarrish** [comment]
Added bullet indicating metadata is extracted from package and pointer to DO for details of creating a packaged epub from a collection as discussed on the call today.
