### ISSUE TITLE
Explicitly disallow hyperlinks to local non-Content Doc resources?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#572]
This issue is about hyperlinks in Content Documents pointing to non-Content Doc resources, e.g.:

``` xml
<a href="images/foo.png">see my image</a>
```

The [XHTML content conformance section](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-conf-content) does **not** forbid it.

However, such hyperlinks might be _considered harmful_™ since an RS is not expected to be able to directly render an out-of-spine resource. Is it a spec oversight?

Note that the Nav Doc spec does explicitly [restrict `a` elements relative `href` to point to Content Documents](http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#confreq-nav-a-href). The question is whether this restriction should actually apply to all hyperlinks.

I believe there is at least an ambiguity that should be made explicit. If the intent is to disallow it, it must be said explicitly ; if the intent is to allow it, an informative note would be welcome.

**Comment by mattgarrish** [comment]
But as long as we have manifest fallbacks you can point to these resources, right? If the reading system can't handle them it falls back to the epub content document in the fallback chain. So the error is not linking but not including the resource in the spine and having a fallback if they do that.

That's my understanding, at least.

**Comment by mattgarrish** [comment]
Maybe we can make that clearer by changing EPUB Content Documents here to publication resources:

All EPUB Content Documents that are linked to from EPUB Content Documents in the spine must themselves be listed in the spine. Linked documents include documents referenced from the href attribute of a and area elements and scripted links (e.g., using DOM Events and/or form elements).

**Comment by mgylling** [comment]
This issue was made redundant by the fix to 611.
