### ISSUE TITLE
Additional schemas for metadata.xml of multiple renditions

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#573]
epubcheck already uses some schemas for checking restrictions on metadata.xml.
They are  is available at:

https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-metadata-30.nvdl
https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-metadata-30.sch
https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-metadata-30.rnc

These schemas should become a part of Multiple Renditions.

**Comment by mattgarrish** [comment]
Appendix A has been updated to include an informative link to the schema. Please verify the following schema is correct:
http://www.idpf.org/epub/renditions/multiple/schema/mr-metadata.rnc

We are only providing the rnc rules for this release, correct?

**Comment by murata2makoto** [comment]
Correct.  Thanks.
