### ISSUE TITLE
Additional schemas for container.xml of multiple renditions

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#574]
The multiple renditions specification introduces some additional attributes to 
container.xml.  Restrictions on these attributes can be checked by schemas.

There are two approaches however.

1) Integration option 

This option integrates the multiple renditions specification as 
part of 3.1.

This is what epubcheck does now.

We modify ocf-container-30.rnc for introducing selection attributes.
(We might want to reference a schema module selection.rnc from 
ocf-container-30.rnc.)

Furthermore, we modify the validation procedure. Before validating
container.xml, the current procedure removes all elements and
attributes from other namespaces including
http://www.idpf.org/2013/rendition.  But the modified procedure does
not remove elements or attributes in
http://www.idpf.org/2013/rendition.

2) Non-integration option

We cannot modify ocf-container-30.rnc and cannot change the current
validation procedure.

Rather, we have to create ANOTHER top-level schema, and introduce
ANOTHER validation procedure.  This procedure will not remove elements
or attributes in http://www.idpf.org/2013/rendition.  If we use
wildcards heavily in out top-level schema or use NVDL, we can
completely avoid removing foreign elements or attributes.

**Comment by mattgarrish** [comment]
Appendix A has been updated to include an informative link to the schema. Please verify the following schema is correct:
http://www.idpf.org/epub/renditions/multiple/schema/mr-container.rnc

**Comment by murata2makoto** [comment]
Looks good to me.
