### ISSUE TITLE
Keep only meaningful clock formats for MO timings

### ISSUE THREAD

**Issue by pettarin** [w3c/epub-specs#579]
The current EPUB 3 Media Overlays specification allows the author of a MO document to use any timing format from SMIL 3.0: http://www.idpf.org/epub/301/spec/epub-mediaoverlays.html#app-clock-examples

In practice, only two formats seem to be used: `[H+]H:MM:SS[.fraction]` and `s.[fraction]`, e.g. `5:34:31.396` and `12.345`.

In particular, I have never seen a SMIL file with timings like `76.2s`, `7.75h` (!), and `2345ms` (!!).

My concern is that, having to deal with so many formats, including the never-used letter-suffixed ones, is just bringing unnecessary complexity for reading systems developers. Moreover, it slows down the processing time of MO document with hundreds or thousands fragments.

My proposal is: restrict the allowed formats to the two mentioned above: `[d+]d:dd:dd[.d+]` and `d+[.d+]`, where `d` is a digit (`0-9`), which are way faster and easier to process.

See also: https://github.com/readium/readium-js/issues/59

**Comment by danielweck** [comment]
Updated examples link:

http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html#app-clock-examples

```
The following are examples of allowed clock values:

5:34:31.396 = 5 hours, 34 minutes, 31 seconds and 396 milliseconds

124:59:36 = 124 hours, 59 minutes and 36 seconds

0:05:01.2 = 5 minutes, 1 second and 200 milliseconds

0:00:04 = 4 seconds

09:58 = 9 minutes and 58 seconds

00:56.78 = 56 seconds and 780 milliseconds

76.2s = 76.2 seconds = 76 seconds and 200 milliseconds

7.75h = 7.75 hours = 7 hours and 45 minutes

13min = 13 minutes

2345ms = 2345 milliseconds

12.345 = 12 seconds and 345 milliseconds
```

**Comment by danielweck** [comment]
I disagree with the proposal to (effectively) deprecate support for an arbitrary subset of "clock value" syntaxes allowed by the SMIL standard:
https://www.w3.org/TR/SMIL/smil-timing.html#TimingSyntax-Clock-value
This would introduce unnecessary backward compatibility issues (or at best: a lot of confusion) in content that use the explicit time units.

Furthermore, I don't think that string parsing performance is greatly impacted by the time unit syntax, so I don't believe that the case for removing support is strong enough.
Example implementations in Readium:
CPP:
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/media-overlays_smil_utils.h#L39
JS:
https://github.com/readium/readium-js/blob/develop/js/epub-model/smil_document_parser.js#L218

I suggest we defer this issue to EPUB4++, or simply reject as "invalid".

**Comment by mattgarrish** [comment]
The working group reviewed this issue on the June 22 call and agreed with the proposal not to change the list of allowed values.
