### ISSUE TITLE
Clarify landmarks references to nav doc

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#587]
In the example in section 2.2.4.2.3,[1] the landmarks reference the toc in navigation document.

That's fine, but there's an unstated assumption that the navigation document is in the spine in order not to run afoul of the requirement re-added in 3.0.1 for all references to content documents to be in the spine.

Since rendering of the table of contents (or any component in the nav doc) is not required to occur in spine, this unstated requirement can be confusing if you follow the example but don't want to use your nav doc in spine.

I expect the answer is that we should clarify that landmarks must only reference content in the spine, so if you reference a local fragment in the nav doc then the document must be in the spine. But, if that's not required, and you can use landmarks to point at the nav doc even when out-of-spine, then we need to clarify that this is not a violation of the spine requirement.

[1] http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-nav-def-types-landmarks

**Comment by mgylling** [comment]
Proposed resolution: same as for #594:

Change the navigation document section to a) require in-spine content document targets for the toc, page-list and landmarks nav; and b)make clear that no such restriction holds for other navs in this document.

**Comment by mattgarrish** [comment]
Clarified that landmarks nav must reference a top-level content document or fragment therein, which will require the nav doc to be in spine when self-referencing to the toc nav:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#confreq-nav-a-href-default

Please close this issue if no other changes are required.
