### ISSUE TITLE
Clarify if nav doc can reference external resources

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#594]
One of the nav element restrictions reads as follows:

The relative IRI reference provided in the href attribute of the a element must resolve to an EPUB Content Document or fragment therein.

But we don't explicitly mandate that only relative IRIs be used or that they always point to content documents. There are hints to that effect in the prose, but without a clear statement it's open to interpretation whether full IRIs are also allowed.

Including a list of external resource links, for example, seems like a valid use of the nav.

**Comment by iherman** [comment]
+1 to use nav for list of external references.

A more general point: we may want to make it sure that only relative IRI-s are used throughout the content to refer to content document or fragments. That sounds obvious, but may not be if we allow content to be unarchived.

**Comment by mgylling** [comment]
Proposed resolution: same as for #587:

Change the navigation document section to a) require in-spine content document targets for the toc, page-list and landmarks nav; and b)make clear that no such restriction holds for other navs in this document.

**Comment by mattgarrish** [comment]
The nav element restrictions have been updated.

The following sentence that sounded like a restriction to content documents in the container has been reworded: "Each list item ( li ) of the ordered list represents a primary heading, structure or other point of interest within the EPUB Publication". It now reads: "Each list item of the ordered list represents a heading, structure or other item of interest".

The requirements for a element referencing have also been split so that only the spec-defined navs are limited to referencing top-level content documents:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#confreq-nav-a-href

Please close this issue if no other changes are required.
