### ISSUE TITLE
make a statement about html5 extension specifications

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#605]
We don't specifically acknowledge extension specifications; it is implied that the functionality they define is not valid in epub because we only reference the core specification.

But "may" they be used/implemented in epub without formal recognition, for example, or is it strictly forbidden to play around with them? Is it realistic for reading systems to turn off extensions implemented in the browser cores they're built on?

I don't believe we had extensions when we developed 3.0, but some clarity on this would be useful.

/cc @mgylling

**Comment by mgylling** [comment]
We will talk to Chaals about this in the DPUB IG and seek his advice.

**Comment by mattgarrish** [comment]
I was looking at the HTML5 extensions specifications and the wiki links led me back to a citation of this paragraph for justifying them:

When vendor-neutral extensions to this specification are needed, either this specification can be updated accordingly, or an extension specification can be written that overrides the requirements in this specification. When someone applying this specification to their activities decides that they will recognize the requirements of such an extension specification, it becomes an applicable specification.

I hadn't thought of them in this light, but they are vendor neutral and it says we get to decide if we will recognize, so I suppose nothing more is needed. Until we recognize them formally, they aren't a part of epub's implementation of HTML5.

**Comment by mattgarrish** [comment]
But the reason I'm not closing is that it still isn't clear if a reading system, like a browser, can elect to support extensions or whether they are only allowed if the extension is referenced as part of epub and required to be supported by all.

**Comment by mattgarrish** [comment]
Looking back in time, we have precedent for disallowing extension experimentation. The longdesc attribute came up during 3.0.1 and got rejected. But if someone builds a reading system on top of a platform that supports longdesc, it is available regardless of what we say.

What about making this explicit with a note like the following at the beginning of the "HTML5 Extensions" section[1] in content docs:

Note
Although HTML5 allows user agents to support vendor-neutral extensions, unless such extensions are listed in this section they are not supported features of EPUB 3.

This sort of leaves the door open to the reality that they may be available, but won't validate and aren't required to be universally supported.

[1] http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-html-extensions

**Comment by GarthConboy** [comment]
Matt's above seems okay to me.

**Comment by TzviyaSiegman** [comment]
+1

**Comment by mattgarrish** [comment]
As resolved on the July 20 call, the above note has been implemented:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-xhtml-extensions

Please close this issue if no other changes are required.
