### ISSUE TITLE
unclear what the lack of a rights.xml file means

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#628]
The digital rights section makes this statement:[1]

When the rights.xml file is not present, the OCF container provides no information indicating any part of the container is rights governed.

Isn't this a self-evident statement? Is there information somewhere else? If we need to make this statement explicit, can we say it in a more direct fashion, like:

When the rights.xml file is not present, no part of the OCF Abstract Container is rights governed.

[1] http://www.idpf.org/epub/301/spec/epub-ocf.html#sec-container-metainf-rights.xml

**Comment by mattgarrish** [comment]
The digital signatures section has a similar statement:

When the signatures.xml file is not present, the OCF container provides no information indicating any part of the container is digitally signed at the container level. It is possible that digital signing exists within any of the contained Renditions, however.

Is this the missing statement from the rights section, that resources might include their own rights/signatures?

Or are these two statements relics from before we changed ocf to allow only renditions of a publication?

**Comment by mattgarrish** [comment]
Propose updating the rights.xml prose to reflect what is said for signatures:

> When the rights.xml file is not present, the OCF container provides no information indicating any part of the container is rights governed at the container level. It is possible that rights expressions exist within the contained Renditions.

Also recommend removing "any of" and "however" from the last sentence of the digital sig paragraph to improve readability:

> It is possible that digital signing exists with the contained Renditions.

**Comment by mgylling** [comment]
Proposed resolution: update the prose on rights.xml as in Matt's comment just above this. This will align the specs statements re this matter for signatures.xml and rights.xml.

**Comment by mattgarrish** [comment]
The signature prose underwent some proofreading after the issue was opened, so to match the implemented prose reads:

> When the rights.xml file is not present, no part of the container is rights governed at the container level. Rights expressions might exist within the contained Renditions.

https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-ocf.html#sec-container-metainf-rights.xml

Please close this issue if no other changes are required.
