### ISSUE TITLE
Future of linear attribute

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#632]
The working group is currently reviewing the purpose of the linear attribute: whether its use can be clarified/standardized or whether it can be removed from the specification.

A review of the issues is available at:
https://docs.google.com/document/d/1b0jz9jpMGew2qj75m8RHklRi3FwafVRprieUDTzyX0E/edit

**Comment by TzviyaSiegman** [comment]
@mattgarrish Clarify language in spec to remove wording such as "supplementary"

**Comment by mattgarrish** [comment]
Ha, you can't toss this one at me. :)

Assuming this was raised in Chicago, but the meeting notes don't appear to contain any information about what you discussed or resolved. I have no context on which to base any changes.

**Comment by TzviyaSiegman** [comment]
I think this was resolved in Chicago with language tweaking? Are we OK to close @mattgarrish @bradyduga @GarthConboy @dauwhe ?

**Comment by mattgarrish** [comment]
Whatever was discussed/resolved wasn't recorded so nothing has changed since the last draft. I thought we reached a truce last fall, though, so in the interests of shipping 3.1 I'm fine leaving the prose as is.

**Comment by mattgarrish** [comment]
Proposed solution is to change this sentence:

> Note that this specification does not require a presentation for non-linear content; Reading Systems MAY handle non-linear content the same way as linear.

to the following paragraph:

> When rendering an EPUB Publication, a Reading System MAY either suppress non-linear content so that it does not appear in the default reading order, or ignore the linear attribute in order to provide Users access to the entire content of the EPUB Publication. This specification does not mandate which model Reading Systems have to use. A Reading System MAY also provide the option for Users to toggle between the two models.

**Comment by rkwright** [comment]
I think the wording is reasonable.  I am quite concerned though, that by waffling so much on whether and how the reading systems will present non-linear content authors will not know how their content will be presented.  The result, I believe, is that the feature won't be used - which will be a shame, IMO.

**Comment by mattgarrish** [comment]
Closing this issue as resolved on the July 27 call.
