### ISSUE TITLE
unversioned alt-ss and cfi specs

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#634]
These two specifications don't have version numbers in their titles, but they've been updated in each core revision (mostly minor changes). We can reference the recommendations by dated filename of the specification, but shouldn't there be a more reliable way of distinguishing one from another?

We also have generic references to these specifications in the core specs, so if a significant incompatible change, or new feature, were to be added, all the old versions of epub would be retroactively required to support whatever change is made.

Recommend we add version numbers to the titles, and consider whether our spec references should be to specific dated versions, even if it will become a maintenance headache.

Realistically, this problem exists everywhere as we didn't add version identifiers to the uris of all the specs but core epub, but these are the only two specs that also excluded a version number.

**Comment by danielweck** [comment]
I agree that just like "EPUB Media Overlays 3.0.1" ( http://www.idpf.org/epub/301/spec/epub-mediaoverlays.html ), the title "EPUB Canonical Fragment Identifiers" ( http://www.idpf.org/epub/linking/cfi/epub-cfi.html ) should contain the specification version number.

**Comment by danielweck** [comment]
Also, the "latest" URL http://www.idpf.org/epub3/latest/mediaoverlays redirects to the editor's draft http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html

Unfortunately http://www.idpf.org/epub/linking/cfi/epub-cfi.html does not redirect to a dated / versioned URL.

**Comment by mattgarrish** [comment]
I've updated both specifications to be "1.1" to match the core revision cycles but account for their not having the history of the EPUB core specs.

Dating of URLs will be handled as part of issue #712.
