### ISSUE TITLE
Remove the switch element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#637]
As part of aligning with the open web platform, and to facilitate grammar equivalence between the HTML and XHTML syntaxes, consensus to remove the switch element from EPUB 3.1 was reached on the 2016-01-08 conference call (https://docs.google.com/document/d/1Ari3a4urma6js0L-GLkzwDEqsI2dKFPs7X1J9LXqNEk/edit#heading=h.zc0soncmn95).

The Content Documents specification includes guidance on using the alttext and altimg MathML attributes, as MathML was indicated as the use of the element in a recent survey of publishers.

This issue will remain open past publication of the first draft for comment.

**Comment by bitsgalore** [comment]
I'm wondering about the implications for existing (e.g. EPUB 3.0.1) documents that have content wrapped in a switch element. Would a 3.1 conforming reader completely ignore this (hope not!), or would at least the content of the `default` element still be rendered? As always, the impact will depend on how widely used the switch element really is, and I don't know if any figures on this exist.

(Side note: I think the Google doc link above is wrong, as it doesn't mention the switch element)

**Comment by mattgarrish** [comment]
That's one of the questions we're still considering in terms of compatiblity of content. One option is to require a 3.1 reading system to support 3.0 content, another is to look at which removals have a real impact on rendering and deprecate instead (or put them all back as deprecated).

I've argued that switch is the most significant, as we know it's been used, if not extensively, and without any awareness a 3.1 reading system will render all of the switch content. Many respondents to our survey weren't even aware that triggers and bindings existed, by comparison

And the minutes are now in the archives at https://docs.google.com/document/d/152AO1a4FzVZwZs2wmJvbVxK5w9cXAJpCvk5NQOHAlFc/edit
