### ISSUE TITLE
How to handle rendition:viewport spine overrides

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#643]
The metadata group's proposal to reduce metadata in the package document, as defined in issue #642, removes the refines attribute.

As a result, it will no longer be possible to override a global rendition:viewport declaration for individual spine items.

As this metadata was only added in 3.0.1 to optimize fixed layout rendering, it is not clear if spine overrides are being used for this purpose, or if only the global setting has any value (the value in the content document always takes priority, so the metadata is also only informational).

The working group needs to determine if a replacement is necessary, and, if so, what form it should take.

**Comment by GarthConboy** [comment]
Discussed in Chicago -- rendition:viewport is optional and redundant (and not in EBPAJ template for FXL) -- seems we can deprecate property, or at the very least deprecate the "refines" portion (making this solely document global info).  Preference to deprecate entirely, given optional and redundant nature.

**Comment by GarthConboy** [comment]
Proposed resolution: deprecate "rendition:viewport" in 3.1.

**Comment by mattgarrish** [comment]
Property has been moved to the appendix of deprecated features.[1] The rendition vocabulary has been similarly updated.[2]

Please review and close if no further changes are necessary.

[1] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#fxl-property-viewport
[2] https://idpf.github.io/epub-vocabs/rendition/#sec-viewport

**Comment by GarthConboy** [comment]
LGTM
