### ISSUE TITLE
Remove the guide element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#644]
The deprecation discussions mostly revolved around elements that were valid in 3.0.1. The guide element is already deprecated, so a formal resolution to remove it wasn't tabled.

There's no value in keeping it if we're removing all the other compatibility pieces, and it looks like an obvious oversight, so suggest we approve taking this out for the first draft, too.

**Comment by elmimmo** [comment]
In order to evaluate the potential impact of removing the guide on current reading systems, is there any solid info on what specific RSs in the market use it for (i.e. info not about what purposes the EPUB 2 spec described it was for, but which ones ended up being actually used by real RS)?

**Comment by bdugas** [comment]
Given that the Guide section is deprecated how would you recommend someone call out a map or other reference section that would have been included in the Guide previously?

**Comment by mattgarrish** [comment]
The guide element was replaced by the landmarks nav in EPUB 3.

**Comment by bdugas** [comment]
Thanks @mattgarrish
