### ISSUE TITLE
required support for xml-stylesheet PIs?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#649]
I noticed the reading system support requirements has this under xml processing:

It must support xml-stylesheet processing instructions [ASSOCSS], and may support additional processing instructions.

This looks like a relic of another age. The other requirements are necessary to support processing the opf, but given the decline of custom xml grammars in epub can this be removed or diminished?

**Comment by tsiegman-wiley** [comment]
+1 I was going to add the same issue, but it's already here.

**Comment by murata2makoto** [comment]
+1

**Comment by mgylling** [comment]
Proposed resolution: in the [section for XML processing requirements for RS](http://www.idpf.org/epub/301/spec/epub-publications.html#confreq-rs-xml-assocss), remove the  paragraph on xml-stylesheet PIs. 

Note: this does not include disallowing PIs to occur in content, only that RS are not required to support them.

**Comment by mattgarrish** [comment]
Bullet that required support has been removed from the section:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-spec.html#sec-epub-rs-conf-xml

As noted above, this change only removes required support. Reading systems may still support.

Please close this issue if no other changes are required.
