### ISSUE TITLE
Adding example of MO document w/ multiple granularities

### ISSUE THREAD

**Issue by pettarin** [w3c/epub-specs#650]
At the moment the only reference to multiple granularities in the MO document is:

http://www.idpf.org/epub/301/spec/epub-mediaoverlays.html#sec-media-overlays-granularity

Adding an example --- XHTML and SMIL --- to illustrate the paragraph/sentence/word function (which is currently implemented in Readium) might help publishers and developers interested in authoring or supporting multiple MO granularities.

**Comment by danielweck** [comment]
A clarification about Readium's implementation of this "experimental" feature:

https://github.com/readium/readium-js-viewer/issues/510#issuecomment-197444617

**Comment by danielweck** [comment]
The current EPUB3 Media Overlays specification does not support "multiple" text-audio synchronisation granularities, as per Readium's experimental implementation (see comment 510 linked from the above item in this discussion thread).

There has not been sufficient interest in the EPUB working group to drive this functionality forward, only internal discussions (which led to the Readium implementation effort). As far as I know, there is no significant content (only demos) that use the concept of multiple SMIL granularities (which would currently only work in Readium).

I suggest we close this issue, as "no fix" or "out of scope".

**Comment by mattgarrish** [comment]
The working group reviewed this issue on the June 22 call and agreed to close this as out of scope since it is not yet standardized behaviour.
