### ISSUE TITLE
EPUB 3.1 4.1.1 sentence structure

### ISSUE THREAD

**Issue by tsiegman-wiley** [w3c/epub-specs#651]
I had to read this sentence a few times to parse:
Authors are free to use both types of resources to construct their EPUB Publications, but need to be aware that not every Reading System might render the Foreign Resources they use.
what about:
Authors are free to use both types of resources to construct their EPUB Publications, but need to be aware that some Reading System might not render the Foreign Resources they use.

**Comment by mattgarrish** [comment]
Change as indicated.
