### ISSUE TITLE
add link to ARIA APG

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epub-specs#652]
Section 2.4.2.1.2 The ARIA role Attribute, informative note. Add link to ARIA Practices Guidelines 1.1 (forthcoming) (1.0 is available at https://www.w3.org/TR/wai-aria-practices/, 1.1 is part of ARIA 1.1 revision)

**Comment by mattgarrish** [comment]
Changed note to "See [ARIA-APG] and [ARIA-HTML] for more information ... "
