### ISSUE TITLE
Reconsider EPUB Style Sheets profile

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#659]
One of the major work items for the 3.1 revision is to revisit the profile of CSS that was defined for EPUB 3.0. This profile has been a source of authoring confusion about what parts of CSS are supported, and also introduced a number of prefixed versions of CSS properties that added to the confusion.

A significant rewrite of the section has been undertaken for the first draft. Details are available in the css subgroup's working document[1]. The new section can be viewed at [2].

[1] https://docs.google.com/document/d/1qauoAGRJzz-BATN-S2VoCnHytKJ-12vfT5WpCS0ETR0/edit
[2] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-css

**Comment by dauwhe** [comment]
Closing as we've done this, and there has been significant review both in GitHub issues and elsewhere.
