### ISSUE TITLE
CD section 2.4.2.1.2 role attribute

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epub-specs#661]
Ideally authors will use both ARIA core and DPUB-ARIA, so I recommend slight wording change:
The primary vocabulary for roles for use in HTML Content Documents is the W3C Digital Publishing WAI-ARIA Module 1.0 [DPUBVocab], but roles defined in [WAI-ARIA-1.1] and in other modules maintained by the WAI-ARIA Working Group are also valid.

s/valid/expected

(especially since the para after the notes explicitly states expectation of familiarity with 1.1)

**Comment by mattgarrish** [comment]
What about stronger encouragement? Maybe:

..., but Authors are strongly encouraged to use any applicable roles defined in [WAI-ARIA-1.1] and other modules maintained by the WAI-ARIA Working Group.

**Comment by TzviyaSiegman** [comment]
that works.
