### ISSUE TITLE
Metadata for expressing the level of ruby annotation

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#663]
Introduce metadata for expressing the level of ruby annotation in the given EPUB publication.  Such metadata is requested by my Japanese colleagues in the DAISY consortium.  I think that such metadata is useful for China and Taiwan as well.

Ruby annotation makes difficult Kanji or CJK ideographic characters more accessible.  More about ruby, see https://en.wikipedia.org/wiki/Ruby_character

There are three levels: 'without ruby', 'with ruby', and 'full ruby'.  'full ruby' implies that all Kanji characters have ruby annotations.

**Comment by mattgarrish** [comment]
Sounds like a case for schema.org's accessibilityFeature property.

The difference between full and partial has been raised for any feature. I'm thinking that we should use the slash modifier syntax to avoid proliferating properties or having to write out every nuance. For example, you could set accessibilityFeature to "ruby/partial" to indicate incomplete support.

The absence of the value in any publication that reports accessibility metadata implies the feature is not present.

**Comment by murata2makoto** [comment]
I think that we need three values.  An EPUB publication may specify 
one of them.

```
<meta property="schema:accessibilityFeature">ruby/full</meta>
<meta property="schema:accessibilityFeature">ruby/partial</meta>
<meta property="schema:accessibilityFeature">ruby/none</meta>
```

**Comment by clapierre** [comment]
I agree this makes sense my only issue is that the word"ruby" may not be discriptive enough.  I had no idea "ruby" was additional pronunciation characters in Chinese.  I though you were originally talking about the computer language Ruby and was wondering why we needed this in an accessibility Feature.  Now maybe it would be in the context that the language was Chinese.  Just raising a concern not sure if it is relevant or not.  I also don't like making things more complicated.  
What do you think about "pronunciationRuby/full" , pronunciationRuby/partial, pronunciationRuby/none"?  Or something similar?

**Comment by murata2makoto** [comment]
I do not want to put "pronunciation" as part of this metadata,
Some ruby is not at all about pronunciation. (Example: I saw
"friend" attached to "enemy" as ruby.  The combination means
"rival".)

Regards,
Makoto

2016-07-12 23:44 GMT+09:00 Charles LaPierre notifications@github.com:

> I agree this makes sense my only issue is that the word"ruby" may not be
> discriptive enough. I had no idea "ruby" was additional pronunciation
> characters in Chinese. I though you were originally talking about the
> computer language Ruby and was wondering why we needed this in an
> accessibility Feature. Now maybe it would be in the context that the
> language was Chinese. Just raising a concern not sure if it is relevant or
> not. I also don't like making things more complicated.
> 
> What do you think about "pronunciationRuby/full" ,
> pronunciationRuby/partial, pronunciationRuby/none"? Or something similar?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/IDPF/epub-revision/issues/663#issuecomment-232069863,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFPqaLtEKjAKSkmZ9nA3_I7io2Vx-b5wks5qU6hMgaJpZM4HP8p6
> .

## 

Praying for the victims of the Japan Tohoku earthquake

Makoto

**Comment by mattgarrish** [comment]
What about rubyAnnotations?

But I think this is a case where if you're looking for ruby or are finding books with it you're going to know what it means.

A minor unrelated point, but we don't technically need 'none' values for features. If a feature isn't present, you wouldn't list it.

I'm going to take this off the 3.1 milestone, as the resolution doesn't require changes to the core specs.

**Comment by mattgarrish** [comment]
We added rubyAnnotations to accessibilityFeature, so this should have been closed.
