### ISSUE TITLE
Package Metadata Vocabulary inaccessible (“Moved permanently”)

### ISSUE THREAD

**Issue by elmimmo** [w3c/epub-specs#669]
In [EPUB Packages 3.1 (Editor's Draft 30 January 2016)](http://www.idpf.org/epub/31/spec/epub-packages-20160130.html), the link to [Package Metadata Vocabulary](http://www.idpf.org/epub/vocab/package/metadata/) in the chapter [4.2.2 Default Vocabulary](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-metadata-default-vocab) returns `301 Moved Permanently` but redirects to the same URL causing and endless redirection loop.

**Comment by mattgarrish** [comment]
Thanks, the url shouldn't end in /metadata. You can get to the vocabulary for now at
http://www.idpf.org/epub/vocab/package/epub-vocab-package.html
