### ISSUE TITLE
Support pre-rendered MathML in EPUB 3.1

### ISSUE THREAD

**Issue by ryanackley** [w3c/epub-specs#670]
In the Readium epub viewer, MathJax is used to render MathML. This is done in JavaScript and it can be very slow to render a lot of equations. Since Readium can't accurately paginate until the content document is finished being layed out, the user is presented with a loading screen while this is happening. 

My thought is why can't the authoring environment render the MathML when the epub file is saved. For example, there would be a MathML representation in the EPUB for editing but there would also be a pre-rendered svg rendition of the MathML already in the EPUB. There would be no need to re-render the MathML in the EPUB.

**Comment by ryanackley** [comment]
Actually looking at the spec there is the altimg attribute. Maybe make this recommended for rendering speed?

**Comment by mattgarrish** [comment]
Closing this as out of scope for the specifications. We don't make recommendations on how reading systems can optimize rendering.
