### ISSUE TITLE
use application/javascript in package document

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#673]
It was pointed out that RFC 4329 obsoletes text/javascript[1].

The IE issues with this media type appear confined to the script element in content, and specifying the type isn't necessary nor do we require it to match the opf media type.

[1] https://www.ietf.org/rfc/rfc4329.txt

**Comment by mgylling** [comment]
Proposed resolution: deprecate text/javascript in OPF and add application/javascript as the CMT designator in OPF.

**Comment by mattgarrish** [comment]
Media type has been updated: https://idpf.github.io/epub-cmt/v3/#cmt-js

Please close this issue if no other changes are required.
