### ISSUE TITLE
add "alternate" link relationship

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#675]
We're going to need the new link type to identify the browser-friendly serialization of the package document.

**Comment by TzviyaSiegman** [comment]
Add rel="alternate" to our rel registry. Point to https://www.w3.org/TR/html5/links.html#rel-alternate

**Comment by mattgarrish** [comment]
I'm having trouble translating this request, as there are three meanings for alternate depending on whether another relationship or types are specified with it.

Which one(s) are we adopting? Can you use alternate with keywords other than stylesheet? What do syndication feeds mean in the context of the package document? What does alternate mean inside a collection, or is it disallowed there?

It's also not clear how creating a hyperlink applies to the package document.

Can we say that it's "similar in nature" to the alternate keyword, but only identifies an alternate representation of the package document as indicated in the media-type attribute?

And possibly that it can be paired with other relationships, in which case it represents an alternate representation? (But does this require at least one use of the relationship without alternate?)

**Comment by dauwhe** [comment]
I think at least two of the uses from HTML5 are appropriate. 

If the media type matches whatever we decide for BFF, then this "indicates that the referenced document is a reformulation of the current document in the specified format." It does seem possible to have a separate "reformulation" of a collection, so I think it could apply there as well... 

We might also want to refer to OPDS feeds with media-type application/atom+xml. 

I'm less sure about rel=alternate for stylesheets. The other concepts apply nicely outside of an html context, but I think any mucking about with alternate stylesheets should happen in the HTML docs.

**Comment by mattgarrish** [comment]
Right, we don't define global style sheets in the package, and shouldn't start. I was wondering about other doubling up, though. At one point we considered alternate + record for the metadata, though we've dropped it now. If we want compatibility, we probably need to say no and wait for some actual cases.

My growing impression is that we can't just go minimal and say it's "the [HTML5] alternate keyword for links" but need a more complete adaptation.

**Comment by dauwhe** [comment]
I wonder if we can do a strict subset of HTML5:

For the package document, the `alternate` value of `@rel` 
-  applies only to `link`
-  can't be combined with other `rel` values
-  does not create a hyperlink, but reading systems may provide means for readers to reach these alternative documents or feeds. 
-  if `@media-type` is `application/rss+xml` or `application/atom+xml` it references a syndication feed
-  if any other media type, it references an alternative version of the publication (or collection, depending where it lives). Would we want to point to alternate translations that are not part of the same publication? 

So we're not changing meaning from HTML5, just restricting it to the cases that make sense in our context. Does this work?

**Comment by mattgarrish** [comment]
That's what I'm thinking.

An OPDS catalog is specified using the record keyword in epub. Looking at the spec, alternate is for linking from a partial to full catalog record, which I don't think we need to accommodate. But there's no harm in allowing a book to be tied to a syndication feed, either.

The only other thing that might be worth stating is that creation of a hyperlink for presentation to a user is not required.

**Comment by mattgarrish** [comment]
Updated here: https://idpf.github.io/epub-vocabs/package/link/#alternate

**Comment by mattgarrish** [comment]
Moving this to final review as we resolved this a long time back and just had to implement.

@dauwhe @TzviyaSiegman do you want to take a look and close if okay?

**Comment by dauwhe** [comment]
Looks good to me. Thanks!
