### ISSUE TITLE
Spread identification in otherwise spread-less FL content

### ISSUE THREAD

**Issue by GarthConboy** [w3c/epub-specs#676]
Particularly for comics and manga, some reading systems support a "fit width" viewing mode (Play Books, and others).  This is generally most useful when reading graphic content on phones or small tablets... the content is consumed in landscape, with each content (portrait) page fit to the the width of the landscape screen and vertically panned and then vertically paged (from the bottom of one page, the top of the next page comes in from below).  This works very nicely for viewing comics on small screens with the next bubbles often big enough to read!

Many (most?) comics and manga are numerous non-spread pages, with the occasional true-spread  thrown in -- in the rare (real spread) cases, the Reading System should render the two even/odd pages stitched together and shown as a full synthetic spread.

We have metadata for controlling rendering/ordering of synthetic spreads "rendition:page-spread-left" and "rendition:page-spread-right".  I think we should augment our text in 3.1 to make it explicit that these should be used to identify "real" spreads in otherwise spread-less FL content.

Such content would likely have volume level metadata:
`<meta property="rendition:layout">pre-paginated</meta>`
`<meta property="rendition:spread">auto</meta>`
or maybe even:
`<meta property="rendition:layout">pre-paginated</meta>`
`<meta property="rendition:spread">landscape</meta>`

Note that if the reading system were operating in "fit-width" mode it would, in general, not make synthetic spreads in landscape, as most pages are really standalone.

For the few page pairs that REALLY want to be rendered as spreads they should be identified as such in the spine (in this example, pages 22 and 23):
    …
`<itemref idref="page22" properties="rendition:page-spread-left"/>`
`<itemref idref="page23" properties="rendition:page-spread-right"/>`
    …

With some additional informational text we should be able to encourage some traction around this markup for identifying only true spreads and supporting this worthwhile use case.

**Comment by GarthConboy** [comment]
I would propose text like above (starting after "I think we should augment our text in 3.1") be added informatively to the 3.1 spec where we originally describe the "page-spread-*" properties.

**Comment by GarthConboy** [comment]
Proposed resolution: above comment.

**Comment by mattgarrish** [comment]
Can you let me know if the following captures the essence of this issue:

Although Authors often indicate to use a spread in certain device orientations, the content itself does not represent true spreads (i.e., two consecutive pages that have to be rendered side-by-side for readability, such as a two-page map). Depending on factors such as the available screen size, Reading Systems will often ignore the spread setting and optimize each individual document for viewing in the viewport. To indicate that two consecutive pages represent a true spread, Authors SHOULD use the rendition:page-spread-\* properties on their spine items. When a Reading System encounters such spine items, it SHOULD create a spread with no space between the adjacent pages, regardless of whether it is using a spread for the rest of the content.

Also, is "should" the correct conformance level?

**Comment by GarthConboy** [comment]
Perhaps slightly more explicit:

...Authors SHOULD use the rendition:page-spread-\* properties on these (true spread) spine items, and omit the rendition:page-spread-\* properties on spine items where one-up or two-up presentation is equally acceptable.

I'd actually remove "Depending on factors such as the available screen size, Reading Systems will often ignore the spread setting and optimize each individual document for viewing in the viewport."

The "normal" use case for this verbiage is when the content has been specified as "rendition:spread" with "landscape" or "auto" -- and the use of "rendition:page-spread-*" properties will control what happens in portrait.  So, the reading system is not ignoring the spread setting, just using this information, when it can.

Yes, SHOULD seems correct.

**Comment by mattgarrish** [comment]
We probably shouldn't use -\* but note that it's for -left and -right. Is the following good, then?

> Although Authors often indicate to use a spread in certain device orientations, the content itself does not represent true spreads (i.e., two consecutive pages that have to be rendered side-by-side for readability, such as a two-page map). To indicate that two consecutive pages represent a true spread, Authors should use the rendition:page-spread-left and rendition:page-spread-right properties on the spine items for the two adjacent EPUB Content Documents, and omit the properties on spine items where one-up or two-up presentation is equally acceptable. When a Reading System encounters two spine items that represent a true spread, it should create the spread with no space between the adjacent pages.

**Comment by GarthConboy** [comment]
Ship it!

**Comment by mattgarrish** [comment]
The specification has been updated and the changes can be reviewed here:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#fxl-properties-page-spread

Please close this issue if no other changes are needed.
