### ISSUE TITLE
ARIA role and multiple values

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#680]
The HTML5 spec [says about ARIA `role`](https://www.w3.org/TR/html5/dom.html#aria-role-attribute):

> The WAI-ARIA role that an HTML element has assigned to it is the first non-abstract role found in the list of values generated when the role attribute is split on spaces.

Does it mean that an element in EPUB can no longer have several equally significant semantic inflections (as it was the case with `epub:type`)?

**Comment by mattgarrish** [comment]
Yes, I'm working on a document of differences here:
http://rawgit.com/IDPF/epub-revision/master/build/vocab/structure/aria-transition.html

**Comment by rdeltour** [comment]
> Yes, I'm working on a document of differences here:
> http://rawgit.com/IDPF/epub-revision/master/build/vocab/structure/aria-transition.html

Cool, very useful!

For the record, the [Indexes spec](http://www.idpf.org/epub/idx/epub-indexes-20150826.html) has many examples of elements with multiple `epub:type` values.

**Comment by mattgarrish** [comment]
Closing since role is no longer replacing epub:type in 3.1. Will handle the authoring difference in the mentioned document.
