### ISSUE TITLE
MathML alternative content

### ISSUE THREAD

**Issue by pkra** [w3c/epub-specs#681]
[@rdeltour was kind enough to re-direct me here (from epubcheck)](https://github.com/IDPF/epubcheck/issues/678#issuecomment-190686098).

To quote Romain:

> EpubCheck applies the conformance statements defined by EPUB for [MathML alternative content](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-mathml-alt).

(Because of this, epubcheck might warn that `MathML should either have an alt text attribute or annotation-xml child element.`)

While I understand the motivation to suggest `alttext` and `annotation-xml`, this does not seem practical in today's state of AT. From my experience, if an AT does not support MathML it will neither support MathML's `alttext` attribute nor support finding something useful in annotation(-xml) elements. Does anyone know of an AT solution that would benefit from this? 

It seems to me that this adds to the burden of content creators without any actual benefit to the reader.  ARIA-based approaches (labels etc) seem more practical.

**Comment by mattgarrish** [comment]
That warning isn't completely correct. MathML should either have an alttext or altimg attribute. A reading system has to give precedence to an xhtml fragment in an annotation-xml element over the attributes, but it's not a requirement to include one.

In terms of what we can implement for 3.1, should we clarify in 2.5.4.1 that the attributes are recommended for reading systems that do not support mathml as an alternative presentation?[1]

We could/should discuss accessibility MathML alternatives in the accessibility techniques, if not leaving it to be addressed in WCAG.

[1] http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-html-mathml-alt

**Comment by pkra** [comment]
Thanks for the additional information, @mattgarrish. 

Could `aria-label` be added to the recommendations? It seems natural for the web and is the only working solution in real life. (FWIW, since most MathML-enabled epub3 reading systems use MathJax somewhere, alttext ends up as aria-labels.)

A side comment, the recommendation for MathML should probably require `alt` text on [mglyph elements](https://www.w3.org/Math/draft-spec/mathml.html#chapter3_presm.mglyph)  (really `alt` this time).

**Comment by mattgarrish** [comment]
We can add any guidance we want to the accessibility techniques document, so no reason we couldn't elaborate on including aria-label and alt there under math fallbacks. If they become future WCAG techniques we can always drop, too.

I'm just wondering what to make of the existing section. It's sort of authoring guidance wrapped up as normative requirements. With altimg being offered as an alternative to using epub:switch to include a fallback image, maybe that's all we should informatively retain (with a link to the accessibility techniques for more information on accessible alternatives).

**Comment by pkra** [comment]
> We can add any guidance we want to the accessibility techniques document, so no reason we couldn't elaborate on including aria-label 

Thanks, that would be good, I think.

> maybe that's all we should informatively retain

I can't really comment on that. As an author or publisher, I wouldn't use MathML in epub3 if I can avoid it (and use HTML or SVG instead).

**Comment by mattgarrish** [comment]
Right, I'm starting to think that we shouldn't have that section in the content docs specification at all. If an author is using MathML, any fallbacks they use shouldn't be spec enforced. Especially when we're silent about reading systems having to use these fallbacks if they don't support mathml rendering.

But I think any decision on the future of the section will need to go through the working group. I'm just going to leave this as an open point for discussion. Thanks, Peter!

**Comment by pkra** [comment]
Thanks, Matt!

**Comment by mattgarrish** [comment]
For the record, what we decided on the last accessibility call is that the techniques document will call out the use of aria-label and aria-describedby for including an accessible description.

If the section in the content documents spec remains, the recommendation is that it only discuss the option of including an alternative image via altimg, but that's to be determined by the core working group.

**Comment by pkra** [comment]
Thanks for the update, Matt.

**Comment by mattgarrish** [comment]
Propose we make the following changes to address this issue:

Strip this authoring bullet from the authoring conformance section,, as descriptions are now defined in the accessibility techniques document:

> Alternative Content
> Alternative content should be included, and, when present, must be represented as defined in Alternative Content.

https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-xhtml-mathml-conf-content

We also strip the following reading system conformance bullet, as it's not applicable and we're not going to influence what reading systems or AT do:

> When producing alternative textual content for MathML markup, it should be able to dynamically generate such content from the given Presentation MathML, and if not, must give preference to XHTML Content Document fragments followed by the alttext attribute on the math element.

https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-xhtml-mathml-rs-conf

Finally, change the title of 2.5.1.4 and simplify to:

> 2.5.1.4 Fallback Content
> As Reading System support for MathML rendering is inconsistent, Authors are encouraged to provide a fallback image using the altimg attribute on the math element. It is recommended that the dimension and alignment attributes (altimg-width, altimg-height and altimg-valign) be used in conjunction with the altimg attribute.
> NOTE
> Fallback images have to conform to the constraints for Publication Resources defined in EPUB Publication Conformance[EPUB 3.1].

https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-xhtml-mathml-alt

**Comment by TzviyaSiegman** [comment]
Looks good. I'm having trouble accessing the rawgit files.

**Comment by mattgarrish** [comment]
Looks like rawgit is down. I haven't updated, so they're just links to the prose as it was in 3.0.1 for comparison.

**Comment by mattgarrish** [comment]
As resolved on the July 20 call, I've implemented the changes in the previous comment. See the links above for the updated prose.

Please close this issue if no other changes are required.
