### ISSUE TITLE
Link to Previous Version / Recommendation of CFI results in redirect error

### ISSUE THREAD

**Issue by bitsgalore** [w3c/epub-specs#682]
The current [Editor's Draft  of EPUB Canonical Fragment Identifiers](http://www.idpf.org/epub/linking/cfi/epub-cfi.html) refers to the Previous Version / Recommendation via this link:

http://www.idpf.org/epub/linking/cfi/epub-cfi-20140626.html

But this gives me a redirect error.

**Comment by mattgarrish** [comment]
Thanks, it should have been:
http://www.idpf.org/epub/linking/cfi/epub-cfi-20140628.html

I just pushed an update to the site to fix the page.
