### ISSUE TITLE
Recovery from HTML syntax errors

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#683]
To introduce the HTML syntax of HTML5, we have to determine whether EPUB RSs  recover from HTML5 syntax errors, as defined in https://www.w3.org/TR/html5/syntax.html#parse-error, or they should fail.  I can imagine that many authors like error recovery.  But can we ensure interoperability and longevity if error recovery is allowed?

**Comment by mattgarrish** [comment]
Closing this as no longer in scope now that we've dropped support for the HTML syntax in 3.1.
