### ISSUE TITLE
Metadata HTTP Protocol: Issue with JSON in example

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#684]
The JSON Example 2 in Appendix A of EPUB Packages 3.1 reads:

```
{
        @context:”http://schema.org”,
        @id: “12345”,
        @type: “Book”,
        “bookFormatType”: “EBOOK”,
        “author”: “Foo Bar”,
        “name”: “Something2016”
    }

```

This doesn't parse properly as JSON due to smart quotes, and I don't think it's the correct use of `@context`. Should this be:

``` json
{
    "@context": {
        "@vocab": "http://schema.org/"
    },
    "@id": "12345",
    "@type": "Book",
    "bookFormat": "Ebook",
    "author": "Foo Bar",
    "name": "Something2016"
}
``
```

**Comment by mattgarrish** [comment]
I've updated this. I was heartened to see that the json-ld spec has an error in its json where it shows a default vocab, too. :)
