### ISSUE TITLE
Metadata HTTP Protocol: why SHOULD for HTTP/1.1 

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#686]
The current Metadata Server conformance says:

> It should be an HTTP/1.1 conformant server

However, isn't it a MUST in practice, given that several later MUST statements are not defined in previous versions of HTTP? (like ETag or code 406).

**Comment by iherman** [comment]
Well, there is another aspect. One could read this sentence by stating that HTTP/1.1 should be preferred over HTTP/2. Is it really what we want to say? Personally, I would think that, in the lifetime of the EPUB 3.1 standard, HTTP/2 might become much more present, and we should not discourage servers to use that...

So, while I am fine with MUST, we should probably say something like HTTP/1.1 and newer, or explicitly HTTP/1.1 or HTTP/2.

**Comment by rdeltour** [comment]
> Well, there is another aspect. One could read this sentence by stating that HTTP/1.1 should be preferred over HTTP/2.

Right, good point. I wasn't sure if an  HTTP/2 server was necessarily backwards compatible with HTTP/1., but [it seems it isn't](https://http2.github.io/faq/#can-i-implement-http2-without-implementing-http11).

**Comment by HadrienGardeur** [comment]
While we shouldn't discourage the use of HTTP/2, we might want to make sure that HTTP/1.1 support is always available.
I could already serve the metadata record only over HTTP/2 today, but this would potentially limit the client's ability to interact with the record.

**Comment by tkanai** [comment]
**Proposed resolution: Replace the HTTP1.1 line to "It should be an HTTP/1.1 or HTTP/2 conformant server."**
