### ISSUE TITLE
Metadata HTTP Protocol: why MUST for entity tags?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#687]
RFC7232 itself is [less restrictive](https://tools.ietf.org/html/rfc7232#section-2.4), stating that

> an origin server SHOULD send an entity-tag validator unless it is not feasible to generate one.

Having a MUST there makes it impossible to use hosting services that do not support ETag, for instance some static hosting providers like GitHub Pages.

**Comment by HadrienGardeur** [comment]
Agree that we need to use a SHOULD but not a MUST if we want a strong statement in favor of caching.

Also, as we potentially extend these statements to all HTTP remote resources and not just metadata records, ETags won't always be the best choice.
For images/CSS/JS, it's a good idea to rely on Cache-Control instead, which is very convenient with a proxy/CDN.
