### ISSUE TITLE
Metadata HTTP Protocol: why explicitly mention code 406 and not others?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#688]
The current Metadata Server conformance says:

> It must respond with a 406 status code [RFC7231] when the server is not able to send acceptable responses.

Why making a special case and explicitly mention code 406? Other codes are equally relevant in the metadata retrieval context, for instance HTTP 304 ("Not Modified"). Mentioning one single code and not others looks a bit odd IMHO.

**Comment by HadrienGardeur** [comment]
IMO we shouldn't mention any code at all and just provide a generic statement about HTTP conformance.
