### ISSUE TITLE
Metadata HTTP Protocol: s/If-Match/If-None-Match

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#689]
Th Metadata Client conformance statements read:

>  It should use the HTTP If-Match header and ETags [RFC7232] to check whether the Metadata Record has changed since it had been updated.

Shouldn't it use the [If-None-Match](https://tools.ietf.org/html/rfc7232#section-3.2) header instead here?

**Comment by HadrienGardeur** [comment]
+1
