### ISSUE TITLE
navigator.epubReadingSystem layoutStyle enumeration, combined values? (e.g. paginated + scrolling)

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-specs#690]
http://www.idpf.org/epub/301/spec/epub-contentdocs.html#app-ers-properties

> A Reading System will typically return one of the values "paginated" or "scrolling", but may define values for any additional layout formats it supports.

QUESTION: what about combining several values (predefined, and custom)? What is the syntax? (space or comma -separated?, etc.)

**Comment by danielweck** [comment]
Garth Conboy says: 

Wonder if this and hasFeature, below, are used in real life. Have we encountered something else we invented from whole cloth that should be deprecated?

**Comment by therealglazou** [comment]
Just repeating here what I said during ftf in Bordeaux: `layoutStyle` is an attribute for a single document rendering and not a characteristic of the reading system in particular if the reading system is multi-window on a desktop environment. More generally, anything that is more related with one package/document's rendering cannot be an attribute on `epubReadingSystem`.

**Comment by danielweck** [comment]
@therealglazou the intent of `layoutStyle` is to convey overall RS capabilities, I think.

**Comment by therealglazou** [comment]
Could a RS have multiple layout capabilities ? AFAIC, 100% possible for desktop apps.

**Comment by danielweck** [comment]
Yes, thus why I logged this issue ;)

**Comment by dauwhe** [comment]
This came up internally at HBG. For example, iBooks supports both a scrolling and paginated mode. What our developer actually wants to know is something about the current document—is it in scrolling or paginating mode? Is it a fixed layout document? But that's another issue.

**Comment by therealglazou** [comment]
layoutStyle should not be a String but a JS object.

**Comment by danielweck** [comment]
If I understand correctly, as per today's concall discussion: deprecation of `navigator.epubReadingSystem.layoutStyle` is on the table. Content creators would then be discouraged to use this property in their scripted EPUB 3.x publications ; assuming this feature has ever been used (which I doubt, but I have no data to prove it) ; and reading system implementations would continue to support the property based on their interpretation of the specification, which may possibly be inconsistent (e.g. layout style "for the current document" vs. "to express the general capabilities of the reading system").

A new, more useful EPUB-next feature (I think @dauwhe will ask HBG/Chris?) would be for `navigator.epubReadingSystem` to expose properties that would express the current "state" of the rendered spine item(s), so that scripted documents can generate more responsive / adaptive content styles depending on pagination vs. scrolling view modes, night vs. day, etc. (the list is pretty open, for example what about media-overlays playing/paused/stopped?) This would need to be addressed in a separate issue though, and seems unrealistic within the 3.1 timeframe. In closing, I would like to resurface comments I made about "state"-like properties such as `navigator.onLine` ( https://html.spec.whatwg.org/multipage/browsers.html#navigator.online ) which go hand-in-hand with DOM events (for example `window.ononline` or `<body onoffline="..." />`). For completeness and consistency with existing `navigator` properties, I think it would be important to expose similar "value changed" events for any future `navigator.epubReadingSystem.currentLayoutStyle` property.

**Comment by danielweck** [comment]
Follow-up to my previous message: I found the reference to `navigator.onLine` at https://github.com/IDPF/epub-revision/issues/648

Verbatim copy/paste from https://docs.google.com/document/d/1aLPwp6bvIki5LHz2yWhypqzajr9jR8CyKqTlpzqUwgs :

W3C HTML 5:
https://www.w3.org/TR/html5/browsers.html#browser-state
W3C HTML 5.1:
http://w3c.github.io/html/browsers.html#browser-state
WhatWG HTML 5:
https://html.spec.whatwg.org/multipage/browsers.html#browser-state

=> regardless of whether or not the actual instance of the window.navigator object is shared across browsing contexts, its internal state is reflected everywhere, and the value of the “onLine” is up-to-date.
Note that this HTML feature includes “online” and “offline” events that can be used from scripting contexts to determine when the value changes.

**Comment by mattgarrish** [comment]
As resolved on the July 20 call, I'm closing this issue by adding the deprecated label.

Please open a new issue to continue discussions about a better replacement.
