### ISSUE TITLE
navigator.epubReadingSystem.hasFeature(“spine-scripting”), non-sensical?

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-specs#691]
http://www.idpf.org/epub/301/spec/epub-contentdocs.html#app-ers-hasFeature

Isn’t navigator.epubReadingSystem.hasFeature(“spine-scripting”) somehow non-sensical?
A spine-level scripted EPUB content document would know that scripting is enabled without querying this.
Would a container-level scripted EPUB content document really need to know if its “parent” (or “top”, for nested iframes) document context can execute scripts? For example, when content authors need to establish communication between host document and embedded iframes, they would just implement a postMessage() protocol that would require the parent (host) to bootstrap the conversation, until which point the children/descendants would have to assume that no scripting is available at the spine level.

**Comment by danielweck** [comment]
@bduga says:

I have no idea if it has every been used in practice. But I can imagine skipping certain things if the parent document can't run scripts. For instance, something that queries the DOM of the parent might not bother trying. But that is a stretch, and there are clearly other mechanisms available. It was a requested feature, maybe a RS that supports scripting could fill us in on whether this check is ever made.

**Comment by danielweck** [comment]
Garth Conboy says: 

Wonder if this and hasFeature, below, are used in real life. Have we encountered something else we invented from whole cloth that should be deprecated?

**Comment by mattgarrish** [comment]
@danielweck this issue is also addressed in the proposed new wording: 
https://docs.google.com/document/d/1DeURYlVpVuWEI-RYOLsYDz9_zodbv0XcxPLpI2jcXFA/edit

**Comment by mattgarrish** [comment]
Revised text can be reviewed here:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#feature-spine-scripting

Please close this issue if no other changes are required.
