### ISSUE TITLE
navigator.epubReadingSystem.hasFeature(“version”)

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-specs#692]
http://www.idpf.org/epub/301/spec/epub-contentdocs.html#app-ers-hasFeature

> If a Reading System supports a feature defined in this section, it must return a true value both when queried without the version parameter set and when that parameter is set to the value "1.0". Otherwise, it must return false. Reading System developers should not change the version number of these features independently of this specification.

Comments:

The optional “version” function parameter is neither that of the reading system, nor that of the actual EPUB revision (e.g. v3 vs. v3.01, etc.). It is arbitrarily set to 1.0, so I am wondering whether this is ever going to evolve? What was the rationale for this parameter?
Do we have any metrics / developer feedback that would help inform decisions such as deprecation of unused / irrelevant features, specification updates / fixes? My personal impression is that this feature has offered no value to content developers (sniffing of browser user agent, and/or reading system name/version is much more effective), and I see no benefits to reading system implementors...just wondering, not trying to diss anything.

**Comment by danielweck** [comment]
@bduga commented:

I think it is the version of the feature itself, which were all set to 1.0. We could decide to increment the version number of a particular feature at some point. In that case, even if a RS supports feature X at 1.0, false would be returned for a check of X at 1.1.

**Comment by danielweck** [comment]
Garth Conboy says: 

Wonder if this and hasFeature, below, are used in real life. Have we encountered something else we invented from whole cloth that should be deprecated?

**Comment by mattgarrish** [comment]
Brady is right, as far as my memory goes. It was added to future proof the method in case we were to make an incompatible change to a feature in a later version of the spec.

It's utterly useless as long as that never happens.

**Comment by mattgarrish** [comment]
Can you have a look at the proposed changes here and see if they're sufficient to address this issue @danielweck : 
https://docs.google.com/document/d/1DeURYlVpVuWEI-RYOLsYDz9_zodbv0XcxPLpI2jcXFA/edit

**Comment by mattgarrish** [comment]
Any thoughts on these changes to address this and #691 @danielweck ?

If not, I'd like to get 72hr resolution emails out.

**Comment by mattgarrish** [comment]
Revised text can be reviewed here:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#app-ers-hasFeature-desc

Please close this issue if no other changes are required.
