### ISSUE TITLE
Should EPUB 3.1 use HTML 5.1?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#696]
W3C plans to ship an HTML5.1 Recommendation in September 2016.

https://www.w3.org/blog/2016/04/working-on-html5-1/

**Comment by mattgarrish** [comment]
The reference to HTML does not include a number and all links now use the /TR/html path. HTML 5.1 will be automatically adopted when it becomes a recommendation.

An explanation of this change and a caution note have been added to the "relationship to html" section.[1]

The same has been done for SVG.

[1] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-overview-relations-html
