### ISSUE TITLE
Whether to add enumeration of identifier types

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#700]
The opf:scheme attribute was added to dc:identifier to identify the type of value. Like the equivalent EPUB 2 attribute, no specific vocabulary of values is required.

A request has been made to include some predefined values for the attribute, but objections have also been raised (e.g., the EPUB definitions will become normative even if the scheme maintainers later change requirements).

**Comment by HadrienGardeur** [comment]
I'm strongly in favor of following what IANA does for rel values:
- define a list of known value with a registry maintained by IDPF (which should live on Github and allow people to send pull requests for proposals)
- also allow extensions, but require URIs for those

**Comment by mgylling** [comment]
Resolved on the May 4 meeting: add enumeration provided via IDPF vocab, + allow full IRIs as extension slot.
