### ISSUE TITLE
Register link relations with IANA

### ISSUE THREAD

**Issue by dret** [w3c/epub-specs#701]
looking at http://www.idpf.org/epub/vocab/package/link/#sec-link-rel i was wondering if there are any plans to register these link relations according to RFC 5988. ideally, when using link relations on the web, these should be either (a) identified by URI in which case they can be freely used, or (b) identified by short strings in which case they should be registered with IANA.
if that helps, i am willing to help with the registration.

**Comment by HadrienGardeur** [comment]
I think that would help.

**Comment by mattgarrish** [comment]
I'm taking off the 3.1 milestone, as this sounds like an issue to solve for the web friendly format being spun out of this revision. The package document as currently manifested isn't really a web technology.

Feel free to disagree, though.

**Comment by dret** [comment]
please just keep in mind that changing link relation type identifiers probably would be a breaking and unfortunate choice. so regardless of the current scope, my recommendation would be to name identifiers so that for any future steps into a more webby scope, no renaming is necessary. maybe registration can wait for now, but for any spec that defines webby concepts (such as link relation types) chances are that these will find their way to the open web.

**Comment by mattgarrish** [comment]
Sure, I don't disagree with registering. It's only that EPUB 4 aims to have a web representation of the package document, and may have other requirements for links. Evaluating and registering the relationships fits better into the scope of that work.

We'll only have three relationships left by the end of this revision (acquire, alternate and record). Any of those can be deprecated or changed later, if needed, as the link registry isn't bound to the revision cycle process.

**Comment by dauwhe** [comment]
Most of these link relations are deprecated. We are not currently working on a web-native packaging format for EPUB, so we feel that there's not a lot of benefit in registering these link relations for use on the web.
