### ISSUE TITLE
Metadata and GET requirement

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#707]
I am confused about the conformance requirements for the metadata server. We specifically list GET as being required, but RFC 7231 already requires that GET be supported by any general-purpose server. Does this mean that the metadata server is NOT a general-purpose server? For instance, is HEAD optional? If so, why? If not, why not just say that the server must be a general-purpose HTTP server, per RFC 7231?

**Comment by HadrienGardeur** [comment]
Agree that this is unnecessary.

**Comment by tkanai** [comment]
It is just a mistake.
I overlooked the section 4.2.6.1 in [Linked Data Protocol specification](https://www.w3.org/TR/ldp/), and thought HEAD is optional in LDP. Now I can't find any reasons to give privilege to GET Method.

**Proposed Resolution: Remove the GET line.**
