### ISSUE TITLE
Metadata and Access-Control-Allow-Origin headers

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#708]
What are the expected values of the cross origin headers? Is it assumed to be *? If so, should that be explicitly stated?

**Comment by HadrienGardeur** [comment]
Also, I don't think that this can be a "MUST", especially if we extend this section to any remote resources.

There are already many metadata records out there that could be useful but that we won't be able to support if we enforce the use of Access-Control-Allow-Origin.

**Comment by tkanai** [comment]
Proposed Resolution: Add  "with the value *" into the line
