### ISSUE TITLE
Metadata HTTP Protocol: Link header

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/epub-specs#710]
The current spec language says:

> It may advertise its protocol support by providing a Link header [RFC5988] with a target IRI [RFC3987] of "http://idpf.org/metadata#Container" and relation type of "type".

But as we're discussing minimization of the various statements regarding HTTP conformance, I really don't think that it makes sense to include such info in a Link header.

It's also unclear to me if "type" really is a good fit here.

**Comment by tkanai** [comment]
I agree with minimizing the protocol requirements.
**Proposed Resolution: Remove the link requirement.**
