### ISSUE TITLE
Unrealistic requirement for mathml and scripted properties

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#715]
From Daniel Glazman:

Last item of this section is completely unrealistic. When a xhtml parser deals with a xhtml document containing a math element, the matml property of the manifest is out of scope. The parser MUST do something with it and this item denies it, or does it mean the manifest entry for a xhtml document containing mathml MUST reflect it through a mathml property? In that case, that's entirely different and this item is very badly phrased. There is another occurence of similar prose later in the document about the scripted property.

Comment is about this bullet:

> It must regard the mathml property [PackageVocab] of the Package Document manifest item element as the authoritative definition of whether an XHTML Content Document includes embedded MathML.

**Comment by dauwhe** [comment]
I'm puzzled by this as well. I can see making it a validity error if a content document contains mathml and the corresponding item does not get the mathml property. But I would want a reading system to be obligated to display any mathml in HTML.  And what is a reading system supposed to do if there's a mathml property on an item that contains no math? Since the property is authoritative, I suppose the reading system is obligated to display some math anyway. I'd suggest the Gauss-Bonnet theorem.

**Comment by mattgarrish** [comment]
It is an error if the content document has mathml and the property isn't set right now, at least if you run epubcheck.

The properties were added to help minimize the rendering footprint of reading systems Some wanted to know what is present in the content up-front so that they didn't have to invoke rendering features that weren't needed.

That's what was intended by the "authoritative definition" to the best of my recollection. If you don't set the property, you can't guarantee your content will render on all, even if the RS is otherwise capable.

**Comment by mattgarrish** [comment]
I'd just add that we tried to deprecate these in 3.0.1, but they are being used by reading systems.

I'm not sure what happens if you don't set the property, though. It may well use whatever (non-existent) capabilities the browser core has in the case of mathml. I don't know that they'd suppress. For scripting, you'd end up with static content.

**Comment by mattgarrish** [comment]
These two bullets really aren't adding anything, though. Regarding these as an "authoritative definition" doesn't mean anything. It places no requirement on the reading system to do anything one way or the other.

What they probably want to say is:

It MAY disable MathML rendering for an XHTML Content Document if the mathml property [PackageVocab] is not set on a Package Document manifest item element.

But, in that case, there probably should also be author warnings where the properties are defined, as in: If Authors do not set these properties on manifest items, there is a risk that a reading system won't render the content.

**Comment by GarthConboy** [comment]
I like Matt's last two paragraphs above.

**Comment by mattgarrish** [comment]
I'm going to alter my proposal slightly, but not materially. In the interests of keeping information together and not having to put statements for every type of document (and for all the optimizations a reading system might make), I think it would be a lot simpler just to make the explanation in the item element definition. The author warning can be inferred, too.

I'm therefore going to change this sentence:

> All applicable descriptive metadata properties MUST be declared for each Publication Resource.

to this:

> Authors MUST declare all applicable descriptive metadata properties for each Publication Resource in this attribute, as Reading Systems MAY optimize the rendering depending on the properties that have been set (e.g., disable a rendering process or use a fallback).

And just remove the offending bullets about regarding properties. Cleaner and simpler.

**Comment by mattgarrish** [comment]
Updated prose can be reviewed here:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#attrdef-item-properties

Please close this issue if no other changes are required.
