### ISSUE TITLE
Rename SSV terms to match ARIA roles

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#717]
The DPUB-ARIA vocabulary has the following differences from the EPUB Structure vocabulary:

doc-backlink = locator
doc-endnote(s) = rearnote(s)
doc-tip = help

Hyphens have also been removed from all names.

**Comment by TzviyaSiegman** [comment]
In the current (published SSV, "locator" is called "referrer". it is a draft term, so we may be able to remove not just deprecate. Recommendation: Deprecate SSV terms, replace with DPUB-ARIA terms and do a 72-hour.

**Comment by TzviyaSiegman** [comment]
Correction: the term in the latest draft of DPUB-ARIA is "backlink" https://www.w3.org/TR/dpub-aria-1.0/#doc-backlink

**Comment by TzviyaSiegman** [comment]
Recommendation: Deprecate SSV terms backlink, rearnote(s), help.
Add to SSV: backlink, endnote(s), tip with definitions from DPUB-ARIA

**Comment by mattgarrish** [comment]
Terms have been renamed:
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#tip
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#backlink
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#endnote
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#endnotes

Old terms have been deprecated:
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#help
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#rearnote
http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#rearnotes

Please close this issue if no other changes are necessary.
