### ISSUE TITLE
Mention/recommend use of DPUB-ARIA in EPUB-A11y?

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epub-specs#718]
(Perhaps I missed a discussion about this). Should we recommend usage of DPUB-ARIA roles (https://www.w3.org/TR/dpub-aria-1.0/) in the EPUB Accessibility (http://www.idpf.org/epub/a11y/accessibility.html). I realize it seems a bit odd to mention the DPUB module without mentioning the Core Spec (ARIA 1.1), but let's consider using this to nudge the module along and show its worth.

**Comment by mattgarrish** [comment]
The plan is to have it in the techniques. I'm still looking at how to structure the document, but there's a placeholder for roles here: https://docs.google.com/document/d/1RSPZKg8gQ9TG5rts8PovUoqHZEr_dfi6b0U7vFzA00g/pub#h.sec102jawtgn

**Comment by mattgarrish** [comment]
Closing this issue as the techniques make reference to DPUB for use role.
