### ISSUE TITLE
Default vocabulary for meta property doesn't have any values

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#719]
The default vocabulary[1] currently only defines rendition: prefixed properties.

It's very confusing to have a vocabulary that's supposed to define the set of unprefixed properties defining only prefixed properties.

The rendition: properties should be in their own vocabulary at [2], but that's problematic as it was a bad choice for an identifier URL (should have been idpf.org/epub/vocab).

Related to issue #465. 

[1] https://rawgit.com/IDPF/epub-revision/master/build/vocab/package/epub-vocab-package.html#sec-meta-property-values
[2] http://www.idpf.org/vocab/rendition/#

**Comment by mgylling** [comment]
Suggest to just leave it as an empty placeholder doc for now. Who knows, perhaps some non-rendition and non-refinement properties will be defined for meta in the future.

**Comment by GarthConboy** [comment]
Proposed resolution -- this is a feature not a bug.  Leave empty placeholder for future definition (https://rawgit.com/mattgarrish/epub-revision/master/build/vocab/package/property/epub-vocab-property.html).  This is per proposed resolution to "https://github.com/IDPF/epub-revision/issues/720".

**Comment by mattgarrish** [comment]
I guess we're stuck with the awkward url for the rendition vocabulary, as that ship has sailed.

I've updated the output and linking to account for it being the sole document outside the /epub branch, so closing this half of the issue.
