### ISSUE TITLE
Consider breaking up the Package Metadata Vocabulary

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#720]
The vocabulary at [1] is defined as the default for several attributes, and currently has sections for each.

Since we've already crossed the bridge of having different defaults for different attributes (link relations are in a different vocabulary), we might as well be consistent and carve the vocabulary up into meta, item and itemref vocabularies.

Similar to #719, the itemref properties section predominantly contains rendition: prefixed property definition that don't belong in a "default vocabulary".

It's all very messy right now.

[1] https://rawgit.com/IDPF/epub-revision/master/build/vocab/package/epub-vocab-package.html

**Comment by GarthConboy** [comment]
Matt, do you want to (would you) propose resolutions to this, #719 and #465?  I'm sure we'll agree with you!  :-)

**Comment by mattgarrish** [comment]
My only thought so far is that we split the package vocabulary in three and move all the rendition: prefixed properties back to their own vocabulary.

These are only definitions, so having them so broken up probably isn't too painful, as there are links out from the specification to the most important ones.

Otherwise, we need to consider rewording this paragraph at the start of the default vocabulary section:

The default vocabulary is a vocabulary that does not require a prefix to be declared in order to use its terms, and whose terms must always be unprefixed.

But that probably still leads to a hack. We were playing a bit of a game before with redirects to make the rendition properties a separate vocabulary coexisting with the default vocabulary in the same document. We can't really get away with that now that we've split the vocabulary out from the specification, not that it was the best idea before.

**Comment by mattgarrish** [comment]
Here's a hack-up of what broken out vocabs could look like:

Manifest properties:
https://rawgit.com/mattgarrish/epub-revision/master/build/vocab/package/item/epub-vocab-item.html

Spine properties:
https://rawgit.com/mattgarrish/epub-revision/master/build/vocab/package/itemref/epub-vocab-itemref.html

Meta properties:
https://rawgit.com/mattgarrish/epub-revision/master/build/vocab/package/property/epub-vocab-property.html

And then all the rendition: prefixed stuff could go in its own:
https://rawgit.com/mattgarrish/epub-revision/master/build/vocab/package/rendition/epub-vocab-rendition.html

**Comment by mgylling** [comment]
If we do as Matt suggests above, then for the sake of cleanliness we should move page-spread-left and page-spread right into the rendition vocab (i.e. be given the rendition prefix). We would create aliases for the old names so that we don't invalidate existing content.

**Comment by GarthConboy** [comment]
Proposed resolution -- break out vocabularies as proposed my Matt two comments above.

Also, create aliases for the existing "page-spread-left" and "page-spread-right" itemref properties as "rendition:page-spread-left" and "rendition:page-spread-right" to match "rendition:page-spread-center" and include these in the "rendition:" prefixed vocabulary.  We would retain the naked versions of the two properties to avoid breaking existing content.

**Comment by mattgarrish** [comment]
Vocabularies added in commit https://github.com/IDPF/epub-revision/commit/bca3d3f1e39a5c3b4556fea98233d0f494bf00cd

Vocabularies are now available at the following locations:
https://idpf.github.io/epub-vocabs/package/meta/
https://idpf.github.io/epub-vocabs/package/item/
https://idpf.github.io/epub-vocabs/package/itemref/

The list of default vocabularies has also been updated at:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#sec-metadata-default-vocab

**Comment by mattgarrish** [comment]
The page-spread-\* properties section has been updated to include the rendition: prefix.[1] I've also added a note about being aliases.[2]

Please review (particularly the note) and close if no further changes are necessary.

[1] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#fxl-properties-page-spread
[2] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#note-page-spread-aliases

**Comment by GarthConboy** [comment]
LGTM.
