### ISSUE TITLE
XML namespace for meta element in metadata.xml

### ISSUE THREAD

**Issue by KitaitiMakoto** [w3c/epub-specs#722]
Hello,

In Multiple-Rendition Publications spec, XML namespace of `meta` element in metadata.xml is not the same to the one in package document.

Example metadata.xml in [Multiple-Rendition](http://www.idpf.org/epub/renditions/multiple/epub-multiple-renditions-20150826.html#sec-2.3.2) spec is:

``` xml
<metadata xmlns="http://www.idpf.org/2013/metadata"
          xmlns:dc="http://purl.org/dc/elements/1.1/"
          unique-identifier="pub-id">
   <dc:identifier id="pub-id">urn:uuid:A1B0D67E-2E81-4DF5-9E67-A64CBE366809</dc:identifier>
   <meta property="dcterms:modified">2011-01-01T12:00:00Z</meta>
</metadata>
```

XML namespace of `meta` in this example seems `http://www.idpf.org/2013/metadata`. On the other hand, the ones in [Publications 3.0.1](http://www.idpf.org/epub/301/spec/epub-publications-20140626.html#sec-package-def) and [Packages 3.1](http://www.idpf.org/epub/31/spec/epub-packages-20160426.html#sec-package-elem) seem `http://www.idpf.org/2007/opf`. But Multiple-Rendition spec says that `meta`s in both spec are the same basically. Is the spec's example wrong? Or actually are nemaspeces different?

Revisions I read are:
- http://www.idpf.org/epub/renditions/multiple/epub-multiple-renditions-20150826.html
- http://www.idpf.org/epub/301/spec/epub-publications-20140626.html
- http://www.idpf.org/epub/31/spec/epub-packages-20160426.html

**Comment by mattgarrish** [comment]
The metadata element's namespace is defined in the OCF specification.[1] We could not change that for the multiple renditions specification.

The content models are defined to be essentially the same, not the namespaces of the elements. The meta and link elements are noted to be in metadata element's namespace. This difference is noted in the bullet list in the metadata element definition.[2]

[1] http://www.idpf.org/epub/301/spec/epub-ocf.html#sec-container-metainf-metadata.xml
[2] http://www.idpf.org/epub/renditions/multiple/#sec-2.1

**Comment by KitaitiMakoto** [comment]
@mattgarrish 

Thank you very much for reply.

> This difference is noted in the bullet list in the metadata element definition.[2]

I just missed that. I'm sorry for bothering you.
