### ISSUE TITLE
clarify "must support CSS as defined in the [CSS-Snapshot]"

### ISSUE THREAD

**Issue by mgylling** [w3c/epub-specs#724]
Unclear what "must support" refers to here, is there a more specific pointer or range? Also note that the must in this bullet is followed by a should in the following bullet re modules, which might confuse readers.  (Is the second bullet intended to cover only the "green areas" in the snapshot spec? If so, that was not immediately clear to me...)

https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-css-rs-conf

**Comment by dauwhe** [comment]
The snapshot doesn't make it easy to link to the appropriate stuff. Perhaps we could slightly change the first bullet to more explicitly target the "official definition" phrase:

> - It must support the official definition of CSS as listed in the [CSS-Snapshot], if it has a viewport.

And perhaps remove the reference to the snapshot in the second bullet:

> - It should support other modules that have reached Candidate Recommendation status [W3C-Process] and are widely implemented.

The green areas in the snapshot are notes, and are non-normative.

**Comment by dauwhe** [comment]
New language from conference call of June 8 added in https://github.com/IDPF/epub-revision/commit/ce30ab72afc0fb4cda0dc36ed21eb542a819fb7e
