### ISSUE TITLE
video core media type for EPUB 3.1?

### ISSUE THREAD

**Issue by mgylling** [w3c/epub-specs#725]
Can we find consensus on a core media type for video, with H.264 now supported broadly in browsers?
http://caniuse.com/#feat=mpeg4

We should keep the patent encumbrance in mind when discussing this potential move -- there needs to be some way for authors to use non-patent encumbered codecs as well, even if we move for H.264 as CMT.

**Comment by danielweck** [comment]
Note to self: `CMT` == Core Media Type :)

**Comment by mattgarrish** [comment]
This proposal was rejected by the working group on the July 13 call due to continued concerns about patent encumbrance.
