### ISSUE TITLE
Deprecate SSV term "subchapter"

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epub-specs#727]
When reviewing terms for DPUB-ARIA, we concluded that "subchapter" cannot be objectively defined and adds no semantic value.

**Comment by mattgarrish** [comment]
Agree wholeheartedly.  Always struck me as a confusion with subsection -- assumes a "chapter" of a textbook can't have subsections but needs a like-named "subchapter".

**Comment by TzviyaSiegman** [comment]
Recommendation: Remove "subchapter" from the SSV

**Comment by mattgarrish** [comment]
Term has been marked as deprecated.[1]

Please close this issue if no additional changes are necessary.

[1] http://rawgit.com/IDPF/epub-revision/master/build/epub/vocab/structure/epub-vocab-structure.html#subchapter

**Comment by robinwhittleton** [comment]
Late to the party, but is there a suggested replacement? Or do we fall back to bare elements / classes?

**Comment by mattgarrish** [comment]
Yes, "subchapter" has no more specific meaning than a nested bare section element. Both are some indistinct subsection of a chapter.

But you can pretty much do whatever you want with epub:type at this point, at least in content documents. Epubcheck will only report deprecated/unknown terms as usage messages. Outside of pop-up footnotes that have some reading system support, the vocabulary is really only helpful for publisher workflows.
