### ISSUE TITLE
Add (AT) under Terminology

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#728]
1.4 Terminology

Assistive Technology
Suggestion:  also include commonly referred to as AT

**Comment by mattgarrish** [comment]
I've avoided the initialism in either of our documents, as they just make specifications harder to read.

I took a look at WCAG and ARIA and they don't use the initialism, either. I'd recommend we not introduce it.

**Comment by clapierre** [comment]
This is fine, we can leave it out.
