### ISSUE TITLE
duplicate "markup" in typographic conventions

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#729]
1.5 Typographic Conventions

markup
Links to markup and code definitions are underlined and in red monospace font.

Shouldn’t this be maybe "markup_link" since "markup" is already defined previously.  Just looked odd just with an underline on this being the only difference between the two.

**Comment by mattgarrish** [comment]
Yes, we also have a similar issue with "Term" being repeated in the core specs. The specs are relying on formatting to differentiate.

I've updated both instances.
