### ISSUE TITLE
discrepancy may/must with WCAG Conformance reporting

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#730]
In section 4.2.2.2 Applying the Conformance Criteria

This specification does not require a [WCAG20] Conformance Claim, as conformance to this specification includes the WCAG conformance level attained (see 4.4 Conformance Reporting). Authors may include such a claim, however.

where we say “authors MAY include”

But in section
4.4 Conformance Reporting

To indicate that an EPUB Publication conforms to both the discovery and content accessibility requirements of this specification, it MUST include the following metadata in its Package Document: 

here we say "it MUST include"

**Comment by mattgarrish** [comment]
I think we can strip that paragraph, as it's not helpful. WCAG doesn't make a conformance claim a requirement, so we aren't changing anything. If you want to make a claim per that specification, you're free to and it has no effect on the requirements of this spec.

**Comment by mattgarrish** [comment]
This is the second time the paragraph has caused confusion, so I'm closing by removing.

Whether someone wants to report wcag conformance separately is their choice.
