### ISSUE TITLE
Optimized Publication metadata example

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#731]
1. Optimized Publications

Maybe we should include an example here of what that metadata would look like?
Since we can't say it conforms to WCAG-a which previously was a MUST include.

**Comment by mattgarrish** [comment]
We can, but does it mean using a fake url or is there an example of a standard we can use? I dislike a fake url that because we say the url should dereference to an explanation.

It would look similar to a conforming publication in terms of the markup:

``` html
<link rel="dcterms:conformsTo" href="http://example.com/daisyaudio"/>
```

**Comment by mattgarrish** [comment]
Added url for daisy audio guidlines
