### ISSUE TITLE
Boken links to all a11yTechniques

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#733]
This version
http://www.idpf.org/epub/a11y/techniques-20160426.html
Latest version
http://www.idpf.org/epub/latest/a11y-techniques
Previous version
http://www.idpf.org/epub/a11y/techniques-20160426.html

all are referenced in latest google doc but are broken.
https://docs.google.com/document/d/1RSPZKg8gQ9TG5rts8PovUoqHZEr_dfi6b0U7vFzA00g/pub

**Comment by mattgarrish** [comment]
The hrefs didn't match the visible text. I've also updated the htaccess file on idpf.org to make the latest version link work, but I've also changed it to http://www.idpf.org/epub/latest/accessibility-techniques to parallel the link for the main spec.
