### ISSUE TITLE
doc-pagebreak ARIA issue

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#736]
EPUB A11Y Techniques
PAGE-001: Provide Page Break Markers

<span title="1" id="page001" epub:type="pagebreak" role="pagebreak”/>

Shouldn’t role=“doc-pagebreak” ?

**Comment by mattgarrish** [comment]
It looks like this issue got cut off, Charles. I spotted role="pagebreak" in the example and fixed. Is that what you were reporting here, or something else?

**Comment by clapierre** [comment]
sorry the rest of the comment was
<span title="1" id="page001" epub:type="pagebreak" role="pagebreak”/>

Shouldn’t role=“doc-pagebreak” ?

**Comment by clapierre** [comment]
oh it is removing the comment since it is code..
`<span title="1" id="page001" epub:type="pagebreak" role="pagebreak”/>
`

Shouldn’t role=“doc-pagebreak” ?

**Comment by mattgarrish** [comment]
Yes, that was a mistake. I'm not used to the prefix. I've fixed it.
