### ISSUE TITLE
DRM circumvention with AT?

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#737]
EPUB A11Y Techniques
DIST-001: Do Not Restrict Access through Digital Rights Management

While I agree with this 100% for AT users, I do have a concern...
I am sure this has been discussed before but, doesn't this mean that anyone could get access to a book by just turning on AT and listen to the book they didn’t purchase.  Isn’t this then a loophole of the DRM system?

We are saying that a reading system should first "unlock" the DRM that the user has legally purchased and then must give 100% access to the content unrestricted for AT correct?  Maybe this could be made clearer so that it doesn't look like a loophole to DRM.

**Comment by mattgarrish** [comment]
Yes, it's not a bypass. The text above mentions legitimate restrictions. Would the following work for you:

The application of digital rights management must not impair or impede the functionality of Assistive Technologies on EPUB Publications Users have the right to access.

**Comment by clapierre** [comment]
Perfect, works for me.
