### ISSUE TITLE
CFI encoding method for XHTML should be removed

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#739]
As discussed in #662, any CFIs will not be used in Content documents, and the section "2.3 Character Escaping : (X)HTML Context" is no longer useful.

**Comment by mattgarrish** [comment]
There's no requirement for reading systems to support them in content documents anymore, but we haven't outright banned them from content documents.

I doubt authors ever have or will use them, based on google's query of their data that returned nothing, but unless we formally forbid them I'd suggest we keep.

**Comment by tkanai** [comment]
I just thought it was formally forbidden, but it seems it is not. Never mind.

**Comment by mattgarrish** [comment]
Okay, closing.
