### ISSUE TITLE
Does page-break-before guidance on body belong in content documents?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#740]
I was skimming the specification and noticed that we still have section 2.5.5.1, which states that page breaks before new content documents can be controlled by a CSS style sheet.[1]

I don't remember who exactly brought this issue up earlier in the revision, but I recall it being questioned how this statement interacts with the rendition:flow property, and whether that property supersedes this.

So I guess the half-remembered issue boils down to:
- should this section be removed from content documents?
- do we need to keep the prose but move it into the rendition:flow or itemref definitions?
- do we need to state anything about rendition:flow being similar to page-break-before?

If anyone has more specific memories of what was being considered to do with this, please feel free to fill in the details.

[1] http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-html-deviations-special-body

**Comment by dauwhe** [comment]
I found [this](https://groups.google.com/forum/#!searchin/epub-working-group/page-break-before/epub-working-group/oZogbLJzs58/V3AWIITrQtMJ), which references issues #250 and #364 .

I remember some earlier discussions about being able to run paginated content documents together, so if there was lots of white space at the end of one, you could start another on the same page. I'm wary of that, as it seems to violate some fundamental HTML principles. Of course we already have `scrolled-continuous`.

**Comment by mattgarrish** [comment]
I've moved the prose as resolved on the July 13 call and tweaked it as best I could to fit based on the conversation:

> Note that when two reflowable EPUB Content Documents occur sequentially in the spine, the default rendering for their [HTML] body elements is consistent with the [CSS 2.1] page-break-before property having been set to always. In addition to using the rendition:flow property, Authors may overridde this behavior through an appropriate style sheet declaration, if the Reading System supports such overrides.

http://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#html-body-page-break-before

Let me know if any additional changes are needed.

/cc @GarthConboy

**Comment by GarthConboy** [comment]
SGTM
