### ISSUE TITLE
decide whether to keep or toss the index

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#741]
See the open issue at:
http://www.idpf.org/epub/31/spec/epub-spec.html#index

**Comment by TzviyaSiegman** [comment]
I think this will be useful. We haven't tested it in the real world yet, but I think we put this in the umbrella  so that users could access anything easily from it. I vote to keep it and see how it's received.

**Comment by mattgarrish** [comment]
We probably just need a quick consensus on a wg call. I was going to update it and then spotted that we still have an unresolved open issue so don't want to waste time.

I found in the old minutes that we did note it to the group, but no consensus was sought about keeping it. We just left the issue open.

**Comment by laudrain** [comment]
I vote for keeping it.

**Comment by mattgarrish** [comment]
It was resolved on the call today (2016-07-06) to keep the index. I'll remove the open issue and update.
