### ISSUE TITLE
CFIs referring to HTML5 documents might cause syntax errors. 

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#743]
Unlike XHTML, we can use any letters for id in HTML5 documents. It means id="1" , id='"test"', id="epub=3" and id="]foobar[", for example, are valid in HTML5.
https://www.w3.org/TR/html/dom.html#the-id-attribute

Since "CFI XML ID assertion" is based on XML ID, some letters / character sequence rules which are prohibited to be used in XML break the assertion process.

I think the spec should clearly mention that RS including authoring tools must not embed any IDs which are incompatible with XML ID into CFI.

Any thoughts?

**Comment by russwyte** [comment]
+1 
I can see where this could be problematic for parsing as well.

**Comment by mattgarrish** [comment]
Do you need to exclude every ID that isn't compatible, or is the problem only with embedded closing square brackets?

**Comment by tkanai** [comment]
@mattgarrish  Since the spec specifies the use of XML ID, excluding every incompatible ID is the right approach, I think. If we will update the spec and make it more HTML5 friendly, then excluding square brackets could be a option.

**Comment by mattgarrish** [comment]
I think it would probably be useful to make it more html5 friendly, since that's the bulk of the content they'll be referencing into.

If a reading system is creating annotations or bookmarks or anything where the IDs are no longer malleable, then it's going to encounter non-XML conformant identifiers. Authors and tools aren't likely to create conformant identifiers just in case a CFI has to be generated.

**Comment by danielweck** [comment]
But just to be clear: there are no plans in EPUB3 to allow HTML5 right? Only the XML serialisation of HTML5 is officially supported, therefore the CFI specification ; as it stands now ; is consistent.

**Comment by mattgarrish** [comment]
It's not a requirement to use XML IDs in HTML5, XML serialization or not.

**Comment by tkanai** [comment]
Besides, what it is available from Web component is HTML DOM, and it could be different from serialized XML DOM (DOM manipulation can not be applicable for XML documents) , then I'm afraid that the CFI spec which is based on XML Content does not meet what it is implemented now.

**Comment by danielweck** [comment]
As pointed out by Brady on today's concall:
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-xmlid
EPUB CFI assertions are for _XML_ IDs (`xml:id` attribute), not the HTML5 `id` attribute which has a different syntax.

**Comment by danielweck** [comment]
New issue: https://github.com/IDPF/epub-revision/issues/750
