### ISSUE TITLE
Typo in EPUB 3.1 Overview document

### ISSUE THREAD

**Issue by JoeUX** [w3c/epub-specs#744]
This document: http://www.idpf.org/epub/31/spec/epub-overview-20160426.html

At the bottom in the Informative References section, it lists this reference and link:

> [EPUB3Changes] EPUB 3.0.1 Differences from EPUB 3.0 .  Markus Gylling, et al.

It should read EPUB **3.1** Differences from EPUB 3.0 (or 3.0.1), as that is in fact what it links to: http://www.idpf.org/epub/31/spec/epub-changes.html

**Comment by mattgarrish** [comment]
Thanks, I've updated the reference.
