### ISSUE TITLE
The Ruby positioning section has gone?

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#745]
I can't find "Ruby positioning", a.k.a CSS Ruby, in the April draft. I checked both email archives and the telcon doc, but find nothing about it.
Am I missing something?

**Comment by mattgarrish** [comment]
It was removed as part of the cleanup of prefixed properties. The proposal document the css subgroup wrote is here:
https://docs.google.com/document/d/1qauoAGRJzz-BATN-S2VoCnHytKJ-12vfT5WpCS0ETR0/edit#heading=h.jc5gcnrdrzlt

There was some discussion on the list here:
https://groups.google.com/d/msg/epub-working-group/cylyFQdh8GM/qD2DGoOICgAJ

And there's a resolution to remove in the January 22 minutes here:
https://docs.google.com/document/d/152AO1a4FzVZwZs2wmJvbVxK5w9cXAJpCvk5NQOHAlFc/edit#heading=h.z0a21cgzc5cm

**Comment by mattgarrish** [comment]
Are you objecting to its removal or just wondering if it was accidentally dropped?

**Comment by tkanai** [comment]
I just thought it was accidentally dropped. I saw some drooped epub prefixed CSS properties in the content document, but no ruby properties were there, and I'm wondering what makes this difference. If we are going to completely drop the ruby properties from the document, I think we should also remove others, and it would help removing "dated" references.

**Comment by mattgarrish** [comment]
I think the initial idea was to remove them all. @dauwhe can probably give more detail, but I believe only properties that we could find evidence were in use were retained.

**Comment by murata2makoto** [comment]
Kanai-san,

Those epub prefixes which are proven to be widely used are not dropped.
The
epub-prefixed ruby position was never implemented and used.  We rather wait
for the CR or Rec of CSS Ruby.

Regards,
Makoto

2016-07-12 9:38 GMT+09:00 Takeshi Kanai notifications@github.com:

> I just thought it was accidentally dropped. I saw some drooped epub
> prefixed CSS properties in the content document, but no ruby properties
> were there, and I'm wondering what makes this difference. If we are going
> to completely drop the ruby properties from the document, I think we should
> also remove others, and it would help removing "dated" references.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/IDPF/epub-revision/issues/745#issuecomment-231906584,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFPqaIIUX1kHJkSUwUeoL9iFeuKtQffeks5qUuIigaJpZM4JH55P
> .

## 

Praying for the victims of the Japan Tohoku earthquake

Makoto

**Comment by tkanai** [comment]
I'm afraid that my comment introduced unnecessary confusions. Here is the simplified version.
- -epub-text-combine has removed in 3.0.1 and -epub-text-combine-horizontal is going to be removed.
  I have no objection to the decision.
- -epub-ruby-position is going to be removed.
  I have no objection to the decision.
- Description about -epub-text-combine and -epub-text-combine-horizontal  are in the spec.
  I can live with it.
- There are no description about -epub-ruby-position in the spec.
  WHY?

Then, I doubt the ruby section has been dropped accidentally from the spec. I think all items which describes about current situation should be removed, especially if the spec refers to the CSS snapshot. Then, I think the description written in -epub-text-combine should be removed, but I'm afraid I might be missing something and I would like to figure out why we have this gap before that.

**Comment by murata2makoto** [comment]
It was unfortunate that -epub-text-combine was deprecated (but not removed)
in 3.0.1.But this is the property widely used in Japan, since it is in the
EBPAJ
profile.  That's why we kept it on purpose.

See
https://docs.google.com/document/d/1qauoAGRJzz-BATN-S2VoCnHytKJ-12vfT5WpCS0ETR0/edit?disco=AAAAAlAtgLo

Regards,
Makoto

2016-07-12 12:36 GMT+09:00 Takeshi Kanai notifications@github.com:

> I'm afraid that my comment introduced unnecessary confusions. Here is the
> simplified version.
> 
>    -
> 
>    -epub-ruby-position is going to be removed.
>    I have no objections to the decision.
>    -
> 
>    -epub-text-combine has removed in 3.0.1 and
>    -epub-text-combine-horizontal is going to be removed.
>    I have no objections to the decision.
>    -
> 
>    There are no description about -epub-ruby-position in the spec.
>    I can live with it.
>    -
> 
>    Description about -epub-text-combine and -epub-text-combine-horizontal
>    are in the spec.
>    WHY?
> 
> Then, I doubt the ruby section has been dropped accidentally from the spec.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/IDPF/epub-revision/issues/745#issuecomment-231929021,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFPqaM2P-xLurNIe733GOIMhd2xax2hQks5qUwuigaJpZM4JH55P
> .

## 

Praying for the victims of the Japan Tohoku earthquake

Makoto

**Comment by dauwhe** [comment]
We also had feedback from people in the educational market in Japan, who said it was OK to drop. 

I've also noticed that the [existing test](http://epubtest.org/testsuite/epub3/feature/epub-ruby-position-property/) for this in epubtest.org is very misleading. Since `over` is the initial value, lots of reading systems pass that test. The test CSS also includes `-webkit-ruby-position` and `ruby-position`, so it not testing for the prefixed version.

**Comment by mattgarrish** [comment]
Note, too, that the removals are all documented in the changes document:
http://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-changes.html#sec-cdoc-css

**Comment by mattgarrish** [comment]
As per the July 13 call, I've tried to increase the guidance to use unprefixed properties. The note has been changed to a caution and now reads:

> CAUTION
> Authors are strongly encouraged to use unprefixed properties, and Reading Systems to support current CSS specifications. The widely-used prefixed properties from [Content Docs 3.0.1] have been retained, but support for the other properties has been removed. Authors are advised to use CSS-native solutions for the removed properties where and when they are available.
> Authors currently using these prefixed properties are advised to move to unprefixed versions as soon as support allows, as these properties are not anticipated to be supported in the next major version of EPUB.

https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-css-prefixed

If this is too strong, or needs other adjustment, please comment.

**Comment by dauwhe** [comment]
There were no comments during the 72-hour review, so I'm closing the issue.
