### ISSUE TITLE
Phase out mathml in favor of svg for math equations in epubs

### ISSUE THREAD

**Issue by ryanackley** [w3c/epub-specs#746]
Having mathml as the standard for math equations in a web based reader is the equivalent to having markdown as the standard for text and styled content. It captures the semantics and structure of your content but it's not natively renderable by the most browsers. 

I can see a strong case for mathml on the editing side. However, EPUB seems to be more of a publishing and packaging format similar to PDF. In the case of PDF files, these are created by many different editing systems without concern for being able to re-open the PDF in the original editor. I can see why this would be useful for epubs but it doesn't seem to be a stated goal.

**Comment by dauwhe** [comment]
I think this is out of scope for the EPUB revision, as math on the web is an issue for the web community as a whole.

**Comment by ryanackley** [comment]
@dauwhe, I disagree that it's an issue. The web community has moved on to using 3rd party tools to create equations then exporting them to svg or raster images. We should be doing the same for epubs. 

Check out [Why did Chrome drop MathML support?](https://www.quora.com/Why-did-Chrome-drop-MathML-support). tldr; Security hole that has long since been fixed but they didn't re-enable because not enough people are asking for it. Note that Google Chrome is based on an open source project. Therefore, you can infer that no developer/organization/company out there cares enough to spend money/time/resources adding it back and maintaining it.

**Comment by TzviyaSiegman** [comment]
It is true that there is not an agreed upon standard for math other than MathML. While there is little support for MathML by browsers, there are widely used polyfills such as MathJax that make MathML a viable option for browsers. Many reading systems do support MathML. This is not the place to debate the value of one method over the other. Removing MathML from EPUB is, IMO, too large a change to make at this stage, especially for a dot release. Further, it would be very difficult from an accessibility perspective.

**Comment by ryanackley** [comment]
I'm not arguing for removing it but rather deprecating it. Deprecation is a process that works for situations like this. In practical terms, this means EPUBs that support the next standard should not have MathML. Eventually, MathML support would be removed completely.

I am familiar with MathJax. It converts MathML to SVG to perform the polyfill. It's actually the inspiration for this issue. Why not just cut out the middle man? I would guess that most authors are not writing MathML by hand but instead using a 3rd party tool. The only advantage MathML has is that it stores the semantics of the math being performed. I haven't seen any evidence that authoring tools or reading tools are taking advantage of this.

**Comment by ryanackley** [comment]
To put MathML browser support in perspective. http://caniuse.com/#feat=mathml.

**Comment by TzviyaSiegman** [comment]
@ryanackley I am aware of browser support issues as well as ongoing efforts to evolve math standards. When we (EPUB WG) very publicly asked for feature requests in 2015-16, no one commented about deprecating mathML [1]. We are currently wrapping up a third draft of 3.1. It is not the appropriate time to make this significant a change when there is no membership support. Please feel free to raise again in the future.

[1] https://docs.google.com/document/d/1QINuKE5Hsemll6G6tSQe6BaRuCHerFuwfXIRTgdaO7o/edit?usp=sharing
