### ISSUE TITLE
Close core media type support loophole

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#748]
The general perception is that core media types must be supported, but the current prose only states that they don't require fallbacks. This is because there is a bullet that allows support to be conditional for certain media type:

> Unless specified as conditional behavior in this section, it must support all Core Media Type Resources.

On the Jul 13 wg call, it was resolved to try and close this loophole so that all core media types are supported.

**Comment by mattgarrish** [comment]
I recommend the following changes to fix this issue:
1. Change the support item that opens the loophole to: "It must support all Core Media Type Resources."
2. Remove conditional support for audio MP4 and reference the audio CMT list by amending the support requirement to: "If it has the capability to render pre-recorded audio, it must support the audio Core Media Types and should support Media Overlays [MediaOverlays31]."
3. Add an exemption for the link element when it has the "pronunciation" relationship so that PLS support remains a should without getting into fallbacks for lexicons (this follows the pattern of having exemptions for the track element). We'd remove PLS as a core media type, since it would no longer be necessary to define.

**Comment by GarthConboy** [comment]
+1

**Comment by TzviyaSiegman** [comment]
+1

**Comment by rkwright** [comment]
+1

**Comment by mattgarrish** [comment]
Proposed changes have been integrated.

Updated support bullet:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-spec.html#confreq-rs-epub3-cmt

Updated audio support bullet:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-spec.html#confreq-rs-epub3-mp3-aac

Updated fallback exemption:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-xhtml-fallbacks

Updated CMT definition:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-spec.html#gloss-core-media-type

Please close this issue if no other changes are required.
