### ISSUE TITLE
XML ID vs. HTML5 ID in EPUB3 XHTML5 content docs (i.e. XML serialisation of HTML5)

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-specs#750]
Issue originally raised there: https://github.com/IDPF/epub-revision/issues/743

The EPUB CFI specification explicitly refers to _XML_ ID for square-bracketed element assertions: http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-xmlid

In other words, when an HTML(5) element inside an XHTML5 EPUB3 Content Document contains the `xml:id` attribute, the generated CFI expression that targets this element _must_ contain the square-bracketed ID assertion (as per the allowed XML syntax for identifiers).

Conversely, when an HTML(5) element inside an XHTML5 EPUB3 Content Document contains the `id` attribute, any generated CFI expression that targets this element cannot contain the square-bracketed ID assertion (HTML5 `id` attributes have different syntactical rules than `xml:id`, see https://www.w3.org/TR/html/dom.html#the-id-attribute ).

However, it is actually unclear whether XHTML5 EPUB3 Content Documents are allowed to contain `xml:id` attributes at all. According to @mattgarrish 's tests, only the HTML5 `id` attribute seems valid. See EPUB-Check schemas:
https://github.com/IDPF/epubcheck/tree/master/src/main/resources/com/adobe/epubcheck/schema/30

So, if  XHTML5 EPUB3 Content Documents are indeed not allowed to contain `xml:id` attributes, then the "square-bracketed element ID assertion" feature of CFI is effectively unusable / useless in the context of EPUB3 ... which seems to negate the need for even defining this feature. Note that strictly-speaking, the CFI specification itself is correct as per its generic relationship to XML documents, but in the real world CFI only exists under the EPUB3 umbrella.

One alternative possibility is that `xml:id` is in fact allowed in the XML serialisation of HTML5, and consequently the EPUB-Check schemas should be updated to reflect that (I understand that Oxygen and other validation tools rely on them, so they report the same `xml:id` error).

@rdeltour any thoughts?

CC @tkanai

**Comment by mattgarrish** [comment]
So far as I'm aware, xml:id has never been allowed in the XHTML serialization as it would conflict behaviourally with id.

It's not listed in the global attributes section of HTML5, unlike it's other xml: counterparts, nor can I find any instance of it in earlier XHTML versions.

If you go to validator.nu and use one of the XHTML presets you will get errors that the attribute is not allowed, for example. (The xhtml presets without a number will validate to the latest version)

The w3c validator also generates an error when validating under the HTML5 preset with the xhtml namespace on the root element, but unlike my initial assumption I don't think it actually is altering its behaviour. It will emit an error for older versions of XHTML, though.

**Comment by mattgarrish** [comment]
For more context, the id attribute in XHTML 1.1 was required to have a conformant XML ID as its value. As has been noted, that restriction was dropped for HTML5. epubcheck was erroneously enforcing this requirement in an alpha release and there was a strongly negative response to it.

We have made non-normative recommendations to use XML-compliant IDs for EPUB 2 compatibility (e.g., in the best practices guide), but there's no way around encountering HTML IDs in content documents.
