### ISSUE TITLE
Incorrect styling of "Must not" in  2.4.3.2 The ssml:ph attribute

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#752]
The MUST NOT in this sentence: "Must not be specified on a descendant of an element that already carries this attribute." is not styled like our other MUST NOTs (it is not in small caps).

Also, the previous sentence starts with an incorrectly styled MAY: "May be specified on all elements [...]".

**Comment by bduga** [comment]
And, same section, in the note: "Reading Systems that support the SSML Attributes and PLS Documents must honor the defined precedence rules for these two constructs."

**Comment by mattgarrish** [comment]
They still have scope statement about only being available in the "xhtml syntax". Leftover from January.

That note doesn't sound like a note. I can't see how that's informative information, but the styling must have been dropped to make it look like one. I'll re-integrate the sentence into the section and fix the styling.

**Comment by mattgarrish** [comment]
The section has been updated to fix the keyword styling, remove the labels and fix the note:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-cd-ssml-ph-attrib

Feel free to reopen if you spot anything that still needs fixing.
