### ISSUE TITLE
clarify alt-script attribute

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#755]
Clarify the definition of the alt-script attribute in the shared attributes section to make clear that it for both alternative languages and scripts. Also add example of an alternative language.

Maybe also reconsider its name.

**Comment by murata2makoto** [comment]
I am now wondering whether we can use multiple title elements for multiple languages.   That is, 

```
<dc:creator xml:lang="en">
    Haruki Murakami
</dc:creator>
<dc:creator  xml:lang="ja">
   村上 春樹
</dc:creator>

```

Can we always use this method?

**Comment by murata2makoto** [comment]
Actually, the above method does not work when there are multiple contributors having the same role.  We cannot know which of the multiple dc:creator elements having xml:lang="ja" corresponds to which of the multiple dc:creator elements having xml:lang="en".

**Comment by mattgarrish** [comment]
Or even that they are alternates and not that the Authors names are just in their native languages.

**Comment by murata2makoto** [comment]
alt-representation might be a better name.

**Comment by mattgarrish** [comment]
Proposed Solution

As discussed on list, change attribute names to alt-rep and alt-rep language and make the definitions:

> opf:alt-rep
> 
> Provides an alternative representation of the associated value in the language (and script) identified by the opf:alt-rep-lang attribute.
> 
> opf:alt-rep-lang
> 
> Specifies the language and optional script of the value of the opf:alt-rep attribute. The value of the attribute must be a language identifier as defined by [BCP 47].
