### ISSUE TITLE
3.1 Nits

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#758]
"single-file format" in the first para of "Purpose and scope" should be "single-file container" or "single file".

What does "these specifications" in the 2nd para mean?

"belong the standard" should be "belong to the standard""

I think that the use of "standard" is misleading, since people will think that a standard is a document.   I think that "format" is much better.  

"EPUB 3.1" is sometimes used as  a specification and sometimes as a format.

**Comment by mattgarrish** [comment]
Proposed Solution:

As noted above:
- Change to "single-file container".
- Change "these specifications" to "EPUB 3.1"
- Change to "are all a part of EPUB 3.1"

Also change the following for additional clarity:
- Change "EPUB 3.1 will be utilized" to "the EPUB 3.1 format will be utilized"
- Change "to the standard" in last paragraph to "to EPUB 3.1".
