### ISSUE TITLE
Terms not frequently used

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#759]
The spec "EPUB 3.1" defines the terminology.  Most terms are heavily used in the EPUB 3.1 family of specifications.  But "content provider" is never used.  We might want to also reconsider some rarely used terms such as "SVG viewpoert"

Here is a sorted list of terms and the number of occurrences.  I used 
`grep -iw -E "Core Media Types?" *.html`
to count the number of occurrences.

Package 417
Reading System  308
Container   227
EPUB Publication    215
Author  202
Rendition   196
EPUB Content Document   156
Spine   140
Manifest    121
User    111
Package Document    84
XHTML Content Document  70
EPUB Package    64
Publication Resource    50
Core Media Type 42
Viewport    40
EPUB Navigation Document    37
Foreign Resource    32
EPUB Reading System 29
Media Overlay Document  28
SVG Content Document    25
Text-to-Speech  21
TTS 21
Unique Identifier   21
Synthetic Spread    17
User Agent  17
Release Identifier  16
EPUB Containers 14
Scripted Content Document   10
Core Media Type Resource    8
Fixed-Layout Document   6
Top-level Content Document  5
Remote Resource 3
SVG Viewport    2
Content Provider    1

**Comment by mattgarrish** [comment]
Content Provider definitely needs to go. It was being automatically filtered out from the terminology in 3.0.1.

SVG viewport also can go, as it's only used once in 3.4:

> If it has an SVG Viewport, it must support the visual rendering of SVG ...

http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-svg-rs-conf

This can easily be reworded to use the existing viewport definition:

"If it has a Viewport capable of displaying SVG images, it must support ..."

I'd leave the rest, as it would mean having to redefine wherever they occur, and even remote resources pops up in two specifications.

**Comment by mattgarrish** [comment]
Proposed Solution:

Delete "Content Provider".

Leave SVG Viewport for now. Will determine what to do with it depending on the outcome of issue #761.
