### ISSUE TITLE
Raster and Vector image core media types

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#761]
The conformance section for EPUB Reading Systems says:

> If it has the capability to render raster images, it must support the raster image Core Media Types [Core Media Types].
> 
> If it has the capability to render vector images, it must support the vector image Core Media Types [Core Media Types].

However, looking at [Core Media Types](https://idpf.github.io/epub-cmt/v3/) the text does not make this differentiation, and has only one section for image media types. Of course, by following up on the media type link one can find out which one is which, but I think the Media Type list should then make this difference.

**Comment by dauwhe** [comment]
I'm confused. SVG support is required for a reading system, period. So how can a reading system support SVG, but not have the capability to render the only vector image Core Media type, which is SVG?

**Comment by iherman** [comment]
@dauwhe to make one step further: supporting SVG means to support pixel images as well, as that is also part of SVG... What this tells me is that the differentiation in the conformance section is unnecessary. Just say

> If it has the capability to render image Core Media Types [Core Media Types].

**Comment by mattgarrish** [comment]
It's not required, though. A reading system doesn't have to have a viewport, for example.

But it looks like another case of difference between what people have come to understand and the original design. From what I see, SVG support is not a requirement even when there is a viewport. Under the SVG RS requirements, a reading system is only required to support SVG Content Documents if it has an SVG Viewport (which is a strange way of saying it must support SVG if it supports SVG).

Going by Ivan's prose, I think we can clarify along the lines of the XHTML requirement to: "If it has a Viewport, it MUST support the image core media types". The SVG Viewport statement in content documents can then similarly be changed to "If it has a Viewport,".

My only concern is why the WG made SVG optional based on the rendering capabilities of the RS, even when it has a viewport. I don't recall any discussion of this in 3.0, but I missed the early stages.

**Comment by dauwhe** [comment]
I think there's a useful distinction between audio-only reading systems and reading systems with a visual component. But if the reading system displays content visually, I think we should require it to support SVG and all the other image core media types. 

To put it another way, can there be a conforming visual reading system that supports HTML but not JPEG?

**Comment by iherman** [comment]
> I think there's a useful distinction between audio-only reading systems and reading systems with a visual component. But if the reading system displays content visually, I think we should require it to support SVG and all the other image core media types.

+1

> To put it another way, can there be a conforming visual reading system that supports HTML but not JPEG?

At this day and age… I do not think so!

**Comment by mattgarrish** [comment]
I don't personally disagree, but making SVG support optional is not just a slip in one bullet. It appears to be deliberate, and I'm not sure why.

@GarthConboy @mgylling do you recall why this was done?

**Comment by dauwhe** [comment]
The whole section looks like it was written very carefully and deliberately, but the motivations are opaque. It would be helpful to add a note to the spec, I think.

**Comment by mattgarrish** [comment]
The only thing I've discovered is that this might have been written in to account for e-ink devices, or because implementations of SVG weren't complete.

I see some lack of support for SVG in spine, but it doesn't appear to relate to the device being a dedicated e-ink reader:
http://epubtest.org/testsuite/epub3/feature/svg-in-spine/

From a user experience perspective, it's really awkward that we allow SVG documents but don't require support for them. It's probably unlikely there are all that many svg-only epubs, but it still feels like a hole we don't need.

My vote is to clean the requirements up and make SVG support required when there is a viewport, just like for xhtml or images or anything else.

**Comment by laudrain** [comment]
+1

**Comment by iherman** [comment]
+1

**Comment by mattgarrish** [comment]
Proposed Solution:
- Replace the current vector and raster bullets with the following requirement: "If it has a Viewport, it MUST support the image Core Media Types."
- In the SVG Content Document RS requirements, change "If it has an SVG Viewport" to "If it has a Viewport".
- Delete SVG Viewport as a term.
