### ISSUE TITLE
Conformance definition on fallbacks for foreign resource 

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#762]
In section 4.1.3 of the EPUB 3.1 document it says:

> If a Foreign Resource is data for a script, the script should present the data as a Core Media Type (e.g., use it to draw in an [HTML] canvas element or inject it into the HTML or SVG DOM as native markup). Otherwise, the scripted content must include a Core Media Type fallback (e.g., if writing the data to an [HTML] embedded content element, include an intrinsic fallback alternative).

This isn't clear. Grammatically, "otherwise" refers the case when the foreign resource is not data for a script; it is unclear how scripted content comes into the picture, that is not the antonym for that sort of data. Did you mean that the "foreign resource", as opposed to "scripted content" must include a core media type fallback?

**Comment by mattgarrish** [comment]
It seems a bit duplicative the more I look at that section. The first paragraph says that foreign resources can't be directly rendered in their native format, so what does saying that a script can't directly present it in its native format really add?

That's all the paragraph is trying to say: scripts have to transform the data or provide a CMT fallback.

How else is it going to present it in its native format except by writing it to an embedded content element?

**Comment by iherman** [comment]
> On 12 Aug 2016, at 20:16, Matt Garrish notifications@github.com wrote:
> 
> It seems a bit duplicative the more I look at that section. The first paragraph says that foreign resources can't be directly rendered in their native format, so what does saying that a script can't directly present it in its native format really add?
> 
> That's all the paragraph is trying to say: scripts have to transform the data or provide a CMT fallback.
> 
> How else is it going to present it in its native format except by writing it to an embedded content element?

I certainly do not have any counterexample in mind at this moment…

**Comment by mattgarrish** [comment]
I was looking at the scripting section, and noticed that we already have a section there about fallbacks.[1] It currently only deals with fallbacks for scripting itself, but maybe we can drop this paragraph and add a second bullet there.

For example:

Scripts that take Foreign Resources as input MUST ensure that any output they generate meets Core Media Type requirements.

(With "Core Media Type requirements" linking to section 4.1 in the epub 3.1 spec.)

[1] http://www.idpf.org/epub/31/spec/epub-contentdocs.html#confreq-cd-scripted-flbk

**Comment by iherman** [comment]
Sounds like a solution...

**Comment by mattgarrish** [comment]
Proposed Solution:

Delete the redundant paragraph about script data from the foreign resources section and add the following bullet to the scripting fallback requirements:

Scripts that take Foreign Resources as input MUST ensure that any output they generate meets Core Media Type requirements.

**Comment by mattgarrish** [comment]
I'd like to amend the wording of this proposal slightly. The output of scripts must meet core media type requirements regardless of the input, so better to shorten to:

Authors MUST ensure that any output scripts generate meets Core Media Type requirements.
