### ISSUE TITLE
BCP or RFC?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#764]
At the moment:
- 3.4.3.1.3, language element defines the values referring to RFC5646. 
- 3.4.11, when defining opf:alt-script-lang refers to the values as BCP47

I believe the two are actually identical (to be checked...) but I think it would be better to be consistent in the document and use only one...

**Comment by mattgarrish** [comment]
A comment was made on list that it should reference BCP 47.

BCP 47 combines RFC 5646 and RFC 4647, so I wonder if the RFC reference in dc:language is the one that needs correcting? I took at look at HTML 5.1 and SVG 2 and they both make reference to BCP 47 for their language attributes.

@murata0204 any thoughts on this?

Whether we correct depends on the outcome of issue #755, as the attributes could be dropped.

**Comment by murata2makoto** [comment]
In the 5th edition of XML, we have this reference.

> IETF BCP 47
> IETF (Internet Engineering Task Force). BCP 47, consisting of RFC 4646: Tags for Identifying Languages, and RFC 4647: Matching of Language Tags, A. Phillips, M. Davis. 2006.

In HTML5, we have this reference.

> [BCP47]
> Tags for Identifying Languages; Matching of Language Tags (URL: http://www.ietf.org/rfc/bcp/bcp47.txt), A. Phillips, M. Davis. IETF.

They are practically equivalent.  I think that we should do the same.

**Comment by mattgarrish** [comment]
Proposed Solution:

Update the dc:language definition to reference BCP 47 instead of RFC 5646.
