### ISSUE TITLE
Minor editorial knit: consistency in references:

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#767]
Two paragraphs above 3.4.3.2 in the package document it says:

> Languages may differ from Rendition to Rendition.

where the first 'Rendition' is a hyperlink to its definition and the second one is not. Isn't it better to have them as identical? 

(Just being picky:-)

**Comment by mattgarrish** [comment]
> Links to term definitions have a dotted blue underline. Only the first instance in each section is linked.

I thought this was stated in the terminology section, but it's kind of buried in the typographic conventions. In a nutshell, it was to balance definition linking with usability (i.e., avoid the effects of excessive linking on AT users).

**Comment by iherman** [comment]
> On 12 Aug 2016, at 14:20, Matt Garrish notifications@github.com wrote:
> 
> Links to term definitions have a dotted blue underline. Only the first instance in each section is linked.
> 
> I thought this was stated in the terminology section, but it's kind of buried in the typographic conventions. In a nutshell, it was to balance definition linking with usability (i.e., avoid the effects of excessive linking on AT users).

Yes, that makes sense in general. It does look funny when the two words are repeated in the same sentence...

**Comment by mattgarrish** [comment]
Hm, I was looking at an older version. I already fixed the new specifications to state in the terminology that only the first instance is linked, except 3.1 which just lists all the terms. I'm going to propose fixing that.

**Comment by mattgarrish** [comment]
Proposed Resolution:
- Add a note to the terminology section in 3.1 that only the first instance is linked
- Change "The X MAY differ from Rendition to Rendition" to "The X for each Rendition MAY differ." where this phrasing has been used.
