### ISSUE TITLE
Definition of alt-script-tag

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#768]
It says

> Specifies the language used in the opf:alt-script

This is not 100% correct. I may want to use

```
alt-script-tag="zh-hans"
```

to indicate that the language is Chinese  _and_ uses the simplified Chinese character set. Ie, it defines the language and the script...

**Comment by murata2makoto** [comment]
But this is inherited from IETF.  See https://tools.ietf.org/html/rfc5646

**Comment by mattgarrish** [comment]
Closing this as addressed in issue #755. The definition will note an optional script.
