### ISSUE TITLE
Clarify that some prefixes are not necessary, package document, 3.4.4. 

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#770]
The text says:

> This specification reserves the [Meta Vocab] for use with the property attribute, but terms from any vocabulary may be used so long as a prefix is declared for the vocabulary.

It may be worth to emphasize that the reserved vocabularies mean that some prefixes are _not_ required to be defined, because they are done implicitly. This means that the example below _is_ correct, although it may not be clear at first glance due to missing prefix definitions.

**Comment by mattgarrish** [comment]
Proposed Solution:

Update the attribute definitions that allow property values to note the reserved prefixes (hyperlinking to the definition in 4.2.3).

For example, the prose above would become:

This specification reserves the [Meta Vocab] for use with the property attribute. Terms from any other vocabulary MAY be used provided they are prefixed (refer to Reserved Prefixes for a list of prefixes that do not have to be declared).

Also, I'd like to fix the first sentence in 4.2.3 to make explicit their purpose:

"This specification reserves a set of prefixes that Authors MAY use in package metadata _without having to declare_."
