### ISSUE TITLE
Move example in 4.3.2.1.2 in package document

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#771]
At the moment, the example at the end of 4.3.2.1.2. makes use of the `rendition:flow-scrolled-doc` property value which is, in fact, defined in the next section. This makes the example unclear when reading it. I would propose to move it to the end of 4.3.2.1.3. when it shows the usage of both family of values.

**Comment by iherman** [comment]
I actually see that the pattern, ie, having examples that 'forward' refer to features that are not yet defined is repeated over the section on rendition...-(

**Comment by mattgarrish** [comment]
Hm, I think this made sense when we originally ported the FXL spec, but then we split out the spine overrides into new sections.

I guess the easy answer would be to make the examples standalone sections, but maybe there's a way to better integrate..

**Comment by mattgarrish** [comment]
I don't see an easier fix to this. I don't want to bury the spine overrides back between the allowed values and the examples.

**Comment by mattgarrish** [comment]
Proposed Solution:

Make the examples proper sections after the spine overrides.
