### ISSUE TITLE
epub:type or rel in 5.4.2.4. section of Packaging document?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#772]
The text says, right before the example:

> The epub:type attribute is REQUIRED on `a` element descendants for the `landmarks nav` element.

However, in the example following that, all the `a` elements have a `rel` value and none of them have an `epub:type` in them. Either I completely miss something or there is a conflict...

**Comment by mattgarrish** [comment]
A relic of our temporary changeover to HTML and the role and rel attributes. I clearly missed while trying to untangle.

**Comment by mattgarrish** [comment]
Proposed Solution:

Change the rel attributes back to epub:type.
