### ISSUE TITLE
Def. of "viewport"

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#774]
Viewport
The region of an EPUB Reading System in which the content of an EPUB Publication is rendered visually to a User.

I am wondering if "EPUB Publication" should rather be "rendition".    One of the multiple renditions may be selected depending on the screen size.

**Comment by mattgarrish** [comment]
I think this definition is necessarily vague. From the perspective of what a viewport is, it doesn't matter which rendition of any publication is being displayed, only that it's where the content gets displayed.

If anything, I'd maybe strike out "the content of".

**Comment by TzviyaSiegman** [comment]
+1 to @mattgarrish 's comment (remove "the content of")

**Comment by mattgarrish** [comment]
Proposed Solution:

Change viewport definition to: "The region of an EPUB Reading System in which an EPUB Publication is rendered visually to a User."
