### ISSUE TITLE
Def. of "user agent"

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#775]
User Agent
A client or application that consumes generic HTML (e.g., Web browser, screen readers)

I propose to replace "User Agent" by "HTML User Agent".

**Comment by iherman** [comment]
Actually... I am not sure the original definition is correct. What about SVG? A User agent should also consume SVG as a content document, shouldn't it?

**Comment by mattgarrish** [comment]
I'd suggest this is a term we can drop. When it's used, it's clear from the context what kind of user agent is being discussed. I don't think we need to define what constitutes a user agent for another technology.

I only spotted one generic use of the term in an introduction, but it's unnecessary and easily removed.

**Comment by TzviyaSiegman** [comment]
User agent is not defined in W3C specs, so I agree with Matt. No need
define.

**Comment by mattgarrish** [comment]
Proposed Solution:
- Remove User Agent from the terminology.
- Check that existing uses are clear about which kind of UA is being discussed.
- Delete the generic use of UA from the semantics introduction
