### ISSUE TITLE
Conformance: EPUB publications or EPUB containers?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#776]
2.1 Specifications in EPUB 3.1 implies that the EPUB 3.1 family of specs define EPUB publications.
But EPUB publications are not required to be represented by an EPUB Container.  I thus think that we should say "EPUB publications wrapped in EPUB containers".

**Comment by iherman** [comment]
> On 13 Aug 2016, at 08:18, MURATA Makoto notifications@github.com wrote:
> 
> 2.1 Specifications in EPUB 3.1 implies that the EPUB 3.1 family of specs define EPUB publications.
> But EPUB publications are not required to be represented by an EPUB Container. I thus think that we should say "EPUB publications wrapped in EPUB containers".

Much as I would like to see generic EPUB be separated from containers, I presume that is the practical reality. Breaking that link was, after alll, the reason of the BFM work, but we could not bring it to a standard...

**Comment by murata2makoto** [comment]
My bad.  EPUB Publications are already required to be stored in EPUB containers.
