### ISSUE TITLE
Should EPUB Accessibility 1.0 be a part of the EPUB 3.1 family?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#777]
I think that it should not be a part of 3.1, since is is applicable to 3.0.1 and even 2.0(?).

To sell this spec well, we should certainly reference it from the 3.1 spec and emphasize its importance.

**Comment by mattgarrish** [comment]
We've set inclusion in the 3.1 "family" as referenced normatively. It doesn't mean exclusive to a version.

CFI and Alt Style Tags are not specific to a version of EPUB, either. We removed CFI from the list because we dropped the requirement to support it for hyperlinking.

**Comment by TzviyaSiegman** [comment]
I agree with @mattgarrish. Further, referring to the accessibility spec is a way to market it. The Accessibility Spec can be updated independently, so this reference is timeless.

**Comment by mattgarrish** [comment]
Closing without action.
