### ISSUE TITLE
Conformance of EPUB publications in the EPUB 3.1 spec

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#778]
Packages
 It must include at least one Rendition of the content that conforms to the requirements for EPUB Packages defined in [Packages 3.1].

Is it possible to have another Rendition that DOES NOT conform to [Packages 3.1]?

I do not know what "of the content" means.  Is this redundant?

**Comment by mattgarrish** [comment]
Proposed Solution:

Reword to: "It MUST include one or more EPUB Packages, each of which MUST conform to the requirements defined in [Packages 3.1]"

**Comment by murata2makoto** [comment]
Agreed.

**Comment by rdeltour** [comment]
I'm slightly worried that the Packages / Rendition terminology might be confusing here. For most people, "package" means "something wrapped in a box"; in computing, packages almost always match there physical archived representation; so it sounds a bit peculiar to have several Packages in a ZIP.

Additionally, there is a strong correlation between "Rendition" and "Package" it sounds almost as if the two are interchangeable. Would it make sense to get rid of "EPUB Package" and instead adapt and use "Rendition" everywhere?

I know I'm late to the party, sorry. Feel free to disregard.

**Comment by mattgarrish** [comment]
I don't completely disagree, but we also adapted this terminology from OPF.

We could make the specification title singular and drop "EPUB Package" as a term. The package would be all the renditions instead of one.

The term is not extensively used, so it's not a big change.

**Comment by mattgarrish** [comment]
Actually, I don't think we could keep the title. The specification defines conformance for one rendition. Either the specification name needs to change or we should keep as-is.

**Comment by rdeltour** [comment]
or make the term "EPUB Rendition Package" instead of "EPUB Package"?
Btw, This naming issue is linked to what was discussed in #773.

**Comment by mattgarrish** [comment]
That kind of sounds like a mouthful.

Adding "EPUB Package" was done to fit the separation of specifications. We previously were using Rendition where package now occurs (with some new additions). I forget why we didn't want to call the specification renditions. It might have been the lack of awareness generally for renditions, so trying to keep specification names that people already associate with epub.

I've sent the chairs a request to look at this, so will wait and see what input they have.

**Comment by GarthConboy** [comment]
Hmmm... on the surface it seems reasonable.

BUT, we're still not sure "multiple renditions" will ever get traction, and switching to "Rendition" seems like an indication that we think it will.  And, the Package is the <package> document (we're not proposing to change our root element to match).  So, I think I'd tend to not make this change for 3.1, but it could well be reasonable in the future.

**Comment by mattgarrish** [comment]
Good enough for me. The change to clarify conformance in this issue still stands.

**Comment by dauwhe** [comment]
Publications are contained in containers. Containers contain renditions, which are described by packages, but packages do not contain containers, and packages do not package anything. Reading systems must render the first rendition, but don't have to render other renditions. How could it be any simpler? ;)

**Comment by rdeltour** [comment]
> we're still not sure "multiple renditions" will ever get traction, and switching to "Rendition" seems like an indication that we think it will

I agree that the switch to Rendition is far from ideal... I was primarily wondering if there was a way to avoid the confusion of "ZIP != package", but if better brains than mine don't find any I'm OK for the status quo... (until Multiple Renditions go the way of the ~~dodo~~NCX 😛)

**Comment by mattgarrish** [comment]
Shh, you're highlighting why I mentioned in the other issue it's not worth promoting these concepts too heavily. It never ends well.

Like with "Author", just accept that the epub definitions are beautiful.
