### ISSUE TITLE
Authors should prefer...

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#781]
> 4.2 Resource Locations
> Authors should prefer locating audio, video and script resources in the Container to allow the user access to the entire presentation regardless of connectivity status.

I do not think that specifications should instruct how people should feel.  How about this?

Locating  audio, video and script resources in the Container allows  allow the user access to the entire presentation regardless of connectivity status.

**Comment by mattgarrish** [comment]
The idea of the statement is sound, but it looks like authoring guidance gone normative. What about making it an informative note and keeping the emphasis on internal location:

Note
Authors are encouraged to locate audio, video and script resources in the Container whenever feasible to allow Users access to the entire presentation regardless of connectivity status.

**Comment by mattgarrish** [comment]
Proposed Solution:

Add the guidance as an informative note.
