### ISSUE TITLE
The use of "container" for XML elements

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#782]
EPUB Packages 3.1 uses "container" 11 times.  Most of them refer to 
EPUB containers, but others (the first three) refer to XML elements 
containing something.   We should be consistent.

**Comment by mattgarrish** [comment]
Proposed Solution:

Change introduction to:

"The Package Document is an XML document that consists of a set of elements that encapsulate information about a particular aspect of the Package. These elements effectively centralize metadata,"

Change "root container" to "root element" in package element definition.

Capitalization of "Container" is also terrible, especially in OCF. Capitalize these uses.

In the future, EPUB needs to stop finding shorthands that make technical terms out of common English words.

**Comment by iherman** [comment]
I agree with using root element.

**Comment by mattgarrish** [comment]
We need to drop "Container" as a shorthand for "EPUB Container". Container in OCF refers sometimes to the abstract container and sometimes to the zip container, and it's clear from context which is which. Having to out write the long-form would be downright ugly.

Content Documents also has container-constrained scripts, which has nothing to do with the EPUB Container.

We can still make the above changes, but also change any capitalized instances of "Container" to "EPUB Container".
