### ISSUE TITLE
Use "local resource" and "remote resource" wherever possible

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#783]
EPUB Publications 3.1 do no always use these noun phrases, but rather uses
- outside the container
- inside the Container
- included in the EPUB Container or made available remotely
- it is hosted in the Container

I think that we should say "local resources" or "remote resources" wherever possible.

**Comment by mattgarrish** [comment]
Proposed Solution:

Review and see if the phrasing can be standardized.

**Comment by mattgarrish** [comment]
Noting that we have "remote resource" defined as a term, but don't link to it. We don't have a parallel for local resource.

Recommend we add a definition for local and standardize and link existing phrasing.
