### ISSUE TITLE
Should Section 4 of EPUB 3.1 stay here?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#784]
Section 4 of EPUB 3.1 is:

> 1. Publication Resources
>    4.1. Core Media Types
>    4.1.1. Introduction
>    4.1.2. Supported Media Types
>    4.1.3. Foreign Resources
>    4.2. Resource Locations
>    4.3. XML Conformance

I am wondering whether 4.1 and 4.2 should rather be moved to different 
specifications.  All other topics in 3.1 are obviously more generic, but 
4.1 and 4.2 are less generic.  Publications 3.1 is an obvious choice.

Does 4.3 apply to container.xml?  Is it a publication resource?

**Comment by mattgarrish** [comment]
Isn't the rendition mapping document a publication resource? It's not bound to any specific rendition.

That's why we chose to keep these publication resource requirements above packages. I don't see benefit in trying to hive off parts of the section.

**Comment by GarthConboy** [comment]
I think okay for 3.1 as is.

**Comment by mattgarrish** [comment]
Closing without action.
