### ISSUE TITLE
refines: deprecated or obsolete?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#785]
Refines is superseded in [Packages 3.1](http://www.idpf.org/epub/31/spec/epub-packages.html#attrdef-meta-refines) ,but is marked as obsolete in [EPUB 3.1](http://www.idpf.org/epub/31/spec/epub-spec.html#index).

**Comment by mattgarrish** [comment]
It's superseded. The index is informative; it carries no weight. Will correct.

**Comment by mattgarrish** [comment]
Proposed Solution:

As with #786, change both instances to deprecated.
