### ISSUE TITLE
Is the use of refines non-conformant?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#786]
In Annex A of EPUB 3.1,  the 2nd bullet for "superseded" 

> Authors may include the superseded feature for compatibility with older versions of the specification, but must use the replacement feature for conformance with the current specification.

Assuming that "refines" is superseded, I think that the second half of this sentence makes the use of "refines" non-conformant.   I strongly believe that refines should be allowed.

**Comment by mattgarrish** [comment]
I think we should look at whether refines is deprecated, not changing the definition. It was resolved to make it superseded by the new attributes, but technically what we're doing is deprecating: warning it will be removed but retaining support.

Supersede is intended to handle cases like the ncx as it was defined in 3.0(.1): allowed quietly in the package but must not be supported. Obsolete was added to bump inclusion to an error, making a path of increasing severity from superseded to removal..

**Comment by mattgarrish** [comment]
Proposed Solution:

Change refines attribute to deprecated.
