### ISSUE TITLE
Unstable Features in 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#788]
[Appendix A ](http://www.idpf.org/epub/31/spec/epub-spec.html#sec-overview-deprecated)of 3.1 defines "deprecated", "superseded", and "obsolete".   Some specs provide list of such features in appendixes.

I created [a Google spreadsheet](https://docs.google.com/spreadsheets/d/15crVdUL_yKZbc7uLEpCX947X7QRtSAU05-QVuexOiNw/edit#gid=0) to compare them and to provide lists of such unstable features.

It appears that "depcreated" and "obsolete" are very similar.  The only difference is that RSs are required to support deprecated features.  Is this correct?  Are there real differences between deprecated and obsolete features?

**Comment by mattgarrish** [comment]
That's the key difference. Is there an issue here?

**Comment by mattgarrish** [comment]
Closing this as covered by the proposed changes in #822.
