### ISSUE TITLE
Publication Rendering Metadata in EPUB Packages 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#789]
I believe that ["Publication Rendering Metadata"](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-metadata-rendering) is about renditions rather than publications.  In fact, all properties begin with the prefix "rendition:".  I propose to rename it as "Rendition Rendering Metadata".

**Comment by mattgarrish** [comment]
"Package Rendering Metadata" would be more accurate, especially given the parent section.

Rendition is an abstract term, but we're stuck with it for the FXL prefix.

**Comment by mattgarrish** [comment]
Proposed Solution:

Rename section and vocabulary to Package Rendering Metadata.
