### ISSUE TITLE
Publications identifiers are not about packages.

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#790]
[Publication identifiers](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-metadata-identifiers) are defined in [Package Metadata](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-metadata).  But publication identifiers are not about packages.  (This is my understanding.  Ideally, I would like to rename "publication identifiers" as "rendition identifier", and introduce another identifier in container.xml.  But I don't think that we can  do so.)

**Comment by mattgarrish** [comment]
Similar to my comment in #773, I don't think it's worth trying to change this now.

Even in MR we had to concede that the default rendition identifier is practically the publication identifier.

**Comment by GarthConboy** [comment]
Agree (for 3.1).

**Comment by mattgarrish** [comment]
Closing for same reason as #773.
