### ISSUE TITLE
Registration of  appliation/epub+zip in OCF 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#791]
I propose to drop the content of [this appendix](http://www.idpf.org/epub/31/spec/epub-ocf.html#app-media-type) but simply refer to [the IANA registration](https://www.iana.org/assignments/media-types/application/epub+zip).

**Comment by iherman** [comment]
> I propose to drop the content of this appendix http://www.idpf.org/epub/31/spec/epub-ocf.html#app-media-type but simply refer to the IANA registration https://www.iana.org/assignments/media-types/application/epub+zip.

I do not know of the IDPF "traditions" in this respect. Ie, just as an info: W3C specifications that also define to a new media type routinely add and keep a similar appendix in the specifications. I guess it is easier for the reader of the spec to see and find it (finding an IANA registration is not always that easy) and it also has a historical side to it, insofar as this type of documentation is what has to be provided for a IANA registration in the first place.

**Comment by iherman** [comment]
I just realized, answering to #792, that the special situation of W3C may come from the fact that, for W3C specifications, the specification itself is considered as the formal document for a media type, hence keeping it in the recommendation. In view of the possible future W3C/IDPF merge, it may be one more reason why keeping that appendix in the document may be better.

**Comment by murata2makoto** [comment]
I did the XML media type registration, and was detached from the XML recommendation.  Later, W3C started what you described.

If IDPF mimicks what W3C is doing without having a special agreement, it will become difficult for the reader to understand which registration is correct.  The one at IANA, or the one in IDPF specs?

**Comment by mattgarrish** [comment]
This looks like a case for deferral to another revision. Same for the similar issue raised in #792 

/cc @TzviyaSiegman @mgylling @GarthConboy

**Comment by TzviyaSiegman** [comment]
I agree with deferring to another version.

**Comment by iherman** [comment]
+1

**Comment by murata2makoto** [comment]
What do you mean by "deferring"?  Status quo?  I don't like it.

Moreover, neither the appendix nor the IANA registration mention 3.1.  Both are problematic.

**Comment by dauwhe** [comment]
The current text refers to the IDPF registry of linking schemes as well as Bill McCoy's IDPF email address. That's in addition to linking to OCF 3.0 as the current version of the spec. 

I think we should figure this out.

**Comment by HadrienGardeur** [comment]
This is also related to #1026 since the registration would have to include parameters.

**Comment by GarthConboy** [comment]
Defer decision to include @murata2makoto (hopefully in a soon weekly call).

**Comment by dauwhe** [comment]
Question for @murata2makoto : How would we update the IANA registration? Can you do this? If so I strongly support your proposal.

**Comment by dauwhe** [comment]
See also #1048. 

@murata2makoto should we do the same thing with the registration of `application/oebps-package+xml`? https://www.iana.org/assignments/media-types/application/oebps-package+xml

Note the IANA version here describes Nick Bogarty as the contact person :)

**Comment by murata2makoto** [comment]
@dauwhe I believe that I filled out a form available at https://www.iana.org/form/media-types   Yes, we should update the registration of application/oebps-package+xml as well.

**Comment by dauwhe** [comment]
W3C has procedures for this, which may only apply to a working group: https://www.w3.org/2002/06/registering-mediatype2014.html

**Comment by iherman** [comment]
@dauwhe unfortunately those procedures have been set up for WG-s: essentially, a W3C Rec is accepted by IANA as the necessary documentation for a media type. This does not work, automatically, for CG reports... 😞

**Comment by murata2makoto** [comment]
I now think that we should try to be consistent with recent W3C specs that introduced media types.  In other words, keep the appendix, and just copy it to the IANA form (https://www.iana.org/form/media-types).

**Comment by murata2makoto** [comment]
As in #792, we should introduce required changes to the Appendix F and then fill out the form (https://www.iana.org/form/media-types).  We should do so after we complete EPUB 3.2 .

**Comment by dauwhe** [comment]
Updated with #1055
