### ISSUE TITLE
Superseding RFC 4839

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#792]
[RFC 4839](https://tools.ietf.org/html/rfc4839) is superseded by [Annex C](http://www.idpf.org/epub/31/spec/epub-packages.html#app-media-type-app-oebps-package) of EPUB Packages 3.1.

I don't think that we should do so.  We should rather submit an I-D for superseding 4839 and request IESG to publish it as an RFC.  @iherman, does W3C now have any rules for media type registration?

**Comment by iherman** [comment]
@murata0204, I am not sure what you ask as for 'rules'. I am not familiar with the official details, but W3C has some special agreements with IETF, whereby W3C specifications may contain the media type specification and are directly referred to from the registries (ie, no need for a separate submission). The submission rules and procedures are also a bit simplified for W3C. But I am not sure of the exact details.

**Comment by murata2makoto** [comment]
Ivan, thank you.  EPUB 3.1 is not (and will not be) a W3C spec, and thus IDPF cannot rely on the special agreements between W3C and IDPF.  I continue to believe that we should submit an I-D.

**Comment by iherman** [comment]
> On 15 Aug 2016, at 12:01, MURATA Makoto notifications@github.com wrote:
> 
> Ivan, thank you. EPUB 3.1 is not (and will not be) a W3C spec, and thus IDPF cannot rely on the special agreements between W3C and IDPF.
> 
> That is correct. But: it is a matter of a separate agreement between IDPF and W3C (to be part of an upcoming MOU) on how exactly the errata management of EPUB 3.1 will occur.We cannot exclude that a possible EPUB 3.1.1 would have to be published as a bona fide W3C Recommendation at some point. This is independent of any work that may occur on PWP (or EPUB4 or anything similar), which are all things up in the air.

It is due to these options that I favour keeping the document with the appendix as is…

**Comment by TzviyaSiegman** [comment]
See comments on #791

**Comment by murata2makoto** [comment]
Annex C does not reference 3.1 either.

**Comment by dauwhe** [comment]
We've updated the registration in our spec with #1054
