### ISSUE TITLE
Non-conformant content document?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#793]
In [2.1 Content Conformance](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-content-conformance) of EPUB Packages 3.1, requirements on constituents of packages are listed.

The first one uses a which clause, but others are not.  I think this discrepancy is strictly speaking a problem.  For example, consider

> EPUB Navigation Document
>   It must contain exactly one EPUB Navigation Document conformant to the content requirements defined in EPUB Navigation Documents — Content Conformance.

I would argue that a package may contain other navigation documents non-conformant to  the content requirements defined in EPUB Navigation Documents.  I propose:

> EPUB Navigation Document
>   It must contain exactly one EPUB Navigation Document, which MUST conform to the content requirements defined in EPUB Navigation Documents — Content Conformance.

This rewrite is similar to the first one, and is clearer.  The same rewrite can be applied to other constituents.

And we have:

>   It must contain at least one EPUB Content Document conformant to the content requirements defined in [Content Docs 3.1].

I would propose:

>   It MAY contain one or more EPUB Content Documents and MUST contain at least one such.  Each MUST conform to the content requirements defined in [Content Docs 3.1].

**Comment by mattgarrish** [comment]
How could you include navigation documents that aren't conformant when only one document can be marked as the navigation document? They'd just be content documents.

I find your latter proposal more confusing. If you want to separate conformance, it can similarly be stated as:

It MUST contain one or more EPUB Content Documents, each of which MUST conform to the content requirements defined in [Content Docs 3.1].

**Comment by mattgarrish** [comment]
Proposed Resolution:

Leave navigation document definition as-is.

Separate conformance requirement from cardinality for content docs:

"It MUST contain one or more EPUB Content Documents, each of which MUST conform to the content requirements defined in [Content Docs 3.1]."

**Comment by TzviyaSiegman** [comment]
I think the new proposal is redundant. I am not sure what the objection to the old language is. By definition, a "navigation document" is conformant. It seems sloppy to add extra MUSTs.

**Comment by mattgarrish** [comment]
It's pedantic. Technically there are two requirements: one for cardinality and one for conformance. There remains no way to include more than one navigation document, though, I agree. I'll remove from the proposal, as I wasn't paying attention to my own comment.

I'd keep for content documents just because the current wording does suggest that non-conformant xhtml might be tolerable.

**Comment by OriKuttner** [comment]
I think it should say "It MUST contain once EPUB Content Document..."
There can't be more then one EPUB content document, any other is just another XHTML file.

**Comment by murata2makoto** [comment]
My objection to the original language is that it appears to suggests that some navigation documents can be non-conformant.  Yes, I'm pedantic, but I am used to this level of pedantic review.

**Comment by mattgarrish** [comment]
Pedantic is fine, but in this case the realism of being able to insert two "nav" items is implausible.

I'll probably edit this section with an eye to splitting out conformance from each item, as conformance in most cases can be made clearer. I agree there shouldn't be a suggestion that invalid alternatives are allowed. For symmetry, I'll write the nav requirement the same way.
