### ISSUE TITLE
Content document, 2.4.1.2: emphasize need for xmlns?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#794]
On the usage of `epub:type`: although it can be inferred from all the other specification point, I wonder whether it is not worth adding that the HTML code MUST include the relevant xmlns attribute on a parent (and it is recommended to put on the html or body element).

**Comment by mattgarrish** [comment]
I'm against just because we have a bunch of namespaced element and are we going to do this for all of them?

We do state that you are required to declare the prefixes in the namespace prefix mapping section, too:
http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-overview-pfx

**Comment by iherman** [comment]
You're right. Closing with no further step.
