### ISSUE TITLE
Content document, 2.4.1.3: placement restriction on the prefix

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#795]
Currently, the document says:

> The prefix attribute is only valid on the [HTML] root html element.

Why is there a need for this.?Technically, this is a restriction on the XML usage; it may be recommended, but why is it a must? (Yeah, thus is a detail.)

**Comment by mattgarrish** [comment]
It was done to simplify reading system implementations (avoid having to look up the entire ancestor chain and compile all declarations to determine what prefixes are valid).

It does make content repurposing more complicated, but the use of prefixes also hasn't really ever taken off.

**Comment by mattgarrish** [comment]
The epub:type attribute is itself quite simple in nature, too. It does basic structural inflection, not class/type encapsulation, so changing prefixes isn't common within a document.

**Comment by iherman** [comment]
> On 15 Aug 2016, at 13:37, Matt Garrish notifications@github.com wrote:
> 
> It was done to simplify reading system implementations (avoid having to look up the entire ancestor chain and compile all declarations to determine what prefixes are valid).
> 
> I take your point. Although… having implemented RDFa (which has the same feature), it is not such a huge deal. But o.k….
> It does make content repurposing more complicated, but the use of prefixes also hasn't really ever taken off.

O.k., in which case we can disregard this issue:-)
