### ISSUE TITLE
Content document, spelling and (possible) English mistakes

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#797]
- [ ] First sentence in 3.5: "synatx" -> "syntax"
- [ ] Note in 4.2: "Fixed and absolute positioning are particularly likely to be problematic." sounds a bit strange for my non-anglo-saxon ears; shouldn't it be "Fixed and absolute positioning are likely to be particularly problematic." (But I do not claim to speak a proper enough English...) 
- [ ] Second paragraph in A.3: "number of properties, about" -> "number of properties about" (no comma)

**Comment by mattgarrish** [comment]
I'd chart a third option for your second item: "Fixed and absolute positioning are particularly problematic."

**Comment by mattgarrish** [comment]
Proposed Solution:

Fixed errors as noted in comments above.
