### ISSUE TITLE
Content document, 5.2 Content conformance for spine-level scripts

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#798]
The text says:

> ... when the document is rendered by a Reading System without scripting support or with scripting support disabled, the top-level document content MUST retain its integrity, remaining consumable by the User...

While I understand and agree with the intention, it bothers me to have a MUST conformance criteria that cannot be properly checked. Which I believe is the case here; I do not see any checker that would be capable of making a clear yes or no check on something like that. If so, then I believe this should be a SHOULD rather than a MUST...

**Comment by mattgarrish** [comment]
Yes, this is actually an old issue. It's understood, especially for scripting, that not everything we normatively define can be checked by machine.

I'm sure this was raised in relation to the progressive enhancement requirement, too, possibly during 3.0.1. We've resolved in the past not to remove/diminish, but I'll leave this to the chairs whether to reopen.

**Comment by TzviyaSiegman** [comment]
If we open this, I think we open many other scripting-related issues. We will probably have to revisit this and related issues in a later draft, but I think it's OK to leave as is for 3.1.

**Comment by GarthConboy** [comment]
Agree.  Okay for 3.1 as is.  Yes, not machine check-able, but really what we want.  :-)

**Comment by mattgarrish** [comment]
Closing without action.
