### ISSUE TITLE
Content Document, 6.2, RS Conformance

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#799]
Second entry says

> It MUST use the dimensions expressed in the viewport meta tag to render XHTML Content Documents, but MAY obtain these dimensions from the package rendition:viewport property [Packages 3.1].

However, the rendition:viewport property is marked as deprecated, and the content document must include a viewport per section 6.4. In other words, the rendition:viewport is completely out of the equation; as a consequence, I would say any reference to it should be removed from the conformance clause here.

The same comment applies to the clause after it, that has a similar reference to SVG

**Comment by mattgarrish** [comment]
I left it because deprecated means it's still supported in reading systems.

Maybe we could move to an unstable features section and recommend against RSes using the meta declaration?

Or should we just strip the property entirely from the specifications given that we have a new version number?

**Comment by iherman** [comment]
> On 15 Aug 2016, at 14:05, Matt Garrish notifications@github.com wrote:
> 
> I left it because deprecated means it's still supported in reading systems.
> 
> Maybe we could move to an unstable features section and recommend against RSes using the meta declaration?
> 
> Or should we just strip the property entirely from the specifications given that we have a new version number?

This is always such a gray area:-)

At this moment my preference would to to your second option

**Comment by mattgarrish** [comment]
Proposed Solution:

Move the prose about using obtaining the viewport from the package document to an unstable features appendix.
