### ISSUE TITLE
Content Document, 6.4.2., example ICB in SVG

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#801]
The example says:

```
<svg xmlns="http://www.w3.org/2000/svg"
     version="1.1" width="100%" height="100%"
     viewBox="0 0 844 1200">
   …
</svg>
```

However, in this case, as far as see the value of `width` and `height` is meaningless, it does not give any new information to the display. If I am right, I do not think it should be kept in the example, because we should not suggest the author to put in unnecessary attributes.

**Comment by mattgarrish** [comment]
It's done in practice to make the SVG fill the screen, but I don't see that it's necessary to reproduce.

**Comment by mattgarrish** [comment]
Proposed Solution:

Remove the width and height attributes.
