### ISSUE TITLE
Media Overlays: meaning of textref

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#802]
The `epub:textref` attribute appears in the definitions and in the examples, but the only description I found is the (standard) attribute description:

> The relative IRI reference [RFC3987] of the corresponding EPUB Content Document, including a fragment identifier that references the specific element as per the [XPTRSH].

but this does not say anything on what this thing is _used_ for. I _guess_, based on the example, that it provides a reference to the element on which the `epub:type` attribute applies to in a Media Overlay setting, but it is just a guess (and therefore may be wrong). Would be good to give a proper description to it somewhere...

**Comment by mattgarrish** [comment]
body and seq are a grouper elements, so the epub:textref attribute is used to provide a pointer to the corresponding structure that they represent. For example, if you have a table in a content document, you would have a seq that references the table element and then nested seq elements that reference each row.

It's giving explicit context for the body/seq, in other words. I'm not aware that the reading system has to do anything with these references, though, which may be why they're not greatly elaborated on. @danielweck might have more insight.

Maybe we could make this clearer in 3.2.1, as this sentence omits mention of the fragment:

"Each seq element must contain an epub:textref attribute which references the corresponding EPUB Content Document element by IRI reference."

**Comment by iherman** [comment]
What I would like to see somewhere is the first paragraph of what just said:-) I do not think the paragraph you propose makes it any clearer...

**Comment by mattgarrish** [comment]
I wasn't proposing that last quote as a replacement. It's the current wording from 3.2.1, but doesn't even mention that seq is supposed to reference a specific element in the content.

3.2.1 just looks like the logical place to expand on this, and we could hyperlink down from the attribute definitions.

**Comment by iherman** [comment]
Ah, sorry, misunderstood you. You mean put, essentially, something like your first paragraph above into section 3.2.1? Works for me.

**Comment by mattgarrish** [comment]
Right.

**Comment by mattgarrish** [comment]
Proposed Solution:

Add explantory prose about purpose of textref to 3.2.1 and link from attribute definition.

**Comment by mattgarrish** [comment]
Looking at 3.2.1, I think it could use some additional reorganization. It discusses matching element to reading order before mentioning the elements, for example. Propose the following rewrite:

"The body of a Media Overlay Document consists of two elements: the par element and the seq element. The ordering of these elements MUST match the default reading order of the EPUB Content Document.

The par element represents phrases. Each element identifies a text and audio component to sychronize during playback.

The seq element represents sequences. It is used to represent nested containers such as sections, asides, headers, and footnotes. It allows the structure inherent in these containers to be retained in the Media Overlay Document.

The seq element MUST contain an epub:textref attribute. The IRI [RFC3987] value of this attribute MUST reference the corresponding structural element in an EPUB Content Document. As seq elements do not provide synchronization instructions, this attribute allows a Reading System to still match the element to a location in the text."

**Comment by iherman** [comment]
Thank you. Now I understand what it is for! :-)

👍
