### ISSUE TITLE
Media Overlays: usage of the '-' character for active classes

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#803]
All the examples for (playback) active classes use the `-` character as a leading character, as in:

```
...property="media:active-class">-epub-media-overlay-active</...
```

while technically correct, I am bothered by it. The CSS practice these days is to use the `-` character for user-defined or user agent specific (CSS) _properties_ or CSS variables. However, the usage in this document is simply a special class name which, though assigned to an element dynamically, is really just that: a class name. I think using the `-` is misleading for the reader (it took me a certain time to realize that we do not define a special CSS property here!).

I would propose to remove that leading `-` character.

**Comment by mattgarrish** [comment]
Sounds reasonable to me.

@danielweck @marisademeglio any thoughts on removing the hyphen from the start of the MO class names?

**Comment by danielweck** [comment]
The "-epub-*" prefixed CSS class name is illustrative only. I am okay with removing the prefix in all the examples.

**Comment by mattgarrish** [comment]
Proposed Solution:

Remove the leading hyphens from the class names.

**Comment by GarthConboy** [comment]
Hmmm... many publications leave out the specification of class name, but expect a default to be used.  For example Play Books uses:

```
String DEFAULT_MEDIA_OVERLAY_ACTIVE_CLASS =
        "-epub-media-overlay-active media-overlay-active";
```

The latter is what early iBooks defaulted to, and former is what many publications expect (incorrectly) to "just work."  I think I'd be leery of making this change.

**Comment by iherman** [comment]
Ouch. You mean the class names used in the examples have become rules? Sigh...

**Comment by mattgarrish** [comment]
But if someone declares the class with a different name, it should work if author styling is supported, right? Or does the reading system ignore the declaration and only look for that class name?

If the issue is some people don't understand the spec and only create a CSS class, isn't better to get them out of the habit? Or are we looking at a sh*tstorm of complaints?

**Comment by GarthConboy** [comment]
Ivan, yes.

And, yes, if something else is specified, it works as expected.

My take is it wouldn't be a sh*tstorm, but would be an irritation that we could avoid by leaving this one alone.
