### ISSUE TITLE
Media Overlays: example in 3.5.1

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#804]
Isn't it correct, per 3.5.2. that the `ch1_audio` element should have a `duration` attribute to make the example correct?

**Comment by mattgarrish** [comment]
Yes, the change from a property to an attribute has made a mess of this earlier section.

We should move the definition of the duration attribute up to 3.5.1 and include the attribute in the examples. 3.5.2 will then correctly focus only on the properties in the metadata section again.

**Comment by mattgarrish** [comment]
Proposed Solution:
- move the duration attribute definition to 3.5.1
- add sample durations to the example
- remove the manifest from the example in 3.5.2
