### ISSUE TITLE
Media Overlays: constraints on media overlay files (3.5.1.)

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#805]
Section 3.5.1. is part of section 3.5., ie, packaging. This includes the following statement:

> A single Media Overlay file may refer to more than one EPUB Content Document, but an EPUB Content Document must not be referenced by more than one Media Overlay file.

However, at least the second statement, is _not_ a clause that can be checked within the package file, ie, the manifest; it is a package level constraint on media overlay files (unless I misunderstand something). On the other hand, all the other statements in this section _are_ on how media overlays should be incorporated into the manifest. That led me astray for a while, because I was wondering on how the second part applies here (an `item` for a media overlay file does not have any back-reference to the content document it refers to in the manifest). 

I am not sure how to solve this properly, I must admit. Maybe simply calling out the fact that this requirement is on the package overall and _not_ on the manifest within the package file.

**Comment by mattgarrish** [comment]
Agree that this is not about packaging. It appears to belong under the "Relationship to the EPUB Content Document" section, but none of the existing sections fit.

I guess we could have a one-sentence section, as odd as it sounds. But then we'd need a conformance requirement to point to a one-sentence section. Yuck.

Then again, maybe we can just drop this straight into the content conformance requirements for MO documents in 2.2:

"It MAY refer to more than one EPUB Content Document, but an EPUB Content Document must not be referenced by more than one Media Overlay Document."

That's the best I can come up with.

/cc @danielweck @marisademeglio

**Comment by iherman** [comment]
I can live with your second option. It sounds about right.

**Comment by mattgarrish** [comment]
Proposed Solution:

Move to the conformance requirements as noted above.
