### ISSUE TITLE
Package conformance rather than content conformance in Packages 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#806]
Content Document 3.1 has 2.2 Content Conformancefor HTML, and 3.2 Content Conformance 
for SVG.  Meanwhile, OCF has  2.1 Container Conformance.

But Packages 3.1 has 3.2 Content Conformance.  It should rather be "Package Conformance".

**Comment by mattgarrish** [comment]
That's because OCF 2.1 has a top-level conformance definition. Same as the umbrella spec.

Whenever we define a document type conformance, we've always used "content conformance", as you've pointed out for SVG and HTML.

I'd recommend changing section 2 to:

```
2. Conformance
   2.1 Package Conformance
   2.2 Reading System Conformance
```

**Comment by mattgarrish** [comment]
Proposed Solution:

Rename sections as specified in my previous comment.
