### ISSUE TITLE
3.4.1 The package Element in EPUB Packages 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#811]
I think that the second half of this sentence is not needed and arguably incorrect, because collections and spines are neither metadata nor resource information.

> [3.4.1 The package Element](http://www.idpf.org/epub/31/spec/epub-packages-20160801.html#sec-package-elem)
> 
> The package element is the root container of the Package Document and encapsulates metadata and resource information associated with an EPUB Package.

**Comment by mattgarrish** [comment]
I'd argue that the spine is a form of metadata and collections provide more complete resource information than the manifest, but I think it's pointless to explain that the root element encapsulates everything inside the root element. We have a general description of what it encapsulates in the intro.

**Comment by mattgarrish** [comment]
Proposed Solution:

Remove the prose from "and encapsulates" on.

**Comment by OriKuttner** [comment]
I would keep it as it is since it does encapsulate both metadata and resource information.

**Comment by murata2makoto** [comment]
If it encapsulates more than that, we should either enumerate all or remain silent.

**Comment by mattgarrish** [comment]
We could change to:

"The package element is the root element of the Package Document. It defines various aspects of the EPUB Package, as described in the introduction."

This would keep it from being a generalized repetition.

**Comment by rdeltour** [comment]
> "The package element is the root element of the Package Document. It defines various aspects of the EPUB Package, as described in the introduction."

Isn't it a problem to refer to the informative introduction in this normative definition?

**Comment by mattgarrish** [comment]
Not for a description, no. If normative requirements slipped into the introduction we'd have a problem.

If "described" is off-putting, we could make the reference a parenthetical:

"The package element is the root element of the Package Document and defines various aspects of the EPUB Package (see the introduction for a general overview)."
