### ISSUE TITLE
Use consistent terms for metadata in Packages 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#812]
We have at least four terms.
- rendering metadata
- presentational metadata
- display and rendering meta
- display and structural metadata

I like rendering or presentational.

**Comment by mattgarrish** [comment]
Proposed Solution:
- Change the sole instance of "presentational" to "rendering"
- Delete "display and rendering"
- Delete the first paragraph of the package document introduction that contains "display and structural". Everything it says is repeated with more detail in the immediately following paragraph.
