### ISSUE TITLE
Why are UUID, DOI, or ISSN not registered in Identifier Schemes Registry?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#813]
While reading  [3.4.3.1.1 The identifier Element](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-opf-dcidentifier) of Packages 3.1, I wonder why this section mentions  UUID, DOI, and ISSN although they are not registered in the  Identifier Schemes Registry.

**Comment by laudrain** [comment]
The identifier registry is a work in progress : see Issue [#753](https://github.com/IDPF/epub-revision/issues/753). Please comment on any other identifier you would need.
