### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#814]
The first link in the first itemized list in [3.4.3.2.5 The subject Element](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-opf-dcsubject) is broken.

**Comment by mattgarrish** [comment]
Proposed Solution:

Fix link to http://idpf.org/epub/registries/authorities/

**Comment by mattgarrish** [comment]
I've fixed this locally and will push with the next updates. Broken links don't need WG review; not sure what I was doing here...
