### ISSUE TITLE
Implementation of collections, Publication  3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#817]
I think that we should avoid the term "implementation" in [3.4.10 The collection Element](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-collection-elem).  How about "specialized collections"?

**Comment by mattgarrish** [comment]
"Specialized collections" is clunky and would take too much rewriting, but I'm fine with changing "implementations" to "specializations".

**Comment by mattgarrish** [comment]
Proposed Solution:

Change "implementations" to "specializations".
