### ISSUE TITLE
May tailor the requirements, in Packages 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#818]
This phrase appears in [3.4.10 The collection Element](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-collection-elem) .  But sentences following this phrase prohibit deviation from the stated requirements.  I think that "my introduce additional requirements on top of " would be clearer.  Then, we can remove the sentences following this phrase.

**Comment by mattgarrish** [comment]
The following wording does not prohibit deviations It requires the content model be valid, but there are many ways to construct the content model, not all of which are wanted.

This wording was agreed on during 3.0.1, so without a more substantive reason to change I'm closing this  without action.
