### ISSUE TITLE
Assining a prefix to default vocabularies

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#820]
I am confused by the last para of   [4.2.2 Default Vocabularies](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-metadata-default-vocab).

> The IRIs associated with the Package Metadata Vocabulary and Metadata Link Vocabulary must not be assigned a prefix using the prefix attribute.

First, should the Package Metadata Vocabulary  be EPUB Meta Properties Vocabulary?

Second, why aren't the EPUB Manifest Properties Vocabulary and the EPUB Spine Properties Vocabulary mentioned?

**Comment by mattgarrish** [comment]
Proposed Solution:

Change to "The IRIs associated with these vocabularies ..."
