### ISSUE TITLE
rendition:flow and rendition:layout for scrollable large pages

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#821]
Somebody recently asked how Webtoon-style comic is supported in EPUB.  Webtoon-style comic is a single page, which is scrolled vertically.  However, such a comic is internally represented by a sequence of
images.

I have thought EPUB 3.0.1 and thus EPUB 3.1 do support Webtoon-style comic, since the rendition:flow property can specify scrolled-doc and scrolled-continuous.  The former is useful when we have a single HMTL containing multiple images.  The latter is useful when we would like to have a sequence of HTML pages, each of which has a single image, and to concatenate them on the fly.

However, I find that [rendition:flow is ignored](http://www.idpf.org/epub/31/spec/epub-packages.html#layout-property-flow) if the rendition:layout value is pre-paginated.  It it ok to specify rendition:layout=reflowable for an HTML document containing images only?

**Comment by GarthConboy** [comment]
In answer to "It it ok to specify rendition:layout=reflowable for an HTML document containing images only?"  Yes.

There are such EPUBs in production use.

**Comment by murata2makoto** [comment]
Thanks!
