### ISSUE TITLE
cleanup of "unstable features"

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#822]
I'd like to rename these sections to "Obsolete Features" as the features aren't necessarily unstable. Their common theme is being old and phased out.

I believe we can do without having superseded and obsolete labels, and instead categorize superseded features as conforming and non-conforming in the appendixes.

The definitions in the 3.1 appendix don't need to change, but superseded becomes superseded and conforming an obsolete becomes superseded and non-conforming.

The NCX in 3.0.1 is an example of superseded but conforming, while in 3.1 it is now superseded and non-conforming.

**Comment by mattgarrish** [comment]
Proposed Solution:

Change appendix name and labels as described in previous comment.

**Comment by murata2makoto** [comment]
This issue is so important that I would like to see the proposed rewrite.

**Comment by mattgarrish** [comment]
A rewrite isn't being proposed. The title changes, superseded gets "and conforming" added and obsolete becomes "superseded and non-conforming":

Appendix A. _Obsolete Features_

Features defined in this specification and its siblings are occasionally removed if they are no longer needed or have been replaced by another feature. Prior to removal, the features are marked as deprecated or superseded as an early warning to the EPUB community. The meaning of these labels are defined as follows.

If a feature is marked as deprecated, the following hold true:
- The feature will be removed in a future version of the specification. The feature is marked as deprecated in order to give Authors and EPUB Reading System developers time to prepare for removal.
- It is strongly recommended that Authors discontinue use of the feature in their EPUB Publications.
- Reading Systems must continue to support the feature as it is defined until it is formally removed.
- Validation tools must alert Authors that inclusion of the feature is deprecated when encountered in an EPUB Publication. It is recommended that the alert be lower in severity than an error or warning.
  
  If a feature is marked as superseded _and conforming_, the following hold true:
- The superseded feature may be removed in a future version of the specification, but there is no definite timeline for removal.
- Authors may include the superseded feature for compatibility with older versions of the specification, but must use the replacement feature for conformance with the current specification.
- Reading Systems must not support the superseded feature in content that conforms to the current version of the specification.
- Validation tools must not alert Authors about the presence of the superseded feature in an EPUB Publication, as it is valid for backwards compatibility. Validation tools must alert Authors if the superseded feature is not conformant to its definition or otherwise breaks a usage requirement.

A feature that is _superseded and non-conforming_ shares the same characteristics of a superseded _and conforming_ feature, but with the following differences:
- The _non-conforming_ feature will be removed in a future version of the specification.
- Validation tools must alert Authors about the presence of _non-conforming_ features. It is recommended that the alert be given the same severity as deprecated features.

**Comment by mattgarrish** [comment]
We don't need two labels to make a chain of obsoletion. The NCX is superseded in both 3.0.1 and 3.1. All that changes is that we want it to be non-conforming now instead of silently allowed. This seems like a cleaner approach to doing that than inventing more labels.

**Comment by murata2makoto** [comment]
I do not understand " but must use the replacement feature for conformance with the current specification." in the 2nd bullet of the 2nd itemized list.  First, does this mean "must use  the replacement feature instead" or  "must use both the superseded feature and the replacement feature", or, "must use the replacement feature and may use the superseded feature"?  Second, if a superseded feature is used, does the EPUB publication conform to EPUB 3.1?

**Comment by mattgarrish** [comment]
That's not really needed since the specification will define what is required and the next bullet covers RS non-support requirements. It means you must follow the new requirements and include the navigation document for conformance with epub 3, for example.

We could also call these cases "superseded" and "superseded and marked for removal". As I mentioned above, we're only changing severity of non-support so it doesn't warrant new labels.

**Comment by mattgarrish** [comment]
Appendix A. _Obsolete Features_

Features defined in this specification and its siblings are occasionally removed if they are no longer needed or have been replaced by another feature. Prior to removal, the features are marked as deprecated or superseded as an early warning to the EPUB community. _A deprecated feature is one that is in the process of being removed from the current version of the specification, while a superseded feature is one that is being retained only for authoring content compatible with an older version._

If a feature is marked as deprecated, the following hold true:
- The feature will be removed in a future version of the specification. The feature is marked as deprecated in order to give Authors and EPUB Reading System developers time to prepare for removal.
- It is strongly recommended that Authors discontinue use of the feature in their EPUB Publications.
- Reading Systems must continue to support the feature as it is defined until it is formally removed.
- Validation tools must alert Authors that inclusion of the feature is deprecated when encountered in an EPUB Publication. It is recommended that the alert be lower in severity than an error or warning.

If a feature is marked as superseded, the following hold true:
- The superseded feature may be removed in a future version of the specification, but there is no definite timeline for removal.
- Authors may include the superseded feature for compatibility with older versions of the specification.
- Reading Systems must not support the superseded feature in content that conforms to the current version of the specification.
- Validation tools must not alert Authors about the presence of the superseded feature in an EPUB Publication, as it is valid for backwards compatibility. Validation tools must alert Authors if the superseded feature is not conformant to its definition or otherwise breaks a usage requirement.

A feature that is _superseded and marked for removal differs from_ a superseded feature in the following ways:
- The feature will be removed in a future version of the specification.
- Validation tools must alert Authors about the presence of _superseded feature that are marked for removal_. It is recommended that the alert be given the same severity as deprecated features.

**Comment by iherman** [comment]
I am not sure I understand this difference between deprecated and superseded:
- For deprecated: "Reading Systems must continue to support the feature as it is defined until it is formally removed."
- For superseded: "Reading Systems must not support the superseded feature in content that conforms to the current version of the specification."

To be specific, I am surprised of the superseded case: why isn't the requirement analogous to the deprecated case? In some sense, the deprecated is a more severe status, but the reading system must still honor it, and the superseded (which is, in my layman term, a bit like deprecated but not clear when it will happen and whether it will be removed at all) has a much more severe consequence of usage (because RS-s will have to ignore it)...

**Comment by mattgarrish** [comment]
It's that way because superseded is for authoring features retained only for backwards compatibility.

To bring up the NCX, it was superseded by the navigation document, but for compatibility with EPUB 2 it is necessary to include. EPUB 3 reading systems must not support this feature, as it is not part of EPUB 3, but content creators can include it. It's not intended to generate warnings until there's a clear case to start discouraging, which is what we found in 3.1.

**Comment by mattgarrish** [comment]
Would it help to add some explanation to this effect to the first paragraph, like:

"Features defined in this specification and its siblings are occasionally removed if they are no longer needed or have been replaced by another feature. Prior to removal, the features are marked as deprecated or superseded as an early warning to the EPUB community. _A deprecated feature is one that is in the process of being removed from the current version of the specification, while a superseded feature is one that is being retained only for authoring content compatible with an older version._

The meaning of these labels are defined as follows."

**Comment by iherman** [comment]
Ok. Your last proposed text helps a lot.

**Comment by mattgarrish** [comment]
Rather than repaste the whole section, I'm just going to modify the version in https://github.com/IDPF/epub-revision/issues/822#issuecomment-241741794 with any updates from now on.

**Comment by mattgarrish** [comment]
If there are no more comments on this, I'll send out to the group for review.
