### ISSUE TITLE
span elements within nav elements

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#824]
http://www.idpf.org/epub/31/spec/epub-packages.html#confreq-nav-a

> Each list item of the ordered list represents a heading, structure or other item of interest, and must contain either a child a element or a child span element. The a element describes the target that the link points to. The span element serves as a heading for breaking down lists into distinct groups (for example, a large list of illustrations can be segmented into several lists, one for each chapter).

Is `<nav epub:type="toc"><ol><li><span>foo</span></li></ol></nav>` allowed?   In other words, can we have a `<span>`without sibling `<a>` elements or `<ol>` elements?

**Comment by rdeltour** [comment]
> Is `<nav epub:type="toc"><ol><li><span>foo</span></li></ol></nav>` allowed? In other words, can we have a `<span>` without sibling `<a>` elements or `<ol>` elements?

No. A following bullet says:

> The `span` element must be followed by an `ol` ordered list; it cannot be used in "leaf" `li` elements.

**Comment by murata2makoto** [comment]
Yes, you are right.  The sentence you quoted disallows my example shown above. 

But I think that we have to be more explicit.  I was confused, and I know that one implementor was confused too. 

nav/ol/li can have either an a element possibly followed by a single  ol element, or a span element  followed by a single ol element.  Other than whitespace, no text chunk is allowed to occur as a child of nav/ol/li.

**Comment by mattgarrish** [comment]
I don't see more prose is going to make it easier to read.

A content model box to the start of the section would probably be better, like this:

<img width="498" alt="nav" src="https://cloud.githubusercontent.com/assets/1565164/17970263/dd473938-6aa3-11e6-822e-833a1d772426.PNG">

**Comment by mattgarrish** [comment]
I think we can also remove the duplicative content model prose if we do this. See a possible rewrite here:
https://docs.google.com/document/d/1l96NqIYEun1dzuepGELsfmnbwucLv4nIKfoWlWJWUds/edit#heading=h.wuwozrqhc3jm

**Comment by mattgarrish** [comment]
Proposed Solution

Add a content model box and update the prose as suggested in the referenced google doc.
