### ISSUE TITLE
Navigation document: The title attribute for alternative text rendering

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#825]
> [If  an a or span element contains instances of HTML embedded content that do not provide intrinsic text alternatives, the element must also include a title attribute with an alternate text rendering of the link label.](http://www.idpf.org/epub/31/spec/epub-packages.html#confreq-nav-a-title)

Does this mean that the a or span element is required to have a title attribute? (Look like so)  Then, is text chunk within the a or span element ignored when text rendering is required?

**Comment by mattgarrish** [comment]
As it says, if it contains instances of HTML embedded content that do not provide instrinsic text alternatives, then a title is required.

The title is provided for use by an assistive technology, for example, or could be used by a reading system when self-voicing is enabled. It is an _alternative_ rendering. It doesn't change the default visual rendering.

**Comment by mattgarrish** [comment]
Any follow up on this, or can it be closed @murata0204 ?

**Comment by murata2makoto** [comment]
I don't like this design, but we cannot change it now.  Agreed to close this without action.

**Comment by mattgarrish** [comment]
It is the correct application of HTML, although I'm not sure it's well supported. It's arguably better done with aria-label.
