### ISSUE TITLE
Navigation document without toc, page-list, or landmarks

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#826]
Is the use of `<nav epub:type="toc" ...>`, or `<nav epub:type="page-list" ...>`, or `<nav epub:type="landmarks" ...>` required?  If I am not mistaken, the current text allows a navigation document not to have any such.

**Comment by rdeltour** [comment]
The `toc nav` is explicitly required, in [5.4.2.2](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-nav-toc)

> The `toc nav` element must occur exactly once in an EPUB Navigation Document.

But the other two are optional. Inclusion of `page-list` is recommended by the [Accessibility Techniques](http://www.idpf.org/epub/a11y/techniques/techniques.html#sec-page-002) document.

**Comment by murata2makoto** [comment]
Thanks. I looked over this sentence.

I would like [5.4.2.1 Introduction](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-nav-def-types-intro) to specify that toc nav is require while toc page-list and toc landmarks are optional.

**Comment by mattgarrish** [comment]
We don't make normative statements in informative sections.

The most I'd offer to do for this is add the following to the toc nav description: "The toc nav is the only navigation aid that has to be included in the EPUB Navigation Document."

**Comment by laudrain** [comment]
Should we also recommend page-list with a reference to accessibility docs?
BTW, as publisher we have made it mandatory in our RFP.

**Comment by mattgarrish** [comment]
We've tried not to cross-pollinate requirements to avoid them getting out of synch. If we move the recommendation into the packages spec, it also potentially becomes a warning for everyone who doesn't include.

If you want it considered, though, please open a new issue.

**Comment by mattgarrish** [comment]
Proposed Solution

Add the following qualification to the nav types introduction: "The toc nav is the only navigation aid that has to be included in the EPUB Navigation Document."

**Comment by laudrain** [comment]
Ok to leave accessibility requirements in a11y docs.
No new issue.
