### ISSUE TITLE
Clarification: Arithmetic-coded JPG/JPEG Support?

### ISSUE THREAD

**Issue by TPS** [w3c/epub-specs#827]
@IDPF I apologize in advance if this is the wrong forum for this question:

Could someone comment on whether [arithmetic-coded](https://en.wikipedia.org/wiki/Arithmetic_coding#US_patents) [JPEGs](https://en.wikipedia.org/wiki/JPEG#Lossless_further_compression):
- ~~must~~
- may
- ~~should not~~

be supported in _~~which~~_ all EPUB versions?  I really can't find anything official, &, from my trials, support is _very_ [willy-nilly](https://en.wiktionary.org/wiki/willy-nilly#Adverb) _(technical term-of-art :wink:)_.

**Comment by mattgarrish** [comment]
EPUB follows the referenced standards. In this case, arithmetic decoding is not required to be supported as part of supporting JPEG, so that holds true for epub implementations.

In less words: may

**Comment by TPS** [comment]
Thank you!  Does that hold true for all EPUB versions, or just the current one?

**Comment by mattgarrish** [comment]
It holds true for all versions. There would be a qualifier somewhere that reading systems must support if we were to override another specification, but there aren't any for JPEG.

**Comment by TPS** [comment]
Thanks you very much, @MattGarrish. :bow:
