### ISSUE TITLE
Navigation documents: target elements might not be ordered

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#828]
> [The order of li elements contained within the toc nav element must match the order of the targeted elements within each targeted EPUB Content Document, and must also follow the order of Content Documents in the Rendition's spine.](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-nav-toc)

I think that this is not completely correct.  When two li reference different fragments of different content documents, the two fragments are not ordered.

In my understanding:

When an li element A precedes an li element B, either 1) the target content document of A precedes that of B in the Rendition's spine, or 2) the target content document and that of A are the same content document and the fragment referenced by A precedes that referenced by B.

**Comment by mattgarrish** [comment]
Sorry, I don't follow what distinction you're trying to make. There are two orderings that have to be respected: 1) the order of elements within the content document, and 2) the order of content documents in the spine.

When you combine those rules, all of the elements in A (in document order) must occur before all of those in B (in document order) before all of those in C ...

So two fragments across different content documents are not ordered by the first rule, but they are ordered by the second.

**Comment by murata2makoto** [comment]
We have the same understanding.  But I don't think that the spec captures your intention.

We have three orderings:

1) the order of li elements contained within the toc nav element

2) the order of the targeted elements within each targeted EPUB Content Document, 

3) the order of Content Documents in the Rendition's spine.

Here 1) always exists,  2) is   non-existent when the targets are in 
different content documents.   That's why I don't think 1) matches 2).
But the spec says 1) matches 2).

**Comment by mattgarrish** [comment]
I'm not sure I see that being said, but what about simplifying this requirement by breaking apart the MUSTs and tweaking the wording as follows:

> The references in the toc nav element MUST be ordered such that they reflect both:
> - the order of the referenced EPUB Content Documents in the spine;
> - the order of the targeted elements within their respective EPUB Content Documents.
