### ISSUE TITLE
page-list and pagebreak

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#829]
Shouldn't [the definition of nav page-list](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-nav-pagelist) mention epub:type="pagebreak"?

**Comment by mattgarrish** [comment]
As I recall, that's by design. We weren't going to make production dependent on the epub:type attribute. You can include just the page-list.

Including both is part of the accessibility techniques.

**Comment by mattgarrish** [comment]
Or are you asking for an informative note, like:

"See also the pagebreak term [StructureVocab] for identifying page break locations in EPUB Content Documents."

**Comment by murata2makoto** [comment]
I first thought that nav page-list  is required to use epub:type="pagebreak" but this requirement is not made clear.  Your first reply shows that there are no such requirements.  Your second reply provides an informative note.   Your note is a good one, but another note (based on your first reply) would be useful.

**Comment by mattgarrish** [comment]
What about making a normative statement:

"The destination of the page-list references MAY be identified using the pagebreak property [StructureVocab]."

This would perhaps give better precedent for increasing the requirement in the accessibility specification.

**Comment by mattgarrish** [comment]
Proposed Solution

Add an informative "may" about use of pagebreak property.
