### ISSUE TITLE
dereferenceable

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#832]
> [The IRI should be dereferenceable to a resource that provides more information about the scheme](http://www.idpf.org/epub/31/spec/epub-packages-20160801.html#attrdef-identifier-scheme)

Somebody pointed out to me that the word "dereferenceable" is difficult for non-native speakers, since most dictionaries do not explain this word.  I think that "The IRI should reference a resource ..." is clearer.

**Comment by iherman** [comment]
I believe that if we do the change, then it should be "The IRI should refer to a resource..."

**Comment by mattgarrish** [comment]
Proposed Solution

Change "be dereferenceable" to "refer".

**Comment by mattgarrish** [comment]
Closing as this as purely editorial and doesn't require group review.
