### ISSUE TITLE
SVG 1.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#833]
We still have three references to SVG 1.1.

In [2.5.2 Embedded SVG](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-svg),

> XHTML Content Documents support the embedding of SVG 1.1 document fragments by reference (embedding via reference, for example, from an img or object element) and by inclusion (embedding via direct inclusion of the svg element in the XHTML Content Document) [SVG].

In [ 3.1 Introduction](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-svg-intro),

> The Scalable Vector Graphics (SVG) 1.1 (Second Edition) specification [SVG] defines a format for representing final-form vector graphics and text.

In 3.2 Content Conformance,

> [It must be an SVG 1.1 document fragment valid to the constructs defined in that specification, and conform to all content conformance constraints expressed in Restrictions on SVG.](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#confreq-cd-svg-docprops-schema)

**Comment by mattgarrish** [comment]
Fixed.
