### ISSUE TITLE
Simplified processing model

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#834]
This phrase "simplified processing model" in [1.2.1 Relationship to HTML](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-overview-relations-html) is not clear to me.  Can we remove this phrase?

**Comment by mattgarrish** [comment]
> This specification defines a simplified processing model that does not require EPUB Reading Systems to support scripting, HTML forms or the HTML DOM. 

What is unclear?

**Comment by murata2makoto** [comment]
First, what is the original processing model?  Does it come from HTML?  Second, how the original model is restricted?

IMHO, we only have to lift the requirement that scripting and HTML forms must be supported.

**Comment by mattgarrish** [comment]
Well, it is the relationship to html section. It even ends by reiterating that an RS might not be a conformant UA because of this difference in processing models:

> This specification defines a simplified processing model that does not require EPUB Reading Systems to support scripting, HTML forms or the HTML DOM. Reading Systems conformant with this specification are only expected to be able to process a conforming EPUB Content Document. As support for scripting and HTML forms is not compulsory, a conformant Reading System might not be a fully-conformant HTML user agent (i.e., it might not implement the complete HTML processing model).

I can't see the point in making a change here.

**Comment by murata2makoto** [comment]
Is it possible to provide a link to somewhere in the HTML spec?

**Comment by mattgarrish** [comment]
The HTML specification defines the processing model. There are over 50 uses of the term in 5.1 alone.

What section are you wanting to pick out, 9.2?

**Comment by murata2makoto** [comment]
Here is my proposal.

This specification does not require EPUB Reading Systems to support scripting, HTML forms or the HTML DOM. Reading Systems conformant with this specification are only expected to be able to process a
conforming EPUB Content Document. As support for scripting and HTML forms is not compulsory, a conformant Reading System might not be a fully-conformant HTML User Agent.

**Comment by mattgarrish** [comment]
Proposed Solution

Reword per previous comment.
