### ISSUE TITLE
Restricted subset of SVG ?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#835]
At the end of  [1.2.2](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-overview-relations-svg) of Content Documents 3.1,

> This  specification defines a restricted subset of SVG 

But does this spec define such a subset?  It introduces a set of additional restrictions.  When they are combined with different versions of SVG, we have different subsets.  The same comment applies to HTML (the phrase "The XHTML document type defined by this specification").

**Comment by mattgarrish** [comment]
Looks like a lingering reference to when animations were restricted. The paragraph is unnecessary.

The other could be "xhtml profile".
