### ISSUE TITLE
Explain RS behaviour when remote script encountered

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#837]
The third item in 4.2 is a major one, of course for security reasons. I think we absolutely need a note explaining what should a Reading System do if it encounters a remote scripting resource... Warn the user, show an alert, call 911?-)

(Submitted by Daniel Glazman)

**Comment by mattgarrish** [comment]
Should we add an RS requirement that is "must not" execute remotely-hosted scripts?

Warnings and alerts to users seem like implementation details.

**Comment by mattgarrish** [comment]
@GarthConboy @bduga @danielweck @rkwright 

Any thoughts on whether an RS requirement banning execution of remotely-hosted scripts is useful, or whether some other description would help?

**Comment by bduga** [comment]
I believe execution of remote scripts is a desired feature. Certainly, it would be hard to allow scripts to access other types of remote resources, but forbid script execution. This item only forbids the base script residing outside of the package, and is not intended as a security measure. I think it is there just for packaging and availability reasons (something should run if there is no network). Now, whether a RS _must_ allow scripts to download remote resources is another question (I don't think that is required).

**Comment by mattgarrish** [comment]
True, I suppose this already falls under the security considerations. We can't prevent a local script from obtaining malicious code to execute.

Is it worth adding something like "to ensure availability at runtime" to avoid the impression of security?

"Resources retrieved by scripts may be located outside the EPUB Container, but the [HTML] and [SVG] script elements must not reference Remote Resources to ensure availability at runtime (i.e., from their src or href attributes, respectively)."

And I'd say retrieving being optional is covered under this RS requirement:

> It may place additional limitations on the capabilities provided to scripts during execution (e.g., limiting networking).

**Comment by bduga** [comment]
That wording works for me.

**Comment by mattgarrish** [comment]
Proposed Solution

Updated the text as described in https://github.com/IDPF/epub-revision/issues/837#issuecomment-247212564
