### ISSUE TITLE
Recommend inclusion of dcterms:created

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#840]
This is a comment I already made about previous versions of EPUB : if we want EPUB packages to be considered as standalone objects on the Web,  we need a second mandatory or at least highly recommended META element in the METADATA element: &lt;meta property="dcterms:created"&gt;

(Submitted by Daniel Glazman)

**Comment by laudrain** [comment]
Interesting. Could please let me know where this recommandation can be found?

**Comment by mattgarrish** [comment]
I assume this a request to make created bound to some nebulous and immutable creation date of the publication, giving a permanent record of when it was "born".

created -> modified -> issued -> modified -> issued 

We'd probably need clarification language, as created can be interpreted as (re)generation of the container from source.

created -> issued -> modified -> created -> issued

**Comment by laudrain** [comment]
My question was more about "EPUB packages to be considered as standalone objects on the Web".
How does it relate to dcterms:created?

**Comment by mattgarrish** [comment]
I believe by rooting it in time, but you'd have to ask Daniel. I don't recall seeing a proposal before.

**Comment by mattgarrish** [comment]
I'm closing this issue as my request on list for more information didn't elicit a response and it's getting to be too late for a bare-bones request like this to be fleshed out and reviewed properly.

Feel free to pursue with Daniel and reopen if you think it's valuable to do for this revision, Luc.
