### ISSUE TITLE
Refer to elements as having text content

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#842]
The spec deals with "element values" all over the place, for example in section 3.4.3.1.2, last paragraph. An XML element has no value, sorry. The correct prose should be "textual content" OR the value of an element should be defined in http://www.idpf.org/epub/31/spec/epub-spec.html#sec-terminology. We may want to refer to https://www.w3.org/TR/2015/REC-dom-20151119/#dom-node-textcontent in the former case .

(Submitted by Daniel Glazman)

**Comment by mattgarrish** [comment]
Looks like a case of a definition being lost in translation. OPF 2.0.1 had this clarification:

> Each Dublin Core field is represented by an element whose content is the field's value.

EPUB 3 will need to account for the meta tag, as well. This could just be a clarification at the start of 3.4.

**Comment by mattgarrish** [comment]
Proposed Solution

Add the following generalized clarification to the start of section 3.4:

"When an element defined in this section has mandatory text content, that content is referred to as the value of the element in the explanatory descriptions."

**Comment by TzviyaSiegman** [comment]
+1
