### ISSUE TITLE
Clarify "individual" in user definition

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#844]
It was questioned if individual refers to a person or something else in the following definition:

> User
> An individual that consumes an EPUB Publication using an EPUB Reading System.

**Comment by mattgarrish** [comment]
I'm not sure this is all that confusing, but I wonder what the point of defining "user" is. It's not a technical term and it's not used in a way that would cause any confusion.

My suggestion would be to drop this as a formal term. I was skimming W3C specs and couldn't find any that define user.

**Comment by mattgarrish** [comment]
Propose Solution

Drop "User" as a term.

**Comment by TzviyaSiegman** [comment]
+1
