### ISSUE TITLE
Add mathml as core media type?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#846]
Since mathml can be referenced from an object element, it's curious that we don't allow equations to be stored in their own files, even if it's not common practice.

Looking at issue #845, I wonder if we should add "application/mathml+xml" and possibly "application/mathml-presentation+xml".

**Comment by mattgarrish** [comment]
The discussion in #845 has surfaced that safari/ibooks/webkit supports embedded mathml but not mathml referenced from an object element.

I wonder if we should defer, given even worse support than embedded mathml.

**Comment by mattgarrish** [comment]
@iherman do you know how standalone math relates to the html support provision?

The mathml in the object becomes a nested browsing context, but that doesn't make the root element the document root, does it? That seems to be the criteria for it being considered embedded. Otherwise, wouldn't adding as a CMT require support for rendering standalone math files?

**Comment by iherman** [comment]
Unfortunately I don't know:-(

---

**Comment by mattgarrish** [comment]
Hm, digging around it seems to reach into an object via javascript you need to call the contentDocument property. That suggests it isn't embedded content.

I think this might be an issue to take up in another revision when we have more time to review whether there are any implications. I'm going to set to defer, but if you disagree feel free to raise it on the list.

**Comment by mattgarrish** [comment]
Although an interesting idea, we've still never had a real-world request for standalone mathml equations. I'm fine with closing this unless someone else wants to argue for it.
