### ISSUE TITLE
EPUB Publication Rendering Vocabulary and EPUB Packages 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#848]
I am wondering why we need EPUB Publication Rendering Vocabulary.  All properties in EPUB Publication Rendering Vocabulary appear to be defined in EPUB Packages 3.1.   I have thought that the whole point of  creating a separate document is to allow easy addition of properties, but are we forced to update both?

**Comment by murata2makoto** [comment]
At present, both EPUB Publication Rendering Vocabulary and EPUB Packages 3.1 provide normative descriptions of properties.  EPUB Packages 3.1 tend to specify fine details.  But some info (e.g, scroll direction) is available only in EPUB Publication Rendering Vocabulary.   Should we make EPUB Publication Rendering Vocabulary informative?   Or, should we move all properties from EPUB Packages 3.1 to  EPUB Publication Rendering Vocabulary ?

**Comment by mattgarrish** [comment]
The vocabularies are not about easy updating. We have six or seven now that used to all be crammed together in the specification. That makes it ambiguous what properties belonged to what vocabulary and could be used in what attributes.

The general definitions were split out for easier referencing, and also to stop the packages document from becoming a bloated mess of property definitions, which is what it had become.

**Comment by murata2makoto** [comment]
I do not understand.  EPUB Packages 3.1 is "a bloated mess of property definitions" at least for the properties in EPUB Publication Rendering Vocabulary.  Nevertheless, we cannot understand these properties without reading EPUB Publication Rendering Vocabulary.  I would argue that we the current organization of specifications hampers readability.

**Comment by mattgarrish** [comment]
Take a look at the publications specification. It's text interspersed with long runs of property definition boxes.[1]

Out of all those sections, which properties are in the rendition vocabulary? It has a URI that redirects to the specification. So which are they? Are page-spread-right and -left in it? The package vocabulary also has a URI that redirects to that document. So which properties are those? Now we have properties for at least four other vocabularies broken off. Are they too going to have URIs that redirect to the packages specification, and what exactly tells you what those are?

Readability is the last thing that having them in the specification provides. There are links to the vocabularies where they matter and where properties are referenced.

[1] http://www.idpf.org/epub/301/spec/epub-publications.html#sec-meta-property-values

**Comment by murata2makoto** [comment]
I then propose to move the normative content of [Publication Rendering Metadata](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-metadata-rendering) to EPUB Publication Rendering Vocabulary.

**Comment by mattgarrish** [comment]
Sure, you can sell @GarthConboy on deintegrating the fxl specification.

**Comment by murata2makoto** [comment]
I will ask the EPUB WG to consider this issue.  I have no problems in having an informative summary of fxl-related properties in EPUB Packages 3.1.  What I am very against is having two normative documents about the same thing.

**Comment by murata2makoto** [comment]
I find two  similar issues.

1) nav of EPUB Manifest Properties Vocabulary

In [EPUB Navigation Document](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-nav) in EPUB Packages 3.1, "Exactly one item must be declared as the EPUB Navigation Document using the nav property."  Meanwhile, in EPUB Manifest Properties Vocabulary, "Cardinality:  Exactly one".  I think that this is a duplication of information.  This can be easily avoided by converting the sentence in EPUB packages to an informative note and reference EPUB Manifest Properties Vocabulary.

2) page-spread-right and page-spread-left of EPUB Spine Properties Vocabulary

[The rendition:page-spread-\* Properties](http://www.idpf.org/epub/31/spec/epub-packages.html#fxl-properties-page-spread) in EPUB Packages 3.1 provide normative descriptions of these properties.

I think that all normative descriptions in this subsection should be moved to EPUB Manifest Properties Vocabulary. Alternatively, we might want to convert some descriptions in EPUB Packages 3.1 to informative notes and and reference EPUB Spine Properties Vocabulary.

My investigation of other vocabularies did not change my opinion.  We should avoid duplication of normative descriptions.

**Comment by mattgarrish** [comment]
There's a raft of useless duplication that we can do away with in the rendition vocabulary. That's why I said there is too much bloat to these. All the it really needs are the property names and descriptions. Everything else is/can be covered in the spec.

The only specification that can't do without some normative statements is the manifest vocabulary. But I'm not buying that having a cardinality statement throws everything into disarray. That's like claiming we can't have content models because an element might state it is required, too.

**Comment by mattgarrish** [comment]
So the proposal I'd offer is:
- remove the allowed values, cardinality, extends and usage fields from the rendition vocabulary
- add the statement "The x property must not be declared more than once." to each property's usage section in the packages spec.
- add the statement "Only one of these overrides is allowed on any given spine item." to each spine overrides section plus the page-spread-\* properties
- remove the conformance statements section

Do similar for the page-spread-\* properties in the spine vocabulary.

Leave the rest as-is.

**Comment by mattgarrish** [comment]
I'm going to take silence on this as assent to move forward with the proposed changes.

**Comment by murata2makoto** [comment]
I think that the description of each property should be a single sentence.  In particular, most of the description of flow-scrolled-continuous should be moved to Packages 3.1.

**Comment by mattgarrish** [comment]
Yes, the vocabulary doesn't need specific implementation details.
