### ISSUE TITLE
page-spread-center missing in EPUB Spine Properties Vocabulary

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#850]
This property apparently belongs to the  EPUB Spine Properties Vocabulary, but is not defined there.

Again, I am concerned about having two documents for the same set of properties.

**Comment by mattgarrish** [comment]
page-spread-right and -left should have been in the rendition vocabulary but were defined before it. The spine vocabulary is not being extended to account for new rendition properties, but we also can't drop the old properties.

**Comment by murata2makoto** [comment]
I see.  I would like to see a note explaining what you wrote.

**Comment by mattgarrish** [comment]
I guess we could add a trailing sentence like the following to the note in the page-spread-\* section that already deals with these properties:

"The [Spine Vocab] is no longer being extended for package rendering metadata, so an unprefixed page-spread-center is not available."

@GarthConboy any issues with noting this rationale?
