### ISSUE TITLE
EPUB Linking Scheme Registry is not in the list of references from EPUB Package 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#851]
Five registries are mentioned in EPUB Package 3.1.   EPUB Linking Scheme Registry is not in the list of references, although the others are.

**Comment by mattgarrish** [comment]
The linking scheme registry was dropped with the requirement to support CFI, which is the only scheme that we ever created. It's only kept around is because it's still referenced from 3.0/3.0.1.

For what purpose would it be put back?

**Comment by murata2makoto** [comment]
First, do we then need this sentence?

> The  IDPF maintains a registry of linking schemes at http://www.idpf.org/epub/linking/. Some of these schemes define custom fragment identifiers that resolve to application/oebps-package+xml documents

Second, in the future, we might want to create a new scheme, for example, for the synergy with the Web.

**Comment by mattgarrish** [comment]
Probably not, but the media type registration was done for 3.0. It mentions 3.0 superseding 2.0.1, links to 3.0 specifications, and Ibis Reader disappeared a long time ago. Are we going to supersede a registration we never registered?

As far as I'm aware, it's not an issue to use other schemes, or support them. The registry was just a way of surfacing which ones were known to be in use. I'm not sure why it wasn't mentioned as a note. If a new scheme is done in coordination with W3C, I'm sure there are better ways of advertising it.

**Comment by mattgarrish** [comment]
Closing this issue, as there's no value in returning the linking registry with CFI support gone and plans for IDPF to create new schemes.

If you want to open an issue about cleaning up the registration, please include the rewrites you'd want.
