### ISSUE TITLE
Changes to the content model of <rp>

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#854]
WhatWG is considering changing the content model of `<rp>` in whatwg/html#1689, and @zcorpan filed issue idpf/epubcheck#703 to see if would EpubCheck would be updated, and if have concrete uses of elements in `<rp>`.

I'm creating an issue here since this is primarily a spec issue, to be discussed with the WG.

**Comment by mattgarrish** [comment]
Interesting, rp is a "discouraged" construct, but is not in an informative section. Do you issue warnings against its use?

**Comment by rdeltour** [comment]
> Do you issue warnings against its use?

Nope, see [our test case in `ruby-001.xhtml`](https://github.com/IDPF/epubcheck/blob/master/src/test/resources/30/single/xhtml/valid/ruby-001.xhtml#L18)

**Comment by murata2makoto** [comment]
rp is to allow ruby-unaware user agents to provide readable results.  I do not believe it is used for Japanese EPUB publications.

**Comment by mattgarrish** [comment]
No spec blessing is needed to change the content model that I can see. If WhatWG approves a change and it goes into 5.1, then we inherit the change.

If the question is just do we think it's concerning to change the content model to text, it sounds like it's not a serious issue since it's both discouraged and not known to be in widespread use.

**Comment by mattgarrish** [comment]
But if the question is whether we should make a change in advance of it getting standardized

**Comment by mattgarrish** [comment]
I started to comment that if the question is whether we should accept a change in advance of it being formalized, no, we've gone down that path before and been burned. Better to stick to the W3C revision cycle.

**Comment by zcorpan** [comment]
That's fine, it was mostly a heads-up and checking if it would be a problem for you down the line if w3c/html copies the change and you have lots of legacy content using elements in `rp` for whatever reason. 😊 But it sounds like that is not the case. Thanks!
