### ISSUE TITLE
Appendix B Issue List (3 items)

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#856]
- **Location**: "This appendix lists deprecated, and..." 
  **Edit**: Remove comma
- **Location**: "Use of the rendition:viewport property [Packages 3.1]..."
  **Note:** this link currently points to '4.3.3.2 The rendition:layout Property' although there is a note that points to rendition:viewport property so this could be fine.
- **Location**: "Use of the rendition:viewport property [Packages 3.1] is now deprecated."
  **Suggested Edit**: Link 'deprecated' http://www.idpf.org/epub/31/spec/epub-spec.html#deprecated

**Comment by mattgarrish** [comment]
Thanks, I've got these fixed and will commit with the next batch.
