### ISSUE TITLE
section 3.2 AVG Content Conformance clarification

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epub-specs#857]
Minor wording tweak for clarity:
"It must be an SVG document fragment valid to the constructs defined in that specification, and conform to all content conformance constraints expressed in Restrictions on SVG."
might be clearer if it said
"It must be an SVG document fragment valid to the constructs defined in the SVG specification, and conform to all content conformance constraints expressed in Restrictions on SVG." 
The current text sounds like it refers to SVG document fragment spec instead of SVG spec.

**Comment by mattgarrish** [comment]
Ya, that's a beefy statement. I think we can go even simpler to:

"It MUST be a valid SVG document fragment [SVG], and conform ..."
