### ISSUE TITLE
Dated CSS reference 6.5.1?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#858]
In section 6.5.1 there is a reference to the initial containing block of CSS2.1. The reference is https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#containing-block-details, ie, using the dated URI of the CSS spec. In view of the evolution of CSS, I am not sure this is wise. At the minimum, using the undated URI, ie, http://www.w3.org/TR/CSS2/ may be wiser.

**Comment by iherman** [comment]
Actually, the same reference is used in 6.5.2, right after the example.

**Comment by dauwhe** [comment]
I think we should use the CSS 2.2. definition  http://www.w3.org/TR/CSS22/visudet.html#containing-block-details.

The CSS 2 link  http://www.w3.org/TR/CSS2/visudet.html#containing-block-details actually has different text, because of the evolving understanding of formatting contexts.

Old:

> For other elements, if the element's position is 'relative' or 'static', the containing block is formed by the content edge of the nearest block container ancestor box.

New:

> For other elements, if the element's position is 'relative' or 'static', the containing block is formed by the content edge of the nearest ancestor box that is a block container or which establishes a formatting context.

Dave

**Comment by mattgarrish** [comment]
Would it make sense to use the CSS Snapshot as the reference when mentioning CSS modules rather than referencing them directly? (With the exception of the dated references for the -epub- prefixed stuff.)

But to deep linking, if we want to keep consistent in the use of undated references we would need to use /TR/CSS2.

**Comment by mattgarrish** [comment]
Perhaps all we should do here is change "[CSS 2.1]" references to "[CSS 2]" and use the /TR/css2 path.

We have some specific module references, but if we removed I think it might become unclear what we are referring to. Looking at HTML 5.1, that would put us in line with their conventions.

Also suggest we change this sentence in the relationship to css section:

> EPUB 3.1 supports CSS as defined by the CSS Working Group Snapshot [CSS Snapshot], based on CSS 2.1 [CSS 2.1] plus many newer modules.

to:

> EPUB 3.1 supports CSS as defined by the CSS Working Group Snapshot [CSS Snapshot].

**Comment by iherman** [comment]
If we do not have specific module references, then why would we refer to "[CSS 2]" and not to the snapshot in general?

I am fine with your proposed change on the css relationship section, b.t.w.

**Comment by mattgarrish** [comment]
If we're deep-linking into /TR/css2, shouldn't we reference [CSS 2]?

But looking at HTML 5.1 closer, the only reference to [CSS 2] is as a heading in the index. But I can't find that the [CSS-2015] snapshot reference is tied to any deep links, either.

In the interests of keeping our undated references as undated as we can, I'm fine with using the snapshot if you think it's more appropriate.

**Comment by mattgarrish** [comment]
Proposed Solution
- change 2.1 references to the snapshot
- fix deep links to /tr/css2
- remove reference to 2.1 from the relationship section
