### ISSUE TITLE
Reference to viewport metadata in 6.5.1 is wrong

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#859]
In 6.5.1 it says:

> di­men­sions must be ex­pressed in a view­port meta tag using the syn­tax de­fined in [Meta Tags]. 

Following up the reference in the reference list, one gets to a web maintained by Apple:

> https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

I do not think we should be dependent on this. 

Looking at the HTML5.1 specification for the accepted values of the `name` attribute of `meta`, one is redirected to the WHATWG Wiki site which is recommended as a registration place for those attribute values:

> https://wiki.whatwg.org/wiki/MetaExtensions

which indeed includes a definition of viewport. I would think that should be used as a proper references.

**Comment by mattgarrish** [comment]
What about referencing the definition in the device adaptation module?
https://www.w3.org/TR/css-device-adapt-1/#meta-properties

The wiki isn't itself a specification, but points to that document.

**Comment by iherman** [comment]
Well... that section is non-normative, whereas the reference chain to get to that wiki page is at least 'official' through the HTML5.1 spec. I am not sure what the intention is with the device adaptation module. Maybe @dauwhe knows more...

**Comment by mattgarrish** [comment]
Yes, but we have the same problem going from HTML, as it says the description is:

> [a] short non-normative description of what the metadata name’s meaning is, including the format the value is required to be in.

The details are supposed to be in a referenced specification.

Granted, none of the three options is all that spectacular, but if we can reference an actual specification it would look better (e.g., for ISO submission).

**Comment by iherman** [comment]
For the time being we can refer to both:-). As for ISO, let us cross the bridge when we get there...

**Comment by mattgarrish** [comment]
Not to belabour this, but the one thing I like about the Apple reference is that it's the only one that actually explains the syntax you have to use. The others just list a bunch of properties you can use in the viewport meta tag.

As this is one of the rare specs I had no hand in developing, I'm fine waiting to see if @dauwhe or @GarthConboy have an opinion to offer.

**Comment by dauwhe** [comment]
I think we should point to CSS-Device-Adaptation. It's the only place that describes how this should actually work.

**Comment by mattgarrish** [comment]
Proposed Solution:

Change Apple documentation reference to CSS Device Adaptation.
