### ISSUE TITLE
Expressing SVG viewbox attribute in 6.5.2 is misunderstandable (Editorial)

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#860]
> For SVG Con­tent Doc­u­ments, the root svg el­e­ment must in­clude ei­ther the view­Box at­tribute or the height and width (and op­tional x and y) at­trib­utes, or both.

I wonder whether adding a comma after `viewBox attribute`, saying

> For SVG Con­tent Doc­u­ments, the root svg el­e­ment must in­clude ei­ther the view­Box at­tribute, or the height and width (and op­tional x and y) at­trib­utes, or both.

Otherwise the term 'both' is not clear in my view.

**Comment by mattgarrish** [comment]
Adding a comma in the middle of an either/or statement strikes me as odd. What if we take "or both" off the end and shorten a little:

"For SVG Content Documents, the root svg element must include either or both of the viewBox and the height/width (and optional x/y) attributes."

**Comment by iherman** [comment]
> On 8 Sep 2016, at 14:33, Matt Garrish notifications@github.com wrote:
> 
> Adding a comma in the middle of an either/or statement strikes me as odd. What if we take "or both" off the end and shorten a little:
> 
> "For SVG Content Documents, the root svg element must include either or both of the viewBox and the height/width (and optional x/y) attributes."
> 
> —

I guess what bothered me (and this is the same here) is that the term 'both' refers to two entities, whereas here we have, on the one hand, a single attribute and, on the other hand, a group of attributes as some sort of a logical unit. But if it is all right for your native ears, then that is fine and we can close it...

**Comment by mattgarrish** [comment]
It's an awkward statement, for sure. I took out "height and width" and replaced with a slash for exactly that reason. We could just make it a list for absolute clarity:

> For SVG Content Documents, the root svg element must include one or both of:
> - the viewBox attribute;
> - the height and width (and optional x and y) attributes.

**Comment by iherman** [comment]
> On 8 Sep 2016, at 15:08, Matt Garrish notifications@github.com wrote:
> 
> It's an awkward statement, for sure. I took out "height and width" and replaced with a slash for exactly that reason. We could just make it a list for absolute clarity:
> 
> For SVG Content Documents, the root svg element must include one or both of:
> 
> the viewBox attribute;
> the height and width (and optional x and y) attributes.

Yes, that is much clearer. Thx
