### ISSUE TITLE
Formatting the HTML example in 7.2 is wrong (Editorial)

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#862]
The `html` element should be aligned to the left.

**Comment by mattgarrish** [comment]
I'm not seeing anything amiss. What browser/platform are you viewing on?

**Comment by iherman** [comment]
Interesting. I read the EPUB document in Calibre, and it went wrong there. I have just checked the original HTML file in FF and it is all right and I also checked the EPUB in the iBook reader on the Mac and it is also all right. This seems to be a Calibre issue then, we can close this issue (I will).

Note that situation is similar with #861; will close that one, too
