### ISSUE TITLE
Link type used for the pronunciation lexicon (section 7.2)

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#863]
The document refers to the `rel="pronunciation"` value in the `link` element. However... (yes, here we go again) that value is not registered anywhere.

Per the current HTML5.1 specification the right approach is to get this value registered on the [microdata wiki](http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions). I think due diligence should require that IDPF adds this value to the table (or at least attempts to do so).

**Comment by mattgarrish** [comment]
We attempted to register. It got as far as the proposals table.

**Comment by iherman** [comment]
Ah! I see it. Well, it is the microformat's wiki procedure that is at fault then; IDPF did due diligence. Ie, there is no issue here for now, I will close the issue (but it may still come back and haunt us if we work on a next version at W3C...)
