### ISSUE TITLE
3.3 Restrictions on SVG (namespace?)

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#864]
The [SVG] foreignObject element must contain either [HTML] flow content or exactly one [HTML] body element.

Would it be beneficial to add a note about namespace?

The [SVG] foreignObject element must contain either [HTML] flow content or exactly one [HTML] body element, and each parent node must have a namespace declaration.

(I reached out to Doug Schepers for help with this.)

**Comment by mattgarrish** [comment]
I know what you're saying, but parent sounds too general as there are many possible parents.

> The [SVG] foreignObject element must contain either [HTML] flow content or exactly one [HTML] body element, each of which must be declared in the XHTML namespace.

But there's an immediately following requirement that it be a valid XHTML document fragment. If you don't declare the namespace, that would tend to break the requirement. Are we perhaps getting too deep into details?

**Comment by clapierre** [comment]
You may be right Matt, Doug's idea was just "The EPUB spec might do authors a favor and include a note about namespaces".

**Comment by TzviyaSiegman** [comment]
The question boils down to whether someone reading the spec needs to know the detail about namespacing while reading this paragraph or can ascertain the info when following the links about XHTML and SVG. I think that it's too much information to include in a brief mention of SVG restrictions. WDYT?

**Comment by mattgarrish** [comment]
My suggestion was technically wrong on this, too, as I was thinking flow content was only elements, but it includes text. The requirement would have to be to declare on all "child elements". (They're all parents of something, but technically their children could be parents, etc.)

But I agree with Tzviya that it's too much detail at this level, as there's a lot that goes into making a valid fragment.

I do think the bullet could use some reformulating. I hate trying to read three normative requirements squashed into one item.

Perhaps we can split it apart:

> The [SVG] foreignObject element must adhere to the following requirements:
> - It MUST contain either [HTML] flow content or exactly one [HTML] body element.
> - Its content MUST be a valid document fragment that conforms to the XHTML Content Document model defined in XHTML Content Documents — Content Conformance.
> - Its requiredExtensions attribute, if given, must be set to "http://www.idpf.org/2007/ops".

Maybe improving the readability will improve comprehension.

**Comment by mattgarrish** [comment]
I've split out the bullet, so closing this issue. Feel free to reopen if you think it needs more consideration.
