### ISSUE TITLE
Are external audio publication resources?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#865]
The third para of the definition of publication resources in EPUB 3.1 implies that remote audio resources are not publication resources.

> Examples of resources that are not Publication Resources include those identified by the Package Document link [Packages 3.1] element and those identified in outbound hyperlinks that resolve to Remote Resources (e.g., referenced from the href attribute of an [HTML] a element).

But in [4.2 Resource Locations](http://www.idpf.org/epub/31/spec/epub-spec.html#sec-resource-locations) 

> All Publication Resources must be located in the EPUB Container, with the following exceptions:
> ›  Audio resources [Core Media Types] may be located outside the EPUB Container.

**Comment by mattgarrish** [comment]
An outbound hyperlink isn't a publication resource as it doesn't bring content into the publication. Audio resources used in the rendering can be located externally (referenced from audio/object/embed).

**Comment by murata2makoto** [comment]
So, when we have `<a href="http://www.example.com/foo.mp3">..</a>` only, this MPEG file is not a publication resource.  When we have  `<source src="http://www.example.com/foo.mp3" type="audio/mpeg">` only, it is a publication resource.  When we have both, it is a publication resource.

I think that some examples are useful.

**Comment by mattgarrish** [comment]
There's no "both" condition, as the evaluation of whether a resource is a publication resource is always independent of other uses. One doesn't change the other.

It's no different than the link element referencing a non-publication resource at the same time as what it references could itself be a publication resource in another context.

**Comment by murata2makoto** [comment]
So, a publication resource in some context is not a publication resource in another context.

As part of EPUB 3.1, do you agree to introduce examples (except for the" both" condition)?  I think that it is useful.

**Comment by mattgarrish** [comment]
If there's a real benefit in showing a relative and full IRI, I guess we could add two examples to the section:

> The following example shows a reference to an audio file located outside the EPUB Container.
> 
> ```
> <audio src="http://www.example.com/book/audio/ch01.mp4" controls="controls"/>
> ```
> 
> The following example shows a reference to an audio file located inside the EPUB Container.
> 
> ```
> <audio src="audio/ch01.mp4" controls="controls"/>
> ```

It's the wrong place to mention hyperlinks, as they're not publication resources. That sort of explanation would probably belong in the manifest item section. We could maybe add a subsection of examples to keep this from cluttering up the definition.

> The following example shows a reference to a remote audio file that has to be referenced from the manifest (the audio is rendered inline in the XHTML Content Document so it is a Publication Resource).
> 
> ```
> <audio src="http://www.example.com/book/audio/ch01.mp4" controls="controls"/>
> ```
> 
> The following example shows a link to the same audio file, but in this case it would not be listed in the manifest (hyperlinked Remote Resources are not Publication Resources). The audio file would only be listed in the manifest if the Author has also referenced it from an [HTML] embedded content element, as above (i.e., in a context where it is used as a Publication Resource).
> 
> ```
> <a href="http://www.example.com/book/audio/ch01.mp4">Go to audio file</a>
> ```
> 
> The following example shows a link to a local audio file (it has to be listed in the spine and the manifest, and requires a fallback to an EPUB Content Document).
> 
> ```
> <a href="images/ch01.mp4">Listen to audio</a>
> ```

I don't think this needs to be prominently highlighted, as it's more of an academic explanation than a major production problem that people run into.

**Comment by mattgarrish** [comment]
Proposed Solution

Add examples as above.
