### ISSUE TITLE
Hyperlinks to external HTML documents

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#866]
I misinterpreted this paragraph in [3.4.5.1 The spine Element](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-spine-elem).    I thought that it prohibits links to external HTML documents.

> All Publication Resources that are hyperlinked to from Publication Resources in the spine must themselves be listed in the spine, where hyperlinking is defined to be any linking mechanism that requires the User to navigate away from the current resource. Common hyperlinking mechanisms include the href attribute of the [HTML] a and area elements and scripted links (e.g., using DOM Events and/or form elements). The requirement to list hyperlinked resources applies recursively (i.e., all Publication Resources hyperlinked from hyperlinked Publication Resources also have to be listed, and so on.).

Since external HTML documents are not publication resources, this para does not apply to external HTML documents.  I think that a note would be helpful.

Note: Since external HTML documents are not publication resources, they can be hyperlinked from EPUB content documents freely.

I was not confused by EPUB 3.0.1, since this paragraph began with "All EPUB Content Documents" rather than "All Publication Resources".

**Comment by mattgarrish** [comment]
The 3.0.1 definition was technically inaccurate, since there is nothing in epub that says that only epub content documents are allowed in the spine, or that you can only hyperlink to them. You can hyperlink to any resource provided it has an epub content document fallback.

This was already covered in https://github.com/IDPF/epub-revision/issues/611

**Comment by murata2makoto** [comment]
I understand that the 3.0.1 definition is inaccurate and that the new definition is technically correct.  But it is too easy to misinterpret it.  I thus proposed a note.

**Comment by mattgarrish** [comment]
If the point is to call out that it doesn't apply to outbound hyperlinks, then why not note that and make html an example?

Note
As Remote Resources referenced from hyperlinks are not Publication Resources, they are not subject to this requirement (e.g., Web pages and resources).

**Comment by mattgarrish** [comment]
Proposed Solution

Add note as above.
