### ISSUE TITLE
Sample in 2.4.1.2 The epub:type Attribute

### ISSUE THREAD

**Issue by laudrain** [w3c/epub-specs#867]
In 2.4.1.2 The epub:type Attribute, the first sample isn't aligned with it's title:

> The following example shows the epub:type attribute used to add footnote and note reference semantics.
> `<html … xmlns:epub="http://www.idpf.org/2007/ops">
>     …
>     <section epub:type="preamble" id="n1">
>         …    
>     </section>
>     …
> </html>`

The title could be:

> The following example shows how a book preamble could be marked up with the epub:type attribute on its containing section element.

**Comment by mattgarrish** [comment]
Thanks, yes, looks like the deprecated note example got changed but the caption left unchanged. I'll also remove the id, as it looks like it was related to the old example (n1=note1).
