### ISSUE TITLE
Page-break sample in 2.4.1.2 The epub:type Attribute

### ISSUE THREAD

**Issue by laudrain** [w3c/epub-specs#868]
In 2.4.1.2 The epub:type Attribute, the third sample on page-break should have also an id attribute, as proposed by EDUPUB (http://www.idpf.org/epub/profiles/edu/structure/#h.8hygsjhkpul0)

The sample could be:
`<html … xmlns:epub="http://www.idpf.org/2007/ops">
   …
  <p> … <span epub:type="pagebreak" title="234" id="page234"/> … </p>    
   … 
</html>`

**Comment by mattgarrish** [comment]
Fixed.
