### ISSUE TITLE
Behavior of RS when epub:type properties conflict

### ISSUE THREAD

**Issue by laudrain** [w3c/epub-specs#869]
In 2.4.1.4 Processing Requirements, we provide rules for Reading Systems when "a given epub:type value conflicts with an element's native behavior".
But should we also provide rules when epub:type values themselves are conflicting?

Something like: 
When Reading System behaviors associated with different epub:type values give on a specific element conflict between each other, the first associated behavior must be given precedence.

**Comment by mattgarrish** [comment]
Proposed Solution

Add conflict resolution statement as suggested above.

**Comment by mattgarrish** [comment]
A growing concern I have with this is that we don't define what behaviours reading systems assign, so why are we prioritizing how they handle their processing?

It also doesn't take into account whether there are parent relationships that could make the first semantic the invalid one in the given context.

It might be better not to say anything.

**Comment by laudrain** [comment]
It seems better indeed not to go in too much detail.
Ok to let it as it is.
