### ISSUE TITLE
What does "space-separated" mean?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#870]
In the [definition ](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-conf-rs)of epub:type, we have a phrase "space-separated terms".  What does it mean?  There are many [space characters](https://www.cs.tut.fi/~jkorpela/chars/spaces.html) in Unicode.  Does it allow CR and LF?

**Comment by iherman** [comment]
> On 11 Sep 2016, at 07:36, MURATA Makoto notifications@github.com wrote:
> 
> In the definition  http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-conf-rsof epub:type, we have a phrase "space-separated terms". What does it mean? There are many space characters https://www.cs.tut.fi/%7Ejkorpela/chars/spaces.html in Unicode. Does it allow CR and LF?

I guess the right answer is that whatever XML allows as separating terms is valid here. After all, this is an XML attribute. Ie, the right terminology is probably to say 'white space separated terms', where white space is defined here:

https://www.w3.org/TR/xml/#NT-S https://www.w3.org/TR/xml/#NT-S

this means that yes, CR and LF are valid indeed. But none of the special space characters listed in the page you referred to are..

My two cents…

**Comment by murata2makoto** [comment]
That's my guess too, but we need more explicit words.

**Comment by laudrain** [comment]
In real production world, I've never seen someone using something else than a regular space character (0x20) in separating attributes values.
As it is XML, the proper terminology is indeed to refer to white-space.

**Comment by mattgarrish** [comment]
Proposed Solution

Add reference to XML white space.
