### ISSUE TITLE
A deprecated property is still listed as an epubReadingSystem property.

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#874]
According to the Content specification Appendix B, the layoutStyle property has been deprecated and asked to refer to the Content 3.0.1 specification.
But, Appendix A still lists the property in IDL Section. Since no appropriate prefixes which say the property is deprecated are available in Web IDL, the layoutStyle property should be removed.

**Comment by mattgarrish** [comment]
Yes, this is related to #799. I missed the inclusion in the IDL, but we've been moving all definitions of deprecated/superseded features to the appendixes.

I'm a little worried people might not pay attention to these appendixes, so might miss that these still have to be supported, but it's the path we've chosen to unclutter the specifications with obsolete feature definitions.
