### ISSUE TITLE
Remove the syntax sections in Content doc Appendix A

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#875]
ReadingSystemObject Syntax has been provided by using Web IDL, and it is crystal clear. On the other hand, two syntax sections are trying to provide syntax related information in the same chapter, and due to the uncleanness of description language, it is uncertain whether they are going to override the Web IDL syntax or not.
If it is trying to tell how to use it, the section title should say "example", instead of "syntax", and provide some examples.

**Comment by mattgarrish** [comment]
There are examples in the descriptions. I think we can do without the syntax sections given the addition of the web idl definition in this revision.
