### ISSUE TITLE
version used in hasFeature() is not always a number.

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#876]
Content doc A 5.1.2 says

> Authors should not include a version number when querying features defined in this specification — these features are considered versionless. If a Reading System supports a feature defined in this specification, it must ignore any supplied version number and return a true value.

According to the Web IDL syntax, the version is `DOMString`, and no restrictions are specified in the document. In the previous phrase, it is said that the version is an optional parameter.  Then, I'm afraid that this phrase might be interpreted that there are ways to include a version number into the string.  The lack of wrapping with `<code>` increases the unclearness.

I think the phrase should say something like this:

Authors should not set a `version`parameter when querying features [...], it must ignore the supplied `version`parameter and return a `true`value.

**Comment by mattgarrish** [comment]
Fixed.
