### ISSUE TITLE
[Content Doc] "IDL" is a little bit unclear as a title of epubReadingSystem interface

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#877]
The title of Content Doc Appendix A.2 is "IDL".
First, it is unclear what "IDL" stands for. Second, since there are several Interface definition languages, the title "IDL" is not an appropriate title for this section.
I think the intention of this section is to specify the epubReadingSystem interface by using Web IDL, and if it is so, the section title should be "epubReadingSystem Interface" or something similar. Plan B is "Web IDL".

**Comment by mattgarrish** [comment]
What about "Interface Definition"?
