### ISSUE TITLE
[Content Doc] Web worker link should point to the undated URL

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#878]
ePubReadingSystem Object in Appendix A. mentions about Web workers, and the reference points to the dated version of Web Workers specification. Since the Web IDL clearly says that the interface is applicable only for `Window`, the current interface won't be applicable for any future versions of Web Workers. Then, following to the dated - undated reference discussion, the link should intentionally points to the undated version.

**Comment by mattgarrish** [comment]
I guess in this case, being an informative reference, it doesn't matter if it's undated.
