### ISSUE TITLE
[Content Doc] epubReadingSystem object does not expose "a number of" properties, just two.

### ISSUE THREAD

**Issue by tkanai** [w3c/epub-specs#879]
Content Doc Appendix A.3 says 

> The object exposes a number of properties about the Reading System, such as its name and version,

But the reality is it only exposes the name and version. Is the word "a number of" appropriate expression in this context?
 It used to expose three properties, but `layoutStyle`  is "deprecated" in version 3.1.

**Comment by mattgarrish** [comment]
Two is a number... ;)

But I agree that we can just delete "a number of" and improve the clarity without losing any vital information:

> The object exposes properties of the Reading System (its name and version),
