### ISSUE TITLE
Section 5.5 Minor errors

### ISSUE THREAD

**Issue by madeleinerothberg** [w3c/epub-specs#880]
In my review of section 5.5 Event Model Considerations http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-scripted-content-events, I noted these minor errors:

1) The link with the text "potentially malicious" seems to point back to section 5.5, but I suspect it was intended to point to section 5.4 Security Considerations.

2) In the second paragraph, the phrase "and in many cases a soft keyboard is only activated only for text input elements" has one too many "only"s.

3) The last sentence reads as if it is referring to some example that isn't fully explained. The easiest fix might be to change "the desired action" to "a desired action".

**Comment by mattgarrish** [comment]
Fixed.
