### ISSUE TITLE
switch of SVG and requiredExtensions

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#881]
[It must recognize the value http://www.idpf.org/2007/ops of the requiredExtensions attribute when appearing on the switch and foreignObject elements as representing the occurrence of XHTML Content Document fragments.](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#confreq-svg-rs-reqdExt)

But switch elements do not specify the requiredExtensions attribute.  Children of switch specify this attribute.

**Comment by mattgarrish** [comment]
Are there uses of requiredExtensions where we want to actively ignore that value?

If not, make the elements examples:

> It MUST recognize the value "http://www.idpf.org/2007/ops" of the requiredExtensions attribute as representing the occurrence of XHTML Content Document fragments (e.g., when the attribute appears on the foreignObject element or children of the switch element).

**Comment by murata2makoto** [comment]
I have no objections.

**Comment by iherman** [comment]
I do not understand this issue. @murata0204 what do you mean by:

> But switch elements do not specify the requiredExtensions attribute. Children of switch specify this attribute.

The switch element, as well as the `requiredExtensions` is well specified in [https://www.w3.org/TR/SVG11/struct.html#ConditionalProcessingRequiredExtensionsAttribute](SVG1.1) and it is also present in [SVG2](https://www.w3.org/TR/SVG2/struct.html#ConditionalProcessingRequiredExtensionsAttribute).

In view of that comment what is in the EPUB spec looks perfectly fine to me...

**Comment by murata2makoto** [comment]
https://www.w3.org/TR/SVG/struct.html#SwitchElement

> The ‘switch’ element evaluates the ‘requiredFeatures’, ‘requiredExtensions’ and ‘systemLanguage’ attributes on its direct child elements in order, and then processes and renders the first child for which these attributes evaluate to true. All others will be bypassed and therefore not rendered. If the child element is a container element such as a ‘g’, then the entire subtree is either processed/rendered or bypassed/not rendered.

**Comment by iherman** [comment]
Ah, o.k. Sorry, you are right, the original text was not o.k.. I agree with Matt's reformulation.

**Comment by mattgarrish** [comment]
Fixed.
