### ISSUE TITLE
"under left" for -epub-text-underline-position

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#882]
EPUB 3.0.1 allows "auto", "alphabetic", "under left", and "under right" for -epub-text-underline-position.  EBPAJ uses "under left", and thus tons of EPUB publications in Japan specify "under left" for this property.   But EPUB Content Document 3.1 allows "alphabetic" only.  I believe that this is a mistake.

**Comment by mattgarrish** [comment]
It allows 'under left'. The double bar in CSS syntax means that at least one of the options has to appear, so it would expand out to 'under', 'left', 'right', 'under left' or 'under right'. Correct @dauwhe ?

We should link to the CSS3 Values and Units definition of this syntax, though.

**Comment by mattgarrish** [comment]
I've added a reference for the syntax, so closing this issue. Feel free to re-open if there's something else that needs addressing.
