### ISSUE TITLE
Def of Scripted Conent Documents

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#885]
In EPUB 3.1, s

> Scripted Content Document
> An EPUB Content Document that includes scripting or an XHTML Content Document that contains HTML forms elements.

But EPUB Content documents 3.1,

> EPUB Content Documents may contain scripting using the facilities defined for this in the respective underlying specifications ([HTML] and [SVG]). When an EPUB Content Document contains scripting, it is referred to in this specification as a Scripted Content Document. 

Is an EPUB content document containing a form a scripted content document?

**Comment by mattgarrish** [comment]
Doesn't the last sentence of the second quote cover this?

> This label also applies to XHTML Content Documents when they contain instances of HTML forms.

I personally don't like this criteria for scripting designation, as form elements don't have to appear in a form in HTML5. And the only reason to consider a document with a form scripted is if there is no local scripting but it submits to a remote server for processing.

That's my take, anyway. I'm sure I asked this in a previous revision, and there was some other justification for keeping it as it is. It's lost on me what it was, though.

**Comment by murata2makoto** [comment]
I see.  Thanks.

**Comment by mattgarrish** [comment]
I think my complaint might have just been considered a niche case not worth the bother of differentiating. The cases for form elements without a form or scripting are pretty rare.

**Comment by mattgarrish** [comment]
Actually, looking at this closer I think the definition is misleading and my complaint is covered. The link (improperly not attributed) doesn't reference all form elements, but the forms definition, which requires the elements inside a form tag.

In both case, the prose would be better to only state "contains [HTML] forms" (varied to fit the context).

But another issue I'm left wondering is why we state in an informative section that forms do not have to be supported, but there are no normative statements to explain what this means, only a pointer to the scripting section.

I assume for forms it doesn't mean they don't have to be rendered, but that submission of forms is optional. I don't see this stated as optional behaviour anywhere, and it can't be inferred from scripting being optional (which the DOM, I suppose, can).

**Comment by mattgarrish** [comment]
I've fixed the editorial part of this issue, so will open a new one to consider forms support.
