### ISSUE TITLE
Inclusion model?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#886]
I think that the phrase ["inclusion model"](https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-scripted-content-content-reqs) in Content Documents 3.1 should be "scripting contexts".

**Comment by mattgarrish** [comment]
Generally agree, but using a context doesn't sound right. Maybe "in either context":

"EPUB Content Documents that include scripting — in either context —"

Seems somewhat like a needless clarification, though. We achieve the same by dropping and simply hyperlinking "includes scripting".

**Comment by murata2makoto** [comment]
I think that 

> EPUB Content Documents that include scripting — using any inclusion model —

needs more work.  First, scripts in SVG documents are neither spine-level nor container-constrained.  Second, do we have something to say about HTML forms?

**Comment by mattgarrish** [comment]
The definitions need to note the SVG script element, but how are the contexts not applicable to SVG?

I'm not sure I see why forms need noting here. Either they are scripted, in which case they fall under one of these contexts, or they submit to a remote server, in which case it's not scripting in this sense.

**Comment by mattgarrish** [comment]
Proposed Solution

Add SVG script element to the scripting context definitions.
