### ISSUE TITLE
What about HTML forms is not supported?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#887]
We state in the relationship to HTML section that support for HTML forms is not part of the profile, but there is only a link to the scripting section by way of explanation, and the scripting section doesn't deal with forms.

The only tenuous link is that an RS can restrict access to the network by scripts, so by limiting access it would also limit access to form submissions, and maybe you could call a form a script???

I can only assume that we forgot to include a statement that support for submission of forms by reading systems is optional. Such a statement doesn't belong under the scripting section, though, as the actual submission of forms isn't dependent on scripting, even if a script can trigger the process.

I believe we just need a short statement in the html deviations section. Something like:

> 2.5.6 Form Submissions
> 
> Reading System support for the submission of [HTML] forms is OPTIONAL. A Reading System might, for example, prevent form submissions by limiting access to networking.

**Comment by mattgarrish** [comment]
I'm taking this off the 3.1 timeline given how late in the process we are and there have been no opinions voiced on the list about how to interpret the statement.

I'm going to set to deferred, as we should clear this up in a future revision.

**Comment by JayPanoz** [comment]
If this is mainly about forms’ `action` and `method` (i.e. [sending form data](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data)), I’m fine with both being optional. 

If this also leaks to form elements in some way, then it’s an issue. Currently, you indeed have Reading Systems which display form elements but make them static (as opposed to interactive) and you can’t check a checkbox or select an option for instance, resulting in a super poor user experience as it would be expected those elements are interactive.

**Comment by dauwhe** [comment]
Closed with #1060
