### ISSUE TITLE
container-constrained scripting and fixed layout

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#888]
Is it possible to have container-constrained scripting within fixed-layout documents?   [5.3](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-scripted-content-rs-reqs) does not mention this case.

**Comment by mattgarrish** [comment]
The fourth bullet captures all other cases: "It may support scripting in other contexts, but this specification does not address such scripting."

**Comment by mattgarrish** [comment]
Closing this issue as there's no fix involved. If you're wanting to increase support to a should, please ask on list.

**Comment by murata2makoto** [comment]
Many fixed-layout picture books use scripting.  I think that the first bullet should be changed to:

> It should support container-constrained scripting.

I will raise an issue in the list.
