### ISSUE TITLE
clarify that multiple itemrefs referencing the same resource leads to ambiguous hyperlinks

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#889]
As raised on the working group list,[1] you can have multiple itemrefs reference the same manifest item, but when it comes to resolving hyperlinks into the document, a reading system won't know which of the references the author wanted to send the user to.

Without explicitly bringing back epubcfi, we should clarify this problem in a way that would allow epubcheck to issue warnings.

As a starting point, I'd suggest adding the following as the third paragraph (from below the definition box) of the itemref definition:[2]

"Although more than one itemref MAY reference the same Publication Resource, Authors SHOULD NOT include hyperlinks into the referenced resource in such cases. A Reading System will not be able to determine which of the references the Author intends the user to follow unless a scheme that can distinguish between spine items is used."

[1] https://groups.google.com/d/msg/epub-working-group/Iap15oYlDAk/NU42YH_AAwAJ
[2] http://www.idpf.org/epub/31/spec/epub-packages.html#sec-itemref-elem

**Comment by danielweck** [comment]
I think that the statement "unless a scheme that can distinguish between spine items is used" is potentially confusing. Sure, such hyperlinking scheme exists (CFI), but content authors are now explicitly told not to use it. I would suggest being more concrete. After "in such cases", I would add ", because a Reading System would be unable to determine the actual spine itemref based on the path of the Publication Resource alone.".

**Comment by mattgarrish** [comment]
Well, technically we're silent on the use of CFI. We dropped the RS support requirement, but we didn't outright ban the use of CFIs. That's what I was trying to tiptoe around.

I agree it makes for confusing wording, though, so I'm fine with your alternate proposal.

**Comment by mattgarrish** [comment]
Consensus on the working group list is that we should re-introduce the EPUB 2 restriction, as loosening was done to support use cases with not enough merit (or production complexity) to justify the problem this introduces.

See the discussion starting at https://groups.google.com/d/msg/epub-working-group/Iap15oYlDAk/IHhKjYQ-BAAJ

**Comment by mattgarrish** [comment]
To wrap this up, it looks like there's been misreading of the specification. The first paragraph after the description box covers uniqueness:

> Each itemref element must reference via an IDREF [XML] a unique item in the manifest via its itemref attribute.

It would have read "exactly one item" in the manifest if unique were only equivalent with one. To fix the obvious attribute name typo in this sentence, and clarify application, the sentence is being modified as follows:

"Each itemref element must reference the ID [XML] of a unique item in the manifest via the IDREF [XML] in its idref attribute (i.e., two or more itemref elements cannot reference the same item)."
