### ISSUE TITLE
request to list recommended specifications

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#890]
Although the working group decided not to normatively incorporate the modular extensions, a request was made to list them in the core specification.

This could be done by modifying the last two paragraphs of section 2.1 as follows:

> These specifications represent the formal list recognized as belonging to EPUB 3.1, and that contain functionality referenced as part of the standard.
> 
> The IDPF has also developed a set of specifications that complement the core functionality of EPUB 3.1, but but whose support in Reading Systems and use in authoring is OPTIONAL:
> - EPUB Canonical Fragment Identifiers
> - EPUB Dictionaries and Glossaries
> - EPUB Indexes
> - EPUB Multiple Renditions
> - EPUB Previews
> - EPUB Region-Based Navigation
> 
> New functionality is also added periodically through the development of extension specifications. Features and functionality defined outside of core revisions to the standard, while not formally recognized in this specification, are nonetheless available for use by Authors and Reading System developers (but are not stable until they reach the status of Recommended Specifications).

**Comment by mattgarrish** [comment]
Proposed Solution

Add a list of optional modules as noted above.

**Comment by OriKuttner** [comment]
CFI was removed from the standard so why add it?

**Comment by mattgarrish** [comment]
CFI was removed from the core because it's no longer required to be supported for linking in content documents. It's still a recommended specification that open annotation, for example, depends on.

**Comment by mattgarrish** [comment]
It's also not forbidden to use CFIs in content, even if there is no guarantee of support.
