### ISSUE TITLE
Foreign Resource Restrictions minor typo?

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#891]
> [Flow content may be embedded within the [HTML] audio and video elements for rendering in older Reading Systems that do not recognize these elements (e.g., EPUB 2 Reading Systems), but it does not does not represent a Core Media Type fallback.](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#confreq-resources-cd-fallback-media)

"does not" is duplicate.

**Comment by mattgarrish** [comment]
Thank you, the duplicate prose has been removed.
