### ISSUE TITLE
"Reading System content display area" and "content rendering area"

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#898]
I tried to understand the relationship among Reading System content display area, content rendering area, initial containing block, and viewports.  The first two terms are used in our 3.1 specifications.  This task appears to be too difficult for me.

Here is my attempt for understanding them.

https://docs.google.com/spreadsheets/d/1fkYTJb1pimBSUxbgi9-VQk7nTU8FpUJNf7xT_SphmgE/edit?usp=sharing

Do we really need both "Reading System content display area" and "content rendering area"?

**Comment by mattgarrish** [comment]
I would imagine not, since they're clearly synonymous. It looks like rendering area was introduced when the viewport rendering section was added in 3.0.1.

**Comment by mattgarrish** [comment]
Is the wording the only issue here, or is there something else you were trying to raise?

**Comment by murata2makoto** [comment]
First, drop either "Reading System content display area" or "content rendering area".

Second, clarify the relationship between "Reading System content display area" and "initial containing block".  The relationship appears to depend on whether or not the spread view is used.

Third, what is the relationship between "initial containing block" and "viewport"?

**Comment by mattgarrish** [comment]
I've replaced rendering area with display area, as that was the original terminology.

As I've understood it, the viewport contains the display area plus margins, running headers/footers, etc. The display area is only the portion where the content gets displayed. The ICB is the region allocated to an FXL document, which fits inside the display area but doesn't necessarily occupy all of it.

I don't know that a spread necessarily affects the content display area, or it at least seems reading system dependent whether both pages are in one content display area or whether there are technically two display areas.

@GarthConboy any thoughts on this, and what changes, if any, are needed?

**Comment by mattgarrish** [comment]
Would it be sufficient to add a definition for content display area to get this done? Perhaps something like:

> Content Display Area
> 
> The area within the Viewport dedicated to the display of EPUB Content Documents. The Content Display Area excludes any borders, margins, headers, footers or other decoration a Reading System might inject into the Viewport.
> 
> In the case of synthetic spreads, the Viewport contains two Content Display Areas.

I can't really see that we need to bring the ICB into the definition, as the FXL already discusses that relationship.

**Comment by rkwright** [comment]
That works for me.

**Comment by murata2makoto** [comment]
Much better than status quo.

**Comment by mattgarrish** [comment]
I've added the definition. As there haven't been any further comments on this, I'm closing the issue.
