### ISSUE TITLE
EPUB Accessibility 1.0; Section 4.3.2.2

### ISSUE THREAD

**Issue by GarthConboy** [w3c/epub-specs#900]
"Authors must not use EPUB's fallback mechanisms to provide a conforming alternate version [WCAG 2.0], as there is no reliable way for users to access such fallbacks. If fallbacks are used, both the primary content and its fallback(s) must meet the requirements for the conformance level claimed. Examples of EPUB-specific fallback mechanisms include manifest fallbacks, bindings and content switching."

What is "content switching"?  Is that multiple renditions?  If so, should probably be explicit.  If not, please define.

**Comment by mattgarrish** [comment]
It's epub:switch. I used the title from the spec,[1] but I guess if it stumped you it could do for a parenthetical.

[1] http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-content-switch
