### ISSUE TITLE
A11y: Printed vs statically-paginated

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#901]
In section 4.4.1.3 we have this text: "identified as the digital equivalent of a statically-paginated publication"

Should "statically paginated" just be "printed", or is it intended to include things like PDF? If it does include things like PDF, then it is strange to call the EPUB the "digital equivalent". I think this should either be digital/printed or dynamically/statically paginated.

**Comment by mattgarrish** [comment]
It possibly includes digital fxl publications, too.

Dynamic would work better.
