### ISSUE TITLE
A11y: example of accessibility summary?

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#905]
In reading Section 5, Optimized Publications, I found myself longing for an example of an accessibility summary.

**Comment by clapierre** [comment]
I will bring this up with the A11Y TF.

**Comment by mattgarrish** [comment]
I'm sure we can come up with some fictitious description of braille optimization, like:

"This publication is optimized for braille reading devices capable of displaying 6 character cells and 40 character line lengths. The text is not contracted, and follows Unified English Braille formatting conventions. All characters are encoded using the Unicode braille character set."

Or something along those lines. I'm sure Lloyd can probably suggest improvements.
