### ISSUE TITLE
Review of 3.3 Linked Metadata Records

### ISSUE THREAD

**Issue by rickj** [w3c/epub-specs#913]
We acknowledge that "precedence given to linked records varies depending on the version of EPUB", and warn that internal and external data should not be contradictory, but we do not declare precedence for EPUB 3.1.

In the event of two metadata statements for the same element (internal, and external), do we want to declare precedence?

**Comment by laudrain** [comment]
Hi,
I think we do define precedence in 3.1.
In "3.4.3.5 The link Element" section see:
 `When it comes to resolving discrepancies and conflicts between metadata expressed in the Package Document and in linked metadata records, Reading Systems must use the document order of link elements in the Package Document to establish precedence (i.e., metadata in the first linked record encountered has the highest precedence and metadata in the Package Document the lowest, regardless of whether the link elements occur before within or after the package metadata elements).`

**Comment by mattgarrish** [comment]
We could probably make the paragraph an informative note, and indicate which versions give which precedence to clarify. We've tried to avoid making the accessibility specification specific to any one version, but the precedence rule seems unlikely to change again, so noting what 3.1 does versus 3.0/3.0.1 doesn't materially change that approach.
