### ISSUE TITLE
are changes and overview really specifications?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#915]
From the list of things I stopped thinking about long ago...

The changes document is not a specification, but we've always identified it as moving through the draft/proposed/recommended specification stages. The overview is similarly not a specification, but more of a feature list/marketing piece. Neither makes normative statements.

It seems like a mistake to have identified them as specifications, and that they should be marked as "draft informational document" while we're working on a revision and published as "informational document" at the end.

**Comment by murata2makoto** [comment]
I agree.  If EPUB 3.1 becomes a multi-part international standard of ISO/IEC, we have to clearly distinguish normative parts and non-normative parts.  Non-normative parts are technical reports in such multi-part international standards.
