### ISSUE TITLE
Do we have to define "author" in EPUB Accessibility 1.0?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#924]
> Author
> The person(s) or organization responsible for the creation of an EPUB Publication. The Author is not necessarily the creator of the content.

But this term is already defined in EPUB 3.1.  Should this term be defined here?  The same applies to several other terms.

**Comment by mattgarrish** [comment]
The specification is not specific to epub 3.1 so the definitions are more generic.

Using 3.1's definitions would bind it to one version.

**Comment by mattgarrish** [comment]
Note that the question of whether to include terminology in the documents or link to them (or not give any links but expect people to find the appropriate version and look up the meanings) was dealt with by the group very early on and this was the decision they came to.

Unless there's a compelling reason to re-open this, let's leave it as is and we can adjust in a future update if it causes real-world problems.

Some of the definitions are exactly the same as in 3.1, but others account for differences across versions, such as what formats are officially content documents.

There's also a note at the end of the section that states that the definitions might have more specific meanings in a given version.
