### ISSUE TITLE
Which natural language is used for accessibilitySummary?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#925]
Is it possible to specify which natural language is used?  Can we specify accessibilitySummary multiple times (once for one language)?

**Comment by mattgarrish** [comment]
You can attach xml:lang, like any other property. You should not repeat it for the same language.

**Comment by mattgarrish** [comment]
I've clarified this in the techniques. See the second last paragraph at:

https://rawgit.com/IDPF/epub-revision/master/build/a11y/techniques/techniques.html#meta-005
