### ISSUE TITLE
Informative sections in Accessibilty 1.0

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#926]
Should 4.4.1.1
https://rawgit.com/IDPF/epub-revision/master/build/31/docs/epub31-v31/EPUB/a11y/accessibility.html#sec-page-nav-obj

4.4.1.2
https://rawgit.com/IDPF/epub-revision/master/build/31/docs/epub31-v31/EPUB/a11y/accessibility.html#sec-page-nav-understand

4.4.1.4

https://rawgit.com/IDPF/epub-revision/master/build/31/docs/epub31-v31/EPUB/a11y/accessibility.html#sec-page-nav-wcag

be marked as informative?

**Comment by mattgarrish** [comment]
I can't see how the objective could be informative since it's the purpose statement, but the understanding and relationship sections could be marked informative.

**Comment by mattgarrish** [comment]
Updated.
