### ISSUE TITLE
[3.1] One container with different EPUB versions inside

### ISSUE THREAD

**Issue by therealglazou** [w3c/epub-specs#935]
AFAICT, nothing normative in the EPUB specs, from 2 to 3.1, prevents a publisher from releasing an EPUB container containing both an EPUB2 and an EPUB3 package, one being the default rendition. I suspect this would be painful to EPUB validators and it's already a nightmare for my own editor, BlueGriffon. Since the EPUB version can only be tested on the `package` element of each rendition, it's impossible to infer the default rendition's EPUB version without looking at the opf files, a rather expensive operation.

I know that all 3.1 specs refer only to other 3.1 specs but a clarification, even as an informative note, about this issue could be really useful. Is it allowed (at the cost of expensive complexity for the aforementioned tools/apps), or is it explicitely forbidden? Thanks.

**Comment by mattgarrish** [comment]
It becomes invalid to mix versions through the definition of a publication, which requires one or more packages each of which has to conform to the specified version.

So while you could have an OCF with package documents conforming to different versions, it would technically be two separate publications, not multiple renditions of the same publication.

But a clear case of the multi-spec approach making these kinds of determinations harder than they should be. I'm fine with a note, or normative statement, that clears this up.

**Comment by therealglazou** [comment]
Excellent, thanks @mattgarrish

**Comment by clapierre** [comment]
@mattgarrish Can this be done in such a way (say in a techniques document) that would not require a new EPUB version to clarify this?

**Comment by murata2makoto** [comment]
I am wondering if W3C can publish errata for any of the existing 
versions of EPUB.  Errata would not require heavy-weight voting or 
new version numbers.

**Comment by mattgarrish** [comment]
All the specs have errata links, but this is more of a clarification of existing requirements.

The multiple renditions specification doesn't account for multiple versions as we made the same determination that they aren't allowed, didn't we? It sort of requires a multiple rendition approach that isn't following that specification.

**Comment by iherman** [comment]
> On 6 Jan 2017, at 15:30, MURATA Makoto <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> I am wondering if W3C can publish errata for any of the existing
> versions of EPUB. Errata would not require heavy-weight voting or
> new version numbers.
> 
Yes. The maintenance is planned to be covered by a W3C Community Group, and a W3C CG has the right to publish any document; it is up to the decision of the CG. Ie, publishing a separate Errata document for EPUB 3.1.

This is not the same as republishing a new version of 3.1, e.g., 3.1.1. That would be much more complicated and I am not sure this is something the CG should do.

**Comment by mattgarrish** [comment]
I'm getting lost, I think. Are we talking about new version number as in specification version number or epub version numbers?

For example, can we publish an Accessibility "1.1" update, for example, but not devise a new version of EPUB that requires version="3.1.1" in the package document?

I fully agree with the latter, but I thought specification updates were fine so long as they don't evolve into new versions.

**Comment by murata2makoto** [comment]
I think that the EPUB 3 (and 2) Community Group should avoid changing spec versions and embedded version strings.  I like errata and new editions (consolidations of errata).

**Comment by mattgarrish** [comment]
Even where that's possible, how do you propose making users aware that the document has changed? If they're just supposed to figure out that the date has changed, we couldn't be more unfriendly.

W3C has a history of appending "X Edition" when reissuing with in-place changes, which has always struck me as a better approach for minor releases.

**Comment by murata2makoto** [comment]
> Even where that's possible, how do you propose making users aware that the document has changed? If they're just supposed to figure out that the date has changed, we couldn't be more unfriendly.


In my opinion, not publishing errata is more unfriendly.

 In the case of IETF, RFCs have links to errata.  W3C Recs also have links to errata.  ISO/IEC standards do not have any links (You are suppose to see the list of published corrigenda).

>W3C has a history of appending "X Edition" when reissuing with in-place changes, which has always struck me as a better approach for minor releases.

When I was active in  W3C (loooong time ago), such editions were published by consolidating published errata.

**Comment by mattgarrish** [comment]
I'm not saying we not publish errata, but it always feels like a useless exercise when people don't follow the links. We published errata post-3.0.1 and had the issues reported again by other people when we started 3.1.

What I am saying is we shouldn't rely on people finding errata, and should be able to republish the corrected documents. In doing that, there should still be some prominent indication that changes have been made, like "EPUB 3.1 (Second Edition)".

But I don't imagine we'll solve this here, so it'll be interesting to see what new process is put in place when the documents move to w3c.

**Comment by iherman** [comment]
@murata0204 : indeed, W3C sometimes publishes new releases, incorporating the errata. These days we also call these 'edited' recommendations. However, unless the changes are only grammatical, those changes may have to go through an AC voting round, just like a new Rec.

However, I agree that issuing something like that is the best for the community

@mattgarrish : indeed, we may not be able to solve it here, but should be discussed as part of the CG setup : will the CG have the right to republish a 2nd edition in... where? The IDPF namespace? A new namespace? 

Cc @whmccoy

**Comment by dauwhe** [comment]
The spec [says](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-ocf.html#sec-container-metainf-container.xml)

> Each rootfile element MUST identify the location of a Package Document representing one Rendition of the EPUB Publication.

Can we add

> Each rendition MUST conform to the same version of the spec as the container.

**Comment by dauwhe** [comment]
Closed with #1060

**Comment by mattgarrish** [comment]
I found this statement a bit confusing, as "of the spec" doesn't refer to anything specifically (made me wonder if it was talking about "1.0" for the container. I've tweaked the wording to:

> Each rendition MUST conform to the same version of EPUB as its container.
