### ISSUE TITLE
[3.1] Add notion of EPUB Authoring System for definitions of deprecated and superseded

### ISSUE THREAD

**Issue by therealglazou** [w3c/epub-specs#936]
Appendix A of http://www.idpf.org/epub/31/spec/epub-spec.html defines what means "deprecated" and "superseded" for Authors, Reading Systems and Validation Tools. But nothing is said about Authoring Systems, that fall into none of these three categories.

Example: the `refines` attribute is now deprecated in 3.1. It means that my editor BlueGriffon must accept it when it opens a 3.1 instance. But should it allow to modify existing `refines` attribute or even create new ones?

I am therefore advocating for the creation of a new category "EPUB Authoring System: a system that outputs EPUB Publications" and the addition of the following mentions to appendix A:

For "deprecated":

> Authoring Systems MUST continue, on input, to support the feature as it is defined until it is formally removed. An Authoring System MAY remove an occurence of the feature if it's already present in a Publication but it MUST NOT add a new occurence of the feature to a Publication nor modify an existing one (unless for a removal).

For "superseded":

> Authoring Systems MUST NOT support the superseded feature in content that conforms to the current version of the specification, on both input and output.

There are certainly other spots in the specs where this could be useful.

**Comment by therealglazou** [comment]
Side note: the question above is a real one. What should BlueGriffon do about `refines` ? Allow removal only? Allow modification of existing ones? Allow creation of new ones? I am very strongly in favor of first option, removal only.

**Comment by mattgarrish** [comment]
I'd think you'd want more flexibility for authoring tools than a specification can offer, as any answer seems to depend on what kind of backwards compatibility support you want to offer your users, and what kind of importing/exporting you support.

Authoring tools should be able to run the gamut from no support for deprecated/superseded features to full support. I'd favour the developer deciding what is reasonable for them to support.

**Comment by dauwhe** [comment]
Consensus on the CG call today was that we don't think the EPUB spec should make requirements for authoring tools.
