### ISSUE TITLE
[3.1] refines is noted 'deprecated' in prose on meta but 'superseded' in definition

### ISSUE THREAD

**Issue by therealglazou** [w3c/epub-specs#938]
Excerpt from http://www.idpf.org/epub/31/spec/epub-packages.html#sec-meta-elem :

> refines [optional] [SUPERSEDED]

Excerpt from http://www.idpf.org/epub/31/spec/epub-packages.html#attrdef-meta-refines :

> Use of the meta refines attribute is deprecated

**Comment by mattgarrish** [comment]
The label should be deprecated. Refines flip-flopped between the two, but settled late on deprecated to retain support.

**Comment by mattgarrish** [comment]
Closing as not applicable to 3.2.
