### ISSUE TITLE
[3.1] Why is container.xml version still 1.0?

### ISSUE THREAD

**Issue by therealglazou** [w3c/epub-specs#939]
the `version` attribute of the `container` element is still 1.0 in EPUB 3.1, forcing applications to parse renditions to know the EPUB version used. Why is that value still 1.0 while it would be very convenient to have a 3.1 there?

**Comment by dauwhe** [comment]
Given that we are reverting the package version to 3.0, and that we are explicitly remaining entirely compatible with 3.0.1, I don't think we can change this. This would be a good issue for EPUB 4 packaging :)
