### ISSUE TITLE
Alternate Style Tags 1.0

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#942]
It should be available at [http://www.idpf.org/epub/altss-tags/altss-tags-20140626.html](http://www.idpf.org/epub/altss-tags/altss-tags-20140626.html), but this URL does not work.  Is this a configuration mistake?

**Comment by mattgarrish** [comment]
Yes, the dated file on the ftp server had "28" not "26" in the name. Should work now.
