### ISSUE TITLE
Incorrect status of EPUB 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#943]
> This document is a draft produced by the EPUB Working Group under the EPUB Working Group Charter approved on 8 July 2015.

> This document is not considered stable and might be updated, replaced or obsoleted at any time. Its publication as a draft does not imply endorsement by IDPF membership or the IDPF Board. When citing this document, clearly refer to it as a work in progress.

The above paragraphs appear in EPUB 3.1 Recommended Specifications available at http://www.idpf.org/epub/31/spec/epub-spec.htm

If I am not mistaken, the same applies to EPUB Packages 3.1, EPUB 3.1 Overview, EPUB Media Overlays 3.1, EPUB Open Container Format (OCF) 3.1.

**Comment by mattgarrish** [comment]
Yes, same boilerplate. It's been fixed.

**Comment by murata2makoto** [comment]
I do not think that we should silently fix this bug.  For example, translations will not be updated, if we do that.  At least, we have to make clear that there was an editorial change on 2017-01-22.
