### ISSUE TITLE
[3.1] markup request - 3.2.1 Structure

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#948]
> [The body of a Media Overlay Document consists of two elements: the par element and the seq element.](http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html#sec-media-overlays-structure)

want to add elements.

"The body element of a Media Overlay ..."

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
