### ISSUE TITLE
[3.1] markup request - 3.3 Semantic Inflection

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#949]
> [In order to express semantic inflections, the epub:type attribute [Content Docs 3.1] may be attached to Media Overlay par, seq, and body elements.](http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html#sec-docs-semantic-inflection)

Please markup "epub:type" as a markup of Typographic Conventions.

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
