### ISSUE TITLE
[3.1] markup request - 2.4.1.1 Introduction

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#950]
> [The epub:type attribute is used to express domain-specific semantics in XHTML Content Documents, ...](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-semantic-inflection-intro)

Please markup "epub:type" as a markup of Typographic Conventions.

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
