### ISSUE TITLE
[3.1] markup request - 5.3 Reading System Conformance

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#951]
> [It should support spine-level scripting in reflowable EPUB Content Documents that use the "scrolled-doc" or "scrolled-continuous" presentation modes defined by the rendition:flow property [Packages 3.1].](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-scripted-content-rs-reqs)

Please markup "rendition:flow" as a markup of Typographic Conventions.
("the" necessary?)

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
