### ISSUE TITLE
[3.1] markup request - A.2 Description

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#952]
> [Reading systems implementations might create cloned instances of the epubReadingSystem object in Scripted Content Documents for technical feasibility reasons.](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#app-ers-desc)

epubReadingSystem is mark up with "code". want to mark up with "markup".

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
