### ISSUE TITLE
[3.1] markup request - 4.2 Semantic Markup

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#953]
> [EPUB 3.1 includes the epub:type attribute, which is meant to be functionally equivalent to the W3C Role Attribute [Role].](http://www.idpf.org/epub/31/spec/epub-overview.html#sec-access-semantic-markup)

Please markup "epub:type" with "markup".

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
