### ISSUE TITLE
[3.1] markup request - 9 EPUB Canonical Fragment Identifiers and 10 Alternate Style Tags

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#954]
> [Refer to the issue tracker for a complete list of clarifications, typos and other issues in the EPUB Canonical Fragment Identifiers specification addressed in this revision.](http://www.idpf.org/epub/31/spec/epub-changes.html#sec-cfi)

> [Refer to the issue tracker for a complete list of clarifications, typos and other issues in the Alternate Style Tags specification addressed in this revision.](http://www.idpf.org/epub/31/spec/epub-changes.html#sec-altss)

mark up the above as a note?

**Comment by mattgarrish** [comment]
Changing to notes would leave no actual text in the sections. I believe that's why they weren't marked up as such.

In any case, this document will never be updated again. It will be replaced by a changes document for whatever version comes next, in which case new prose will be written.
