### ISSUE TITLE
[3.1] Redirect from Latest version

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#955]
- EPUB 3.1 Overview
- EPUB Content Documents 3.1
- EPUB Open Container Format (OCF) 3.1
- EPUB Media Overlays 3.1
- Changes from 3.0.1

The redirect from the Latest version of the above specification has been transferred to the 3.0.1 specification.
Why is not 3.1 specification?

**Comment by mattgarrish** [comment]
Closing as not an issue or already fixed. In any case, the links appear to work fine.
