### ISSUE TITLE
[3.1] markup request - ACCESS-001: Ensure linear reading order of the publication

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#958]
> [Authors also need to ensure that they identify whether items in the spine contain primary or supplementary information using the linear attribute [Packages] so that the Reading System can optimally present such content.](http://www.idpf.org/epub/a11y/techniques/techniques-20170105.html#access-001)

Please markup "linear" with "markup" at Typographic Conventions.

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
