### ISSUE TITLE
[3.1] markup request - SEM-001: Include ARIA and EPUB semantics

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#959]
> [The following example shows the epub:type attribute used to provide additional semantic information.](http://www.idpf.org/epub/a11y/techniques/techniques-20170105.html#sem-001)

Please markup "epub:type" with "markup" at Typographic Conventions.

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
