### ISSUE TITLE
[3.1] typo report - TITLES-002: Ensure numbered headings reflect publication hierarchy

### ISSUE THREAD

**Issue by imagedrive** [w3c/epub-specs#961]
> [For example, if a document starts with an h3 heading, there shouldn't be an h2 heading later in the document (...](http://www.idpf.org/epub/a11y/techniques/techniques-20170105.html#titles-002)

"shouldn't" is not typo, but please write "should not".

**Comment by mattgarrish** [comment]
Markup issue fixed as part of port to w3c respec format.
