### ISSUE TITLE
Planing to CSS Fragmentation Module Level (css-break) 

### ISSUE THREAD

**Issue by ppKrauss** [w3c/epub-specs#971]
As https://www.w3.org/TR/css-break/ is coming (!), the future portable-EPUB releases can say something about it. Example: *printable EPUB* and HTML-css-break recomendations in "paged media".

**Comment by teytag** [comment]
It’s good article…

**Comment by dauwhe** [comment]
EPUB now officially uses the [CSS snapshot](https://www.w3.org/TR/CSS/)

Right now, this document describes CSS-break with the phrase

> The following modules have completed design work, and are fairly stable, but have not received much testing and implementation experience yet

> We hope to incorporate them into a future snapshot.

So this will happen automatically once the CSS working group decides the spec is both stable and widely implemented.
