### ISSUE TITLE
Reserved prefixes added in 3.0.1 and 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#974]
Apple iBook does not recognize a reserved prefix(*) which was introduced in EPUB 3.0.1.  If this prefix is explicitly declared,  iBook has no problems in handling it.  But if it is not, iBook reports an error.  Since this prefix is predefined in EPUB 3.0.1, this behaviour does not conform to 3.0.1.  Apple turned down the request by KADOKAWA to change this behavior.

* http://www.idpf.org/epub/301/spec/epub-publications.html#sec-metadata-reserved-vocabs

I am personally sympathetic to Apple, as additions of reserved prefixes causes troubles to existing RSs.  I thus propose to add a warning about this issue and a recommendation to explicit declare this prefix by publishing an erratum to EPUB 3.0.1 and 3.1.

Reserved prefixes added in 3.0.1 are:

    a11y http://www.idpf.org/epub/vocab/package/a11y/#
    epubsc http://idpf.org/epub/vocab/sc/#
    rendition http://www.idpf.org/vocab/rendition/#
    schema http://schema.org/

**Comment by mattgarrish** [comment]
Didn't we already have this discussion somewhere else and agreed that we should adopt language like in RDFa that reserved prefixes should be declared as they're only a convenience and can't be relied on?

I'd also be fine pulling these back into the specification. I'd hazard a guess that the days of spinning off satellite specs that need their own metadata prefixes is over.

**Comment by RachelComerford** [comment]
@GarthConboy (from CG meeting):
Proposal: Said prefixes SHOULD be explicitly declared (to defined values) – this should yield a warning in epubcheck.  This is done to not invalidate previous content that depended on implicit definition.

**Comment by mattgarrish** [comment]
It's tricky to make a normative rule out of this. What does it do to dcterms:modified for example? I'm not sure if that is the proposal here as warnings and not invalidating appear together.

My thought is only that we "strongly encourage" declaration in a note and cite the validation problem as the reason why.

**Comment by dauwhe** [comment]
Addressed with #1044. We can close issue if people are good with that.

**Comment by dauwhe** [comment]
Having heard no complaints, I'm closing the issue.
