### ISSUE TITLE
Nav doc: access to all nav elements?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#975]
In section 5.3 we say:

> When requested by a user, it must provide access to the links and link labels in the nav elements of the EPUB Navigation Document in a fashion that allows the user to activate the links.

http://www.idpf.org/epub/31/spec/epub-packages.html#confreq-nav-access

Is this more wishful thinking than reality? Does any reading system present all the nav elements?

I also can't make this statement jibe with the landmarks nav, which is supposed to be there only to provide enhanced behaviours.

Should we try and make the statement more realistic, like a reading system must provide access to the table of contents and page list (when available) and may provide access to other navs?

**Comment by GeorgeKerscher** [comment]
This sounds right to me. Thank you Matt for the detailed review.
