### ISSUE TITLE
Nav doc: current reading position and external links

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#977]
Section 5.4 includes this requirement:

> When a link is activated, [the reading system] must relocate the application's current reading position to the destination identified by that link.

http://www.idpf.org/epub/31/spec/epub-packages.html#confreq-nav-activation

But we also allow lists of external hyperlinks. If the reading system presents such a list, shouldn't the current reading position remain unchanged when a link is activated? (i.e., spawn a browser and close the navigation)

**Comment by GeorgeKerscher** [comment]
If an external link is activated,  I agree that the current location should be the last known position in the EPUB. In addition, when links to footnotes or to (in the future) aria-details of extended descriptions, the current location is the position that should be stored.

**Comment by dauwhe** [comment]
At least for many common types of `nav` elements, we're good:

> In the case of the toc nav, landmarks nav and page-list nav,  [the links] must resolve to an Top-level Content Document or fragment therein.

Could we say:

> When a link is activated, [the reading system] must relocate the application's current reading position to the destination identified by that link, if the link destination is a publication resource.
