### ISSUE TITLE
OPF-001 Issue; Version Issue in OPF (Package)

### ISSUE THREAD

**Issue by Sudhakar2007** [w3c/epub-specs#979]
Dear All,

I run the ePUB 3.1 version file in the ePUB checker 4.0.2 and get the following error message.

"ERROR(OPF-001): NEW.epub/OEBPS/content.opf(-1,-1): There was an error when parsing the EPUB version: Version not supported."

XHTML Package code as follows:
<package xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns="http://www.idpf.org/2007/opf" xmlns:dcterms="http://purl.org/dc/terms/" version="3.1" xml:lang="en" unique-identifier="p9780124046320">
<metadata xmlns:opf="http://www.idpf.org/2007/opf">
. . .
. . .

Could you please provide me a solution to resolve this issue.

Thanks,
Sudhakar

**Comment by Sudhakar2007** [comment]
Code:
&lt;package xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns="http://www.idpf.org/2007/opf" xmlns:dcterms="http://purl.org/dc/terms/" version="3.1" xml:lang="en" unique-identifier="p9780124046320"&gt;
&lt;metadata xmlns:opf="http://www.idpf.org/2007/opf"&gt;

**Comment by TzviyaSiegman** [comment]
please log issues related to epubcheck on the epubcheck repo https://github.com/IDPF/epubcheck/issues. The epubcheck update for 3.1 is a work in progress.
