### ISSUE TITLE
Normative reference to HTML

### ISSUE THREAD

**Issue by LJWatson** [w3c/epub-specs#980]
Please could the [normative references in EPUB 3.1](https://w3c.github.io/publ-epub-revision/epub31/spec/epub-spec.html#normative-references) point to the [W3C HTML specification](https://w3.org/tr/html)? Thanks

**Comment by TzviyaSiegman** [comment]
Thanks @LJWatson. That was supposed to be changed before publishing.

**Comment by LJWatson** [comment]
Thanks @TzviyaSiegman. Is it too late for it to be updated at this point?

**Comment by TzviyaSiegman** [comment]
@LJWatson We have a group working on maintenance. This is the first erratum we've received. I will look into whether we can update easily.

**Comment by mattgarrish** [comment]
That reference only exists in the unpublished w3c draft as far as I can find. It was a mistake in the conversion from the IDPF sources.

What we were using in IDPF was a reference to /TR/html/, which always points to the latest standard. Looking in the list of specref links, I don't see an equivalent, so we might need to get one made. Can always add to the local biblio as a temporary workaround, though.

**Comment by mattgarrish** [comment]
This was temporarily patched in https://github.com/w3c/publ-epub-revision/commit/ac5dd29fd91b8ffe071b160eb2165667d50647e8

I'm going to leave this issue open, as longer term we need to figure out whether and how to submit this as an official specref entry (e.g., reference id might need to change to something more universally palatable).

**Comment by therealglazou** [comment]
WAIT. Validators use the normative references to validate EPUB. Rendering engines do NOT implement that W3C version (almost nobody does), they implement the WHATWG version of html. So can someone share what's the goal here and what the impact on validators is supposed to be?

**Comment by mattgarrish** [comment]
Closing this issue as fixed. We're using the same local bibliography approach here that we've employed in the web publications specs.
