### ISSUE TITLE
Update OCF in 3.0.2

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#985]
@dauwhe I've updated version numbers in OPF, and changed a reference to a package version attribute from 3.1 to 3.0. But my understanding is that no substantive changes to OCF were proposed. 

@murata2makoto does this resolve your request?

**Comment by GarthConboy** [comment]
I would tend to think there is nothing substantive (decision wise) to do here.  Should be no OCF changes -- just accept 3.1 OCF language which describes (unchanged) OCF from 3.0.1.

**Comment by mattgarrish** [comment]
Closing this in favour of reporting specific changes, if any are discovered.
