### ISSUE TITLE
Need document or wiki that explains why this revision is happening (3.0.2)

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#987]
@mattgarrish A document or wiki that explains why this revision is happening (3.0.2) would also be useful. The technical details are important when it comes to patching the specs, but the first thing you want to know when you hear of a change like this is why it's necessary to do and what impact it has (e.g., what does "withdrawn" mean wrt 3.1). Beyond: https://docs.google.com/document/d/1r2RbLipc5VY3vUp_iuPak3oaNxI5BF9gJ5s-98qsmEY/edit 

I don't see it serving the purpose I mentioned, no, or it doesn't provide any specific rationale for why this is being done that I spotted; only technical details of what 3.0.2 might look like.

When someone asks why 3.1 is being abandoned, for example, what are the answers? Is there a business case that spells out the advantages? I'd like to avoid the appearance that this is a capricious change, as I can see it frustrating people who are already anticipating or working toward 3.1 support (and providing ammo to the detractors of the format).

I also think we need to be clear about 3.1 support (or lack thereof), too. It's going to be very confusing that a higher numbered standard is not the most recent or supported version if it lingers on. It may look like it lives on in parallel, like 2.0 and 3.0 already do.

**Comment by murata2makoto** [comment]
A section "Rationale" has been added to the document referenced above.

**Comment by RachelComerford** [comment]
@mattgarrish Does this cover your needs? If it does, I'm happy to close.

**Comment by mattgarrish** [comment]
This really isn't a spec issue, so you can close on that count if you want.

The proposal document is probably fine for the technically advanced members of the group, but I still think we need a more comprehensive accounting of this revision written for the average community member not involved in developing 3.1 or for whom these details will go over their heads.

Maybe I'll try to put something together to this effect, but I was actually hoping for a break from this stuff for a couple of weeks... :(

**Comment by mattgarrish** [comment]
I'm going to open this in the publ-cg repository as this isn't specifically related to changing the specifications, but something for the cg to publish.

**Comment by dauwhe** [comment]
> The proposal document is probably fine for the technically advanced members of the group, but I still think we need a more comprehensive accounting of this revision written for the average community member not involved in developing 3.1 or for whom these details will go over their heads.

[https://www.w3.org/blog/2018/04/why-specs-change-epub-3-2-and-the-evolution-of-the-ebook-ecosystem/](https://www.w3.org/blog/2018/04/why-specs-change-epub-3-2-and-the-evolution-of-the-ebook-ecosystem/)
