### ISSUE TITLE
3.0.1 etc not in the list of charter responsibilities

### ISSUE THREAD

**Issue by RachelComerford** [w3c/epub-specs#990]
Proposed Solution: Add to epub CG charter with approval from @whmccoy and Ralph Swick, as the the charter was established as a part of the IDPF merger.

cc: @iherman

**Comment by GarthConboy** [comment]
No objection (at all) to doing as proposed in the first comment.  Though, I could also posit that nothing is really required to be done, with the current charter stating "The EPUB 3 CG shall develop future revisions to, and maintenance of, EPUB 3 and extension modules. In scope are follow-on work from EPUB 3.1..." and "The EPUB 3 CG shall also undertake work on ancillary deliverables around EPUB 3 as appropriate,...".  I view the current 3.0.2 proposal as "follow-on work" to 3.1 and it is clearly "deliverables around EPUB 3" -- nothing in the current charter defines a going forward numbering scheme.

**Comment by dauwhe** [comment]
Based on the direct quote from the charter, I'm comfortable that our current effort is in scope.
