### ISSUE TITLE
canonical idpf.org addresses

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#998]
As I expect all IDPF repositories will move into W3C with this revision (at least those directly related to the specs), we should be mindful that if we actually change the references to these repositories within the specifications we'd technically be changing EPUB 3.2 in an incompatible way (although practically the effects may be minimal, as this is more an RS implementation issue).

The easy answer is to leave the canonical vocabulary addresses alone and use redirects to keep them current to wherever they move next. That's the way we configured them to work for 3.1, after all. But it means we might end up with some w3c and some idpf paths.

We can't change namespaces, so that's another case that only URIs of the current/previous spec nature should change.

I don't think we're compelled to change the URIs, so this may be something of a no-brainer not to do, but just wanted to put it out there.

**Comment by murata2makoto** [comment]
Do "the canonical vocabulary addresses" mean 

http://idpf.org/epub/vocab/structure/

or 

https://idpf.github.io/epub-vocabs/structure/

?

Will the domain idpf.org continue to be available?

**Comment by mattgarrish** [comment]
The former are the canonical, as they're referenced within the specifications and are supposed to be unchanging.

We have redirects on all those to the actual github locations, which also allows us to move the host at any future date without impacting the specifications.

> Will the domain idpf.org continue to be available?

That's the other question. I don't know what the agreement is as far as continued hosting goes. If there's a fixed life, we should look at modifying.

But a change also raises other questions, like in some places we ban "idpf.org" from URI identifiers, so do we ban a new domain that previously wasn't banned instead?

**Comment by mattgarrish** [comment]
But just to reiterate. The dangers of any changes are probably mostly theoretical, but I haven't tried to dig through them all. The problem just occurred to me today thinking about them.

**Comment by mattgarrish** [comment]
Although... what if someone is prefixing rendition: to the idpf.org vocabulary to avoid validation errors and we swap in a w3c address for it?

A newer reading system has to respect the declaration to a URI it doesn't recognize if we just quietly shift, or we have to patch in notes to support two URIs for all prefixed vocabs.

Food for thought.

**Comment by murata2makoto** [comment]
I think that we should stick to IDPF addresses for the EPUB 3 family.

If we adopt W3C addresses, newer implementations have to support both the idpf address and w3c address.  Old publications will work for both new and old implementations.  New publications will not necessarily work for old implementations.  This means that publishers will continue to use idpf addresses and thus implementors will not be encouraged to support w3c addresses.

**Comment by iherman** [comment]
I think I agree with @murata2makoto. If we want to manage repositories or registries on W3C sites, that is perfectly fine, as long as the old URL-s are redirected (which should be doable). But changing official URL-s is a recipe for troubles.

**Comment by mattgarrish** [comment]
Closing this issue and removing from the 3.2 milestone as there's no value in fiddling with the URIs.
